### ISSUE TITLE
`InMemoryChannelLayer.receive` does not implement `block` argument according to spec

### ISSUE THREAD

**Issue by ralokt** [django/channels#1000]
The [channel layers specification](http://channels.readthedocs.io/en/stable/channel_layer_spec.html#specification-details) describes the `receive` method as follows:

> `coroutine receive(channels, block=False)`, that takes a list of channel names as unicode strings, and returns with either `(None, None)` or `(channel, message)` if a message is available. If `block` is True, then it will not return a message arrives (or optionally, a built-in timeout, but it is valid to block forever if there are no messages); if `block` is false, it will always return immediately. It is perfectly valid to ignore `block` and always return immediately, or after a delay; `block` means that the call can take as long as it likes before returning a message or nothing, not that it must block until it gets one.

However, the `block` argument is not implemented:
```python
    async def receive(self, channel):
        """
        Receive the first message that arrives on the channel.
        If more than one coroutine waits on the same channel, a random one
        of the waiting coroutines will get the result.
        """
        assert self.valid_channel_name(channel)
        self._clean_expired()

        queue = self.channels.setdefault(channel, asyncio.Queue())

        # Do a plain direct receive
        _, message = await queue.get()

        # Delete if empty
        if queue.empty():
            del self.channels[channel]

        return message
```
([source](https://github.com/django/channels/blob/4d48d80746be03505a94eb4a1e06619ad5ef17e4/channels/layers.py#L223))

Unfortunately, I'm pretty new to asynchronous programming in Python, so I won't presume to be capable of implementing this to the standards of this project, at least without direction.

**Comment by andrewgodwin** [comment]
The spec was wrong, sorry. I updated it quickly to match the final implementation.

**Comment by ralokt** [comment]
No problem, thanks for the quick response!
