### ISSUE TITLE
Chunked request body support

### ISSUE THREAD

**Issue by zemelLeong** [django/channels#1001]
django 2.0.2
channels 2.0.2
os: ubuntu
mode: debugger

Hi,
My project can receive large file upload,  when using channels before. It will write a temporary file in the /tmp directory. But, when I use channels. Nothing in the /tmp directory.  About transmit 12M will fail.
Could you tell me what is problem?

My settings.py config:
INSTALLED_APPS = [... , channels]
ASGI_APPLICATION = "myproject.routing.application"

I use javascript client test it can be connect success

**Comment by matthiask** [comment]
Daphne/Channels do not support chunked request bodies yet.

Here's the relevant issue for Daphne: https://github.com/django/daphne/issues/126

`AsgiHandler` / `AsgiRequest` in Channels do not handle chunked request bodies either (https://github.com/django/channels/blob/6579c0f278adad0a0187f888d40baae5e0b5e060/channels/http.py#L110)

This will probably not be easy to solve / fix.

**Comment by zemelLeong** [comment]
It means that channels has blocked the file upload request, but it can't handle the file upload request. Is it?

**Comment by andrewgodwin** [comment]
Channels will never write files into /tmp - it is meant to blocking-receive them from the client and pass them to the application in chunks, which can then proceed to stream that to disk if it wants (Django will do this). I'll move this into a chunked request body ticket.

**Comment by hozblok** [comment]
Сurrently related PR is https://github.com/django/channels/pull/1251

**Comment by carltongibson** [comment]
Going to close as _plain-old HTTP_™ should move to using Django's `ASGIHandler` — we'll be removing the Channels version.
