### ISSUE TITLE
Unable to route to defined route ("Not found: '/lobby/')

### ISSUE THREAD

**Issue by mike-johnson-jr** [django/channels#1002]
routing.py

    from channels import include, route
    from chat import consumers
    from . import game_consumers

    channel_routing = [
	    #game routing
	    route('websocket.connect', game_consumers.ws_connect_lobby, path=r"^/lobby/$"),
        route('websocket.receive', game_consumers.ws_receive_lobby, path=r"^/lobby/$"),
        route('websocket.disconnect', game_consumers.ws_disconnect_lobby, path=r"^/lobby/$"),

app.js

    Websocket = {
        lobby_socket: null,
        setup_ws_lobby : function(){
		    Websocket.lobby_socket = new ReconnectingWebSocket(Websocket.ws_scheme + '://' + window.location.host + '/lobby/');
		    Websocket.lobby_socket.onmessage = function(message) {
		        //nothing yet
                };
	    },
    }
    Websocket.setup_ws_lobby();

The url is `127.0.0.1:8000/game`. `Websocket.setup_ws_lobby()` is executed on page load. I don't see what I'm doing wrong. I get the error `Not Found: /lobby/` in my `python manage.py runserver` console when I load the page. My routes are clearly set and my js setup seems to route to those routes. Can anyone help? Thanks in advance.

**Comment by andrewgodwin** [comment]
I'm afraid this is for Channels 1, so we can't provide support any more as it's end of life.

**Comment by mike-johnson-jr** [comment]
Where can I find Channels 1 documentation?

**Comment by andrewgodwin** [comment]
http://channels.readthedocs.io/en/1.x/
