### ISSUE TITLE
authentication example

### ISSUE THREAD

**Issue by luk156** [django/channels#1004]
the example on:

http://channels.readthedocs.io/en/latest/topics/authentication.html#custom-authentication

is correct or we should use database_sync_to_async?

**Comment by andrewgodwin** [comment]
I believe it's fine as `__call__` is a `def`, not an `async def`. What probably needs to be ensured is that servers run the constructors for ASGI applications in a threadpool as they may be blocking, which I have made sure is written down in https://github.com/django/daphne/issues/188
