### ISSUE TITLE
How to send message to user by medel trigger event?

### ISSUE THREAD

**Issue by sunmoon11** [django/channels#1007]
I'm trying to send message to user by model change event or special one. I can't the way for that because in channel 2, it's using class based consumer.
In other words, I can't use the following code.
`Group("%s" % <user>).add(message.reply_channel)`
Can you tell me how to send?

**Comment by andrewgodwin** [comment]
You can load an instance of the channel layer directly - it's covered in the docs here: http://channels.readthedocs.io/en/latest/topics/channel_layers.html#using-outside-of-consumers
