### ISSUE TITLE
Modularizing a single websocket connection for specific app and its consumer

### ISSUE THREAD

**Issue by KakarN** [django/channels#1010]
Hi,

I have three main Django apps: accounts, chat and notification. I am using channels to create a single connection from the client, and use that for routing WebSocket connections/disconnect/receive. All the channels related logic are inside `accounts/consumers.py`. 

Since all the code for handling chat messages/threads or notification handling is inside one consumers.py, it has become very difficult to maintain the code. Is there any way to modularize this? I was thinking of modularizing every application specific related code inside their specific app/consumers (maybe how its documented in [Worker and background task](https://channels.readthedocs.io/en/latest/topics/worker.html)). 

Example when a websocket receives a message, if its chat related then route that message to the chat app's consumers.py using chat app's fixed channel name. 

But I am not sure if it's going to have the same effect (eg. latency) versus having all the channels logic in one consumer. It would be great if anyone could advise me on this.

Sincerely,
Kakar

**Comment by andrewgodwin** [comment]
Much like Django views, you can just split up individual consumers into their own files. If you have all your logic in one consumer, I instead suggest you refactor out any large pieces of business logic into a separate file as standalone functions and call them from the main consumer.
