### ISSUE TITLE
Enabling channels breaks `FORCE_SCRIPT_NAME`

### ISSUE THREAD

**Issue by prokher** [django/channels#1016]
Hi all!

Today I suddenly figured out that enabling Channels breaks URL "routing" inside Django Admin when `FORCE_SCRIPT_NAME` is set. I have Django running behind Nginx reverse proxy with `/api/` URL prefix. To make Django respect this prefix I set `FORCE_SCRIPT_NAME = '/api'` in the Django setting file. Everything works fine until I enable Channels by `INSTALLED_APPS += ['channels']`. After this Django Admin login screen POSTs data the wrong URL, the one without `/api/` prefix. If I disable Channels it works fine again. I simply do not know where to dig further. Any help is appreciated.

My setup:
- channels (2.1.0)
- daphne (2.1.0)
- Django (2.0.4)
- Ubuntu Linux 16.04

**Comment by andrewgodwin** [comment]
Yup, there is no support for this yet as it's overriding a WSGI-specific thing and we'd need to make sure it . You can instead use the `--root-path` option to Daphne to provide this right now until this is fixed.

**Comment by prokher** [comment]
@andrewgodwin Thank you. I will use `--root-path` for now.

**Comment by maribedran** [comment]
Hey! I'm at the DjangoCon EU sprints. I'm working on this issue.

**Comment by maribedran** [comment]
Hey @andrewgodwin! Opened the #1064 PR. Could you check if everything is OK?
Thank you for all the help :)

**Comment by andrewgodwin** [comment]
Looks lovely - thanks for your work on that!
