### ISSUE TITLE
Nginx error message when closing websocket connections

### ISSUE THREAD

**Issue by DrPyser** [django/channels#1021]
I'm running a django channels/daphne api server behind nginx. I only use daphne to handle websocket connections(by redirecting traffic based on path), and uwsgi for normal http traffic.  

It's mostly working, but I'm getting errors in the nginx log when I'm closing connections:

`2018/04/17 18:41:29 [error] 13#13: *1 recv() failed (104: Connection reset by peer) while proxying upgraded connection [...]`

For example, I do custom JWT-based authentication of the connection request, all in the 'connect' handler of the consumer, which goes like this:
1. I accept the connection
2. I try to authentify the request(by checking that a 'token' query parameter is there and is valid)
3. If the authentication fails, I send an error message and close the connection. 

And everytime the connection is closed, nginx displays the above error. Otherwise everything works fine.

The relevant nginx conf 'location' block:
```
        location /ws/ {
            rewrite /ws/(.*) /$1 break; # remove '/ws/' prefix before forwarding
            proxy_pass http://daphne; # upstream alias defined earlier
            
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
```

The command I use to launch daphne:
```
daphne -b 0.0.0.0 -p 9012 config.asgi:application
```
OS: `Linux server-04 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
django version: 2.0.4
channels version: 2.0.2
daphne version: 2.1.0

**Comment by andrewgodwin** [comment]
This is a deliberate thing Channels does - if you reject the WebSocket connection we close it with an error code. I'm not sure why Nginx is erroring out on this - I searched the error message you got and it seems it's a common problem with Nginx and WebSocket servers.

I'd suggest looking around for more help in how to tell Nginx this is OK, or to see if you have strange networking (e.g. Docker) that's absorbing the connection RST packet incorrectly.

**Comment by DrPyser** [comment]
OK, thanks.

**Comment by ahb10** [comment]
I'm also having this problem. When I load the page the socket connects but as soon as i send a message from the client to the server, the socket closes...
Any ideas how to solve this... I've also posted this here [https://stackoverflow.com/questions/65010138/recv-failed-104-connection-reset-by-peer-while-proxying-upgraded-connection](url)

**Comment by rudradesai200** [comment]
@ahb10 I saw you found the solution to this problem. Can you please post it here? I am also facing the exact same issue. Thanks in advance!

**Comment by zliassurance** [comment]
@ahb10 I am facing the same issue, how did you resolve it?

**Comment by DanielSwain** [comment]
I'm encountering this error too and am interested to know how others have solved this problem.  When clicked, the link above goes to a different location than the text of the link.  Copying and pasting the visible link text also goes nowhere, but it does, at least, bring up a list of suggestions on StackOverflow might be helpful depending on your environment.

**Comment by zliassurance** [comment]
@DanielSwain I ended up using uvicorn, that works perfectly

**Comment by 3s-hoand2020** [comment]
I am also having problem like this. Has anyone found a solution yet?
