### ISSUE TITLE
Integration with DRF and auth

### ISSUE THREAD

**Issue by jvhjvh** [django/channels#1022]
I wrote a piece of software with Channels 1.6 that is using a front end server that responds to https using Django Rest Framework (and websockets) and is using a bunch of builtin authentication schemes. It also has several servers that communicate using Channels in separate processes that also send messages back to the front end. I was now attempting to upgrade to channels 2.1.1 and ran into a few issues that I hope you don't mind me bringing up even if they likely are due to my ignorance of the new Channels.

The first one was that I had a bit of hard time getting the authentication working.
First there was no security context. When I added to routing.com the middlewar stack to ProtocolTypeRouter I got a security context.

        "http": SessionMiddlewareStack(AuthMiddlewareStack(
            AsgiHandler
        )),

Now the remaining problem was that 'user' and 'session' were in scope[] rather than in request{}. I tried replacing all references to request.user with request.scope['user'] and request.session with reuest.scope['session'] it actually all worked. Unfortunately this is not very maintainable as many of the references were in standard distribution files (I upgraded all the newest versions).
So my question is whether the plan is to 1) upgrade all the standard libraries or 2) would it be easy enough to add user and session to AsgiHandler that could just delegate to scope, or 3) most likely I am using the interfaces incorrectly. If, as most likely, it is #3 I will try to provide more details.

**Comment by andrewgodwin** [comment]
AsgiHandler creates a `request` object internally, so I'm not sure why you had to go look at `scope`. If you are trying to use DRF code outside of the Django view system - i.e. in a separate AsyncConsumer - you are going to have problems as there's not a `request` object, but the backwards-compatability of `AsgiHandler` is there for a reason.

Is there something I'm missing?

**Comment by jvhjvh** [comment]
Yes, it is a request object but the request object did not have the 'user' and 'session' fields directly but only within scope. I will gather specific examples and get back to you.

It is also possible I setup the request handling incorrectly somehow.

Sorry, the channels 2 are new to me and I am still figuring them out but trying to let you know where I got into trouble. Thanks for your good work!

**Comment by jvhjvh** [comment]
For instance with the django/contrib/admin/sites.py#has_permission() refers to request.user with the request object being an AsgiRequest object when I print it out. That object has a scope that contains a 'user' but there is no user field directly in AsgiRequest. The AsgiRequest comes from the ProtocolTypeRouter line I sent previously.

The code works with Channels 1 and also with vanilla wsgi so it is confusing how the MIDDLEWAREcould affect this.

I don't know if this makes sense or not but that is what I see...
Thanks

**Comment by jvhjvh** [comment]
There is really no simple way code could find the user and session attributes in AsgiRequest as there is no such code in http.py. You can try running any service with e.g. django.contrib.admin with it and just go to the main admin page.
Instead of editing all the code to deal with scopes I tried adding simple accessors to AsgiRequest instead. This seems to work as well with limited testing. Seems there is little downside and the admin and DRF views start working. Here is a naive code snippet (for class AsgiRequest):

    @property
    def user(self):
        return self.scope['user']

    @user.setter
    def user(self, user):
        self.scope['user'] = user

    @property
    def session(self):
        return self.scope['session']

    @session.setter
    def session(self, session):
        self.scope['user'] = session

**Comment by jvhjvh** [comment]
OK, thanks, I was trying to figure out what is wrong with the middleware. It seems some startup errors are silent for some reason but Itried to run some manually from routing.py to see what is happening.

One offender is django.contrib.messages.middleware.MessageMiddleware. It is needed by django.contrib.admin for instance when you save an object from the admin page.

The middleware uses hasattr for 'session'. However, the session in channels/session.py is a dict. And hasattr does not work for dict content. In addition MessageMiddleware assumes there is COOKIES in the session. COOKIES is in fact initialized to an empty set in django/http/request.py but not in channels/http.py. It also ends up looking for _messages in AsgiRequest (should be delegated to scope).

It might be a good idea to test the whole admin functionality to make sure it works for you or somebody else as it may be that I am still doing something wrong. I added some simple code to channels/sessions.py to get MessageMiddleware to work but since I don't expect anybody to like the code I will just cut&paste it here for reference. This just makes the dict members wok with hasattr and adds COOKIES.

class ScopeDict(dict):
    def __init__(self, *args, **kwargs):
        super(ScopeDict, self).__init__(*args, **kwargs)
        self.__dict__ = self
        self['COOKIES'] = {}

class SessionMiddlewareInstance:
    """
    Inner class that is instantiated once per scope.
    """

    def __init__(self, scope, middleware):
        self.middleware = middleware
        self.scope = ScopeDict(scope)

**Comment by jvhjvh** [comment]
You are right. At the very last line of the Django 2.0 release notes it says that MIDDLEWARE_CLASSES has been removed. Since I did not really change anything else I incorrectly assumed all the problems had to do with channels. Thanks for pointing that out.
I think I now have the old code mostly working again after the upgrade so I can get to some new code. Thanks again for your help.

**Comment by angadsinghsandhu** [comment]
Can you make DRF and Channels 2 work together, without having any issues (eg. `Request` Object) ??
