### ISSUE TITLE
Sending channel messages back to front end

### ISSUE THREAD

**Issue by jvhjvh** [django/channels#1023]
My second issue with the front end server that receives channels messages back is that I could not find any obvious way of receiving protocol type 'channel' messages at the front end. manage.py runserver does not take a list of channels and running both runserver and runworker in the same process is not supported.
I'm not sure if this is a usage question, a feature request or an omission so my apologies for sending it here.

**Comment by andrewgodwin** [comment]
I don't understand this question entirely either - let me outline how things work in Channels 2 and that will hopefully help.

* Messages to and from the client socket - so HTTP or WebSocket - are handed in-process as part of the server, like WSGI. Each connection starts up a new application instance, and if you have channel layers turned on, each instance will have its own unique channel name you can send to (and add to groups) which is how you can get them messages. Docs here: http://channels.readthedocs.io/en/latest/topics/channel_layers.html

* Messages on "custom" channel names, like task queues, are handled in a worker still. More on that here: http://channels.readthedocs.io/en/latest/topics/worker.html
