### ISSUE TITLE
Signal when channels ready (consumer_started never sent)

### ISSUE THREAD

**Issue by jvhjvh** [django/channels#1024]
In order to run initialization code that is executed after Channels have been started but not when running e.g. migrations it would be nice to have a Channels related signal. In fact there is one already (consumer_started) but it is never called. I added the call to my version of channels/management/commands/runworker.py at the end just before worker.run(). This is probably the wrong signal and wrong place but is somehow needed nevertheless.

**Comment by andrewgodwin** [comment]
We can't actually implement this now as Channels runs inside a host ASGI server and so doesn't have control over its startup process (most installations don't need workers now). I recommend you do whatever you need in an application's setup function like you would for normal Django.
