### ISSUE TITLE
How to receive method receive a message and send meny message real time

### ISSUE THREAD

**Issue by huxianglin** [django/channels#1029]
hello,
I'm a new leaner of channels, I want to realize receive and  real time send many messages, but when i use self.send(message=data) send data, the data is not real time send to client.
my env:
python 2.7.10, Django 1.9.7, channels 1.1.8

consumers.py

```
from channels.generic.websockets import WebsocketConsumer, JsonWebsocketConsumer
import time

class envUpgrade(JsonWebsocketConsumer):
    http_user = True
    strict_ordering = False
    def receive(self, content, **kwargs):
        for i in content['data']['new']:
            time.sleep(1)
            self.send(content=i)
            # self.message.reply_channel.send(i)
        else:
            self.close()
```

This is my chrome broswer receive data.

```
{"new": 7, "name": "user_auth_info"} | 36 | 15:46:53.367
{"new": 6, "name": "p2p_regist"} | 32 | 15:46:53.367
{"new": 7, "name": "invest_page_list"} | 38 | 15:46:53.368
{"new": 16, "name": "channel_account_info"} | 43 | 15:46:53.369
```

But i receive data is not real time, can you tell me how can i do?
Thank you very much.

**Comment by huxianglin** [comment]
I hope that when i use self.send() send my message to broswer, broswer can receive this message instant.
But, in this case, actually broswer receive messages is not real time. broswer receive messages look like at the same time.

**Comment by andrewgodwin** [comment]
Oh, you are using Channels 1 - yes, messages do not send until after the `receive()` function exits. Channels 2 fixes this, but you will have to rewrite your code slightly.
