### ISSUE TITLE
aioredis error

### ISSUE THREAD

**Issue by linmanpeng** [django/channels#1032]
I ran the following code on centos 7.0 with channels==2.1.1 and channels_redis==2.1.1

$ python3 manage.py shell
> import channels.layers
> channel_layer = channels.layers.get_channel_layer()
> from asgiref.sync import async_to_sync
> async_to_sync(channel_layer.send)('test_channel', {'type': 'hello'})

but got error

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    async_to_sync(channel_layer.send)('test_channel', {'type': 'hello'})
  File "/root/anaconda3/lib/python3.5/site-packages/asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "/root/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/root/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/root/anaconda3/lib/python3.5/site-packages/asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/root/anaconda3/lib/python3.5/site-packages/channels_redis/core.py", line 132, in send
    async with self.connection(index) as connection:
  File "/root/anaconda3/lib/python3.5/site-packages/channels_redis/core.py", line 399, in __aenter__
    self.conn = await aioredis.create_redis(**self.kwargs)
  File "/root/anaconda3/lib/python3.5/site-packages/aioredis/commands/__init__.py", line 174, in create_redis
    loop=loop)
  File "/root/anaconda3/lib/python3.5/site-packages/aioredis/connection.py", line 124, in create_connection
    loop=loop)
  File "/root/anaconda3/lib/python3.5/site-packages/aioredis/connection.py", line 163, in __init__
    self._close_waiter = loop.create_future()
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'create_future'
Task was destroyed but it is pending!
task: <Task pending coro=<RedisConnection._read_data() running at /root/anaconda3/lib/python3.5/site-packages/aioredis/connection.py:181> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by andrewgodwin** [comment]
I don't get this locally. Are you sure you have everything up to date (including `asgiref`)?

**Comment by linmanpeng** [comment]
Everything is up to date other than Django.

Collecting channels
  Using cached https://files.pythonhosted.org/packages/c0/24/f1f1ab62b4b35984d757dd1acbfed0f1c681c79e9beb4d275d18d42d4989/channels-2.1.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): Django>=1.11 in /root/anaconda3/lib/python3.5/site-packages (from channels)
Requirement already satisfied (use --upgrade to upgrade): asgiref~=2.3 in /root/anaconda3/lib/python3.5/site-packages (from channels)
Requirement already satisfied (use --upgrade to upgrade): daphne~=2.1 in /root/anaconda3/lib/python3.5/site-packages (from channels)
Requirement already satisfied (use --upgrade to upgrade): pytz in /root/anaconda3/lib/python3.5/site-packages (from Django>=1.11->channels)
Requirement already satisfied (use --upgrade to upgrade): async-timeout~=2.0 in /root/anaconda3/lib/python3.5/site-packages (from asgiref~=2.3->channels)
Requirement already satisfied (use --upgrade to upgrade): autobahn>=0.18 in /root/anaconda3/lib/python3.5/site-packages (from daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): twisted>=17.5 in /root/anaconda3/lib/python3.5/site-packages (from daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /root/anaconda3/lib/python3.5/site-packages (from autobahn>=0.18->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): txaio>=2.10.0 in /root/anaconda3/lib/python3.5/site-packages (from autobahn>=0.18->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): incremental>=16.10.1 in /root/anaconda3/lib/python3.5/site-packages (from twisted>=17.5->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): Automat>=0.3.0 in /root/anaconda3/lib/python3.5/site-packages (from twisted>=17.5->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): hyperlink>=17.1.1 in /root/anaconda3/lib/python3.5/site-packages (from twisted>=17.5->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=4.0.2 in /root/anaconda3/lib/python3.5/site-packages (from twisted>=17.5->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): constantly>=15.1 in /root/anaconda3/lib/python3.5/site-packages (from twisted>=17.5->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): attrs in /root/anaconda3/lib/python3.5/site-packages (from Automat>=0.3.0->twisted>=17.5->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.5 in /root/anaconda3/lib/python3.5/site-packages (from hyperlink>=17.1.1->twisted>=17.5->daphne~=2.1->channels)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /root/anaconda3/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg (from zope.interface>=4.0.2->twisted>=17.5->daphne~=2.1->channels)
Installing collected packages: channels
Successfully installed channels-2.1.1
