### ISSUE TITLE
Accesing Database

### ISSUE THREAD

**Issue by Hunterhal** [django/channels#1034]
Hello, I wanted to access database with async json consumer. I am using the following code, code saves the data to database, and if I wanted to send another data it is also saved to database but, server gives error. Actually it says "connect call failed". Lastly it doesn't enter the disconnect routine. Listing is working without errors. I couldnt find  any solution, I am doing IoT project and I am stuck please help. If possible please expand the information in database in the docs. Note: I am connecting to server through websocket script.

from channels.generic.websocket import AsyncJsonWebsocketConsumer
from channels.db import database_sync_to_async
from asgiref.sync import async_to_sync
from iot_manager.models import PacketID
from django import db
import json

class MyConsumer(AsyncJsonWebsocketConsumer):
    async def connect(self):
        await self.accept()
        print("Connected")

    async def receive_json(self, json_data):
        print("Receiving")
        print(json_data)
        await database_sync_to_async(self.get_name)(json_data)
        print("saved to database")
        await self.send_json(json.dumps(['foo', {'bar': ('baz', None, 1.0, 2)}]))
        print("data sent")

    async def disconnect(self, close_code):
        print("Disconnected")
        pass

    def get_name(self, json_packet):
        print("Inside the function")
        print(type(json_packet[0]))
        dict_packet = json.loads(json_packet[0])
        print(dict_packet['ID'])
        PacketID.objects.create(top_name = dict_packet['ID'])
        print('created')
        print('saved')
        print(PacketID.objects.values_list('top_name'))
        print("listed")

**Comment by andrewgodwin** [comment]
From what I can see of your code it should work, so I don't know why it is not. Unfortunately I cannot offer individual programming help here - this is only for issues in Channels itself, and we have tests that should cover everything you are using.
