### ISSUE TITLE
User not set on consumer

### ISSUE THREAD

**Issue by DiegoGallegos4** [django/channels#1037]
Why is the user not set on message? 

- Channels (1.1.8), Django(2.0.3)
- Running Channels with `python manage.py runserver`
- Error I get: 
> AttributeError: 'Message' object has no attribute 'user'

Code: 
```
class ConsumerX(BaseConsumer):
      http_user = True # when using channel_session_user I get AnonymousUser
      method_mapping = {"http.user": "method_x"}

      def method_x(self, message, **kwargs):
             print(message.user)
             ...     
```

I am logged in and other API calls have request.user. In theory as this [link](https://channels.readthedocs.io/en/1.x/generics.html#sessions-and-users) explains  it should populate *message.user* with *request.user*

**Comment by andrewgodwin** [comment]
If I remember right it's message.http_user - take a read through the 1.x docs to check.

**Comment by DiegoGallegos4** [comment]
Well no, that's why I posted the documentation on the question, for what it says about http_user. Exploring the source code, no http_user appear under base consumer handler function logic (only channels_session). This should not be closed, as it is an issue with documentation. Problem got solved by implementing similar logic as WebSocketConsumer.

**Comment by andrewgodwin** [comment]
It is closed because this is Channels 1.x, which is no longer supported, otherwise I would have left it open.
