### ISSUE TITLE
Anonymous user

### ISSUE THREAD

**Issue by DiegoGallegos4** [django/channels#1042]
- channels (2.1.1), django(2.0.4)

I have run the project on development with django commands: 
- python manage.py runserver
- python manage.py runworker <channel-name>

When trying to access user instance via **self.scope["user"]** inside the consumer it all works as expected. 

On prod I am running the daphne process as a systemd process: 
- daphne -b 0.0.0.0 -p 8001 project.config.asgi:application

On this case when to access user instance I get anonymous therefore the consumer returns 403, Forbidden. I've tried login/logout but still seems session is not being set while on regular restful endpoints session and user are set.

The consumer looks as follows:

```
class UserTransactionsDownloadConsumer(AsyncHttpConsumer):
    async def handle(self, body):
        user = self.scope["user"]
        if not user.has_perm(models.CAN_VIEW_TRANSACTIONS) and \
           not user.has_perm(models.CAN_ACCESS_USER_PROFILE):
            await self.send_response(403, core.constants.FORBIDDEN)
            return

         # self.send_response and self.channel_layer stuff that is working ok
        ...
```

Routing:

```
application = ProtocolTypeRouter({
    "http": AuthMiddlewareStack(
        URLRouter([
            url(r"^stream/profile", consumers.UserTransactionsDownloadConsumer,
            url(r"(.*?)", AsgiHandler),
        ])
    )
})
```

What is the difference between running with django commands and production?

**Comment by andrewgodwin** [comment]
Hmm, that is odd. Have you tried running with daphne in development to see if it is different?

**Comment by DiegoGallegos4** [comment]
Yes run it on development as well. Same behavior.

**Comment by andrewgodwin** [comment]
That's strange, then, since `runserver` also just runs Daphne in the background. You're running both those commands in the same local terminal and one works and one 403s?

**Comment by DiegoGallegos4** [comment]
On different instances, I tested running runserver and daphne on local and running a web server on prod like this nginx > uwgsi > daphne.

**Comment by andrewgodwin** [comment]
If this only fails running behind nginx in production, then it's likely a header configuration issue with nginx and so not a Channels problem.

If it fails locally with daphne and works with `runserver`, then please paste the exact console output of both commands running, one after the other, and what they print when you try to make things work.

**Comment by DiegoGallegos4** [comment]
Yes just checked daphne without any web server in front and it works. What configuration(documentation) can you point me out to check out the headers?

**Comment by andrewgodwin** [comment]
I don't have a good, specific place to point you unfortunately - look around for nginx WebSocket forwarding tutorials/documentation and make sure your configuration matches, and make sure that you have a new enough version that supports HTTP 1.1.

**Comment by DiegoGallegos4** [comment]
Just wanted to expand a little bit more on this. I think I have narrowed what the issue is: We are using a server for wsgi and another for asgi(daphne). Our web server proxies all http to **/** route and async tasks to */stream*, config is pretty much similar to anything out there. All http routes are correctly receiving user instances and permissions are applied correctly but asgi route apparently are not setting user/session instances. Can this be because daphne and wsgi servers are accessing different sessions? Is there any way to share the same session?

**Comment by andrewgodwin** [comment]
I'd check that you have a session backend set in Django that works cross-process, and that both servers are receiving the session cookies from the clients.

**Comment by DiegoGallegos4** [comment]
Actually, on Request Headers I can see that Cookie header is the same for both http and asgi requests. What varies is the Response Headers. I can see **Set-Cookie Header** not being set on daphne.

I see a similar issue with daphne a couple of versions ago discussed here:

[channels discussion set-cookie header](https://github.com/django/channels/issues/89
)

Regarding config I have the following: 
- **django.contrib.sessions** on INSTALLED_APPS
- **django.contrib.sessions.middleware.SessionMiddleware** on MIDDLEWARE

**Comment by DiegoGallegos4** [comment]
The first is daphne and the other is served via wsgi server: 

![image](https://user-images.githubusercontent.com/5933437/39659936-4fbe9072-4ff1-11e8-95e5-278ec988b73d.png)

**Comment by andrewgodwin** [comment]
Channels cannot set cookies over WebSocket connections. It can do them over HTTP connections, but only if you either use Django views or manually call session save from async consumers (see the docs: http://channels.readthedocs.io/en/latest/topics/sessions.html#session-persistence)

**Comment by DiegoGallegos4** [comment]
Yes they are all http consumers. When adding **SESSION_SAVE_EVERY_REQUEST** to True,   I get the following testing it this way: 

1. Go to homepage where is logged in 
2. Go to http consumer endpoint and get anonymous user then return to homepage where now has been logged out.

**Comment by DiegoGallegos4** [comment]
Tried getting user with *channels.auth.get_user(self.scope)* but still getting anonymous user. *session_key* is set but cannot get the user from it.

**Comment by DiegoGallegos4** [comment]
any insight on why session is correctly set but not being fetched by authentication methods?

**Comment by antimatterjs** [comment]
A bit late to the party with this being about a year and a half old, but I seem to be having a similar problem - did you get this sorted?

**Comment by Joeyn1993** [comment]
Just ran into a similar problem, any solution here?

**Comment by Aperyon** [comment]
My authentication only fails sometimes, randomly. Some connections succeed, some fail. The request headers are identical in both cases. Any idea why?

**Comment by ExtraE113** [comment]
Another year later, and I'm experiencing the same issue; daphne behind nginx making all users anonymous. Any fix?

**Comment by Saadelkouari** [comment]
Same problem here anyone got a solution???
