### ISSUE TITLE
Slow with Debug=False

### ISSUE THREAD

**Issue by dragonbone81** [django/channels#1048]
So I've set up channels, and it works great in debug with websockets connecting and everything is fast.
However as soon as I turn debug=False the speed for any request goes way down (like 5-10 seconds to load the admin page) And as soon as I remove the channels app from installed_apps, the speed is back to normal.

I'm running the server with just the normal (manage.py runserver) as opposed to daphne or something... not sure yet how that works, and I need to limit the workers to only one for now anyways.

Again, it works great with debug on, and with channels app removed, but slows to a crawl when debug is turned on and channels app is installed.

https://github.com/dragonbone81/bobcat-courses-backend

**Comment by andrewgodwin** [comment]
That's strange behaviour indeed. You mention it's slow when "debug is turned on and channels app is installed" - which of these actually causes it? Does it only happen when both are true? Basically, can you fill out the fast/slow for each combination of:

- Debug on, channels installed
- Debug off, channels installed
- Debug on, channels not installed
- Debug off, channels not installed

**Comment by dragonbone81** [comment]
- Debug on, channels installed -> Works good
- Debug off, channels installed -> Works bad
- Debug on, channels not installed -> Works good
- Debug off, channels not installed -> Works good

So yeah it's installing channels, and running with debug off that causes the slowdown, every other combinations works great.

**Comment by andrewgodwin** [comment]
OK.

- Do you have `CHANNEL_LAYERS` set? If you do, what happens if you set it to `{}`?
- Is it only certain URLs that are slow, or all of them?
- What does the network panel of your browser show is the slow part of the page load - the page itself or the static resources?

**Comment by dragonbone81** [comment]
- Yeah I'm not using CHANNEL_LAYERS. I set it up to a redis database, but wasn't really sure what it was doing, and it didn't look like i was using it. I ran these tests with it set to `{}`.
- It's all as far as I can see (admin, DjangoRestFramwork, and the regular urls for my site)
- The first two pictures are loading the base page of the admin in cached and uncached, and the last on is DRF root api page that just shows all the endpoints in JSON.
Looks like static resources take a long time to load, but the page itself also takes like 2 seconds.
![unchached_snip](https://user-images.githubusercontent.com/23389970/40258828-c838b878-5aa7-11e8-8171-0194a1f7b4cd.PNG)
![cached_snip](https://user-images.githubusercontent.com/23389970/40258829-c85778b2-5aa7-11e8-8231-bb14268ff2a7.PNG)
![json_snip](https://user-images.githubusercontent.com/23389970/40258830-c877d88c-5aa7-11e8-90eb-bb5f8e75cf5d.PNG)

**Comment by andrewgodwin** [comment]
Hm, I'm a bit stumped then. Nothing in Channels should be impacting the normal URL path at all, and I definitely have never seen this happen. Looks like everything takes ages to load.

Just to check, what are the versions of all the packages you have? And do you have any other apps or middleware that could be interfering?

**Comment by dragonbone81** [comment]
I disabled `'whitenoise.middleware.WhiteNoiseMiddleware'` and the speed of loading has gone up and is now twice as fast. Not sure if I need this middleware, but will test that. However it's still slow, and that's the only middleware i have that's not django's.
I'm going to try to run your example channels app and see what happens :)

I have the latest version of channels and a lot of other packages that are up to date.

**Comment by dragonbone81** [comment]
I have found the reason that this occurs.
`django_heroku.settings(locals())` I set this at the bottom of setting.py, and removing this causes everything to work nicely. Although I need this to deploy to heroku.

**Comment by andrewgodwin** [comment]
Ah! I would suggest that you have separate local dev settings from deployment settings, in that case, and then you can have it work differently per environment. There should be some articles around for different ways to set that up.

**Comment by dragonbone81** [comment]
So I've tried to replicate what's causing this my manually specifying the staticfiles and database attrs.
`PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
 STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/')
 STATICFILES_DIRS = ()`
This is what I've seen work on production in Heroku, and it does work, but causes slow loads.
Same slowdowns happen on my dev if I use those settings too.

Is there something that channels does to staticfiles that I need to change or add?

**Comment by andrewgodwin** [comment]
It overrides a few things to make it work, but it shouldn't matter (and you shouldn't be using staticfiles in production, just `collectstatic`).

**Comment by dragonbone81** [comment]
I'm not understanding, I was following this ->
https://devcenter.heroku.com/articles/django-assets
Where I set up the directories for static files and whitenoise.
Heroku runs `python manage.py collectstatic --noinput` but this can't run if I don't set the staticfiles directories.

So I'm not sure what I'm doing wrong, and how using staticfiles causes the slowdowns

**Comment by dragonbone81** [comment]
Ok, so I've tried to use your example app in heroku, and I get the same thing. I deployed it without basically touching it apart from adding heroku config stuff like Whitenoise and django-heroku to set up the environmental variables and DB. I've also disabled the Redis logic so the app doesn't really work, but the admin page takes a considerable time to load just like in my app.

https://github.com/dragonbone81/channels-test
https://channels-test-django.herokuapp.com/admin/chat/room/
user: admin pw: admin -> if you want to check it out.

Sorry for using your time. Maybe if someone else has encountered this they can help out, but I've looked around and I can't find a similar issue.

**Comment by dragonbone81** [comment]
Is it ok if the issue is opened again? @andrewgodwin

**Comment by andrewgodwin** [comment]
Well, an open issue means it is definitely a problem with Channels that can be solved - as in, someone can actively reproduce a bug on a local dev environment and fix it.

When you were saying things were slow, was that always on Heroku or on a local dev copy as well? If it's something that only happens on Heroku I'm afraid there's not much I can do; I can't act as their support team if their Python environment is somehow slightly different...

**Comment by dragonbone81** [comment]
No I get the same result on my laptop if I use staticfiles with whitenoise and turn debug off.

I don't know if this is an explicit issue with channels, but it must be interferering somehow with staticfiles with debug off.

**Comment by ericls** [comment]
The slowness comes from `__init__` of `WhiteNoise`, which scans the `STATIC_ROOT` folder (https://github.com/evansd/whitenoise/blob/master/whitenoise/base.py#L105) and ASGI handler instantiates middleware classes for each request, a folder scan is performed on each request.

**Comment by sciyoshi** [comment]
@andrewgodwin can we reopen this ticket? Seems like @ericls has found the root cause: Channels is breaking [Django's API contract](https://docs.djangoproject.com/en/2.0/topics/http/middleware/#init-get-response) which says that a middleware's `__init__` will only get called once at server startup.

**Comment by sciyoshi** [comment]
Thanks @andrewgodwin, we've worked around this by reimplementing `whitenoise`'s static file handling as an ASGI handler. It still think it would be nice for this behavior to be explicitly documented somewhere.

**Comment by typistX** [comment]
@sciyoshi Care to elaborate more how you guys solved this? I'm experiencing the same thing on Heroku and it's killing my web-app.

**Comment by sciyoshi** [comment]
@typistX - we wrote our own ASGI handler that serves middleware (pretty short, under 100 lines of code), @ericls could give more details about that. There's also a [PR in Whitenoise](https://github.com/evansd/whitenoise/pull/181) that seems to be similar, maybe you can give that a shot as well.

**Comment by alsib** [comment]
Woops, sorry about that. 

I'm experience performance loss when serving template too. 

Would you have any idea ?
