### ISSUE TITLE
warnings/errors logged after disconnecting async http request

### ISSUE THREAD

**Issue by jkarneges** [django/channels#1049]
Hi,

I'm using version 2.1.1. I set up a simple consumer (almost the same as the SSE example from the docs). If I use runserver, and connect a client and then disconnect, some ugly logging occurs some time after.

10 seconds after disconnecting, there's a warning:

```
2018-05-19 21:20:20,065 - WARNING - server - Application instance <Task pending coro=<AsyncHttpConsumer.__call__() running at /home/justin/dev/django-eventstream/examples/chat/venv3/lib/python3.6/site-packages/channels/generic/http.py:25> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb79ead45b8>()]>> for connection <WebRequest at 0x7fb79fb2ff28 method=GET uri=/events/ clientproto=HTTP/1.1> took too long to shut down and was killed.
```

A client disconnecting from a stream is something I would consider to be normal behavior, and should probably not cause noisy logging.

60 seconds after disconnecting, there's an exception:

```
Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /home/justin/dev/django-eventstream/examples/chat/venv3/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py:287
handle: <TimerHandle when=275136.787314338 AsyncioSelectorReactor.callLater.<locals>.run() at /home/justin/dev/django-eventstream/examples/chat/venv3/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py:287>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/justin/dev/django-eventstream/examples/chat/venv3/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "/home/justin/dev/django-eventstream/examples/chat/venv3/lib/python3.6/site-packages/daphne/server.py", line 276, in timeout_checker
    protocol.check_timeouts()
  File "/home/justin/dev/django-eventstream/examples/chat/venv3/lib/python3.6/site-packages/daphne/http_protocol.py", line 260, in check_timeouts
    self.basic_error(503, b"Service Unavailable", "Application failed to respond within time limit.")
  File "/home/justin/dev/django-eventstream/examples/chat/venv3/lib/python3.6/site-packages/daphne/http_protocol.py", line 293, in basic_error
    (b"Content-Type", b"text/html; charset=utf-8"),
  File "/home/justin/dev/django-eventstream/examples/chat/venv3/lib/python3.6/site-packages/daphne/http_protocol.py", line 208, in handle_reply
    raise ValueError("HTTP response has already been started")
ValueError: HTTP response has already been started
```

That said, the warnings and errors appear to be harmless. New connections work as expected.

Here's the consumer:

```py
class EventsConsumer(AsyncHttpConsumer):
    async def handle(self, body):
        await self.send_headers(headers=[
	    ("Cache-Control", "no-cache"),
            ("Content-Type", "text/event-stream"),
        ])
        while True:
            payload = "data: %s\n\n" % datetime.now().isoformat()
            await self.send_body(payload.encode("utf-8"), more_body=True)
            await asyncio.sleep(1)
```

**Comment by jkarneges** [comment]
Ah, thank you. And here's the relevant docs about handling disconnects:
https://channels.readthedocs.io/en/latest/topics/consumers.html#closing-consumers

It says "the generic consumers do this for you" which is not quite true. `AsyncHttpConsumer` doesn't raise `StopConsumer` in reaction to `http.disconnect`. It also seems that a `http.disconnect` message isn't posted to the consumer if the client disconnects after sending the complete request.

**Comment by erm** [comment]
I see. I'm not particularly familiar with the Channels generics, but a potential streaming implementation of the `AsyncHttpConsumer` could like this:

```python
import asyncio
from datetime import datetime

from channels.generic.http import AsyncHttpConsumer

class AsyncStreamingHttpConsumer(AsyncHttpConsumer):

    async def __call__(self, receive, send):
        self.send = send
        body = []
        self.is_streaming = False
        while True:
            message = await receive()
            if message["type"] == "http.disconnect":
                self.streaming = False
                return
            else:
                if "body" in message:
                    body.append(message["body"])
                if not message.get("more_body"):
                    self.is_streaming = True
                    asyncio.get_event_loop().create_task(self.handle(b"".join(body)))

    async def handle(self, body):
        await self.send_headers(headers=[
            ("Cache-Control", "no-cache"),
            ("Content-Type", "text/event-stream"),
        ])
        while self.is_streaming:
            payload = "data: %s\n\n" % datetime.now().isoformat()
            await self.send_body(payload.encode("utf-8"), more_body=True)
            await asyncio.sleep(1)
        return
```

This way the loop that handles the streaming is doesn't block the application queue and can be returned when a disconnect message is received.

**Comment by jkarneges** [comment]
Thanks, I've confirmed that works. Backgrounding `handle` so that `__call__` returns makes it so `http.disconnect` does now get delivered to the object. Good to know this issue doesn't go very deep. Probably AsyncHttpConsumer should be updated accordingly.

**Comment by andrewgodwin** [comment]
Yes, the auto-close stuff only works if you don't block `__call__` like that; you should use `create_task` in handle if you want to run something ongoing. I'll update the docs to note that.

**Comment by jkarneges** [comment]
If create_task is used in handle, there still needs to be a way to know when a disconnect occurred so the task can be stopped, I think? Else the user still has to override __call__.

**Comment by andrewgodwin** [comment]
Yes, correct, if you launch your own background coroutines you also need to clean them up (I added this note into the docs too)

**Comment by erm** [comment]
This seems to work fine without having to override `__call__` or explicitly handling the state:

```python
class AsyncStreamingHttpConsumer(AsyncHttpConsumer):

    async def handle(self, body):
        await self.send_headers(headers=[
            ("Cache-Control", "no-cache"),
            ("Content-Type", "text/event-stream"),
        ])
        asyncio.get_event_loop().create_task(self.streamer())

    async def streamer(self):
        while True:
            payload = "data: %s\n\n" % datetime.now().isoformat()
            await self.send_body(payload.encode("utf-8"), more_body=True)
            await asyncio.sleep(1)
```

**Comment by andrewgodwin** [comment]
That will still leave the `streamer` task running, though. You should get warnings about non-cleaned-up tasks when you finally exit the server.

**Comment by erm** [comment]
Yeah, that's what I would expect to happen, and I wouldn't recommend not explicitly cleaning the tasks up. I had just noticed that when running with `daphne` it doesn't seem to raise any errors, though with `uvicorn` it will raise an exception because it will attempt to write to an empty transport - perhaps there is something additional `daphne` is doing.

**Comment by erm** [comment]
There may also still be a problem when not overriding `__call__` that @jkarneges mentions: how to retrieve the `http.disconnect` message to modify the state and cleanup the task? 

Would it be a good idea to add a `disconnect()` method to the consumer that users can implement themselves if they extend the class/run background tasks? It could be triggered when an `http.disconnect` message is received and default to the current behavior. Or is the recommended approach to override `__call__` in these cases?

**Comment by andrewgodwin** [comment]
Yes, a disconnect method that's overrideable is a good idea, I think. Could you open a separate issue to track that, and then we can put it in the list of things to work on?

**Comment by jkarneges** [comment]
I spoke too soon. @erm's first AsyncStreamingHttpConsumer example will still produce the "HTTP response has already started" Exception if two connections are made, one is closed, and then after about 60 seconds. Is that class still not cleaning up properly somewhere, or is there possibly a deeper bug?

**Comment by erm** [comment]
It is likely that there is more required to properly handle the disconnect and cleanup - that example isn't very robust and was mainly for demonstrating how the stream could be managed. I'll open a new issue for making an overridable disconnect method on the class then it will be easier to test a complete example when that is implemented.

**Comment by jkarneges** [comment]
Even with the disconnect handler, I'm still getting the error. This issue should be re-opened I think.

Channels version 4425ba165b7c588147f968b3a1d520d292676204, asgiref 2.3.2, daphne 2.1.1.

Here's my code:

```py
class EventsConsumer(AsyncHttpConsumer):
    async def handle(self, body):
        await self.send_headers(headers=[
            ("Cache-Control", "no-cache"),
            ("Content-Type", "text/event-stream"),
        ])
        self.is_streaming = True
        asyncio.get_event_loop().create_task(self.stream())
        print('end handle')

    async def stream(self):
        while self.is_streaming:
            payload = "data: %s\n\n" % datetime.now().isoformat()
            await self.send_body(payload.encode("utf-8"), more_body=True)
            await asyncio.sleep(1)
        print('end stream')

    async def disconnect(self):
        self.is_streaming = False
        print('disconnect')
```

Steps to reproduce: create 2 client connections, then disconnect one of them.

The printed output is as expected:

```
140372095273840 end handle
140372095371248 end handle
140372095371248 disconnect
140372095371248 end stream
```

However, after 60 seconds, the following exception is logged:

```
Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /home/justin/dev/django-eventstream/examples/chat/venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py:287
handle: <TimerHandle when=26573.539875226 AsyncioSelectorReactor.callLater.<locals>.run() at /home/justin/dev/django-eventstream/examples/chat/venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py:287>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/justin/dev/django-eventstream/examples/chat/venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "/home/justin/dev/django-eventstream/examples/chat/venv/lib/python3.6/site-packages/daphne/server.py", line 276, in timeout_checker
    protocol.check_timeouts()
  File "/home/justin/dev/django-eventstream/examples/chat/venv/lib/python3.6/site-packages/daphne/http_protocol.py", line 260, in check_timeouts
    self.basic_error(503, b"Service Unavailable", "Application failed to respond within time limit.")
  File "/home/justin/dev/django-eventstream/examples/chat/venv/lib/python3.6/site-packages/daphne/http_protocol.py", line 293, in basic_error
    (b"Content-Type", b"text/html; charset=utf-8"),
  File "/home/justin/dev/django-eventstream/examples/chat/venv/lib/python3.6/site-packages/daphne/http_protocol.py", line 208, in handle_reply
    raise ValueError("HTTP response has already been started")
ValueError: HTTP response has already been started
```

**Comment by andrewgodwin** [comment]
@jkarneges Are you absolutely sure your application is closing its coroutine properly?

**Comment by erm** [comment]
Not sure, but it could be that `StopConsumer()` needs to be raised in the `disconnect()` method and then handled in the `__call__`. 

Try to reproduce the error with this:

```python
from channels.consumer import AsyncConsumer
from channels.exceptions import StopConsumer


class AsyncHttpConsumer(AsyncConsumer):
    """
    Async HTTP consumer. Provides basic primitives for building asynchronous
    HTTP endpoints.
    """

    async def __call__(self, receive, send):
        """
        Async entrypoint - concatenates body fragments and hands off control
        to ``self.handle`` when the body has been completely received.
        """
        self.send = send
        body = []
        try:
            while True:
                message = await receive()
                if message["type"] == "http.disconnect":
                    await self.disconnect()
                else:
                    if "body" in message:
                        body.append(message["body"])
                    if not message.get("more_body"):
                        await self.handle(b"".join(body))
        except StopConsumer:
            pass

    async def send_headers(self, *, status=200, headers=None):
        """
        Sets the HTTP response status and headers. Headers may be provided as
        a list of tuples or as a dictionary.
        Note that the ASGI spec requires that the protocol server only starts
        sending the response to the client after ``self.send_body`` has been
        called the first time.
        """
        if headers is None:
            headers = []
        elif isinstance(headers, dict):
            headers = list(headers.items())

        await self.send({
            "type": "http.response.start",
            "status": status,
            "headers": headers,
        })

    async def send_body(self, body, *, more_body=False):
        """
        Sends a response body to the client. The method expects a bytestring.
        Set ``more_body=True`` if you want to send more body content later.
        The default behavior closes the response, and further messages on
        the channel will be ignored.
        """
        assert isinstance(body, bytes), "Body is not bytes"
        await self.send({
            "type": "http.response.body",
            "body": body,
            "more_body": more_body,
        })

    async def send_response(self, status, body, **kwargs):
        """
        Sends a response to the client. This is a thin wrapper over
        ``self.send_headers`` and ``self.send_body``, and everything said
        above applies here as well. This method may only be called once.
        """
        await self.send_headers(status=status, **kwargs)
        await self.send_body(body)

    async def handle(self, body):
        """
        Receives the request body as a bytestring. Response may be composed
        using the ``self.send*`` methods; the return value of this method is
        thrown away.
        """
        raise NotImplementedError(
            "Subclasses of AsyncHttpConsumer must provide a handle() method."
        )

    async def disconnect(self):
        """
        Overrideable place to run disconnect handling. Do not send anything
        from here.
        """
        pass


class EventsConsumer(AsyncHttpConsumer):

    async def handle(self, body):
        await self.send_headers(headers=[
            ("Cache-Control", "no-cache"),
            ("Content-Type", "text/event-stream"),
        ])
        self.is_streaming = True
        asyncio.get_event_loop().create_task(self.stream())
        print('%s end handle' % id(self))

    async def stream(self):
        while self.is_streaming:
            payload = "data: %s\n\n" % datetime.now().isoformat()
            await self.send_body(payload.encode("utf-8"), more_body=True)
            await asyncio.sleep(1)
        print('%s end stream' % id(self))

    async def disconnect(self):
        self.is_streaming = False
        print('%s disconnect' % id(self))
        raise StopConsumer()

```

**Comment by erm** [comment]
@jkarneges 

This may work:

```python
class EventsConsumer(AsyncHttpConsumer):
    async def handle(self, body):
        await self.send_headers(headers=[
            ("Cache-Control", "no-cache"),
            ("Content-Type", "text/event-stream"),
        ])
        self.is_streaming = True
        self.stream_task = asyncio.get_event_loop().create_task(self.stream())
        self.stream_task.add_done_callback(self.stream_complete)
        print('%s end handle' % id(self))

    async def stream(self):
        while True:
            payload = "data: %s\n\n" % datetime.now().isoformat()
            await self.send_body(payload.encode("utf-8"), more_body=True)
            await asyncio.sleep(1)
            if not self.is_streaming:
                break

    async def disconnect(self):
        self.is_streaming = False
        print('%s disconnect' % id(self))

    def stream_complete(self, task):
        try:
            task.exception()
        except Exception as error:
            pass
        print('%s stream complete callback' % id(self))

```

**Comment by jkarneges** [comment]
Hi @erm, I tried this but it doesn't change anything. I don't think the issue I'm reporting is cleanup-related. The stream coroutine is intentionally long-running, and the error appears while the client is still connected.

I think the issue here is Daphne's timeout checker, and that it tries to timeout/close any HTTP response that lasts longer than 60 seconds.

**Comment by andrewgodwin** [comment]
Oh, right, yes, it does. I need to remove the default HTTP timeout. You can disable it by passing a much longer timeout on the command line for now.

**Comment by andrewgodwin** [comment]
OK, just pushed up a commit that removes the timeout by default and additionally makes it not error if the timeout happens mid-response.

**Comment by jkarneges** [comment]
Great, I've confirmed with Daphne master that the connection doesn't timeout now, as long as I run daphne separately.

Using `runserver` still results in the connection getting killed after 60 seconds, with output "Application timed out while sending response". I see the 60 second default being set in Channels' `runserver.py`. Probably this should default to unset?

**Comment by andrewgodwin** [comment]
I've pushed a change up to unset that too.

**Comment by jkarneges** [comment]
Thanks, all seems to be well now!

**Comment by VladimirPetrov239** [comment]
@andrewgodwin 
@erm 
Hello! It seems I have similar problem.
I'm also using nice tutorial at hhttps://channels.readthedocs.io/en/latest/introduction.html about DjangoChannels. All understood, wrote my own one (suppose the same as there), everything is working, thanks for clear explanation on the site! 
However, I ran into a problem: when updating the chat page, the server throws this exception, moreover not in 60 seconds, but immediately (and after that I can't send messages, so that's quite harmful):

Exception in callback AsyncioSelectorReactor.callLater..run() at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py:287 handle: .run() at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py:287> Traceback (most recent call last): File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 81, in _run self._context.run(self._callback, *self._args) File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 290, in run f(*args, **kwargs) File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/daphne/server.py", line 229, in application_checker exception = application_instance.exception() asyncio.exceptions.CancelledError

(I am using WebsocketConsumer, python 3.8.2)

Actually, I suppose there is a problem with the disconnection with the server when updating the page. I tried to solve it myself but unfortunately didn't succeed :( Could anybody please help me?
