### ISSUE TITLE
ability to include kwargs in routings

### ISSUE THREAD

**Issue by jkarneges** [django/channels#1050]
Hi,

I'm looking at porting our library, [Django EventStream](https://github.com/fanout/django-eventstream), to Channels.

Django EventStream lets the user serve Server-Sent Events endpoints without writing any code, by specifying the paths and associated data channels in `urls.py`, like this:

```py
urlpatterns = [
    url(r'^foo/events/', include(django_eventstream.urls), {'channels':['foo']})
]
```

This means if a client connects to `/foo/events/`, they will be listening for data on channel `foo`. We're able to make this work because the the third argument to `url` gets passed along to the executed view as kwargs.

However, if such additional data is including in an analogous `routing.py`:

```py
urlpatterns = [
    url(r'^foo/events/', AuthMiddlewareStack(
        URLRouter(django_eventstream.routing.urlpatterns)
    ), {'channels': ['foo']}),
    url(r'', AsgiHandler),
]
```

Then this data does not seem to be passed along to the consumer. Probably it should be put in the scope object somewhere?

**Comment by andrewgodwin** [comment]
The kwargs from the pattern matching go into `scope["url_route"]["kwargs"]` - I think it would make sense to put these in there as well.

**Comment by jkarneges** [comment]
I think PR #1030 might have implemented this?
