### ISSUE TITLE
Memory leak when using channels_redis with daphne or runserver

### ISSUE THREAD

**Issue by bydesign** [django/channels#1052]
I have a websocket consumer and a huey job that runs every 30 seconds, pushing data to the frontend. However, over time the memory increases on the protocol server with each data push. In production it starts around 100MB growing to eventually surpass the 512MB limit of my Heroku server. The heroku server reboots once the usage gets to 1024MB. On my local I've watched it grow from 70MB to 300MB. In production this can happen in as little time as 2 hours. Note that the huey process memory usage stays pretty constant as does the redis server.

Here's my setup:
Localhost: MacOS 10.13.4
Production: Heroku
Python 3.6.5
Django==2.0.4
channels==2.0.2
channels-redis==2.1.1
asgi-redis==1.4.3
asgiref==2.3.0
django-redis==4.9.0
redis==2.10.6
daphne==2.1.0
Twisted==17.9.0
huey==1.9.1

settings.py
`
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
        },
    },
}
`
consumers.py - note that I've tried this using WebsocketConsumer, AsyncJsonWebsocketConsumer, and AsyncWebsocketConsumer with the same result.
`
class DashboardConsumer(WebsocketConsumer):
    def connect(self):
        self.slug = self.scope['url_route']['kwargs']['slug']
        board = Dashboard.objects.prefetch_related('sites').get(slug=self.slug)
        self.user = UserAccount.objects.filter(account=board.account)[0].user
        # ... some error handling omitted ...
        self.accept()

        # add consumer to group
        async_to_sync(self.channel_layer.group_add)(
            self.slug, 
            self.channel_name
        )

        # loop over sites and send data
        for site in board.sites.all():
            message = {
                'board_slug': self.slug,
                'user_id': self.user.id,
                'analytics_account': site.analytics_account,
                'analytics_property': site.analytics_property,
                'analytics_view': site.analytics_view,
                'first_time': True,
            }
           # this call starts the huey job if not already started
            site_tick(message, channel_name=self.channel_name)

    # Receive message from huey job
    def update_dashboard(self, event):
        # Send message to WebSocket
        self.send(text_data=json.dumps(
            {
                'site': event['site'],
                'users': event['users'],
                'sessions': event['sessions'],
            }
        ))
`

tasks.py - this is part of what huey calls from a separate process every 30 seconds. Data size can be pretty big (30-100K characters)
`
async_to_sync(channel_layer.group_send)(
                site_board_slug, 
                {
                    "type": "update_dashboard",
                    'site': site.id,
                    'users': users_list,
                    'sessions': session_count,
                }
            )
`

I would expect that no matter how much data is passed through the consumer its memory usage would remain constant. I couldn't find anyone else experiencing the same problem. Please advise.

**Comment by andrewgodwin** [comment]
It's hard to tell what's causing memory leaks up front, and if it's a core Channels problem or your code - without further details or a specific thing that needs fixing, I can't do anything and will have to close this.

Have you tried progressively removing parts of the consumer to see if the memory leak goes away? Or running a memory profiler on it?

**Comment by bydesign** [comment]
@andrewgodwin Ok, my third attempt at running tracemalloc finally resulted in something useful. I'm running very similar code, basically having a worker process push the contents of Moby Dick through a channel to a websocket in the browser (3 browsers, 3 consumers). Over 20 minutes the memory usage grew from 70MB to over 500MB. The only memory item that changed throughout that time was this one:
`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/channels_redis/core.py:397: size=6914 KiB, count=65, average=106 KiB`
... 20 minutes later ...
`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/channels_redis/core.py:397: size=509 MiB, count=3743, average=139 KiB`

That line of code is in the deserialize function in core.py:
`return msgpack.unpackb(message, encoding="utf8")`

The worker process I'm running is basically calling this:
`
    channel_layer = get_channel_layer()
    mobydick = open('templates/moby-dick.txt')
    data = mobydick.read()

    async_to_sync(channel_layer.group_send)(
        'channel-group-name', 
        {
            "type": "update.dashboard",
            'users': data,
        }
    )
`

The consumer function being called looks like this:
`
async def update_dashboard(self, event):
        await self.send_json({
            'users': event['users'],
        })
        # memory trace happens here
`

**Comment by andrewgodwin** [comment]
Hm, I don't see what on that line of code could be causing memory leakage, though, that's the thing. Did you try changing it to see if that changes the memory usage profile?

**Comment by bydesign** [comment]
@andrewgodwin I just found another clue. On a clean server start I can load the connecting page (first channel connection) the first time and it will run just fine. It's only once I reload the page (disconnecting a channel) that the memory leak starts to appear. Maybe I'm not cleaning the channel up properly? Here's my disconnect function:

`async def disconnect(self, close_code):
        # Called when the socket closes
        slug = self.scope['url_route']['kwargs']['slug']
        self.channel_layer.group_discard(slug, self.channel_name)`

**Comment by bydesign** [comment]
@andrewgodwin wow, I feel like an idiot. I added `await` to the group_discard call and it appears to be pretty stable at least with initial testing. I'll do further testing.

On a side note, the [docs say](https://channels.readthedocs.io/en/latest/topics/channel_layers.html#groups) that channels "Provides group expiry for clean-up of connections whose disconnect handler didn’t get to run (e.g. power failure)" How long does it take for the group to clean up those connections?

**Comment by bydesign** [comment]
Just confirmed that this fixed the memory leak, you can close this ticket. Thanks for your help.

**Comment by andrewgodwin** [comment]
No problem - glad we could quash it.

**Comment by DiegoArrieta** [comment]
Thanks for this!!!!

**Comment by vishal7x7** [comment]
helpful
