### ISSUE TITLE
is it possible to send files and pictures in Chat application?

### ISSUE THREAD

**Issue by trDjango** [django/channels#1053]
Hello there,
It is possible to send files and pictures in Chat application.
Thanks
Note:this link([closed issue](https://github.com/django/channels/issues/11)) is mentioned but I am asking if the second version has been changed

**Comment by andrewgodwin** [comment]
Large file uploads are still inefficient, but they work. You will have to build them using normal Django methods, though (browsers don't have good support for sending files over WebSockets)

**Comment by trDjango** [comment]
@hishnash very good suggestion, thanks.

**Comment by zeyadShapan** [comment]
@hishnash I did the first part but I can't figure out how to load the images uploaded as a normal text message (without having to refresh the page)
