### ISSUE TITLE
Missing information for Redis Connections

### ISSUE THREAD

**Issue by iMerica** [django/channels#1054]
Currently the docs for setting up channel layers include this example snippet:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis-server-name", 6379)],
        },
    },
}
```

This might be helpful for people who are kicking the tires locally on Docker-Compose, but in a production environment, Redis URLs have many more parts. Can someone share how they've setup their URL configuration when using a Redis-as-a-service like Redis Labs or Elastic Cache (e.g using every option in the URI scheme) ?

**Comment by kevinqqnj** [comment]
set your `REDIS_URL` variable in your server, e.g.`REDIS_URL=redis://username:passwd@host:6379/0`

Then update your `# settings.py`
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://redis:6379')],
        },
    },
}
```

**Comment by iMerica** [comment]
Thanks @kevinqqnj
