### ISSUE TITLE
Errors: Task was destroyed but it is pending

### ISSUE THREAD

**Issue by brianmay** [django/channels#1057]
Since upgrading to Channels 2, I get a number of these errors. I suspect this happens when restarting the deployed instance:

```
Task was destroyed but it is pending!
task: <Task pending coro=<AsgiHandler.__call__() running at /usr/local/lib/python3.6/site-packages/channels/http.py:180> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff75c2d5d68>()]>>
```

**Comment by andrewgodwin** [comment]
This is an incredibly common error for asyncio apps.

- Does this happen every single restart? Or just sometimes?
- Does your code ever call create_task or ensure_future?
- What versions are you running of `daphne`, `channels`, `asgiref`, `channels-redis`, and `twisted`?

**Comment by brianmay** [comment]
Yes, I have seen this a lot in my own code. The only difference here is this does not appear to be my own code...

Only seems to happen when shutting down the docker container on deployment. Seems to happen repeatedly. So far my attempts to reproduce it on my own box have failed.

Routing is pretty simple:

```
application = ProtocolTypeRouter({

    "websocket": AuthMiddlewareStack(
        URLRouter([
            url("^ws/$", CumulocityConsumer),
        ])
    ),

    "channel": ChannelNameRouter({
        "lcl": LclConsumer,
    }),

})
```
Latest versions of everything:

```
asgiref==2.3.0
channels_redis==2.2.1
channels==2.1.1
daphne==2.1.1
```

I noticed that Twisted isn't pinned, however, I imagine it will be the latest version, which I think is Twisted==17.9.0

**Comment by andrewgodwin** [comment]
As with your other ticket, unless it's reproduceable it's not fixable and I won't be able to tackle this! Will leave this open for a few weeks in case it's possible to get a reproduceable case.

**Comment by brianmay** [comment]
It is reproducible, and it occurs frequently; we are going numerous errors of this type. It just hasn't happened on my local development box as of yet.

**Comment by andrewgodwin** [comment]
Well, reproduceable in this case means I can produce it on demand to fix it, unfortunately.

**Comment by brianmay** [comment]
Looking at my logs, this always seems to happen 5-6 minutes after every daphne error https://github.com/django/daphne/issues/205. So I will try to deploy the master version of Dahpne, and see if that helps this also.

**Comment by brianmay** [comment]
Closing this for now as it no longer occurring for me - at least with daphne master. Will reopen if the problem reoccurs.

**Comment by rgill02** [comment]
Happened for me when i was running tests with pytests and forgot to disconnect my communicators at the end of each test
