### ISSUE TITLE
URLs in channels tutorial are based on Django 1.11 but requirements.txt has Django 2.0. As a result some URLs don't work in Django 2.0.

### ISSUE THREAD

**Issue by amakarudze** [django/channels#1061]
I am learning to use channel and came across this issue with the Channels Tutorial Documentation.

#chat/urls.py

`urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
] `

Results in a page not found. 
![channels issue](https://user-images.githubusercontent.com/13593285/40576404-f0caa950-60f5-11e8-9303-2d7592c3555c.PNG)

should be updated to 

`urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'(?P<room_name>[^/]+)/$', views.room, name='room'),
] `

or use `path` keyword.

Am using Django 2.0

**Comment by andrewgodwin** [comment]
Hm, now I'm looking at this side-by-side, it's strange that it only worked without the `^` - Django URLs are meant to work OK like that when they are included.

If you still have the same file around, did going to just `/chat/` work?

**Comment by amakarudze** [comment]
Yes, I still have the file. Whenever I have the `^` the code breaks. Not sure about changes in 2.0 because I haven't got myself to read the release notes yet.

Yes, going to /chat/ works, it redirects to a chatroom, without a name though.

**Comment by andrewgodwin** [comment]
I'm going to have to put this aside and investigate it (or get someone else to) a bit later on, since I can't reproduce it locally straight away.

**Comment by mynameisbenzo** [comment]
So in the channels tutorial you have:

`url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),`

...and it looks like if you change that to:

`url(r'^/(?P<room_name>[^/]+)/$', views.room, name='room'),`
`      ^`

then all is well.

**Comment by spielmannj** [comment]
I agree with @mulka , from the screenshot it looks like the file was not included correctly. The tutorial worked for me when I worked through it a few days ago.

**Comment by spielmannj** [comment]
However, after thinking about it for a minute, I still think we should move to `path` instead of `url` in the tutorial.

**Comment by sabuhish** [comment]
You can do with new version of url as well like  follows:
```
# url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
```
you can write both of them below:
```
    path('<str:room_name>/', views.room, name="room"),
    path('<room_name>/', views.room, name="room"),

```

**Comment by sgpritam** [comment]
from django.urls import path
from .views import index, room

app_name = 'chat'

urlpatterns = [
    path('', index, name='index')
    path('<str:room_name>/', room, name="room"),
]
