### ISSUE TITLE
Docker is not mentioned in dependencies but is required in part 2 of the tutorial.

### ISSUE THREAD

**Issue by amakarudze** [django/channels#1063]
Part 2 of the tutorial mentions Docker but it is not mentioned in the dependencies or installation/setup section of the documentation. This may be confusing to a new developer. I would suggest adding that to the dependencies required in setting up the project.
![channels issue 2](https://user-images.githubusercontent.com/13593285/40576851-43c532c2-60fd-11e8-893d-e425488a9115.PNG)

**Comment by andrewgodwin** [comment]
So it looks like there is a section on installing Docker at the top of Part 1, but it's just a single paragraph that is hard to miss. I will make the whole section a bit easier to read.

**Comment by changeling** [comment]
Out of curiosity, why not simply go with redis-server? Docker adds an additional complication to an otherwise wonderfully just-the-facts learning experience.

**Comment by carltongibson** [comment]
@changeling I'd **guess** "because Windows", i.e. as far as I know, you can't just download and run redis... — but maybe an alternate in the docs would be a good addition, since if you're on a compatible system it's a pretty easy install.

**Comment by changeling** [comment]
That seems a worthwhile approach. I skipped Docker and just ran redis directly, but would have been frustrated if I'd had to go the Docker route. I do use it occasionally, but it's definitely a non-trivial dependency, particularly for newbies.

**Comment by carltongibson** [comment]
OK, well a PR is always welcome! 🙂
