### ISSUE TITLE
how can I close a connection from outside?

### ISSUE THREAD

**Issue by ruoshui1314** [django/channels#1066]
hi
   thanks for your wonderful module for websocket. There is a scene that I would like hold just one connection in one room so the pre-connection should be closed while the new websocket is connected.
I try to close outside or close pre-connection while get a new connection in current room.
Any suggestion that I can figure it out?
I just think out one way that store all websockets and remove it while get the newer connection.

**Comment by ruoshui1314** [comment]
Is there a way that I can choose which connection to close ?

**Comment by andrewgodwin** [comment]
You can close connections only from inside the consumer instance that is attached to them; how you communicate to the instances to work out which one to close is something you have to solve yourself (either via a database or some other communication mechanism).

**Comment by ruoshui1314** [comment]
ok~3q
