### ISSUE TITLE
channels 2 websocket disconnect on exception

### ISSUE THREAD

**Issue by sebhaase** [django/channels#1068]
Hi, after migrating to channels 2 I noticed that an exception in my websocket receive (JsonWebsocketConsumer)  immediately disconnects the client.
Is this change from channels 1 anywhere documented ?  And: is it really desired  ?
Thx. -Sebastian

**Comment by andrewgodwin** [comment]
It was not documented anywhere as a change - I've added it to the upgrade guide now. It was intentional; if you don't want errors to close the socket, catch them yourself rather than letting them bubble up into the server :)

**Comment by sebhaase** [comment]
Thanks for the info. That is exactly what I did:
```
    async def receive_json(self, event):
        import traceback
        try:
            await self.receive_json_1(event)
        except:
            traceback.print_exc()

    async def receive_json_1(self, event):
        # ASGI WebSocket packet-received and send-packet message types
        # both have a "text" key for their textual data.
        print(event)
```
Maybe you want to add this snippet to your documentation - even though I'm very insecure regarding async and await (Do I really need the async for the 2nd ("inside") function ?)

Thx, Sebastian,
