### ISSUE TITLE
Consumers should be able to listen on non-default channel layers

### ISSUE THREAD

**Issue by stasdavydov** [django/channels#1069]
I have two channel layers defined in settings: "default" and "progress" (with short lifetime of messages)
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
    "progress": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
            "prefix": "progress",
            "expiry": 5,
        },
    },
}
```

The routing is:
```
application = ProtocolTypeRouter({
...
    "channel": ChannelNameRouter({
        'o-ready': Consumer,
        'o-progress': ProgressConsumer,
    })
})
```

I run two workers: one for "o-ready" channel and one for "o-progress". 
The issue is when the `ProgressConsumer` is instantiated and receiving a message the `self.channel_layer` points to "default" layer instead of "progress" layer. The reason of this the line 42 of channels/consumer.py:

[https://github.com/django/channels/blob/master/channels/consumer.py#L42](url)
```
# Initalize channel layer
self.channel_layer = get_channel_layer()   # <-- line 42
```
It seems the channel_layer should be initialized with the channel_layer from worker to use correct layer when send message from consumer via `self.send`.

Windows, Python 3.6.5, channels 2.1.1, channels-redis 2.1.1, django 2.0.5

**Comment by andrewgodwin** [comment]
Yeah, the `channel_layer` attribute is fixed to the default layer for now; multi-layer support is very thin in Channels 2. I'll turn this into a feature request ticket and leave it open for future implementation, though it likely has to be an attribute on the consumer, not a function of the worker.

**Comment by ZijianHe** [comment]
Hi @andrewgodwin , I was wondering if there is any chance I can try to implement this feature?

**Comment by andrewgodwin** [comment]
@ZijianHe You're more than welcome to work on it! What sort of guidance do you need?

**Comment by ZijianHe** [comment]
@andrewgodwin Thanks Andrew. I figure I have all information to get started as it a simple one and I think I will be able to make a pr for it within today

**Comment by ross-weir** [comment]
Hi @andrewgodwin 

Looks like this one is no longer being worked on? If this is the case can I have a go at it?

**Comment by andrewgodwin** [comment]
@ross-weir Feel free to have a crack - you'll want to look at the previous PR and my comments on it too I suspect.
