### ISSUE TITLE
I want to send messages to all the members of the group

### ISSUE THREAD

**Issue by Mu-Cheng** [django/channels#1070]
`channel_layer =  layers.get_channel_layer()`
`        channel_layer.group_send(
            "rs_loging",
            {
                "type": "chat.message",
                "text": str(pos*100//sum),
            },
        )`
It won't work. What should I do?

**Comment by andrewgodwin** [comment]
That looks correct to me - do you have a corresponding chat_message method defined on consumers listening to that group?

Closing the bug as it’s support rather than a bug.

**Comment by Mu-Cheng** [comment]
**
class RecommendConsumer(AsyncWebsocketConsumer):

    async def connect(self):
        await self.accept()
        await self.channel_layer.group_add("rs_loging", self.channel_name)

    async def chat_message(self, event):
        await self.send(text_data=event["text"])

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard("rs_loging", self.channel_name)
        await self.close()

**
It's my consumer class. How do I listen to this group?

**Comment by andrewgodwin** [comment]
You seem to be listening to it correctly. Did you set `CHANNEL_LAYERS` correctly? And where are you sending the message from?
