### ISSUE TITLE
Inconsistency in scope encoding

### ISSUE THREAD

**Issue by imbolc** [django/channels#1071]
I found some part of scope variables are not decoded (headers, query_string, etc) is it intentional decision or I can provide a PR to make all of them decoded?

**Comment by andrewgodwin** [comment]
Some parts are deliberately not decoded as there's no specified encoding in the HTTP standard for them, or they need to stay encoded for some other reason. See http://asgi.readthedocs.io/en/latest/specs/www.html for details about what should be what.
