### ISSUE TITLE
Basic setup fails on testing on Shell

### ISSUE THREAD

**Issue by Six-wars** [django/channels#1072]
I'm trying out the basic chatsys with channels, so far it worked ok till the step of testing it out on the shell to make sure connections work correctly. Got an error listed with all the code [here on stackoverflow](https://stackoverflow.com/questions/50695786/django-channels-testing-fails)

**Comment by andrewgodwin** [comment]
That error does really mean your Redis is not running correctly - just check your firewalls and that you can open the port directly using something like `telnet 1.2.3.4 6379`

**Comment by Six-wars** [comment]
this is on a google cloud ubuntu 18.04 clean vm... the ip is 35.185.80.98 so this is what I've tried

    muiruri_samuel@train:~$ telnet 35.185.80.98 6379
    Trying 35.185.80.98...
    telnet: Unable to connect to remote host: Connection timed out

Unless Google locks the firewall or a port needs to be opened for it.

**Comment by andrewgodwin** [comment]
I'm afraid I don't know how to solve this - it's purely a system administration issue, and not something Channels can help you with! Hopefully you can find help elsewhere.

**Comment by bastbnl** [comment]
Oh well... Try to connect to 127.0.0.1 instead of 35.185.80.98 in your settings. Redis may listen on 127.0.0.1 only.

Also - if you can - run `netstat -tulpn` to see if redis is running on the VM you're using. Look for port 6397.
