### ISSUE TITLE
Backwards incompatible change in 2.1

### ISSUE THREAD

**Issue by sebhaase** [django/channels#1073]
Is it possible that there is another backwards incompatible change in 2.1:
I get: `Cannot import BACKEND 'channels_redis.core.RedisChannelLayer' specified for default`

If I downgrade using `pip install ` to 2.0 it works again... Would I have to change my `settings.py` ?

Thanks, Sebastian

**Comment by andrewgodwin** [comment]
I don't believe there is, no. Could you post the full traceback? It's likely there's another ImportError that's happening.

**Comment by sebhaase** [comment]
`pip install -U channels`
now installed 
`channels-2.1.1`
And now it seems to start without problems...
Thanks,.

**Comment by andrewgodwin** [comment]
OK!
