### ISSUE TITLE
pending_message_store.send_and_flush missing in Channels 2

### ISSUE THREAD

**Issue by sebhaase** [django/channels#1074]
How can we send pending messages BEFORE doing a `sleep()` in Channels 2
I get:
`No module named 'channels.message'`
Thanks, Sebastian.

**Comment by andrewgodwin** [comment]
Channels 2 does not buffer messages - everything is sent immediately. Any flushing/sending pending messages code you may have seen from Channels 1 is no longer needed.

**Comment by sebhaase** [comment]
Thanks for the info. I think my mistake was also that I was using
```
import time
time.sleep(3)
```
instead of
```
import asyncio
await asyncio.sleep(3)
```
Is this really needed like that ?
Thx.

**Comment by andrewgodwin** [comment]
If you want to sleep asynchronously, then yes, you need to `await asyncio.sleep(3)`.

**Comment by sebhaase** [comment]
I think there lies the rub... I don't really know... I have multiple websocket clients talking to a "core" that's kind of a state machine handling multiple sessions. So I want the "sleep" to block the clients in the same session but of course not the entire system handling multiple independent sessions.
BTW, is the a better place, to get advice on which type (sync or async) jsonConsumer to choose for one's situation?
Thx, Sebastian.

**Comment by andrewgodwin** [comment]
If you are in an async consumer you always want to async sleep - it behaves the same as normal sleep but doesn't block the whole process.

There's no good advice around on async vs sync consumer; I would summarise it as "async is always better but more complicated to write; sync is simpler and harder to get wrong but you'll get bad performance above around 20 connections"
