### ISSUE TITLE
disconnect for websocketconsumer not working

### ISSUE THREAD

**Issue by plutoRed** [django/channels#1076]
Noticed in the source code of WebsocketConsumer that 
`disconnect`
method is said to` pass `only while other relevant (`connect, recieve `) are set to their respective websocket counterparts.
This does not execute the post `disconnect` code while it is expected to.
Current solution is to override the websocket_disconnect and raise a 
`channels.exceptions.StopConsumer`
at the end.

**Comment by andrewgodwin** [comment]
I don't see anything wrong with that method - `websocket_disconnect` already raises `StopConsumer` in both the sync and async functions. The `disconnect` method is deliberately blank because it's for user code.
