### ISSUE TITLE
websocketbridge.send() should not stringify ArrayBuffer

### ISSUE THREAD

**Issue by DoubleCouponDay** [django/channels#1080]
- Detailed description of the overall behaviour
The wrapper `websocketbridge` parses the input message through `JSON.stringify()` when user invokes `.send()`.

- Reasoning why it should NOT be in Channels rather than a third-party app
Consuming the `bytes_data` parameter in a django channels consumer cannot occur with usage of `websocketbridge.js` since stringifying the argument will only supply `text_data` to the consumer.

This configuration results in an error being thrown within the channels consumer.

- Your OS and runtime environment, and browser if applicable
windows 10, python 3.6 (32 bit), firefox.

- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (channels_redis normally)
django 2.0.4, channels 2.1.0, channels-redis 2.1.1, twisted 18.4.0, waitress 1.1.0

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
WSGI backend using waitress for production.

- Console logs and full tracebacks of any errors
```
2018-06-12 15:39:05,925 - ERROR - server - Exception inside application: receive() missing 1 required positional argument: 'bytes_data'
  File "C:\Users\sjsui\Desktop\git_workshop\MoonMachineProprietary\herokuproprietary\herokuproprietary\MoonMachine\MoonMachine\env3.6.5\lib\site-packages\channels\consumer.py"
```

**Comment by andrewgodwin** [comment]
The websocket library is deliberately very simplistic and only supports JSON text frames - if you want to send raw bytes, just don’t use it and use a socket directly. We’re probably going to remove the library anyway soon.
