### ISSUE TITLE
How can I make tests setup and teardown like testcase classes?

### ISSUE THREAD

**Issue by japrogramer** [django/channels#1082]
Hello, I have looked at the channels docs to see how to test the channels app and I see an important aspect of tests that I have used for every testcase in Django and that is the setup and teardown method s. Could an example be added to the docs or pasted to my issue.

**Comment by andrewgodwin** [comment]
Setup/Teardown in pytest-style tests is covered by their fixtures system - you can read more about it here: https://docs.pytest.org/en/latest/fixture.html
