### ISSUE TITLE
Probable ASGI scope non-conformance

### ISSUE THREAD

**Issue by pgjones** [django/channels#1086]
ASGI states that the 'client' (and 'server') value in the scope be [`List of [host, port] two-item iterables`](https://github.com/django/asgiref/blob/master/specs/www.rst#L208) whereas channels assumes it to be a [single two-item iterable](https://github.com/django/channels/blob/master/channels/http.py#L64). I think Daphne is also incorrect [here](https://github.com/django/daphne/blob/master/daphne/http_protocol.py#L71), or the ASGI spec is :p. 

Naturally I did the opposite in [Hypercorn](https://gitlab.com/pgjones/hypercorn/blob/master/hypercorn/base.py#L104), and I'm willing to update to which ever is correct.

**Comment by andrewgodwin** [comment]
The spec was poorly worded - I had meant "a two-item iterable, like a list". I've updated it to just say "A two-item iterable of `[host, port]`" now.

**Comment by pgjones** [comment]
Thanks
