### ISSUE TITLE
Probable websocket send message ASGI non-comformance

### ISSUE THREAD

**Issue by pgjones** [django/channels#1087]
The ASGI Websocket protocol states that the `websocket.send` message should have a `bytes` key that is [`Byte string of binary message content, or None`](https://github.com/django/asgiref/blob/master/specs/www.rst#L276). Channels [omits the key](https://github.com/django/channels/blob/master/channels/generic/websocket.py#L69) if it isn't bytes data (and vice-versa for text data). I think it should include the key with a value of None.

**Comment by andrewgodwin** [comment]
Hmm, I'd be alright updating the spec to say it can be `None` or missing, if you think that's fine?

**Comment by pgjones** [comment]
Yep, sounds good.

**Comment by andrewgodwin** [comment]
OK, I updated the spec to say that.
