### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 500

### ISSUE THREAD

**Issue by kshitij3199** [django/channels#1089]
hello everyone , i am new to channels and trying to make a chat app by following the documentation .
i followed each step . But i am facing this problem
(index):17 WebSocket connection to 'ws://127.0.0.1:8000/ws/chat/test10/' failed: Error during WebSocket handshake: Unexpected response code: 500
(anonymous) @ (index):17
and (index):17 is  
var chatSocket = new WebSocket('ws://'+window.location.host+'/ws/chat/'+roomName+'/');
please help . and thanks in advance

**Comment by andrewgodwin** [comment]
A 500 error means you have a problem in your Django code - look at the console that is running `runserver` to see what it is and fix it. It's not a Channels-specific problem.

**Comment by JesusD2405** [comment]
Hola! Estuve siguiendo el tutorial y también tuve el mismo error.. En Ubuntu 18.04 LTS

Lo solucioné haciendo la instalación de redis:

`sudo apt install redis-server`

Ya qué en la sección de pruebas arrojaba error cuando ejecutaba en la shell de Django:

`>> async_to_sync(channel_layer.receive)('test_channel')`

Luego que hice la instalación de redis el ejemplo se ejecutó con éxito.

**Comment by kshitij3199** [comment]
@andrewgodwin thanks, i fix the problem

**Comment by mrkp305** [comment]
@JesusD2405 's solution also works..but as  for me it was much simpler, I has forgotten to run the redis server!

So first check if the redis server is running

**Comment by rahimnagori** [comment]
> @andrewgodwin thanks, i fix the problem

Can anybody please explain how to fix this problem?

**Comment by Ubaid-Parvaiz** [comment]
> @andrewgodwin thanks, i fix the problem

How i'm also facing the same error.How did you detect the error?

**Comment by deftydev** [comment]
@kshitij3199 can you please tell me how you fixed that???

**Comment by deftydev** [comment]
@kshitij3199 i am getting same error in my django code by using asyncconsumer.

**Comment by middleverse** [comment]
@deftydev @Ubaid-Parvaiz its been a while since you guys asked, but it turned out the issue was:

"consumers.ChatRoomConsumer" in chat/routing.py was supposed to be "consumers.ChatRoomConsumer.as_asgi()"
