### ISSUE TITLE
ChannelsLiveServerTestCase doesn't load static files

### ISSUE THREAD

**Issue by kradem** [django/channels#1092]
This is the screenshot of the problem:
![chrome-static-files](https://user-images.githubusercontent.com/7360633/42321299-bd431040-8058-11e8-8ac6-e1a7449e1fdd.png)

Development server works as intended:
![chrome-devserver](https://user-images.githubusercontent.com/7360633/42321478-63a468da-8059-11e8-81fa-fd57cd759977.png)

That testing code you may found in this [channels-examples fork](https://github.com/kradem/channels-examples).

    $ pip freeze
    aioredis==1.1.0
    asgiref==2.3.2
    async-timeout==3.0.0
    atomicwrites==1.1.5
    attrs==18.1.0
    autobahn==18.6.1
    Automat==0.7.0
    channels==2.1.2
    channels-redis==2.2.1
    constantly==15.1.0
    daphne==2.2.0
    Django==2.0.7
    hiredis==0.2.0
    hyperlink==18.0.0
    idna==2.7
    incremental==17.5.0
    more-itertools==4.2.0
    msgpack==0.5.6
    pluggy==0.6.0
    psycopg2-binary==2.7.5
    py==1.5.4
    pytest==3.6.3
    pytest-asyncio==0.8.0
    pytest-django==3.3.2
    pytz==2018.5
    selenium==3.13.0
    six==1.11.0
    Twisted==18.4.0
    txaio==2.10.0
    zope.interface==4.5.0

I'm afraid I can't locate commit in time as [this solved bug would emerge](https://github.com/django/channels/issues/1008).

**Comment by andrewgodwin** [comment]
Are you running your tests with `DEBUG=False`? That would disable Django's built-in static file serving.

Also - is this behaviour different if you don't have channels installed?

**Comment by kradem** [comment]
> Are you running your tests with DEBUG=False? That would disable Django's built-in static file serving.

Nope. I override nothing during tests and in settings it's `DEBUG = True`.

> Also - is this behaviour different if you don't have channels installed?

I'm subclassing `ChannelsLiveServerTestCase` so it's not applicable I'm afraid.

All my other tests are doing fine and these misbehavior hadn't existed before - all the static files had been loaded and I could successfully test. This problem emerged somewhere around 2.0.1 version.

**Comment by andrewgodwin** [comment]
Any chance you could narrow down the release/commit it actually occurs in? That would let me find the source much easier with the limited time I have to work on each issue!

**Comment by kradem** [comment]
Yes, I followed the instructions from the readthedocs' tutorial and it doesn't load css.

**Comment by andrewgodwin** [comment]
Have you tried a different machine, maybe it's that?

I'm afraid I won't have time to look at this and reproduce it for a month or two with my current schedule and all the other bugs, so I'm trying to help you discover what's happening. Maybe someone else ca help too.

**Comment by kradem** [comment]
I just cloned my channels-examples repo to a VirtualBox machine with Ubuntu and it's the same.

**Comment by andrewgodwin** [comment]
OK, it might be a fundamental problem in the static file server then I guess? I'll try to get to this at some point.

**Comment by shjohnson-pi** [comment]
It appears that static functionality was deleted in commit 15f8b7d44362537d9cbc3fe16b91092b9bf6c6c5 as part of related Issue #897, and Pull Request #934.

**Comment by andrewgodwin** [comment]
Ah yes, that would have been it, so the code to add the static serving needs to be added back in then.
