### ISSUE TITLE
How can I get Consumer instances in Outside Of Consumers

### ISSUE THREAD

**Issue by hongweipeng** [django/channels#1093]
There is define the Consumer:
```
class ChatConsumerAsync(AsyncWebsocketConsumer):
    async def connect(self):
        self.room_name = self.scope['url_route']['kwargs']['room_name']
        self.room_group_name = 'chat_%s' % self.room_name

        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name
        )
        await self.accept()
```
I want to get the ChatConsumerAsync instances in the `room_group_name`,in order to get the number of people and do more complex things. There is no idea in the document [https://channels.readthedocs.io/en/latest/topics/channel_layers.html#using-outside-of-consumers](https://channels.readthedocs.io/en/latest/topics/channel_layers.html#using-outside-of-consumers), can u help me?

The versions:
```
Django                  2.0.6
channels                2.1.2
Twisted                 18.4.0
```
ASGI backend is `channels_redis`, Im running Cahnnels in `runserver`

**Comment by andrewgodwin** [comment]
You can't get the number of listeners (consumer instances) on a group using channels-redis - that's not something it's coded to do. If you want to track how many people you have you need to build your own "presence" solution using Redis or a database.

**Comment by hongweipeng** [comment]
ok,I get it, thx for your reply.
