### ISSUE TITLE
I am working on a project in which i am building a chat app using django channels 2.0 and expecting around 3000 concurrent connections. Is django channels scallable to that point, or will I have to add a load balancer, or use a reverse proxy like pushpin to handle the traffic? if yes, how to integrate consumers with pushpin?

### ISSUE THREAD

**Issue by tHeMaskedMan981** [django/channels#1095]
Please submit **questions** about usage to django-users@googlegroups.com (https://groups.google.com/forum/#!forum/django-users) and about development to django-developers@googlegroups.com (https://groups.google.com/forum/#!forum/django-developers).

If you're submitting a feature request, please try to include:

- Detailed description of the overall behaviour
- Reasoning why it should be in Channels rather than a third-party app
- Examples of usage, if possible (it's easier to discuss concrete code examples)

If you're submitting a bug report, please include:

- Your OS and runtime environment, and browser if applicable
- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (channels_redis normally)
- What you expected to happen vs. what actually happened
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
- Console logs and full tracebacks of any errors

**Comment by andrewgodwin** [comment]
Please write your questions/queries in the comment field, not the title.

As for the question, I can't give you an answer on integration with pushpin - I've never used them - and scaling entirely depends on your hardware. The only real way to know is load tests.
