### ISSUE TITLE
Channels 2 scalability issue

### ISSUE THREAD

**Issue by tHeMaskedMan981** [django/channels#1098]
Please submit **questions** about usage to django-users@googlegroups.com (https://groups.google.com/forum/#!forum/django-users) and about development to django-developers@googlegroups.com (https://groups.google.com/forum/#!forum/django-developers).

If you're submitting a feature request, please try to include:

- Detailed description of the overall behaviour
- Reasoning why it should be in Channels rather than a third-party app
- Examples of usage, if possible (it's easier to discuss concrete code examples)

If you're submitting a bug report, please include:

- Your OS and runtime environment, and browser if applicable
- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (channels_redis normally)
- What you expected to happen vs. what actually happened
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
- Console logs and full tracebacks of any errors

**Comment by tHeMaskedMan981** [comment]
sorry for the last issue. also, can u suggest some ways on how to do load tests? I know how to do basic tests as explained in the docs, but load tests for channels don't seem obvious to me. Can you help me out on this? Also, getting the required hardware is not a problem. So can u suggest which hardware to use if I am expecting 3000 concurrent connections?

**Comment by andrewgodwin** [comment]
I'm afraid I can't provide general development support - this issue tracker is for issues with Channels itself only. I suggest you ask elsewhere (e.g. django-users) for help.
