### ISSUE TITLE
Javascript library: latest version number lower than the current one

### ISSUE THREAD

**Issue by bluesurfer** [django/channels#1101]
Really minor issue here 😄 

I have installed the Channels javascript library using `npm`. 
When I run `npm outdated` to get the list of outdated packages I always get `django-channels`. 

```
Package          Current   Wanted  Latest  Location
django-channels    1.1.8    1.1.8   1.1.6  app
```
But the current version is higher than the latest one 🤔

**Comment by andrewgodwin** [comment]
Hm, that is weird - I don't really know how I'd solve it though? Have any ideas?

**Comment by pvanagtmaal** [comment]
@bluesurfer could you add exact reproduction steps? I cannot seem to reproduce:

```
npm install django-channels
+ django-channels@1.1.6
added 2 packages from 1 contributor and audited 2 packages in 2.356s

npm outdated
<nothing>
```

**Comment by jonathan-s** [comment]
Although I'd say it feels pretty valuable to have a javascript client that works well together with django channels. Similar to the approach that rails takes with actioncables. They bundle the js client together with actioncables which is the equivalent to django-channels. 

So if anything I'd vouch for having a js client included. 

See for how rails does it: https://github.com/rails/rails/tree/master/actioncable/app/javascript/action_cable

**Comment by hishnash** [comment]
@jonathan-s https://github.com/theY4Kman/dcrf-client is an option. (this does bring in more of the dependency on a multiplexer and the subscriptions to db items.

**Comment by carltongibson** [comment]
Closing as stale
