### ISSUE TITLE
websocket connection disconnceted after 20seconds

### ISSUE THREAD

**Issue by makeforever** [django/channels#1102]
i just connected and after 20 seconds later disconnected. how can i set auto disconnection time ? i cant find configuration.

**Comment by andrewgodwin** [comment]
There's no auto disconnection time from inactivity on WebSockets in channels or Daphne. You may, however, have something else in the way (like a proxy or firewall) that's blocking the socket's ping mechanism and making it close itself down.

**Comment by makeforever** [comment]
think you. i think it a os problem.
