### ISSUE TITLE
Cannot input string variable as group name in channel_layer.group_send

### ISSUE THREAD

**Issue by adszzxc** [django/channels#1104]
Ubuntu 16.04
Channels 2.1.2
Daphne 2.2.0
Twisted 18.4.0
Django 2.0.7
Python 3.5.2

Project is ran by Nginx/Gunicorn in front, Channels is running with runserver

In case of my app, each Profile object has a string called usercode. Consumer uses that string to add channels to the group of the user (multiple clients in mind). 
I'm trying to send a message from view, but the same thing happens from shell.
In this case, `e1cfb86161` is one of these strings.
```
channel_layer = get_channel_layer()
async_to_sync(channel_layer.group_send)("e1cfb86161",{"type":"chat.message", "text":"what's up?"})
```

This works no problem, the message reaches listening client. But:
```
channel_layer = get_channel_layer()
chat_name = "e1cfb86161"
async_to_sync(channel_layer.group_send)(chat_name,{"type":"chat.message", "text":"what's up?"})
```

Does not. Neither does this: (tom.usercode returns a string)
```
channel_layer = get_channel_layer()
async_to_sync(channel_layer.group_send)(tom.usercode,{"type":"chat.message", "text":"what's up?"})
```
I can't figure why that is. I think it's just a bug, passing `str(tom.usercode)` doesn't help either. There are no logs to the console. Method gets executed, but there's absolutely no feedback to the log as if it executed correctly.

**Comment by Forchapeatl** [comment]
I am facing the same issue , please how did you resolve this?

**Comment by twrutniak** [comment]
Sorry, but I just don't remember. It's been 5 years.

**Comment by Forchapeatl** [comment]
Thank you
