### ISSUE TITLE
Can't run tests using ChannelsLiveServerTestCase

### ISSUE THREAD

**Issue by NVishnya** [django/channels#1106]
I followed the [tutorial](http://channels.readthedocs.io/en/latest/tutorial/index.html). But I couldn't run the tests using ChannelsLiveServerTestCase. The tests are the same as the tests [here](http://channels.readthedocs.io/en/latest/tutorial/part_4.html).
When I try to run the tests I got Bad Request (400) error.
![screenshot from 2018-07-16 15-25-49](https://user-images.githubusercontent.com/23117124/42758636-d4411640-890c-11e8-9bbf-c873cec0c8e3.png)
Then I tried using `cls.driver = webdriver.Firefox()` insted of `cls.driver = webdriver.Chrome()`. But I got the same error.
![badrequestscreen](https://user-images.githubusercontent.com/23117124/42758834-82f8ecc6-890d-11e8-9dfc-0484d3679fec.png)

I tried replacing `ChannelsLiveServerTestCase` with `StaticLiveServerTestCase`. Then I got this:
![screenshot from 2018-07-16 15-43-18](https://user-images.githubusercontent.com/23117124/42759375-6cd86ba4-890f-11e8-8e38-8b2fcc6d7ae3.png)
Tutorial says:

> Our test suite extends ChannelsLiveServerTestCase rather than Django’s usual suites for end-to-end tests (StaticLiveServerTestCase or LiveServerTestCase) so that URLs inside the Channels routing configuration like /ws/room/ROOM_NAME/ will work inside the suite.

So it's okay, that StaticLiveServerTestCase doesn't work. But why ChannelsLiveServerTestCase doesn't work?

My OS is Linux Mint. **Channels 2.1.1, Django 2.0.5, Daphne 2.1.1, channels_redis 2.1.1.**
Here are my settings:
![screenshot from 2018-07-16 15-58-38](https://user-images.githubusercontent.com/23117124/42759932-4be60cce-8911-11e8-8fd9-34ae92da4f03.png)

**Comment by andrewgodwin** [comment]
Can you update to the newest versions of channels and Daphne please? I'm pretty sure we already fixed this - reopen if that doesn't solve it.
