### ISSUE TITLE
Missing 'user' in scope when testing with WebsocketCommunicator

### ISSUE THREAD

**Issue by pfk-beta** [django/channels#1107]
I have a simple Consumer, which rely on AuthMiddlewareStack, and need 'user' in score. When I do manually simple test with browser - it works perfectly. When I write test case with WebsocketCommunicator  I've got  KeyError on such line `self.scope['user']`. How can I configure TestCase to have 'user' in scope?

**Comment by andrewgodwin** [comment]
You need to send the right cookies with your tests, or otherwise pass the `user` argument to the communicator.
