### ISSUE TITLE
Support for Python 3.7 

### ISSUE THREAD

**Issue by denself** [django/channels#1108]
Is it possible to add support for the installation of `channels` from pip on Python 3.7?
I checked through the direct installation of the library from git, it seems to work fine with the latest version of `twisted` (18.7.0), all tests passed.

**Comment by andrewgodwin** [comment]
What aspect of installing via pip does not work? There was no 3.7 classifier on the package (I've fixed that for the next release), but the actual installation should not have failed...

**Comment by denself** [comment]
Pip could not find a version that would satisfy requirements before
```
  Could not find a version that satisfies the requirement channels (from versions: )
No matching distribution found for channels
```
But now it looks like everything with channels classifiers fine, but twisted doesn't provide a proper classifier:
```
...
  Could not find a version that satisfies the requirement twisted>=18.7 (from daphne~=2.2->channels) (from versions: )
No matching distribution found for twisted>=18.7 (from daphne~=2.2->channels)
```
Is there a way to request Python 3.7 support from twisted? (Sorry, I know it's not relevant to this repo question)

**Comment by andrewgodwin** [comment]
Pip shouldn't be using classifiers to select if packages are downloadable or not - I just tried a Python 3.7 version of pip and it happily downloads twisted. Do you have some sort of strange setup?

(I'm going to close the ticket too, as _we_ have support for 3.7 at least)

**Comment by adonese** [comment]
Channels support python 3.7 but twisted doesn't (as of version 18.7, from pip error message). They are working on [adding support for python 3.7](https://twistedmatrix.com/trac/milestone/Python%203.7%20support), so you might wait for that or use python 3.6

**Comment by adonese** [comment]
Channels support python 3.7 but twisted doesn't (as of version 18.7, from pip error message). They are working on [adding support for python 3.7](https://twistedmatrix.com/trac/milestone/Python%203.7%20support), so you might wait for that or use python 3.6

What i've done is building twisted from the source without relying on pip to do that.

**Comment by luskbo** [comment]
Just FYI, for anyone that comes across this issue. Like adonese, i was successful only after manually installing Twisted-18.7.0 from source. With pip, I installed all versions from 3.6.0 to 3.7.0 and all failed with `Could not find a version that satisfies the requirement twisted>=18.7`
