### ISSUE TITLE
sync_to_async(...) has its own database transaction

### ISSUE THREAD

**Issue by ostcar** [django/channels#1110]
I have the following test:
```python
@pytest.mark.asyncio
@pytest.mark.django_db
async def test_db_write():
    from openslides.users.models import User  # Could be any Model
    user = User.objects.create()  # This blocking code is only for demonstration

    @database_sync_to_async
    def sync_get_user():
        return User.objects.get(pk=user.pk)

    assert await sync_get_user() == user
```
On Postgresql, this raises a `DoesNotExist` exception inside `sync_get_user()`. It seems, that the code inside `database_sync_to_async` runs inside another transaction. It does not change, if I use `sync_to_async` instead of `database_sync_to_async`.

On SQLite this raises `django.db.utils.OperationalError: database table is locked: users_user`.

This can be fixed by using `@pytest.mark.django_db(transaction=True)`. But this has no effect on tests inside a `TestCase`. So I have to rewrite all my old tests to fix this. Here is an example of the test inside a `TestCase` that failes with `transaction=True`:

```python
class TestSyncChannels(TestCase):
    @pytest.mark.django_db(transaction=True)
    def test_db_write_sync(self):
        from openslides.users.models import User  # Could be any Model
        user = User.objects.create()

        async def async_get_user():
            return await sync_get_user()

        @database_sync_to_async
        def sync_get_user():
            return User.objects.get(pk=user.pk)

        assert async_to_sync(async_get_user)() == user
```

I can not tell, if this is specific to the test environment or could also happens in production. Maybe this is connected to https://github.com/django/channels/issues/1091.

```
channels==2.1.2
daphne==2.2.1
Django==2.0.7
Twisted==18.7.0
asgiref==2.3.2
channels-redis==2.2.1
pytest==3.6.3
pytest-asyncio==0.8.0
pytest-django==3.3.2
```

PS: I really like what you have done with channels2!

**Comment by ostcar** [comment]
I did some more testing and can confirm, that this is not a testing issue, but also happens in production.

When you add this code to a classic django view, the function get_user() raises a DoesNotExist exception. Without the transaction block, it works.

```python
        with transaction.atomic():
            test_user = User.objects.create(username="test_user2")

            @database_sync_to_async
            def get_user():
                return User.objects.get(pk=test_user.pk)

            async def async_get_user():
                return await get_user()

            inner_user = async_to_sync(async_get_user)()
            print(test_user, inner_user)
```

**Comment by andrewgodwin** [comment]
Yes, you can't use transactions with async code, as there's no async support for the Django ORM and so we have to run everything in a subthread. This isn't possible to fix in Channels - it will have to eventually be addressed in Django itself.

In the meantime, if you need transactions, you'll need to do them entirely inside an already-synchronous function.

**Comment by fozcode** [comment]
I think it's this issue that also means you can't use `django.test.TestCase` along with `setUpTestData(cls)` for installing test data for the tests.  With Postgres at least this uses a database transaction for rolling back the database state, but that transaction isn't visible to the async code and the consumers under test simply see an empty test database.

I've changed my tests to use `django.test.TransactionTestCase` with `serialized_rollback = True` so that database transactions are not used, and while it's slow it does work.  Figuring this out wasn't much fun and I can't see anything in the docs about it.
