### ISSUE TITLE
AuthMiddleware not called during tests

### ISSUE THREAD

**Issue by Neraste** [django/channels#1115]
Hello channels devs team,

I am writing the tests for the websocket consumers of my application and I cannot successfully test my authentication process. I use a custom  AuthMiddleware to use tokens instead of cookies ([this one](https://gist.github.com/rluts/22e05ed8f53f97bdd02eafdf38f3d60a)) and it seems that the middleware is not called at all during tests, whereas it is actually called with real-world testing (*i.e.* when running the app).

I cannot say if my problem is related to #903, as I process the login by another way with Django REST Framework. The authentication only works if the user is already connected.

Here is the test:
```python
import pytest
from channels.testing import WebsocketCommunicator
from rest_framework.authtoken.models import Token
from my_app.routing import application

@pytest.mark.asyncio                                                           
@pytest.mark.django_db(transaction=True)                                       
async def test_authentication():
    # create a token                                                           
    user = get_an_user_somehow()
    token = Token.objects.create(user=user)                         
    headers = [(b'authorization', "Token {}".format(token.key).encode())]      
                                                                               
    # create communicator and connect
    communicator = WebsocketCommunicator(application, "/ws/my/path/",  
                                         headers=headers)                      
    connected, _ = await communicator.connect()                                
                                                                               
    assert connected  # fails here
    await communicator.disconnect()                                            
```

According to the AuthMiddleware code, a user will always be added to the scope, even if the authentication fails (an anonymous user is added in this case). But there is no user in my scope after awaiting connect, this is why I believe that the AuthMIddleware is not called by the WebsocketCommunicatior. This does not seem to be a problem from the custom AuthMiddleware side.

What do you think?

* **OS and runtime environment** Linux kernel 4.17.11-1-default, Python 3.6.5;
* **Versions** Channels 2.1.2, Daphne 2.2.0, Django 1.11.13, Django REST Framework 3.6.4, Twisted none, ASGI backend in memory;
* **Running** in dev mode with runserver or with pytest.

**Comment by andrewgodwin** [comment]
Did you verify the AuthMiddleware is being run at all? Put a print or something in it? As long as the middleware is in the `routing` you inherit from, it will run, otherwise it will not.

**Comment by Neraste** [comment]
Using prints is how I figured out that the AuthMiddleware is run when using the runserver command, but not during a test with pytest. More precisely, the `__init__` method is called in both cases (obviously) and the `__call__` method only using runserver.

The documentation states that I can pass an application built with URLRouter. The application I use is built with ProtocolTypeRouter (on top of URLRouter), like this one:

```python
# my_app.routing.py
from channels.routing import ProtocolTypeRouter, URLRouter         
from channels.security.websocket import AllowedHostsOriginValidator
from django.conf.urls import url
from my_app.token_auth import TokenAuthMiddlewareStack  # the custom AuthMiddleware
from my_module import consumers

application = ProtocolTypeRouter({
    'websocket': AllowedHostsOriginValidator(
        TokenAuthMiddlewareStack(  # the custom AuthMiddleware
            URLRouter([
                url(r'^ws/my/path/$', consumers.MyConsumer),
            ])
        )
    )
})
```

Maybe such a stack is not valid for the WebsocketCommunicator?

**Comment by andrewgodwin** [comment]
Hmm, that's totally how you're meant to do it. When you say it "fails here" on that first line, do you mean that it never gets accepted? Raises a traceback? Or something else?

I'm trying to work out what's happening because there's not even a reference to the inner consumer in the test at all - it would _have_ to go through the auth middleware stack somehow, so the question is how it's skipping the middleware down a later, or if that's what you're saying it does.

**Comment by Neraste** [comment]
The assert simply fails, meaning that the WebsocketCommunicator did not connect.

Technically, in the test, I try to test the `connect` method of my consumer and the AuthMiddleware. I will create a MWE to isolate the problem.

**Comment by Neraste** [comment]
It seems that AllowedHostOriginValidator rejects the connection during tests, even if I have `ALLOWED_HOSTS = ['*']` or `DEBUG = True` in my `settings.py`.

**Comment by Neraste** [comment]
I did some digging of the source code of OriginValidator:

https://github.com/django/channels/blob/e7295efdfd2a191f5865018d08abb95cf061afeb/channels/security/websocket.py#L24-L31

The parsed origin extracted during a test is `None`. This value is not allowed by the `valid_origin` method:

https://github.com/django/channels/blob/e7295efdfd2a191f5865018d08abb95cf061afeb/channels/security/websocket.py#L48-L50

 So for OriginValidator, it appears that a connection performed a test is intrinsically invalid.

**Comment by andrewgodwin** [comment]
Ahh, yes, that explains it. That's actually how Django's tests behave normally - they validate host names during tests (https://docs.djangoproject.com/en/2.1/topics/testing/advanced/#topics-testing-advanced-multiple-hosts)

Given that, I don't think I can change Channels here; instead, you should change the ALLOWED_HOSTS setting for the duration of the tests, or always pass a hostname header that matches one you allow.

**Comment by Neraste** [comment]
There is no `origin` in the headers of the test connections, and my `ALLOWED_HOSTS` for tests is already `['*']`, so the only way is to manually add one in the headers of the communicator:

```python
    headers = [
        (b'authorization', "Token {}".format(token.key).encode()),
        (b'origin', b'localhost'),
    ]
```

I think there should be at least one line or two in the tests documentation about that. Personally, I never had to edit my `origin` header with Django tests. Or maybe this could be a default argument for the WebsocketCommunicator?

**Comment by andrewgodwin** [comment]
Oh, the problem is that the middleware reads the setting at declaration time, not when the test is run. Hmm. You're right, there should be a better solution for this, I'll reopen it and get round to it eventually (or let someone else fix it - my suggestion would be for the middleware to somehow detect a change in ALLOWED_HOSTS and re-import it in the `__call__` if there was no explicit argument passed).

**Comment by Neraste** [comment]
I do not think this is the problem. The problem is there is no `origin` in the headers of the test connections. Whatever the value of `ALLOWED_HOSTS` is, the connection will be rejected.

**Comment by andrewgodwin** [comment]
I thought you said:

>  If I remove it, the communicator can connect and the test passes. Same behavior if I use an OriginValidator with ['*'] as second argument.

I read that as "Giving OriginValidator a `*` value for the allowed hosts makes the tests pass".
