### ISSUE TITLE
Messages to channels doesn't come after some channels in group

### ISSUE THREAD

**Issue by applecat** [django/channels#1116]
I have a problem with message delivery to groups that have many channels in it.

I noticed that after I have many channels in a group -- this channels stop receive messages posted to that group.

Here is my consumer class:
```
class NotificationConsumer(WebsocketConsumer):
    def connect(self):
        user = self.scope['user']
        if user.is_authenticated:
            async_to_sync(self.channel_layer.group_add)('auth', self.channel_name)
            async_to_sync(self.channel_layer.group_add)(user.channels_group_name, self.channel_name)
        else:
            async_to_sync(self.channel_layer.group_add)('noauth', self.channel_name)
        self.accept()

    def disconnect(self, close_code):
        user = self.scope['user']
        if user.is_authenticated:
            async_to_sync(self.channel_layer.group_discard)('user_%s' % user.id, self.channel_name)
            async_to_sync(self.channel_layer.group_discard)('auth', self.channel_name)  
        else:
            async_to_sync(self.channel_layer.group_discard)('noauth', self.channel_name)

    def message(self, event):
        message = event['message']
        self.send(text_data=json.dumps({'type': 'message', 'object': message}))

    def comment(self, event):
        comment = event['comment']
        status = event['status']
        self.send(text_data=json.dumps({
            'type': 'comment',
            'object': comment,
            'status': status,
        }))
```

Here is how I send a messages to the groups:
```
async_to_sync(channel_layer.group_send)('user_123', {'type': 'message', 'message': message_data})
async_to_sync(channel_layer.group_send)('auth', {'type': 'comment', 'comment': data, 'status': status})
```

Consumers, connected to the small personal user's groups (called 'user_[id]') receiving messages is ok, while new connected consumers to the groups 'auth' and 'noauth' don't receiving messages after some channels in the group (~200-300+ channels in the group I guess). 

We use: channels==2.1.2, channels-redis==2.2.1, daphne==2.2.0, Django==2.0.6, Twisted==18.4.0
```
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': { "hosts": ["redis://127.0.0.1:6379/6"]},
    },
}
```
Channels run with daphne and Nginx in front.

**Comment by applecat** [comment]
Same thing happens with async consumer class:
```
class AsyncNotificationConsumer(AsyncJsonWebsocketConsumer):
    async def connect(self):
        user = self.scope['user']
        if user.is_authenticated:
            await self.channel_layer.group_add(user.channels_group_name, self.channel_name)
            await self.channel_layer.group_add('auth', self.channel_name)
        else:
            await self.channel_layer.group_add('noauth', self.channel_name)
        await self.accept()

    async def disconnect(self, close_code):
        user = self.scope['user']
        if user.is_authenticated:
            await self.channel_layer.group_discard('user_%s' % user.id, self.channel_name)
            await self.channel_layer.group_discard('auth', self.channel_name)
        else:
            await self.channel_layer.group_discard('noauth', self.channel_name)

    async def message(self, event):
        await self.send_json({
            'type': 'message',
            'object': event['message']
        })

    async def comment(self, event):
        await self.send_json({
            'type': 'comment',
            'object': event['comment'],
            'status': event['status'],
        })
```

```
application = ProtocolTypeRouter({
    'websocket': AuthMiddlewareStack(
        URLRouter([url(r'^ws/notification/$', consumers.AsyncNotificationConsumer),])
    ),
})
```

We have 3 project deployments with same codebase - 
1) dev site env;
2) lang1 site with low amount of users;
3) lang2 site with high amount of users. 

dev and lang1 site works file, messages comes to consumers in all groups.
lang2 site with hi traffic have problems with messages delivery in 'auth' and 'noauth' groups. Some first connected consumers received messages, and the rest doesn't receive anything.

This is kind of bug or we do something wrong?

**Comment by applecat** [comment]
Also I noticed that in log files we have this kind of warnings:
```WARNING  Application instance <Task pending coro=<SessionMiddlewareInstance.__call__() running at /web/envs/project/lib/python3.6/site-packages/channels/sessions.py:175> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb4f03ecf48>()]>> for connection <WebSocketProtocol client=None path=b'/ws/notification/'> took too long to shut down and was killed.```

This happens every time after sending message to `auth` and `noauth` groups.

Seems like Daphne kills process than take longer than 10 seconds. But it is strange for me that sending about 600-800 websocket messages takes so long. If I extend this Daphne timeout, for example, to 20 seconds than later users will receive messages in 20 seconds after event. I think it is too long for real time experience.


And also we faced with this error `[Errno 24] Too many open files`:
```
  File "/web/envs/project/lib/python3.6/site-packages/channels/utils.py", line 57, in await_many_dispatch
    await task
  File "/web/envs/project/lib/python3.6/site-packages/channels/utils.py", line 49, in await_many_dispatch
    result = task.result()
  File "/web/envs/project/lib/python3.6/site-packages/channels_redis/core.py", line 184, in receive
    self.receive_loop_task.result()
  File "/web/envs/project/lib/python3.6/site-packages/channels/sessions.py", line 175, in __call__
    return await self.inner(receive, self.send)
  File "/web/envs/project/lib/python3.6/site-packages/channels/middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "/web/envs/project/lib/python3.6/site-packages/channels/consumer.py", line 54, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "/web/envs/project/lib/python3.6/site-packages/channels/utils.py", line 57, in await_many_dispatch
    await task
  File "/web/envs/project/lib/python3.6/site-packages/channels/sessions.py", line 175, in __call__
    return await self.inner(receive, self.send)
  File "/web/envs/project/lib/python3.6/site-packages/channels/middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "/web/envs/project/lib/python3.6/site-packages/channels/consumer.py", line 54, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "/web/envs/project/lib/python3.6/site-packages/channels/utils.py", line 57, in await_many_dispatch
    await task
  File "/web/envs/project/lib/python3.6/site-packages/channels/utils.py", line 49, in await_many_dispatch
    result = task.result()
  File "/web/envs/project/lib/python3.6/site-packages/channels/utils.py", line 49, in await_many_dispatch
    result = task.result()
  File "/web/envs/project/lib/python3.6/site-packages/channels_redis/core.py", line 184, in receive
    self.receive_loop_task.result()
  File "/web/envs/project/lib/python3.6/site-packages/channels_redis/core.py", line 184, in receive
    self.receive_loop_task.result()
  File "/web/envs/project/lib/python3.6/site-packages/channels_redis/core.py", line 202, in receive_loop
    real_channel, message = await self.receive_single(general_channel)
  File "/web/envs/project/lib/python3.6/site-packages/channels_redis/core.py", line 218, in receive_single
    async with self.connection(index) as connection:
  File "/web/envs/project/lib/python3.6/site-packages/channels_redis/core.py", line 447, in __aenter__
    self.conn = await aioredis.create_redis(**self.kwargs)
  File "/web/envs/project/lib/python3.6/site-packages/aioredis/commands/__init__.py", line 177, in create_redis
    loop=loop)
  File "/web/envs/project/lib/python3.6/site-packages/aioredis/connection.py", line 107, in create_connection
    timeout, loop=loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/web/envs/project/lib/python3.6/site-packages/aioredis/stream.py", line 19, in open_connection
    lambda: protocol, host, port, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 778, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.6/asyncio/base_events.py", line 745, in create_connection
    sock = socket.socket(family=family, type=type, proto=proto)
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
  [Errno 24] Too many open files
```

Number of open files in system are significantly increased - 60-70k with sites running with Channels and Daphne and about 7-12k with our old uWSGI + Centrifugo deployment.

Unfortunately, we had to go back to the old proven solution (with uWSGI + Centrifugo) while we don't solve these issues.

**Comment by LogX7** [comment]
any ideas on why this could be happening ? + how many active users (channels) did you add to the group for you to start having this issue .. i would like to try and replicate it

**Comment by andrewgodwin** [comment]
In general I wouldn't recommend Channels groups for any sort of large-scale
work - you should probably roll your own solution if you have more than
about 50 concurrent users in any single group, as you'll know the best
option to use at your scale.

Sorry we can't make something that works better out of the box, but it
would be a significant project to make them scale well to large group sizes
and I don't have a real-life deployment of that I can test on. Groups is
more designed to have hundreds of groups with only a few members in each
(i.e. per-user).

Andrew

**Comment by LogX7** [comment]
@andrewgodwin  can i have a group that contains 1 users
so for each user a group, so that i could send a notification for example to that only users .. and have thousand of groups ???

by 'roll your own solution' what do your recommend since i just started learning about channels 3 days ago

**Comment by andrewgodwin** [comment]
The original idea of groups is that it's for sending things to multiple
tabs of one user or small chats, so that's what it's best used for.

When I say "roll your own", I mean that if you want real-time messaging
between a cluster of servers with thousands to tens of thousands of sockets
receiving messages, that requires some actual software architecture and
network design we can't do for everyone, and has to be done individually
with skill - maybe looking at a different transport that scales that way,
like Kafka, or a modified Redis with listening rather than lists.

It's not the sort of project you can just jump into immediately; channels
is a framework to build sites on, not a completely-done solution for big
chats.

Andrew

**Comment by LogX7** [comment]
@andrewgodwin  i am not using it for chat, i'm using it to add a real time notification system, to my already present notification system, so instead of just creating a notification and saving it to a user in my db i want to check if the user is connected to a socket at the time of the creation of the notification if so, i send him/her the notification using the socket, 

i am implementing this on my test machine, and this site would have about 4000~7000 signed users and maybe 1000~2000 active at a time, so i was wondering if i could create a group for each user on connection and use group_send in my view, without it causing a problem after production (4000 users)

**Comment by applecat** [comment]
@andrewgodwin Thank you for the answer! Now I understand the use case of groups in channels. In fact groups with small amount of users (10-50) works really well, problems starts with large groups only. Ok, I'll try to implement another solution to send notifications about new comments on site to all online users.


@LogX7 
> i've seen alot of people do self.scope['user'].channels_group_name (like you're doing)
i have never used it before, and everytime i try to it says that self.scope['user'] doesn't have a channels_group_name attribute ... how come ? and what does it do ?

This is simple method inside custom User model:
```
class User(AbstractUser):
    ...    
    @property
    def channels_group_name(self):
        return f"user_{self.id}"
```

**Comment by andrewgodwin** [comment]
Closing as this isn't an actionable issue any more (see http://channels.readthedocs.io/en/latest/support.html)
