### ISSUE TITLE
group_send does not working

### ISSUE THREAD

**Issue by LogX7** [django/channels#1117]
- OS : Linux Mint 19
- using docker-compose -> click [HERE](https://pastebin.com/yvKL1xkQ) for .yml file
- using Django 2.0, Channels 2.1.2 , Channels-redis 2.2.1
- i'm using runserver to run everything

Routing.py : 
```
from channels.routing import ProtocolTypeRouter, URLRouter
from django.urls import path
from channels.auth import AuthMiddlewareStack
from channels.security.websocket import AllowedHostsOriginValidator
from gce_app.consumers import MainConsumer

application = ProtocolTypeRouter({
    # Empty for now (http->django views is added by default)
    'websocket': AllowedHostsOriginValidator(
        AuthMiddlewareStack(
            URLRouter([
                path("", MainConsumer)
            ])
        )
    ),
})
```

Consumers.py : 
```
from channels.generic.websocket import AsyncJsonWebsocketConsumer

class MainConsumer(AsyncJsonWebsocketConsumer):

    async def connect(self):
        await self.accept()
        await self.channel_layer.group_add('connectedUsers', self.channel_name)
        print('connected')

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard('connectedUsers',self.channel_name)
        print('disconnected')
        


    async def receive(self, text_data=None, bytes_data=None ):
        print('received')

        await self.channel_layer.group_send(
            'connectedUsers', {
                'type': 'connectedUsers.notify',
                'content': 'this is a group message'
            })

        await self.send_json({
                'content': 'this is a message for the one making the call'
            })

    async def connectedUsers_notify(self, event):
        self.send(event)

```

asgi.py : 
```
import os
import django
from channels.routing import get_default_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")
django.setup()
application = get_default_application()
```

settings channels config : 
```
ASGI_APPLICATION = "gce.routing.application"

### Channel Redis Host 
redis_host = os.environ.get('REDIS_HOST', 'redis')   

# Channel layer definitions
# http://channels.readthedocs.org/en/latest/deploying.html#setting-up-a-channel-backend
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(redis_host, 6379)],
        },
    },
}
```

as you can see everyhting is correct (i think, from tutorial, i'm new)
this works, i receive a message in the client sending a call to the consumer
```
await self.send_json({
    'content': 'message for the user who we received a call from'
})
```

but this doesn't, i don't receive anything, in any client .. 
```
await self.channel_layer.group_send(
    'events', {
        'type': 'events.alarm',
        'content': 'This is sent to all users connected using socket'
    })
```

HELP please, i'm new to channels, i'm afraid this is not a bug but i'm doing something wrong, the channels documentation is very obscure.

this is my js : 

```
var ws;
function init_socker_connection(){
    ws = new WebSocket("ws:/localhost:8000");
    ws.onopen = e => {
        console.log('Open ', e);
    }

    ws.onmessage = e => {
        console.log('Message ', e);
    }

    ws.onerror = e => {
        console.log('Error ', e);
    }

    ws.onoclose = e => {
        console.log('Close ', e);
    }
}

function send_test() {
    ws.send("Hello");
}

document.addEventListener('DOMContentLoaded', () => {
    init_socker_connection();
}, false)
```

**Comment by LogX7** [comment]
hello so i solved this by changing some things in consumer
1 - change order of accept and group_add
```
await self.accept()
await self.channel_layer.group_add('connectedUsers', self.channel_name)
```
to
```
await self.channel_layer.group_add('connectedUsers', self.channel_name)
await self.accept()
```


2 - this : 
```
async def connectedUsers_notify(self, event):
        print(event)
        self.send(event)
```
to this : 
```
async def connectedUsers_notify(self, event):
        await self.send_json({
                'content': event['content']
            })
```

**Comment by senjespakk** [comment]
in your routing.py Try path("", MainConsumer.as_asgi()) instead of path("", MainConsumer)

**Comment by ashupednekar** [comment]
I updated the channels version to 3.0.3, and added .as_asgi() to my routing file

Still not getting any ws messages on the client, using websocketking for testing

**Comment by ashupednekar** [comment]
UPDATE

Changed to AsyncWebsocketConsumer and made sure all the intermittent calls were made async and awaited properly.

Same behaviour with channels 3 with .asgi or otherwise.

Thanks for all the help

**Comment by LennyLip** [comment]
> Changed to AsyncWebsocketConsumer and made sure all the intermittent calls were made async and awaited properly.

Same issue, and the [docs describes](https://channels.readthedocs.io/en/latest/topics/channel_layers.html#single-channels) not Async version. My version is 3.0.4

**Comment by amaangigani7** [comment]
The thing you did to fix your problem does not work for me.

**Comment by HAtherlolz** [comment]
I had the same issue. You can try to allocate a separate redis database for channels_layer. This is done by adding the redis database number after its port + '/{number_of_database}'

Seems like that 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/1'

By default, Redis instances have 16 databases (numbered 0 to 15), but this can be configured in the Redis configuration file. Each database is a separate namespace that can hold its own set of keys and values.

Note that when using Redis databases in a production environment, it's a good practice to separate different types of data into separate databases or even separate Redis instances to avoid conflicts and improve performance.

In settings.py

```
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": ['redis://' + REDIS_HOST + ':' + REDIS_PORT + '/1'],
        },
    },
}
```

**Comment by abhakhi** [comment]
I had this issue with `AsyncHttpConsumer`. Looks like it does not natively support channel layer messages: https://github.com/django/channels/issues/1302#issue-448533285. So I used `AsyncConsumer`.
