### ISSUE TITLE
Missing step in tutorial

### ISSUE THREAD

**Issue by mulka** [django/channels#1129]
When going through the channels tutorial with the latest channels release and django 1.11, I ran into an error when running the tests in part 4:
https://channels.readthedocs.io/en/latest/tutorial/part_4.html

Error: "ChannelLiveServerTestCase can not be used with in memory databases"

I figured out that the DATABASES configuration needed to be modified to add a TEST section, but that wasn't in the tutorial. I think it should be added. Here's the configuration I used to fix the issue:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        "TEST": {
            "NAME": os.path.join(BASE_DIR, "db_test.sqlite3"),
        },
    }
}
```

macOS High Sierra 10.13.6
Python 3.6.4
channels 2.1.3
django 1.11.15

**Comment by andrewgodwin** [comment]
The default Django project configuration uses an on-disk SQLite database, not an in-memory one, so I don't know why it would raise this error. Can you paste the full error and traceback please?

**Comment by mulka** [comment]
$ python3 manage.py test chat.tests
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
EE
======================================================================
ERROR: test_when_chat_message_posted_then_not_seen_by_anyone_in_different_room (chat.tests.ChatTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mulka/Documents/Code/channels-tutorial/venv/lib/python3.6/site-packages/django/test/testcases.py", line 202, in __call__
    self._pre_setup()
  File "/Users/mulka/Documents/Code/channels-tutorial/venv/lib/python3.6/site-packages/channels/testing/live.py", line 34, in _pre_setup
    "ChannelLiveServerTestCase can not be used with in memory databases"
django.core.exceptions.ImproperlyConfigured: ChannelLiveServerTestCase can not be used with in memory databases

======================================================================
ERROR: test_when_chat_message_posted_then_seen_by_everyone_in_same_room (chat.tests.ChatTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mulka/Documents/Code/channels-tutorial/venv/lib/python3.6/site-packages/django/test/testcases.py", line 202, in __call__
    self._pre_setup()
  File "/Users/mulka/Documents/Code/channels-tutorial/venv/lib/python3.6/site-packages/channels/testing/live.py", line 34, in _pre_setup
    "ChannelLiveServerTestCase can not be used with in memory databases"
django.core.exceptions.ImproperlyConfigured: ChannelLiveServerTestCase can not be used with in memory databases

----------------------------------------------------------------------
Ran 0 tests in 1.908s

FAILED (errors=2)
Destroying test database for alias 'default'...

**Comment by mulka** [comment]
I was using django 1.11.15 before, but this time I also reproduced with django 2.1

**Comment by mulka** [comment]
If it helps, I ran through the tutorial and committed after each step. Here's the repository: https://github.com/mulka/channels-tutorial

**Comment by andrewgodwin** [comment]
Yes, it looks like the in-memory check for the live server is not quite accurate enough. I'll update it.

**Comment by andrewgodwin** [comment]
Ah, no, weird, it is accurate.

**Comment by mulka** [comment]
From the Django docs:
“When using SQLite, the tests will use an in-memory database by default (i.e., the database will be created in memory, bypassing the filesystem entirely!). The TEST dictionary in DATABASES offers a number of settings to configure your test database. For example, if you want to use a different database name, specify NAME in the TEST dictionary for any given database in DATABASES.”
https://docs.djangoproject.com/en/2.1/topics/testing/overview/

**Comment by andrewgodwin** [comment]
Yeah, I got that far yesterday, sorry, I forgot to update here. All someone needs to do is update the tutorial to add the `TEST` section, then.

**Comment by JuanjoA** [comment]
@mulka @andrewgodwin This can be closed.
