### ISSUE TITLE
Testing documentation for Client/HttpClient

### ISSUE THREAD

**Issue by jarus** [django/channels#113]
Hi Andrew,

thank you very much for channels. Its design, architecture and integration into Django is really inspiring.

It would be really great if there would be documentation about "How I test my channels-powered application". Also I think we need maybe a similar toolset like Django with a "fake" message client.

Thank you and best regards
Christoph

**Comment by andrewgodwin** [comment]
Yes, you're right - I finished off and committed the `ChannelTestCase` on the flight I just got off, which provides the "fake" message client and some utility functions to get messages, just need to write some docs on it.

**Comment by DebVortex** [comment]
Hey!

I like the ``ChannelTestCase`` so far, however I was not able to find anything in the documentation how to write tests for channels that use the authentication decoreators. Any tips for that? I tried not using your ``TestCase`` and instead Writing a ``FakeMessage`` I can put into the consume. However, the ``FakeMessage`` itself got so big so quickly, that I dismissed this Idea again.

**Comment by DebVortex** [comment]
I checked a bit your own tests and have seen some good hints in the ``test_sessions.py``. However, I was not able to find a good way to test ``channel_session_user_from_http`` and ``@channel_session_user``.

**Comment by Krukov** [comment]
Hello, 
If @andrewgodwin do not mind :confused: , you can use undocumented test util named `HttpClient`

```python
from channels.tests.http import HttpClient
from channels.tests import ChannelTestCase

class TestName(ChannelTestCase):
    def test_test(self):
        ...
        client = HttpClient()
        client.login(username='username', password='123')

        client.send_and_consume('websocket.connect')
        client.send_and_consume('chat.receive', {'command': 'join', 'room': 'room})

        self.assertTrue('room' in user.rooms)
        ...
        received = client.receive()
        self.assertTrue('text' in received)



```
Look at [simple example](https://github.com/Krukov/channels-examples/blob/example-new-tests-utils/multichat/chat/tests.py)

**Comment by andrewgodwin** [comment]
Yes, that's the way to do it, we haven't got good docs written up yet, I'll make sure I get to it soon.

**Comment by Krukov** [comment]
@andrewgodwin  I can make PR to the https://github.com/andrewgodwin/channels-examples with example, does it make sense?

**Comment by andrewgodwin** [comment]
@Krukov No, there needs to be written documentation in a narrative style for the `docs/` folder in the repo. I'm happy to do it, will just need to be after PyCon finishes.

**Comment by Krukov** [comment]
Hi @andrewgodwin 
I counted for documentation about `Client`/`HttpClient`. What about this?

**Comment by andrewgodwin** [comment]
Urgh, sorry, I closed this from the first few parts not the last. I will reopen and fix the title.

**Comment by Krukov** [comment]
Can we close  this issue?

**Comment by andrewgodwin** [comment]
Yup!
