### ISSUE TITLE
How to use the Redis in AsyncConsumer ？

### ISSUE THREAD

**Issue by ou-bing** [django/channels#1133]
use redis or aioredis？
can you give me a demo?
-_-

**Comment by andrewgodwin** [comment]
I'm afraid we don't have the resources to give a demo, but you should use an async-capable Redis library (aioredis is the one we use internally).

**Comment by ou-bing** [comment]
Thanks  for your answer, I may know how to use it

**Comment by JoshYuJump** [comment]
@ou-bing Are there any examples?

**Comment by ou-bing** [comment]
> @ou-bing Are there any examples?

I'm used redis finally -_-!
