### ISSUE TITLE
Ability to centralize middleware configuration

### ISSUE THREAD

**Issue by jkarneges** [django/channels#1134]
Hi,

When using multiple routing.py files in a manner similar to urls.py, with one for the project (same dir as settings.py) and one in each app dir, with the project-level routing.py referencing out to the various app routing.py files, it doesn't seem to be possible to specify, from the project-level routing.py, a set of middleware to run on all async routes while excluding it from sync routes. Individual apps might have both async and sync routes, and if, for example, AuthMiddlewareStack is placed in the project-level routing.py, then such middleware could get incorrectly applied to a route that an app ultimately passes to AsgiHandler (which may redundantly trigger the standard Django auth middleware).

As a result of this behavior, I end up putting async middleware in the app-level routing.py files instead of the project-level routing.py, with potential duplication across apps. This is the opposite of how normal Django middleware is centralized in settings.py.

Maybe Channels could allow middleware to be configured in settings.py too? e.g. `ASYNC_MIDDLEWARE = [...]` or something.

**Comment by andrewgodwin** [comment]
I'm trying to avoid adding extra settings, and middleware firmly falls into that camp - there are patterns that you can use to share middleware across different routing files without using settings, such as making predefined bundles of them like this:

```
bundle = lambda x: middleware_1(middleware_2(x))
```

Then you can more easily re-use things in routing files.

I'm going to close this as I don't think I want to include centralised middleware settings without a very convincing argument why it's definitely needed and much, much better than making a single bundle and reusing it where needed.
