### ISSUE TITLE
Object instance for each WebsocketConsumer

### ISSUE THREAD

**Issue by Hapyr** [django/channels#1139]
Hello hello,
I know this is not the place to ask questions, but I don't know where else to ask.
Is it possible to assign a separate object instance to each connection in "connect()"?
   
    class Multiplayer(WebsocketConsumer):
        def connect(self):
            self.user = self.scope["user"]

            self.user.profile.game = game.Game(user=self.user,name="Test",...)

That didn't work out. 
The object is the same for all users from the channel.

I would be very happy to receive an answer. I do not want to use the database if possible.

LG Jakob

**Comment by andrewgodwin** [comment]
Yes, it is the wrong place to ask questions, but I will answer this quickly. Use something other than `self.user` and it might work - the user is a special object.

**Comment by Hapyr** [comment]
Thanks for your answer.
I treid before like u say. Something like

Self.game = Game()

But this doesn't work. If I change (with object intern functions) the instance on one connection it changes for all connection. Or did I miss understand something?!
