### ISSUE TITLE
Serious Memory Leak.

### ISSUE THREAD

**Issue by madlee** [django/channels#1146]
It consumed all my 32G memory in less than one day.
I have not use session or some other advanced things. Just simply call group_send periodically in some daemon django-commands. And I await group_discard properly in disconnect function according to the Tutorial Part 3.

I am working on Red Hat 4.8.5 with Anaconda Python 3.6.2
 
aioredis==1.1.0
asgiref==2.3.2
async-timeout==3.0.0
attrs==18.1.0
autobahn==18.6.1
Automat==0.7.0
certifi==2018.4.16
channels==2.1.2
channels-redis==2.2.1
chardet==3.0.4
constantly==15.1.0
daphne==2.2.0
Django==2.0.7
gunicorn==19.9.0
hiredis==0.2.0
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
kazoo==2.5.0
msgpack==0.5.6
mysql-connector==2.1.6
numpy==1.14.5
PyHamcrest==1.9.0
pytz==2017.2
redis==2.10.6
redis-py-cluster==1.3.4
requests==2.19.1
six==1.11.0
Twisted==18.7.0
txaio==2.10.0
urllib3==1.23
websockets==6.0
zope.interface==4.5.0

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                 "unix:///tmp/redis.sock",
            ],
        },
    },
}

I connected to redis on a unix socket. 
I am run in daphne behind  nginx.
daphne -b $LOCAL_HOST -p 8091 Ra.asgi:application

I've checked some memory leak issues of this project. They have been closed but I do not think they fit my situations.

Would you please give me some tips?
Thank you very much.

**Comment by andrewgodwin** [comment]
I'm afraid we can't just tackle mysterious memory leaks - we need detailed instructions on how to make the leak happen with simple example code (see http://channels.readthedocs.io/en/latest/support.html for more).

It's likely that you have a memory leak in your application instead - I'd recommend looking for Python memory leak articles and tutorials to help you trace it down.
