### ISSUE TITLE
Problem in Hosting

### ISSUE THREAD

**Issue by Vishnupriya1507** [django/channels#1147]
Hi this is Vishnupriya,I am trying to host my web app which is based on django channels .This is the link of my repo-https://github.com/Vishnupriya1507/Django-Channels/tree/Index-page-Backend
Site is hosted on digital ocean but its giving error as-"Firefox can’t establish a connection to the server at ws://sportzilla.ml/ws/chat/Room10/.".
Please help me  on getting started.
This is my ngnix configuration file:
![websocket](https://user-images.githubusercontent.com/31389478/45172641-8b91fc80-b223-11e8-8493-11ecc5be4722.png)
this is my settings.py [channels layer]--
![settings](https://user-images.githubusercontent.com/31389478/45172764-ec213980-b223-11e8-9391-c8ad3a804c7f.png){redis server name is incorrect i think}.
and ALLOWED_HOSTS = [ 'sportzilla.ml','139.59.94.9',].
I have used gunicorn and ngnix .
this is how terminal look like:
![runserver](https://user-images.githubusercontent.com/31389478/45173741-b6318480-b226-11e8-8df1-cda4b6fc809c.png)

Thanks in advance:)

**Comment by andrewgodwin** [comment]
I'm afraid we can't do general support on the issue tracker - please see http://channels.readthedocs.io/en/latest/support.html for more information and where to go!
