### ISSUE TITLE
Allow reuse of database query results in the same consumer

### ISSUE THREAD

**Issue by malefice** [django/channels#1149]
The title can be a bit confusing, and I do not know how to make it concise and clear, so I will be using Tutorial 3 as a starting point to explain what I mean. Say, we have a `ChatConsumer` like the one below. If there are N connected clients, then the database query will be executed N times as well. There are cases when this is desirable, like when you are expecting different results for each connected client, but for cases where every client must get the same result anyway, this seems kind of inefficient.

```
class ChatConsumer(AsyncWebsocketConsumer):
    # ...

    async def chat_message(self, event):
        message = event['message']

        # Send message to WebSocket
        await self.send(text_data=json.dumps({
            'message': message
        }))

       # Perform database query
       result = await perform_db_query()
       await self.send(text_data=json.dumps({
            'data': result
        }))
    
    @database_sync_to_async
    async def perform_db_query(self):
        return SomeModel.objects.get_some_data()
```

I was wondering if there are any plans to create some sort of decorator that not only does what `database_sync_to_async` already does, but it also ensures that the function it wraps will only execute once for a given group with an option to return a certain value, and said value will only be computed once. You can kind of think of it like the `get_or_create` method for dealing with models.

I was able to do something like this by using the caching framework, but I think my work is kind of ugly, so I was also wondering if you have ever encountered such a need or if you have something more elegant in mind.

**Comment by andrewgodwin** [comment]
There are no plans for anything like this built in - the invalidation of the query would vary massively by project and implementation. I would just implement this yourself using the caching framework, and if you end up making it reuseable, releasing it as a separate app people can use.

**Comment by malefice** [comment]
Hi Andrew! How about if we make it more specific? So, is broadcasting the same result to a certain group for a given message not a common enough use case to warrant considering adding that feature to channels? 

That is to say, if there are N clients, and for any given message, anything wrapped inside this decorator will only be executed once and will save the result to cache. The remaining N-1 clients will only retrieve from cache, and once that is all done, the cache will be invalidated in preparation for the next message to the same group.

I do not know how common this use case is for everyone else, but I think that this might be something really useful in helping a channels project scale up as well. If you think it is best to implement it as a separate app or for individual projects to create their own implementation, then no problem. Personally, I just prefer something out of the box from channels and an "official" opinion on how to go about that.

**Comment by andrewgodwin** [comment]
I'm already looking to reduce the scope of channels so there's a chance of keeping it maintainable by our small team, so I don't think this is wide-enough scope to include, sorry!

**Comment by malefice** [comment]
Alright, I totally understand, Andrew. Guess I will just have to stick to my implementation of a custom `DatabaseSyncToAsync` subclass for this purpose. Thanks for taking the time to respond!
