### ISSUE TITLE
Delay protocol server

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#115]
A "protocol" server (more just a special process) that listens on a given channel for messages with `channel`, `content` and `delay` keys, and re-inserts them onto the destination channel after the specified delay. Used to have tasks happen after a delay without clogging up the main channel layer with them until they're ready to be worked on.

The suggested channel name is `channels.delay`, with the idea that the `channels` namespace can grow to cover other generic (non-protocol-specific) things like this.

This might also share an implementation with #74.

**Comment by linuxlewis** [comment]
I think this can be closed now

**Comment by hoaivan** [comment]
This is wonderful. Any schedule to make this into a release 0.17.4?

**Comment by andrewgodwin** [comment]
It'll be in the 1.0 release when I can get it out (this likely involves my wrist healing up first!)
