### ISSUE TITLE
channels.db.DatabaseSyncToAsync vs aiopg

### ISSUE THREAD

**Issue by lboc80** [django/channels#1151]
I'm looking for something that can allow the usage of the Django ORM with asyncio (with PostgreSQL). 
As of now I found only [aiopg](https://github.com/aio-libs/aiopg) in the asyncio ecosystem, which allows to run raw SQL or to use SQLAlchemy only.

is this:
https://github.com/django/channels/blob/master/channels/db.py
the missing piece that I was looking for?
I'd like to have an opinion from someone from the channels community

Thanks

**Comment by andrewgodwin** [comment]
Hi, this issue tracker is for bugs and feature requests only, not discussion (see https://channels.readthedocs.io/en/latest/support.html) - you're better off asking that question on a mailing list or other forum.
