### ISSUE TITLE
Channels ASGI thread count is increasing

### ISSUE THREAD

**Issue by ekbts7** [django/channels#1152]
Hi, I am new to Django and channels. I am using AsyncWebsocketConsumer and when I needed to debug something I realized there are so many running threads. Thread count is increasing every time I call sync_to_async function for calling sync function or send a new http request to the server.

I also followed the documentation here from start:
https://channels.readthedocs.io/en/latest/tutorial/part_1.html

After completing this part, in every page request, thread count is increasing at top 23(Near CPU * 5 I suppose) I am checking thread counts in OS-level.

Is this normal behaviour when using ASGI? Even I stop sending requests, running thread count doesn't decrease. When I switched back to WSGI I didn't observe the problem. I also found the same problem here with no answers: 
https://stackoverflow.com/questions/52110761/django-and-channels-and-asgi-thread-problem

I am using Python 3.6.5 on mac,
aioredis==1.1.0
asgiref==2.3.2
async-timeout==3.0.0
attrs==18.1.0
autobahn==18.7.1
Automat==0.7.0
certifi==2018.8.13
channels==2.1.2
channels-redis==2.2.1
chardet==3.0.4
constantly==15.1.0
daphne==2.2.1
Django==2.1
hiredis==0.2.0
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
msgpack==0.5.6
PyHamcrest==1.9.0
pytz==2018.5
redis==2.10.6
requests==2.19.1
six==1.11.0
Twisted==18.7.0
txaio==18.7.1
urllib3==1.23
websocket-client==0.49.0
zope.interface==4.5.0

Running channels: runserver

Thank you for your help,
Erkin

**Comment by andrewgodwin** [comment]
Hey - this is normal behaviour, and I explained a little more on the mailing list post you made on django-users.
