### ISSUE TITLE
Documentation on Ubuntu deployment with Apache2 and Daphne

### ISSUE THREAD

**Issue by Jaime5** [django/channels#1153]
It would be nice to include this documentation directly to support integration of websockets to the majority of the Django ecosystem.

**Comment by andrewgodwin** [comment]
I'll happily accept this documentation as a pull request if someone has the time, but it's not something we're actively seeking to add and so I'm going to close this as an issue.

(Plus, Apache2 has big problems proxying WebSockets so it's going to be unusual for most people to use it)
