### ISSUE TITLE
Complete a mission with channels2.0 and celery

### ISSUE THREAD

**Issue by YoLoveLife** [django/channels#1157]
OS: CentOS7.2
package: channels 2.1.1  channels-redis 2.2.1  celery4.2.1
way: django runserver
question:
I have a task in celery(the task is a mission,and it will finish some work in os).And i want to make a websocket with channels2.0.When the websocket connect, the task of celery will push out.Then the celery-task will send some message to the websocket.
Like
[ User => Websocket(when connect) => (push)Celery Task ]
[ Celery Task(when some msg need to tell user) => Webcoket => User]
**Channels will be the middleman in my work.**
when i in old version of channels, i use the channels like:
```python
def connect(self, message):
      self.accept()
      task.delay(self)  #channels socket to celery
```
And the celery-task will send the msg back to channels ..to the websocket.
But when channels 2.1.1  channels-redis 2.2.1  celery4.2.1.
Something wrong happened.
wrong: 
**You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly**
or
**Exception inside application: Cannot serialize socket object** 
Maybe celery task can't get the socket object through this way.

Could you tell me in my use case how can i do in my code.
I'mat the end of my rope.

**Comment by andrewgodwin** [comment]
This is not the right place to ask for support - please see https://channels.readthedocs.io/en/latest/support.html for the right places.
