### ISSUE TITLE
channel_layer.group_send isn't asynchronous

### ISSUE THREAD

**Issue by ZuluPro** [django/channels#1160]
When I tried to send messages with `channel_layer.group_send`, they aren't asynchronous and come at the end of the function.

Here's the code:

```
class MyConsumer(AsyncJsonWebsocketConsumer):
    ... 
    async def connect(self):
        await self.accept()
        await self.channel_layer.group_add('thegroup', self.channel_name)

    async def disconnect(self, close_code):
        await self.channel_layer.group_discard('thegroup', self.channel_name)

    async def receive(self, text_data):
        # Receive data and dispatch to methods
        payload = json.loads(text_data)
        await getattr(self, payload['command'])(payload)

    async def run(self, event):
        await sync_to_async(my_long_task_sending_messages)()

    async def user_message(self, event):
        await self.send_json(event["text"])
    ...

```

If I don't use directly `MyConsumer.send_json`, messages aren't asynchronous, even with `channel_layer.group_send`. My `my_long_task_sending_messages` could be:

```
def my_long_task_sending_messages():
    channel_layer = get_channel_layer()
    def send(msg):
        async_to_sync(channel_layer.group_send)('thegroup', {
            'type': "user_message",
            'text': msg,
        })
    send('foo')
    time_sleep(3)
    send('bar')
    time_sleep(3)
    send('ham')
```

This task will take 6 seconds and all the message will be given at the end.

My envs are:
- Linux env
- Python 3.5/3.6
- asgiref 2.3.2
- daphne 2.2.2
- channels 2.0.2
- channels-redis 2.3.0

I tried with `runserver` and `daphne` with the same results.

Do you have any idea why ?

**Comment by andrewgodwin** [comment]
I'm afraid the issue tracker is for replicatable bugs only, rather than support requests - please see https://channels.readthedocs.io/en/latest/support.html for more.

In your case, I would make sure you are running any synchronous code, like your function, in a separate environment far away from any async code. There's a whole heap of ways they can block each other otherwise.
