### ISSUE TITLE
More security guidelines in docs

### ISSUE THREAD

**Issue by eddy-ojb** [django/channels#1168]
Hi,

This is a feature request for more detail in the docs on the security of using websockets in channels. Happy to help document this as I find out more.

Issue: It has been unclear to me as a relatively new user of channels as to how e.g. forms should be constructed and validated when migrating my mindset from core Django to channels. For example, the tutorials define forms in the html template, implying that Django forms are not necessary. I take it they are not pairable with websockets as they post data instead of send, but I think feature differences like this amd csrf tokens should be more explicit. Does this also mean that we should also write our own equivalent to .is_valid() logic?

I'm sure that I'm just scraping the surface here but even just some links to recommended reading for websockets security would result in quick, useful gains for newbies.

Ed

**Comment by andrewgodwin** [comment]
I'm not sure this is really something we can cover in the Channels docs directly - web security is a massive topic, and Channels' only unique feature is WebSockets, which have a very strict security model already that is covered elsewhere (and which we ship an origin-header checking module for with docs).

If you can gather useful links to add in I can mix them in, but I don't have any on hand right now.

**Comment by eddy-ojb** [comment]
Thanks Andrew.  I am feeling my way around security issues as I become more familiar with Channels and 
 will return with some links. I imagine it would be quite useful as I expect most others to have the same query.
