### ISSUE TITLE
Handle large request bodies correctly

### ISSUE THREAD

**Issue by dav20011** [django/channels#1169]
These are two distinct issues on the same topic:
### 1. Add a size limit for request bodies
Upon reading the request body Django's request objects check the content length and compare it to a size limit set in the config:
```
# Limit the maximum request data size that will be handled in-memory.
if (settings.DATA_UPLOAD_MAX_MEMORY_SIZE is not None and
        int(self.META.get('CONTENT_LENGTH') or 0) > settings.DATA_UPLOAD_MAX_MEMORY_SIZE):
    raise RequestDataTooBig('Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE.')
```
AsgiRequest objects do not perform this check, which is very dangerous. I was able to spam the server with only a few large request, which made the server incapable of handling any other request.

### 2. Support manual handling of the body input stream
Django requests only contain a stream for the request body and lazy load the "request.body" property if needed. This is very intuitive because you can handle tasks like a file upload without loading the entire file into the memory while keeping the possibility of easily accessing the request body.

AsgiRequests on the other hand load the entire body before the execution of the view and only offer a fake stream. Looking at this code, it seems perfectly doable to handle this exactly like Django does by default. There actually is a TODO for this feature in the code, but I think it got forgotten.

**Comment by andrewgodwin** [comment]
Please open these as two separate issues so we can track and discuss them separately - thanks!
