### ISSUE TITLE
Correct use of Django Channels

### ISSUE THREAD

**Issue by PythonDeGenerous** [django/channels#1173]
We are currently using https://github.com/django/channels/ to get logs and send commands from and to docker containers. Multiple users connect on the site and simultaneously to the websocket that connects to our consumer.

The connection itself is working, but as soon as more and more users are trying to use the functionality, the threads are all used and only the first ~20 users can use it. No further threads and connections can be opened.

We assume that it's related to the loop that we are using to allow realtime information of the containers. This is the logic we are using:
```
class TerminalConsumer(JsonWebsocketConsumer):

def connect(self):
    self.accept()
    try:
        group_name = 'server-%s' % self.scope['session']['server_id']
        server = CustomModel.objects.get(id=self.scope['session']['server_id'])
        container = get_docker_container(server)
        self.channel_layer.group_add(group_name, self.channel_name)
        if container is not False:
            for line in container.logs(stream=True, tail=150):
                self.send_json(line.strip().decode('utf-8'))
                asyncio.sleep(0.01)
    except Exception:
        pass

def disconnect(self, close_code):
    group_name = 'server-%s' % self.scope['session']['server_id']
    self.channel_layer.group_discard(group_name, self.channel_name)
    try:
        group_name = 'server-%s' % self.scope['session']['server_id']
        self.channel_layer.group_discard(group_name, self.channel_name)
    except Exception:
        pass
```
The client never disconnects and so the threads are completely used by the first users connecting. Where would we have to put the loop to disconnect the websocket accordingly? Or is there any workaround?
On Stackoverflow nobody was able to help us, so this is kinda our last chance.

We are using Debian Stretch, Python 3.7.0, UWSGI for the app, daphne for channels, nginx as webserver.
We also tried Python 3.6 and 3.5 - no change.

**Comment by andrewgodwin** [comment]
I'm afraid I can't do support here - see https://channels.readthedocs.io/en/latest/support.html for more info. Answering support here would leave no time for anything else.
