### ISSUE TITLE
Django Channels trying to send to single channel layer outside of consumer

### ISSUE THREAD

**Issue by prajvalbavi** [django/channels#1184]
Below code is in my view.py
def func1():
    async_to_sync(channel_layer.send)(_clinetNameObj.clientName, {"type": "play_message"})
async def play_message(event):
	print("********************** calling here **********************")
	sys.stdout.flush()
	await AsyncConsumer.send({"text": "something"})

I am getting issue saying "No handler for message type play_message"

**Comment by andrewgodwin** [comment]
Hey, this isn't the right place to ask for help with Channels apps - you can read more about where to look at https://channels.readthedocs.io/en/latest/support.html
