### ISSUE TITLE
ModuleNotFoundError: No module named 'channles'

### ISSUE THREAD

**Issue by sachinsiddhpura** [django/channels#1186]
While done installtion of 'channles'...But it is doesn't work in my projects.. however i was install channels still show 'ModuleNotFoundError: No module named 'channles''

**Comment by andrewgodwin** [comment]
The package is spelled `channels`, not `channles` - make sure you installed the right one (and don't install `django-channels`, which is not the right package either).

**Comment by sachinsiddhpura** [comment]
Sorry .. Its my spelled mistake in issue..but in projects it is channles ..But won't work,,

**Comment by sabuhish** [comment]
well I had the same issue before, I solved by changing it is place like it follows:
INSTALLED_APPS = [
    "chat",
    "channels",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "my_app.apps.MyAppConfig",
]

**Comment by ChristianTBaker** [comment]
I'm having a similar issue.  It worked as I was going through the tutorial, but once I reopened the project later it said "channels module not found" . when I tried to run the Django server.

**Comment by carltongibson** [comment]
Check you activated your venv.

**Comment by ChristianTBaker** [comment]
I figured it out finally.  I'm still a beginner.  I was using a cloned venv folder.  I needed to delete that folder, create a new venv and reinstall the dependencies on that venv.  I made a requirements.txt to make it easier next time.  I also added venv to my .gitignore, cleared the index, and made sure to only add necessary file to the repository.

**Comment by Niyy** [comment]
The solution that I found with docker was to rebuild. I always forget to rebuild after editing the settings.py. 
```
docker-compose build web
```
I did this with a docker-compose file, and replace web with your container. :)
