### ISSUE TITLE
Add commonly implemented consumers 

### ISSUE THREAD

**Issue by WisdomPill** [django/channels#1187]
Hello,
I found myself implementing consumers to do basic stuff, like checking if the user is logged in, so I made two consumers that resemble the LoginRequiredMixin and UserPassesTestMixin from django.
I propose a basic implementation of these two to be included in the next version of channels, like the following

``` python
from channels.exceptions import DenyConnection, AcceptConnection
from channels.generic.websocket import AsyncWebsocketConsumer


class AsyncLoginRequiredConsumer(AsyncWebsocketConsumer):
    user = None

    async def connect(self):
        self.user = self.scope['user']

        if self.user.is_authenticated():
            raise AcceptConnection
        else:
            raise DenyConnection


class AsyncUserPassesTestConsumer(AsyncWebsocketConsumer):
    user = None

    async def connect(self):
        self.user = self.scope['user']

        if self.user.is_authenticated() and self.test_func():
            raise AcceptConnection
        else:
            raise DenyConnection

    def test_func(self):
        raise NotImplementedError(
            '{0} is missing the implementation of the test_func() method.'.format(self.__class__.__name__)
        )

```

best regards, WisdomPill

**Comment by andrewgodwin** [comment]
Actually I've decided against including them in the past, because they tend to be something people want to customise at a deep level (add logging, etc.), and it means more code to maintain, so I'd rather leave them out for now. Thanks for the code though, hopefully people can find them here and use them if they want!
