### ISSUE TITLE
Possible to use persistent "channel_name" for user?

### ISSUE THREAD

**Issue by gotexis** [django/channels#1190]
I've come to notice that channel_name will be generated at random on each WebSocket connection.

My use case will be like a mailbox for each user. I wonder if it is possible to manually specify a channel name like "user_channel_%UID" so that later if I want to send a notification to that user, it will be easier?

Cheers

**Comment by andrewgodwin** [comment]
That's what groups (https://channels.readthedocs.io/en/latest/topics/channel_layers.html#groups) are for - persistent names that you can send things to. This is done because a user might have multiple tabs open, so generally any "per user" socket identification has to allow for multiple sockets!
