### ISSUE TITLE
[Suggestion] Downgrade redis in the tutorial

### ISSUE THREAD

**Issue by vincent-lg** [django/channels#1192]
You have done a great job if trying to summarize a complex topic in the tutorial, and providing a step-by-step process that should lead to understand channels and channel layers, among other topics.  However, I feel there is one specific topic about channel layers that is a bit too complicated for the typical Django user (as I understand it, anyway): `redis` as a default.

`redis` is sure great, but for a basic tutorial, it's not the best solution.  Here's why:

1. It requires yet another additional dependency.  I guess you are aware of it, but to have the channels tutorial working, one has to install a lot of things.  Fortunately, most are one command installation through `pip`.  `redis` is not one of them.  At best, you have to setup docker if you don't want to get `redis` manually.
2. `redis` is not very compatible with other OSes, in particular Windows.  I had to hunt for a `redis` version that worked on Windows, and when I had set it up, I was told some features of the channel layers weren't available on the version I had.

To address both issues, I would recommend to include something much more simple: relying on the `InMemoryChannelLayer` channel layer.  It certainly has its pitfalls, may not be a good choice in production, but it's portable, easy to setup, doesn't require additional dependencies.  So I would suggest to update the documentation, to either mention `InMemoryChannelLayer` or even bring it up **before** `redis`.  You could, of course, indicate the danger of this layer, but I still think a Django user (particularly on Windows) won't mind having something not fit for production immediately:

```python
# ... excerpt for mysite/settings.py
# ...
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}
```

Thanks for your great work!

**Comment by andrewgodwin** [comment]
The in-memory channel layer is not designed to be used outside of tests though, so as much as getting Redis working is annoying, it's currently the only option. We'd need another backend that worked across processes working first before we could rewrite the tutorial to remove Redis.

**Comment by changeling** [comment]
Perhaps [python-diskcache](http://www.grantjenks.com/docs/diskcache/) ?
