### ISSUE TITLE
Why AsyncToSync not utilizing outer event loop when called from sync code?

### ISSUE THREAD

**Issue by Sovetnikov** [django/channels#1194]
I have a situation when async code calls sync code and sync code need to make group_send call with AsyncToSync.
AsyncToSync call raises exception "You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.".
But why not just inject group_send call in outer loop by create_task if AsyncToSync detects it?

**Comment by andrewgodwin** [comment]
Because that won't work - if you are blocking-calling async-to-sync in the async thread, then the outer event loop will never get to run. The error message is just alerting you to the fact you're trying to run sync code in an async thread, which is a bad idea for anything long-running.

**Comment by Sovetnikov** [comment]
Will never get run? That is strange assumption.
Origin of this situation is that async code calls sync code and then control is returned back to async code, then next ticks are processed.
This is real world situation.
You are saying that event loop -> async -> sync -> group_send is not possible... but that's not true.
You are too async.

**Comment by andrewgodwin** [comment]
What I'm saying is that if you call a blocking sync function on the thread where the async event loop is running (which is where that error occurs), the sync function will block the event loop from running further, as it does not release control.
