### ISSUE TITLE
How to check the group is empty?

### ISSUE THREAD

**Issue by ixser** [django/channels#1201]
The case is : when i want to add a channel_layer to a group, i promiss the group is empty, but i don not know how to check if the group is empty? it seems that the framework function has no method to check it out, should i check it myself by read from redis db?

**Comment by andrewgodwin** [comment]
You cannot check how many channels are in a group (or if it is empty), `channels_redis` deliberately doesn't provide that as it doesn't work well with the sharded backend. If you need presence, you need to read and write to a database or redis yourself.

**Comment by patata3000** [comment]
I'm a bit of a noob in this domain so let me ask: does having a database dealing with this makes your code a lot slower ?
I don't know how to know if it's gonna be a big slow down... If the database is local or if it's far away... Any tips on that ?
