### ISSUE TITLE
Possible memory leak when sending large messages via web sockets

### ISSUE THREAD

**Issue by devxplorer** [django/channels#1202]
This issue is the continuation of #1181.

Current leak can be easily reproduced by following steps in readme of [test project](https://github.com/devxplorer/ws_test/tree/big_payload). Please note that the branch is different - `big_payload`.

The result of the steps will be a graph on which you can clearly see that the memory starts to grow in spurts and is not released completely ([example graph](https://github.com/devxplorer/ws_test/blob/big_payload/plots/big_payload.png)). 

The test environment is the same as in the previous issue.

**Comment by andrewgodwin** [comment]
OK - note that it may be a few months before I can get to this, so if anyone else wants to take a look they're welcome.

@devxplorer Have you confirmed this problem is in Channels rather than the Redis layer?

**Comment by devxplorer** [comment]
@andrewgodwin 

> @devxplorer Have you confirmed this problem is in Channels rather than the Redis layer?

I can not say for sure, could you please tell how can I find it out?

**Comment by devxplorer** [comment]
Strange thing, I tried to run a test script on another computer, there was no memory leak on the resulting graph. I will try to find out under what conditions it occurs.

**Comment by andrewgodwin** [comment]
You can turn off the Redis channel layer (set `CHANNEL_LAYERS` to empty), make sure none of your code uses it, and test again.

**Comment by agronick** [comment]
@devxplorer you sure you updated all your channels packages?

**Comment by devxplorer** [comment]
> @devxplorer you sure you updated all your channels packages?

Maybe. But now I can not repeat the result which is on the graph neither with the old versions of libraries, nor with the new ones.

**Comment by carltongibson** [comment]
I'm going to close this. If something is still reproducible here please open a fresh issue.
