### ISSUE TITLE
`AsyncConsumer` does not seems to consume asynchronous.

### ISSUE THREAD

**Issue by ryanrain2016** [django/channels#1203]
I have a consumer like this below
```python
class PrintConsumer(AsyncConsumer):
    async def print(self, message):
        print('we are in print consumer')
        import time
        print(time.time())
        await asyncio.sleep(3)
        print(message)
```
I use `await asyncio.sleep(3)` to  simulate a asynchronous IO operation. I exepect it to comsume message asynchronously. Unfortunately, When I send some message to it simultaneously in a `WebsocketConsumer` use code below, which is not blocked
```python
print('sending time', time.time())
async_to_sync(self.channel_layer.send)('print-channel',
                               {
                                   'type': 'print',
                                   'data': text_data
                               })
```
I got the runworker output
```
Running worker for channels ['print-channel']
we are in print consumer
1545365742.3813963
{'type': 'print', 'data': '{"a": 1}'}
we are in print consumer
1545365745.3783274
{'type': 'print', 'data': '{"a": 1}'}
we are in print consumer
1545365748.3837793
{'type': 'print', 'data': '{"a": 1}'}
we are in print consumer
1545365751.3891735
{'type': 'print', 'data': '{"a": 1}'}
we are in print consumer
1545365754.3929133
{'type': 'print', 'data': '{"a": 1}'}
```
The output shows the consumer comsumes message synchronously.

- OS
Win10, redis 4.0.9 on wsl(ubuntu 18.04),
- some package version as below:
aioredis==1.2.0
channels==2.1.6
channels-redis==2.3.2
daphne==2.2.4
asgiref==2.3.2
Django==2.1.4
- How you're running Channels?
python manage.py runserver / daphne.exe -p 8000 myproject.asgi:application (two ways, same result)
python manage.py runworker
- Console logs and full tracebacks of any errors
runserver logs as below and runworker logs as above:
```
December 21, 2018 - 12:15:34
Django version 2.1.4, using settings 'myproject.settings'
Starting ASGI/Channels version 2.1.6 development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
WebSocket HANDSHAKING /ws/ [127.0.0.1:18279]
sending time 1545365742.3783987
WebSocket CONNECT /ws/ [127.0.0.1:18279]
WebSocket HANDSHAKING /ws/ [127.0.0.1:18283]
WebSocket CONNECT /ws/ [127.0.0.1:18283]
sending time 1545365742.7515204
WebSocket HANDSHAKING /ws/ [127.0.0.1:18286]
WebSocket CONNECT /ws/ [127.0.0.1:18286]
sending time 1545365743.1572874
sending time 1545365743.5453074
WebSocket HANDSHAKING /ws/ [127.0.0.1:18287]
WebSocket CONNECT /ws/ [127.0.0.1:18287]
WebSocket HANDSHAKING /ws/ [127.0.0.1:18288]
WebSocket CONNECT /ws/ [127.0.0.1:18288]
sending time 1545365743.9188855
```

**Comment by ryanrain2016** [comment]
I inspect the source code, find that the one channel's message will be consumed in sequences.  Is that the design? How can I handle messages simultaneously in one channel?

**Comment by andrewgodwin** [comment]
Yes, that is the intended design, as it's the safest way (it prevents race conditions if you're not aware of it). If you are happy to run messages in parallel, just spin off your own coroutines whenever you need them (using `asyncio.create_task`), making sure that you clean them up and wait for them on shutdown. It's quite a lot of overhead, so hopefully we'll ship an opt-in mode for that in the consumer in future, but for now all we ship with is the safe option.
