### ISSUE TITLE
Multiple ASGI applications using Supervisor

### ISSUE THREAD

**Issue by devalfrz** [django/channels#1208]
## Objective

I'm trying to deploy multiple **ASGI** applications on the same server using **supervisor** and **nginx**. Since I'm working on multiple applications it is difficult to keep track of which ports are available or which port corresponds to which application. In this example I'm using **port 8001**.

## Current Configuration (Works)

`/etc/nginx/sites-available/my-app01.conf` **Works**:
```
upstream my_app01_wsgi {
  server unix:///var/run/my_app01/wsgi.sock;
}

upstream my_app01_asgi {
  server localhost:8001;
}

server {
  listen [::]:80;
  listen 80;

  server_name my_app01.some-domain.com;

  charset utf-8;

  client_max_body_size 75M;

  location / {
    uwsgi_pass  my_app01_wsgi;
    include /etc/nginx/uwsgi_params;
  }

  location /ws/ {
     proxy_pass http://my_app01_asgi;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";

     proxy_redirect     off;
     proxy_set_header   Host $host;
     proxy_set_header   X-Real-IP $remote_addr;
     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header   X-Forwarded-Host $server_name;
  }
}
```

`/etc/supervisor/conf.d/my_app01.conf` **Works**:
```
[fcgi-program:my_app01]
socket=tcp://localhost:8001
directory=/path/to/my_app01/
command=/path/to/my_app01/env/bin/daphne -u /var/run/%(program_name)s/asgi%(process_num)02d.sock --fd 0 --access-log - --proxy-headers my_app01.asgi:application
numprocs=20
process_name=%(program_name)s_asgi%(process_num)02d
autostart=true
autorestart=true
stdout_logfile=/var/log/%(program_name)s_asgi.log
redirect_stderr=true
```

## Ideal Configuration (Doesn't Work)

`/etc/nginx/sites-available/my-app01.conf` **Doesn't Work**:
```
upstream my_app01_wsgi {
  server unix:///var/run/my_app01/wsgi.sock;
}

upstream my_app01_asgi {
  server unix:///var/run/my_app01/asgi.sock;
}

server {
  listen [::]:80;
  listen 80;

  server_name my_app01.some-domain.com;

  charset utf-8;

  client_max_body_size 75M;

  location / {
    uwsgi_pass  my_app01_wsgi;
    include /etc/nginx/uwsgi_params;
  }

  location /ws/ {
     proxy_pass http://my_app01_asgi;
     proxy_http_version 1.1;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";

     proxy_redirect     off;
     proxy_set_header   Host $host;
     proxy_set_header   X-Real-IP $remote_addr;
     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header   X-Forwarded-Host $server_name;
  }
}
```

`/etc/supervisor/conf.d/my_app01.conf` **Does't Work**:
```
[fcgi-program:my_app01]
socket=unix:///var/run/%(program_name)s/asgi.sock
socket_mode=0666
directory=/path/to/my_app01/
command=/path/to/my_app01/env/bin/daphne -u /var/run/%(program_name)s/asgi%(process_num)02d.sock --fd 0 --access-log - --proxy-headers my_app01.asgi:application
numprocs=20
process_name=%(program_name)s_asgi%(process_num)02d
autostart=true
autorestart=true
stdout_logfile=/var/log/%(program_name)s_asgi.log
redirect_stderr=true
```

## Observations

Running the supervisor with the *unix socket* option creates a socket located in `/var/run/my_app01/asgi.sock` with the propper permissions, but nginx gives me a *502 Bad Gateway* error when I call it.
I'm using Debian with Python3.5.

**Comment by andrewgodwin** [comment]
I'm not sure exactly what to do with this - it's not a bug in Channels, so it doesn't belong here. It might be a bug in Daphne, but you're not exactly clear what is wrong - as you say, it creates a UNIX socket in the right place with the right permissions, so I suspect this is a config issue on the nginx end. I'd try playing around with just using the ASGI socket and some other things to work out what's wrong, and if you do find an actual bug in Daphne, open a ticket over on its tracker.

**Comment by JanMalte** [comment]
@devalfrz How did you solved this issue? I'm currently having the same issue. The TCP socket is working, but a UNIX socket isn't.
