### ISSUE TITLE
Can't install channels successful using pipenv

### ISSUE THREAD

**Issue by abhisunkewar** [django/channels#1210]
When trying to install channels using pipenv it shows - **An error occurred while installing twisted==18.9.0**. 

Please note that channels also fails to install in the pipenv shell using pip. The error displayed is _Failed building wheel for twisted_ in this case.

The dependencies always fail to install. Please fix it ASAP.

**Comment by andrewgodwin** [comment]
I'm afraid I can't help with installing Twisted on your platform - you'll need to seek help elsewhere for how to do that before you can install Channels.
