### ISSUE TITLE
WebSocket connection to 'ws://127.0.0.1:8000/ws/' failed: Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by Pkaran26** [django/channels#1212]
WebSocket connection to 'ws://127.0.0.1:8000/ws/' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by andrewgodwin** [comment]
This isn't an issue report we can act on - please either give more detailed information including steps to replicate done on a new machine, or look at other resources for support (read more here: https://channels.readthedocs.io/en/latest/support.html)
