### ISSUE TITLE
AsyncHttpConsumer  handle

### ISSUE THREAD

**Issue by insung151** [django/channels#1219]
```python
    async def http_request(self, message):
        """
        Async entrypoint - concatenates body fragments and hands off control
        to ``self.handle`` when the body has been completely received.
        """
        if "body" in message:
            self.body.append(message["body"])
        if not message.get("more_body"):
            try:
                await self.handle(b"".join(self.body))
            finally:
                await self.disconnect()
                raise StopConsumer()
```
This is the method in AsyncHttpComsumer class.

If the user makes a request to the server, this method is executed and this method called self.handle.

But since the handle method is in the try clause, I do not know the error that raised in the handle method.
Is this intended?

**Comment by andrewgodwin** [comment]
That's a try/finally, which won't catch errors, it just runs the `finally` block and then continues the error propagation. If you're not seeing an error, your logging is likely wrong or you have another app/middleware catching it.
