### ISSUE TITLE
Expose daphne.server.Server's ready_callable

### ISSUE THREAD

**Issue by patrys** [django/channels#1220]
I have an application where I'd like to use an asynchronous database API ([GINO](http://gino.fantix.pro/en/latest/index.html)) that needs to be initialized asynchronously.

I could create a temporary event loop and have it run the initialization code until completion at import time but GINO expects to be initialized using the same event loop that is later used for querying.

Since daphne already exposes a "ready" callback, maybe channels could use it and support something like:

```python

class MyASGIApp(ProtocolTypeRouter):
    @classmethod
    async def ready(cls):
        ....
```

or even just `async def ready(): ...` in the settings file?

**Comment by andrewgodwin** [comment]
This is more an ASGI problem than a Daphne one itself - we made a thing for this in ASGI, which is the `lifespan` protocol: https://asgi.readthedocs.io/en/latest/specs/lifespan.html

That's the thing that needs implementing, and once that's done you'll be able to use it for things like this.
