### ISSUE TITLE
Custom Authentication Documentation: close_old_connections() should be called BEFORE database operations

### ISSUE THREAD

**Issue by gitaarik** [django/channels#1227]
The documentation for Custom Authentication says that we should call `close_old_connections()` after we do database operations. We did this, but we were still getting `MySQL server has gone away` errors. They happen when the daphne process is still running but didn't do any queries for a time longer than the MySQL connection timeout setting, and then after that time tried to do a query again.

This is the relevant documentation section:
https://channels.readthedocs.io/en/latest/topics/authentication.html#custom-authentication

After I tried placing the `close_old_connections()` at the start of the `__call__()` method before doing any database queries, the problem didn't occur anymore. Thinking about it the fix makes sense; before you do any database queries you want to clean up the old timed-out database connections so you won't use these. If you call this method just after you done the query, the database connection is probably still active and it's not cleaned up. So I think the documentation should be updated to placing `close_old_connections()` at the start of the `__call__()` method.

**Comment by carltongibson** [comment]
Thanks for the report. Fancy doing a PR @gitaarik?
