### ISSUE TITLE
valid_group_name throwing wrong exception message

### ISSUE THREAD

**Issue by ericls** [django/channels#1229]
`valid_group_name` always throws the message `Group name must be a valid unicode string containing only ASCII alphanumerics, hyphens, or periods.`, even if the actual error is group name being too long. Would be helpful if we throw a different message or include the length limit in the message.

**Comment by andrewgodwin** [comment]
I agree, it would be helpful, this wouldn't be too hard for someone to write a patch for.

**Comment by ericls** [comment]
I'll submit a PR shortly. Also, is it documented anywhere why there's a restriction on the length of the names? Thank you!

**Comment by andrewgodwin** [comment]
There's no specific reason, but it's so the names can be more easily portable across different backends. Unlimited length names would be hard to deal with in some places.
