### ISSUE TITLE
when client close the web socket,the server disconnect() can't work

### ISSUE THREAD

**Issue by Gaoyongxian666** [django/channels#1231]
ubuntu 18

I wrote a class.（constumer） 
When the browser actively disconnects，Server-side function（disconnect ）don‘t execute.

**Comment by andrewgodwin** [comment]
Sorry, but we can't help out with general support requests here - the issue tracker is for reproduceable bugs and concrete feature requests only! Please see our support documentation (http://channels.readthedocs.io/en/latest/support.html)
for more information about where you can get general help.
