### ISSUE TITLE
add in group

### ISSUE THREAD

**Issue by yuta86** [django/channels#1233]
Hi!  I am trying to use your library for my project. Basically, i am trying to implement the next algorithm: User "X" presses the button to make a new chat with "Y" user. The very record to database regarding this event I have made, but how can I include both of this users to the group, so they can communicate with each other in real time? Cannot resolve this issue for a long time, сould you help me with that, please?
Thank you!

**Comment by andrewgodwin** [comment]
Hey, I'm afraid we can't help you with design questions here - try asking one of the other support channels! https://channels.readthedocs.io/en/latest/support.html
