### ISSUE TITLE
Update Django Docs Example app

### ISSUE THREAD

**Issue by vaibhavkumar049** [django/channels#1236]
Please update Django app example given in Docs to Django 2.1

**Comment by vaibhavkumar049** [comment]
I have implemented it , Please check here
https://github.com/vaibhavkumar049/django-chat-channels

**Comment by auvipy** [comment]
could you send a pr?

**Comment by vaibhavkumar049** [comment]
@auvipy sorry, I am nat able to find the main repo of that example , so that after forking ,I'll be able to make PR request :(

**Comment by jpic** [comment]
@vaibhavkumar049 maybe the page you're referring to is in the tutorial directory ? https://github.com/django/channels/tree/master/docs/tutorial

**Comment by carltongibson** [comment]
Resolved in  #1273
