### ISSUE TITLE
Httpconsumer problem

### ISSUE THREAD

**Issue by waqasraz** [django/channels#1245]
```
class FetchVendorConsumer(AsyncHttpConsumer):
    async def handle(self, body):
        try:
            await self.send_response(200, b"Hello", headers=[
                ("Content-Type", "application/json"),
            ])
        except:
            print('ss')
```
When i send request to this view, it print ss. Not sure how can I get the exception that is being raised? 

I am doing this because when I send request from frontend I don't get any response back.

**Comment by jpic** [comment]
Can you get it with the [traceback module](https://docs.python.org/3/library/traceback.html) ?

**Comment by waqasraz** [comment]
There was no documentation on header must be a byte string. Any how it's fixed now.

(b"Content-Type", b"application/json")

**Comment by matthiask** [comment]
That cannot be. The *body* has to be bytes, yes, but headers don't have such a requirement (I think); otherwise why would the test here pass? https://github.com/django/channels/blob/6f8bf164922482604bb2d462adb75414b0bc2d4b/tests/test_generic_http.py#L21

**Comment by waqasraz** [comment]
```
Traceback (most recent call last):
.....
ValueError: Header name 'Content-Type' expected to be `bytes`, but got `<class 'str'>`

```

**Comment by matthiask** [comment]
Interesting. Which ASGI server are you using? (Daphne, uvicorn?)

**Comment by matthiask** [comment]
Ah nice. That seems to be a deficiency in the test suite. Daphne was updated recently to not accept `str` headers anymore:

https://github.com/django/daphne/commit/e93643ff5a2797f05e88bc59800d7b4dbf41765d#diff-85b85c74fb75ac361c16115d9ffd1977
