### ISSUE TITLE
Redis slave is wrong

### ISSUE THREAD

**Issue by zdYng** [django/channels#1252]
Why is redis multi-node not compatible with channels' websocket module?

**Comment by zdYng** [comment]
When I start multiple redis nodes, django channels will report an error, indicating that no extra slots are allocated.

**Comment by carltongibson** [comment]
Hi. Please see https://channels.readthedocs.io/en/latest/support.html for support channels.

**Comment by zdYng** [comment]
Hello, the URL you provided does not really help me :)

**Comment by carltongibson** [comment]
It's a guide to places you can get support. (I'm afraid we can't offer support here.)

If you can identify a specific issue in channels we're happy to look.
