### ISSUE TITLE
How to do Websocket binding in a django model that has a field of ForeignKey type?

### ISSUE THREAD

**Issue by datasleek** [django/channels#1253]
Suppose I have a model whose one field is of ForeignKey type.

```
class House(models.Model):
     house_name = models.CharField(max_length=120)
     tenant = models.ForeignKey('Tenant',on_delete=models.CASCADE)

class Tenant(models.Model):
    name = models.charField(max_length=120)
    married = models.BooleanField(default=False)
    phone = models.CharField(max_length=10)
```

I want to bind events of model House using WebsocketBinding.So i have written down the following

```
class HouseBinding(WebsocketBinding):
    model = House
    stream= "houseStream"
    fields = ["__all__"]
    
    @classmethod
    def group_names(cls, *args, **kwargs):      
        return ["binding.values"]
    
    def has_permission(self, user, action, pk):
        return True    
```

Now whenever an object of House model will be created or updated or deleted the payload will be sent to the connecting client.I have added the Demultiplexer route in routing.py and a WebsocketDemultiplexer class  in consumers.py .Now suppose i am creating, updating and deleting objects of House model at server end using form having fields like house_name,tenant_name,tenant_married_status and tenant_phone_number.

I am listening these events at client side using the following code.

```
    var webSocketBridge = new channels.WebSocketBridge();
    webSocketBridge.connect(ws_path);
    webSocketBridge.listen();
    webSocketBridge.demultiplex('houseStream', function(payload, streamName) 
       {  
           console.log(payload.data.house_name);  //I am getting correct value for this.
           console.log(payload.data.tenant.name);    //getting 'undefined' for this
           console.log(payload.data.tenant.married);  //getting 'undefined' for this
           console.log(payload.data.tenant.phone);  //getting 'undefined' for this
        });
```
Could you please tell me why am i getting 'undefined' whenever i try to fetch any value that is stored in 'Tenant' model. If i am doing something wrong or there is different approach for handling these situations, then please guide me as **i cannot find any resource on internet to sought out this issue**
 
**Thanks in advance**

**Comment by hishnash** [comment]
Channels 2 does not include any `WebsocketBinding` https://github.com/hishnash/djangochannelsrestframework aims to provide some of this as an extension to channels

**Comment by datasleek** [comment]
> Channels 2 does not include any `WebsocketBinding` https://github.com/hishnash/djangochannelsrestframework aims to provide some of this as an extension to channels

Sir, I am not using Channels 2. I am using channels 1.8

**Comment by jheld** [comment]
Would it be useful to include a version tag for this issue to let others know easily that it's for an older (e.g. unmaintained?) version of channels?

**Comment by carltongibson** [comment]
TBH, let's just close it...
