### ISSUE TITLE
Upload file timeout settings

### ISSUE THREAD

**Issue by d270624** [django/channels#1256]
I use input to upload files, but browsers will prompt ERR_CONNECTION_RESET to upload large files for more than 60 seconds, but if I stop registering channels, the phenomenon will be restored. I tried to add - http_timeout 60000 at startup, but it did not solve the problem. I did not find the relevant settings on the document.What caused this problem?

**Comment by guiagge** [comment]
Hi @d270624, did you manage to solve this issue? I'm also facing a timeout trying to upload files to a Django server.
I didn't understand what you meant by "stop registering channels", did that fix the problem?
I tried changing every configuration regarding timeouts on Django itself and on the other layers of the application, but still the uploads always timeout after exactly one minute, is this an inherent problem with Django that can't be circunvented?

Best regards!
