### ISSUE TITLE
No LICENSE file in PyPi package

### ISSUE THREAD

**Issue by d-s-e** [django/channels#1257]
I just noticed, that the LICENSE file is missing in the PyPi package. It should better be present there.

**Comment by carltongibson** [comment]
OK. Yes. Would (happily) take a PR on the MANIFEST.in ... 🙂

**Comment by d-s-e** [comment]
sure, can do this.

**Comment by d-s-e** [comment]
#1259

**Comment by carltongibson** [comment]
Closed by #1259
