### ISSUE TITLE
Explain Callback Function in Tutorial 2

### ISSUE THREAD

**Issue by claytondaley** [django/channels#1261]
After several passes, I finally guessed (correctly as it were) that `type` key identifies the callback function for a particular channel.  Unfortunately, this isn't clearly stated in Tutorial 2 so it took me several passes to guess -- and a deep dive on the code to confirm.

 - I suggest actually explaining this relationship in the tutorial.
 - As part of this explanation, it may be worth discussing any restrictions on `type` in `get_handler_name` (e.g. `.` to `_` conversion).  It looks like you could even send `type=disconnect`, but I'm not sure if this would be a feature or bug.  Nor do I know the consumer well enough to know if you could do any real damage by sending an unexpected `type`.
 - If this is not a feature, perhaps the handler should be called with `kwargs` instead of `args` to prevent calls to methods that don't explicitly accept an `event` (though this would certainly be backwards incompatible).

**Comment by carltongibson** [comment]
Yep. OK. Cool. All clarifications welcome!

**Comment by carltongibson** [comment]
I think this is covered in the explanation at the bottom of the [Enable a channel layer](https://github.com/django/channels/blob/main/docs/tutorial/part_2.rst#enable-a-channel-layer) section of Tutorial Part 2. 

> An event has a special 'type' key corresponding to the name of the method that should be invoked on consumers that receive the event.

Happy to look at PRs improving that but...
