### ISSUE TITLE
net::ERR_CONNECTION_RESET 

### ISSUE THREAD

**Issue by d270624** [django/channels#1264]
Uploading files for more than 60 seconds always prompts net:: ERR_CONNECTION_RESET
Turn off channels is works
This is bug?

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="/static/jquery-1.10.2.js"></script>
</head>
<body>
<input id="up" type="file" name="myfile">
<button id="upbutton">click</button>
</body>

<script>
    $(function () {
        var ufile = $('#upbutton');
        ufile.click(function () {
            var formData = new FormData();
            formData.append("myfile", document.getElementById("up").files[0]);
            $.ajax({
                url: "/up/",
                type: "POST",
                data: formData,
                contentType: false,
                processData: false,
                success: function (data) {
                    console.log('123')
                },
                error: function () {
                    console.log('456')
                }
            });
        });
    });
</script>

</html>
```

**Comment by carltongibson** [comment]
This isn't an addressable bug report... **guessing**: there's a timeout somewhere. Is it your webserver, is it Daphne, is it...? Find that. Can you adjust it? If not (if it's Daphne/Channels) come back with a specific issue. 

If you need support please see https://channels.readthedocs.io/en/latest/support.html

**Comment by d270624** [comment]
The server has checked no problems, check the django manual, did not find a place to set the timeout, this problem has been bothering me for a long time，I tried to test with the easiest way, the problem is still

Git address：
https://github.com/d270624/channel
