### ISSUE TITLE
ASGI 3.0 Upgrade

### ISSUE THREAD

**Issue by auvipy** [django/channels#1266]
https://github.com/django/daphne/pull/255

**Comment by daleobrien** [comment]
Looks like  https://github.com/django/channels/pull/1278 has this covered

**Comment by rajasimon** [comment]
I can't able to run my project because of the incompatibility. Waiting for the `channels` update now.

**Comment by carltongibson** [comment]
@rajasimon `pip install daphne==2.2.*` should get you running. Updated channels release coming this weekend.
