### ISSUE TITLE
await  function  doesn't run in sequence

### ISSUE THREAD

**Issue by Lionelvsv** [django/channels#1267]
i was trying to the write the message to database after group send function in channels. But rather than completing the group send function it executes the group send function and pauses the function in between and  executes the database write function and then executes the group send which adds delay in group send function. is there is any way to run the group send function to complete first

```
# group  send function
await self.channel_layer.group_send(
        self.room_group_name,
        {
            'type': 'chat_message',
            'message': final_message_data
        }
    )
# database  write  funtion
await self.create_chat_message(user, message_data['msg'])
```

**Comment by hishnash** [comment]
so the `group_send` function will be complete before `create_chat_message` however just calling that function does not mean the `group` will consume the events before your `create_chat_message` method. 


basically, group_send will tell the backend you are using to send the msg to all consumers registered to this group. but it can't wait until all these consumers get this message (they might be on other machines listening to the Redis que)

if you want to ensure that enough time has passed what you could do is on you consumer (that is sending this group message) subscribe to the group `room_group_name` and when the consumer gets the message (it just sent) then `create_chat_message`. 

I would suggest the best way to do this is in the message include the `self. channel_name` then you cant test for this in your `chat_message` method.

**Comment by carltongibson** [comment]
Yep. That sounds about right. 

(This isn’t really an Issue, more a usage question...)
