### ISSUE TITLE
Django deprecation warnings not shown when using channels server

### ISSUE THREAD

**Issue by OskarPersson** [django/channels#1268]
When using the channels development server none of the expected Django deprecation warnings appear. 

I've tested it by creating a new Django 1.11 project and followed the [channels installation instructions](https://channels.readthedocs.io/en/latest/installation.html). When the project was setup I simply renamed the `MIDDLEWARE` setting to the deprecated `MIDDLEWARE_CLASSES` setting.

When running the server with warnings enabled I get no warnings:

```
python -Wd manage.py runserver 0:8000
Performing system checks...

System check identified no issues (0 silenced).
March 25, 2019 - 21:54:56
Django version 1.11.20, using settings 'chnl.settings'
Starting ASGI/Channels version 2.1.7 development server at http://0:8000/
Quit the server with CONTROL-C.

```

Removing `channels` from `INSTALLED_APPS` and running the built-in development server displays the expected warning:

```
$ python -Wd manage.py runserver 0:8000
Performing system checks...

System check identified no issues (0 silenced).
March 25, 2019 - 22:02:40
Django version 1.11.20, using settings 'chnl.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.
/Users/oskar/.pyenv/versions/channels/lib/python3.6/site-packages/django/core/handlers/base.py:52: RemovedInDjango20Warning: Old-style middleware using settings.MIDDLEWARE_CLASSES is deprecated. Update your middleware and use settings.MIDDLEWARE instead.
  "instead.", RemovedInDjango20Warning

```

---

And here are my installed packages (running Python 3.6.7 on macOS 10.14.3)

```
$ pip freeze
asgiref==2.3.2
async-timeout==3.0.1
attrs==19.1.0
autobahn==19.3.3
Automat==0.7.0
channels==2.1.7
constantly==15.1.0
daphne==2.2.5
Django==1.11.20
hyperlink==18.0.0
idna==2.8
incremental==17.5.0
PyHamcrest==1.9.0
pytz==2018.9
six==1.12.0
Twisted==18.9.0
txaio==18.8.1
zope.interface==4.6.0
```

**Comment by carltongibson** [comment]
Hmmm. I guess we **could** add a warning in `AsgiHandler.load_middleware()`. Would you be up for doing that? (Half-wondering if it's worth it at this point in time...?)

**Comment by carltongibson** [comment]
Closing as stale since we're dropping `AsgiHandler` in favour of Django's own for Channels v4.
