### ISSUE TITLE
the service run for a while ，but don't push the message sudden,  you have to restart the service. Why is that?

### ISSUE THREAD

**Issue by xiaoqiao99** [django/channels#1271]

**Comment by hishnash** [comment]
@xiaoqiao99 could you provide some more details about your setup, 

what channel layer are you using, what version of channels, Django etc?

**Comment by xiaoqiao99** [comment]
channels==2.1.7
channels-redis==2.3.3
beatserver==0.0.6

**Comment by hishnash** [comment]
can you describe your issue a little more as well :)

as I understand you are running the server and after a while (how long?) it stops responding and you need to restart it?

can you still send messages to the server? 

what messages stop sending?

**Comment by xiaoqiao99** [comment]
redis_version:4.0.10    
The service did not report an error . About six or ten hours later, 
the page will not receive messages  and server did not receive heartbeat.，the connecttion  is  good.
the page use https://github.com/zimv/websocket-heartbeat-js

**Comment by qeternity** [comment]
@xiaoqiao99 are you running behind nginx?

**Comment by xiaoqiao99** [comment]
yes. nginx  +  supervisor

**Comment by qeternity** [comment]
Please see this comment https://github.com/django/channels/issues/1244#issuecomment-478258245

**Comment by carltongibson** [comment]
Closing as a likely Duplicate of #1244.
