### ISSUE TITLE
Conflicting dependencies for asgiref

### ISSUE THREAD

**Issue by dblenkus** [django/channels#1277]
Latest `channels` release (2.1.7) has [following requirements](https://github.com/django/channels/blob/ae9f7a8b1976dcfafeb2c88fd40800ab28b87eaf/setup.py#L17-L18):
```
        'asgiref~=2.3',
        'daphne~=2.2',
```
So it installs latest `2.x` version of `daphne`, which is currently `2.3`.

The problem is that `daphne 2.3.0` [reqires `asgiref~=3.0`](https://github.com/django/daphne/blob/1759643f1ff2ef7b5958f190d4a681ab13cc7fd5/setup.py#L25), which is not compatible with requirements above. So **the current version of channels can no longer be installed** due to the conflict.

 The safest solution is to limit `daphne` to `~=2.2.0`. Is this also the right solution? Or should the `asgiref` requirement be bumped to support versions `2.x` and `3.x`?

**Comment by carltongibson** [comment]
Yep. We should bump. (Daphne will automatically wrap an older app.)

**Comment by carltongibson** [comment]
Anyone seeing this before the new release: 

```
pip install channels
pip install -U asgiref
```

The error message is misleading here. (It is compatible...)

**Comment by michael-k** [comment]
`channels_redis` needs a version bump of asgiref too.  I've opened a PR: django/channels_redis#153
