### ISSUE TITLE
Package Conflicts

### ISSUE THREAD

**Issue by mevaibhav** [django/channels#1280]
Channels 2.1.7 and Channels-redis 2.3.3 are looking for different asgiref also daphne is looking for different version of asgiref
```

channels 2.1.7 has requirement asgiref~=2.3, but you'll have asgiref 3.0.0 which is incompatible.
channels-redis 2.3.3 has requirement asgiref~=2.1, but you'll have asgiref 3.0.0 which is incompatible.


```
After correcting above, daphne goes bad

`daphne 2.3.0 has requirement asgiref~=3.0, but you'll have asgiref 2.3.2 which is incompatible.
`

**Comment by fdev** [comment]
This PR seems to be the cause: https://github.com/django/daphne/pull/255

**Comment by malohacker** [comment]
please update it in the PIP

**Comment by chtseac** [comment]
Same issue here. I'm using pipenv and the graph looks like this:

```
channels [required: ~=2.0, installed: 2.1.6]
  - asgiref [required: ~=2.3, installed: 2.3.2]
    - async-timeout [required: >=2.0,<4.0, installed: 3.0.1]
  - daphne [required: ~=2.2, installed: 2.3.0]
    - asgiref [required: ~=3.0, installed: 2.3.2]
```

There's no version that's both `~=3.0` and `~=2.3`.

I don't know which party needs to change the dependency.

**Comment by auvipy** [comment]
I hope 2.2 release fixed it?

**Comment by chtseac** [comment]
2.2 fixed it for me. Just had to make sure everything was up to date.

**Comment by NeoHimu** [comment]
"pip install asgiref~=2.3" fixed the problem for me
