### ISSUE TITLE
Ensure that a send call is sent immediately.

### ISSUE THREAD

**Issue by dajkatal** [django/channels#1284]
I have researched an found out that the Immediately=True parameter could be used to do this, but it seems it is only for Channels 1.0. When i recieve a message, my backend sends back three different messages at different times. However, they all arrive at once.

How can i fix this and ensure they arrive the same time I send them?

**Comment by ranjan435** [comment]
what is the answer?

**Comment by lroolle** [comment]
Same question anyone solved? @dajkatal @ranjan435

**Comment by CarneyC** [comment]
Also encountered the same issue, any solution?
