### ISSUE TITLE
Move daphne to extras_require

### ISSUE THREAD

**Issue by blueyed** [django/channels#1285]
Daphne is not really required, e.g. when only using the `AsgiHandler`.

It is currently used for the runserver command, and otherwise imported in channels/apps.py and channels/testing/live.py only.

For a more lightweight installation it would be nice if this dependency could be made optional.

**Comment by carltongibson** [comment]
This has come up before. Andrew’s objection was to keep the basic pip install channels plus runserver working without making user handle more complex installations. I think we should maintain that at the moment. 

(Ref your issue on ASGI ref: happy to see input here updating the middlewares etc.)

**Comment by blueyed** [comment]
Just for reference:

There is also a hard dependency during `django.setup()`:
```
/app/src/project/dj/asgi.py:9: in <module>
    django.setup()
/usr/local/lib/python3.7/site-packages/django/__init__.py:24: in setup
    apps.populate(settings.INSTALLED_APPS)
/usr/local/lib/python3.7/site-packages/django/apps/registry.py:91: in populate
    app_config = AppConfig.create(entry)
/usr/local/lib/python3.7/site-packages/django/apps/config.py:116: in create
    mod = import_module(mod_path)
/usr/local/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    from django.apps import AppConfig

    # We import this here to ensure the reactor is installed very early on
    # in case other packages accidentally import twisted.internet.reactor
    # (e.g. raven does this).
>   import daphne.server
E   ModuleNotFoundError: No module named 'daphne'
```

**Comment by carltongibson** [comment]
I'm going to say no to this for now. Andrew's original goal was to make the first run experience for beginners as easy as possible. (More advanced folks know more advanced tricks.) 

Will review again for Django 3.0, for which presumably Channels will drop in scope.
