### ISSUE TITLE
When I establish a socket connection.Protocol error, got "H" as reply type byte.

### ISSUE THREAD

**Issue by appleUserName** [django/channels#1298]
asgi-redis 1.4.3
asgiref 3.1.2
channels 2.2.0
channels-redis 2.4.0
redis 2.10.6
django 2.1.5
I use these packages in django project.
When I resume websocket communication，I get a error:Protocol error, got "H" as reply type byte.
Please tell me why and how to fix it, thanks!!!

<img width="615" alt="57348785-fff1b680-7189-11e9-9354-b4b85e4912f3" src="https://user-images.githubusercontent.com/14973392/57498392-48d27800-730e-11e9-8745-ee169f1fe3b6.png">
<img width="522" alt="57348793-0c760f00-718a-11e9-9994-eaf4f958d617" src="https://user-images.githubusercontent.com/14973392/57498396-4b34d200-730e-11e9-8f46-90559978b525.png">

**Comment by carltongibson** [comment]
Grrr. There's not enough to even begin to know where to help with this. Can you provide a minimal project to reproduce the issue? Short of that I'm not sure what to say. Sorry.
