### ISSUE TITLE
typo in the doc for channels version

### ISSUE THREAD

**Issue by LukeVideo** [django/channels#1304]
Going through the channels tutorial i couldn't get the desired channels version with this command

`
$ python3 -c 'import channels; print(channels.__version__)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'channels' has no attribute 'version'
`
but 
`
python3 -c 'import channels; print(channels.sys.version)'
3.6.6 (default, Jul 19 2018, 16:29:00) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
`
Nothing major, but still worth an update i guess.

**Comment by carltongibson** [comment]
Hi @LukeVideo.

I'm not sure what to say about this one. I see quite different results: 

```
$ python3 -c 'import channels; print(channels.__version__)' 
2.2.0
$ python3 -c 'import channels; print(channels.version)' 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'channels' has no attribute 'version'
$ python3 -c 'import channels; print(channels.sys.version)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'channels' has no attribute 'sys'
```

`print(channels.sys.version)` is printing your Python version. (But as you see from the traceback I get, `channels` doesn't import `sys`. 

If you `pip freeze` what channels version do you have installed?
