### ISSUE TITLE
Why is the cookie in scope empty and user is anonymous?

### ISSUE THREAD

**Issue by zdYng** [django/channels#1305]
![image](https://user-images.githubusercontent.com/17880611/58849400-c8105d00-86bc-11e9-9542-29f40ff5f3d3.png)

As shown，thanks

**Comment by zdYng** [comment]
ok, I know my fault 
Thanks :)

**Comment by ajaytechvins** [comment]
> ok, I know my fault
> Thanks :)

can you please help me with this issue?
