### ISSUE TITLE
not issue, question

### ISSUE THREAD

**Issue by sabuhish** [django/channels#1311]
Hello I am build web-app with MQTT mosquito broker, in order to make connections between devices and web applications. devices will publish data to broker we will listen to each topic and recive datas. We should use websocket for that in order to push web real-time data to front. Do you think we can use django-channels for that? is there samples, anyone has used MQTT protocol over django-cahnnels?

**Comment by carltongibson** [comment]
Please see Support documentation: https://channels.readthedocs.io/en/latest/support.html

**Comment by sabuhish** [comment]
I have read it I am already aware of it. I was wondering if someone has done such application or can django-channels handle MQTT message payload, like transfer to websockets. Whole point to know work cycle both two protocols and channels implementation on it.
