### ISSUE TITLE
Documentation of in-memory channel layer

### ISSUE THREAD

**Issue by oTree-org** [django/channels#1314]
The docs say: 

> Channels does not ship with any channel layers you can use out of the box

https://channels.readthedocs.io/en/latest/topics/channel_layers.html

What about `channels.layers.InMemoryChannelLayer`?

**Comment by carltongibson** [comment]
This is intended just for testing and is deliberately undocumented.

**Comment by keithhackbarth** [comment]
@carltongibson - I think that the decision to hide the In-Memory layer should be revisited.

LIke most beginners to Django Channels, I started my way to Django Channels via using `runserver` on my local dev box. For this purpose (single-process, non-production), the in-memory layer was an ideal first-step. It lowered the barrier to entry and got me into and discovering Django Channels quickly. And freed me from having to learn Redis at the same time I was already learning about Channels + Async + Websockets.

With Django Cache for example, the In-Memory Layer is documented — with a thorough explanation about why it shouldn't be used in production environments. In my opinion, Django Channels should follow the same paradigm. It is much better to educate than to hide a feature. Users are bound to find it regardless.

This is clearly is this is an ongoing source of confusion. I've found multiple tickets and threads about it: #1039, #1040, #1314

I'd be happy to do a Pull Request with a tweak to the docs explaining which it exists and the advantages/disadvantages to using it if you'd allow it.

**Comment by oTree-org** [comment]
By the way, InMemoryChannelLayer is mentioned in the docs here: https://channels.readthedocs.io/en/latest/topics/consumers.html?highlight=inmemorychannellayer#websocketconsumer

**Comment by keithhackbarth** [comment]
Good point @oTree-org. There is still lots of documentation around referencing it. So why not explain to users what is it and when to avoid using it?

**Comment by keithhackbarth** [comment]
Also, it is definitely relevant for lightweight testing purposes: https://channels.readthedocs.io/en/latest/topics/testing.html

**Comment by carltongibson** [comment]
> I'd be happy to do a Pull Request with a tweak to the docs explaining which it exists and the advantages/disadvantages to using it if you'd allow it.

OK, happy to look at a PR @keithhackbarth. Thanks. 

It needs to be restricted to the testing section really, and clearly say "Don't use this except for testing".  The point being that otherwise folks will try to deploy it and will be in trouble. 

(No promises 🙂)

**Comment by jonathan-s** [comment]
May I suggest that we keep this ticket open since there is a PR that covers this.
