### ISSUE TITLE
Daphne takes the channel layer as an argument?

### ISSUE THREAD

**Issue by oTree-org** [django/channels#1315]
The deploy docs say:

> Then, you can run Daphne and supply the channel layer as the argument:
> 
> daphne myproject.asgi:application

https://channels.readthedocs.io/en/latest/deploying.html#http-and-websocket

Isn't that argument the application, not the channel layer? They are the same thing?

**Comment by carltongibson** [comment]
Yeah, that should probably say ASGI application.
