### ISSUE TITLE
Bundled middleware doesn't support ASGI 3 apps

### ISSUE THREAD

**Issue by rakyi** [django/channels#1316]
On ASGI 2 I was able to combine middleware provided by starlette and channels and their base apps (such as consumers and e.g. starlette's `GraphQLApp`). This no longer works since starlette moved to ASGI 3. I'd expect this to continue to work, since channels now also depends on ASGI 3. Minimal example of failing ASGI 3 app:

```python
from channels.sessions import CookieMiddleware
from starlette.responses import PlainTextResponse

async def hello(scope, receive, send):
    assert scope['type'] == 'http'
    response = PlainTextResponse('Hello, world!')
    await response(scope, receive, send)

app = CookieMiddleware(hello)

```

**Comment by carltongibson** [comment]
Hi @rakyi. OK, yep. Fancy helping to update the middleware?

**Comment by rakyi** [comment]
Thanks for the ack! I can take a stab at it, but most likely not very soon. Free to take for anyone else, but please let me know here, so we don't duplicate the work.

**Comment by jaydenwindle** [comment]
@rakyi I'd love to take a stab at this. Does this change need to maintain backwards compatibility with ASGI 2?

**Comment by carltongibson** [comment]
Hi @jaydenwindle. Super, welcome aboard! 

> Does this change need to maintain backwards compatibility with ASGI 2?

No, not initially. asgiref has utils to allow converting between the single and double callable models. So... let's aim for the future: Make everything v3, then we can look at if and where we need to wrap applications. Make sense?

**Comment by jaydenwindle** [comment]
@carltongibson thanks! Sounds like a plan :)

**Comment by carltongibson** [comment]
Fixed in Channels v3.
