### ISSUE TITLE
Raising ResponseLater() produces error in Django 1.10+

### ISSUE THREAD

**Issue by kenjones21** [django/channels#1317]
## Description

When raising a `AsgiRequest.ResponseLater` exception with channels 1.1.8, django projects using django 1.10+ produce the following error.
```
Traceback (most recent call last):
  File "/Users/kennethweaver/.virtualenvs/djangodev/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/kennethweaver/.virtualenvs/djangodev/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/kennethweaver/.virtualenvs/djangodev/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/kennethweaver/.virtualenvs/djangodev/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kennethweaver/Documents/test-project/testchannels/testapp/views.py", line 7, in subscribe
    raise AsgiRequest.ResponseLater()
channels.exceptions.ResponseLater
```
Pip freeze is below:
```
asgiref==1.1.2
asn1crypto==0.24.0
attrs==19.1.0
autobahn==19.6.2
Automat==0.7.0
cffi==1.12.3
channels==1.1.8
constantly==15.1.0
cryptography==2.7
daphne==1.4.2
Django==1.10
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
pycparser==2.19
PyHamcrest==1.9.0
six==1.12.0
Twisted==19.2.1
txaio==18.8.1
zope.interface==4.6.0
```

Running on MacOS 10.14.5, python 3.6.4. 

## To reproduce

1. Clone [this repository](https://github.com/kenjones21/channels_118_issue).
2. Install channels and django (pip3 install django==1.10.0 channels==1.1.8)
3. Run the server (`python manage.py runserver`)
4. Make a call to `localhost:8000/test`
5. Observe error in console

**Comment by carltongibson** [comment]
Grrr. Neither Django 1.10 nor Channels 1.x are supported I'm afraid... You'll need to ask elsewhere, maybe StackOverflow. 

**BUT** it looks like your report says, "Raising an exception raises an exception". 

```
    raise AsgiRequest.ResponseLater()
channels.exceptions.ResponseLater
```

Unless you're expecting channels.exceptions.ResponseLater to be caught in an `except` block this is expected behaviour, so, why are you expecting that, and why isn't it happening? 

(Sorry, can't say more here.)

**Comment by kenjones21** [comment]
Thanks for the response! This happens with django 1.11 as well as 1.10 (hence the 1.10+); I have not yet attempted with any of the 2.x versions of django. I could not find anything that concretely said channels 1.x was no longer supported, but I suspected it, so thank you for confirming. 

Although this is not documented concretely AFAIK (only in CHANGELOG.txt) I believe raising `ResponseLater` is how one implements Long Polling with django channels. Given that 1.1.8 is no longer supported, we will plan on upgrading channels in the near future rather than trying to figure this out, however.

**Comment by carltongibson** [comment]
For long polling see https://channels.readthedocs.io/en/latest/topics/consumers.html
