### ISSUE TITLE
websocket reject and disconnect connection with vue.js

### ISSUE THREAD

**Issue by sabuhish** [django/channels#1321]
Hi there!

our team having issue on connection to websocket via Vue.js app.
configuration of channels applied as mentioned on docs. I am using asigiref async_to_sync function to send data to channel_layer.
everything works fine on default browser. When Vue app tries to connect where attemption  get rejected. it Actually disconnects from websocket, what could be the problem, have faced this problem before?
Below attaching the codes and pictures:

consumer.py:
https://pastebin.com/dxrCy4YX

vue.js:
https://pastebin.com/SKA4Y3hm

error:
![Screenshot from 2019-07-17 19-15-32](https://user-images.githubusercontent.com/46589585/61451044-8801f280-a969-11e9-945c-514d32402ce1.png)

**Comment by carltongibson** [comment]
This looks like a usage question. It's not clear where or if there's meant to be an issue with Channels here.

**Comment by sajjatflutterdeveloper** [comment]
I have the same issue 
 django = "==3.0.8"
channels = "==3.0.5"
