### ISSUE TITLE
How to refresh a session in consumers?

### ISSUE THREAD

**Issue by DiDHack** [django/channels#1324]
I log in by HTTP then create a websocket-connection. The consumer gets the user's session. Fine.
After, I log out by HTTP (the standard django's logout) but the socket continues working (sees the old user and lets working with the connection) because it has the old session's data. I tried to use get_user(self.scope) but it returnes a user from old session. Only a socket's reconnection helps.

**Comment by DiDHack** [comment]
I found a poor workaround: use this code in every method:
        if not self.scope['session'].exists(self.scope['session'].session_key):
            self.scope['session'].flush()
            await self.close()

is there a better method?

**Comment by carltongibson** [comment]
>  I log out by HTTP (the standard django's logout) but the socket continues working

This isn't something we've got built in but, you could receive the [`user_logged_out` signal](https://docs.djangoproject.com/en/2.2/ref/contrib/auth/#django.contrib.auth.signals.user_logged_out) and use that to flush the session. 

(I'd double check references. `session.flush()` is called from `logout()` — so you want to make sure you're clear on when you need to refresh...)

**Comment by DiDHack** [comment]
session.flush() is called - yes. This session is removed from DB and from the Django variable. But as I understood, a channel has its own copy of the session data which got from DB. And it doesn't check actual data until a user try to disconnect from the socket and connect again.

Oh, I forgot about that there is user_logged_out. Thank you!

**Comment by carltongibson** [comment]
>  a channel has its own copy of the session data which got from DB.

Then, yes, using the signal to refresh is going to be necessary.

**Comment by tim-schilling** [comment]
@carltongibson This issue appears to be still a problem for the case of a session expiring behind the scenes. Existing websocket connections are still allowed, only on a reconnect does it finally break.

**Comment by tim-schilling** [comment]
Ah, never mind. I missed this part of the documentation:

> If you are using a long running consumer, websocket or long-polling HTTP it is possible that the user will be logged out of their session elsewhere while your consumer is running. You can periodically use get_user(scope) to be sure that the user is still logged in.

**Comment by DiDHack** [comment]
In first message, I wrote:
> I tried to use get_user(self.scope) but it returns a user from old session

**Comment by Coronon** [comment]
Hi guys, I just had the exact same problem and came up with what I consider quite the clever solution, using Channels itself :)

When a client connects over WS it is added to a special channels group named after its `sessionkey`, when you log out over http that group will recieve a `websocket_disconnect` event, so all consumers that used that sessionid will be disconnected. This avoids logging the user out on multiple devices with different sessions. It should also scale quite well as channels can be accessed in a multi server environment :)

Decorator for the connect function (sync):
```py
import functools
from asgiref.sync import async_to_sync

def ws_login_required_connect(func):
    """
    Decorator for ws-channels that checks that the user is logged in,
    closing the connection if necessary (Only works on 'connect').
    """
    @functools.wraps(func)
    def wrapper_ws_login_required_connect(self, *args, **kwargs):
        if self.scope["user"].is_authenticated:
            async_to_sync(self.channel_layer.group_add)(f"SESSION-{self.scope['session'].session_key}", self.channel_name)
            return func(self, *args, **kwargs)
        else:
            self.close()
    return wrapper_ws_login_required_connect
```

My custom logout view (HTTP):
```py
from django.contrib.auth import logout
from django.http import HttpResponse

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
# Create your views here.

def logout_view(request):
    channel_layer = get_channel_layer()
    print(request.session.session_key)
    async_to_sync(channel_layer.group_send)(f"SESSION-{request.session.session_key}", {"type": "websocket_disconnect", "code": -1})
    logout(request)
    return HttpResponse("*OK*")
```

If you find any flaws with this, please let me know. The only thing that comes to my mind is normal session expiry, but that should be handable :)

**Comment by Incred** [comment]
@Coronon  Looks really helpful. Thank you!

**Comment by Skogis02** [comment]
> I found a poor workaround: use this code in every method: if not self.scope['session'].exists(self.scope['session'].session_key): self.scope['session'].flush() await self.close()
> 
> is there a better method?

Reading this many years later, as for some reason, the problem persists. As I am a beginner, might I ask what makes the solution "poor"? In my project I put your lines in a decorator and it looks quite neat. Any security or performance issues?

**Comment by Coronon** [comment]
@Skogis02 You are indeed right that this approach may work, but there are a few important considerations with that code and your described usage:
- You may never forget that decorator on any _method_, while my approach is consumer based
- Also consider cases where the server sends data to the connected client e.g. in a chat room, you would also have to always check there (the client does not directly ‘request content’)
- When running longer tasks after a request and responding in the same method the connection will not be closed and data may be sent to an ‘unauthenticated’ client
- Depending on your session backend the state may not be shared between multiple instances (multiprocess), leading to unauthorised access
- You always do the work to check the session with your code, while using signals allows you to simply be notified (way less work - also depends a lot on the session backend you use)

**Comment by Skogis02** [comment]
@Coronon I agree with your reasoning. Question: what happens if the user logs out via the REST api at the same moment that the consumer is being established? Could the consumer possibly "miss" the user_logged_out signal as it (the consumer) is still being instantiated?

I am thankful for your feedback!
