### ISSUE TITLE
JSON improperly delivered in production over nginx

### ISSUE THREAD

**Issue by addsimm** [django/channels#1325]
Using a local server the following code works fine in that the client side JS can capture all parts of the event:

 `

    class ChatConsumer(AsyncJsonWebsocketConsumer):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.groups is None:
            self.groups = []
        self.room_name = self.scope['url_route']['kwargs']['room_name']
        self.room_group_name = 'chat_%s' % self.room_name

    async def connect(self):
        # Join room group
        await self.channel_layer.group_add(
            self.room_group_name,
            self.channel_name
        )

        await self.accept()

    async def disconnect(self, close_code):
        # Leave room group
        await self.channel_layer.group_discard(
            self.room_group_name,
            self.channel_name
        )

    # Receive message from WebSocket
    async def receive_json(self, content, **kwargs):
        message = content['message']
        typ = content['type']

        if typ == 'chat_message':
            # Send message to room group
            await self.channel_layer.group_send(self.room_group_name, {
                'type': 'chat_message',
                'username': self.scope['user'].get_full_name(),
                'message': message
            })

        if typ == 'heartbeat':
            # Send message to room group
            await self.channel_layer.group_send(self.room_group_name, {
                'type': 'heartbeat',
                'username': self.scope['user'].get_full_name(),
                'message': message
            })

    # Receive message from room group
    async def chat_message(self, event):
        # Send message to WebSocket
        await self.send_json(event)

    async def heartbeat(self, event):
        # Send message to WebSocket
        await self.send_json(event)`
    
However in production (the same code but under daphne, gunicorn, nginx) only part of the object is delivered

here are some excerpts from the console.log:

local development:

`data received: {"type":"chat_message","username":"Adam Simon","message":"- Adam S. has arrived -"}

?user_id=2:580 type: chat_message

?user_id=2:576 data received: {"type":"heartbeat","username":"Adam Simon","message":"Adam S.here for seconds: 2"}

?user_id=2:580 type: heartbeat

production:

`data received: {"message":"- Adam S. has arrived -"}

?user_id=2:580 type: undefined

?user_id=2:576 data received: {"message":"Adam S.here for seconds: 2"}

?user_id=2:580 type: undefined

?user_id=2:576 data received: {"message":"Adam S.here for seconds: 4"}

?user_id=2:580 type: undefined`

for some reason the object is not all there, I am guessing the issue is with channels or unix, so here is my current nginx file:

`server {
    server_name 159.65.105.226 joinourstory.com www.joinourstory.com;

    location = /favicon.ico { access_log off; log_not_found off; }

    # ADAM add
    location /ws/chat/ {
        proxy_pass http://127.0.0.1:8001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /static/ {
        root /home/adam/LOCdojos;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/adam/LOCdojos/dojos.sock;
    }
 
    .
    .
    .

}

server {

    if ($host = www.joinourstory.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    .
    .
    .

}

Happy to provide any other info -

~ `

**Comment by carltongibson** [comment]
Hi. Sorry to say but this isn’t as yet an addressable issue. It looks like an nginx config issue, but hard to say. 

I’d suggest you try StackOverflow. 

If you can identify a concrete issue with channels then happy to look.
