### ISSUE TITLE
The threading issues of django/channels

### ISSUE THREAD

**Issue by Jmxmanman** [django/channels#1328]
- Your OS and runtime environment, and browser if applicable
  - windows 10
- A `pip freeze` output showing your package versions
  - Django 1.11.4
  - channels 2.2.0
  - python 3.5.4
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
  - runserver
- Console logs and full tracebacks of any errors
Here are some of my problems：
I have a client and a server,when the client connects,the server adds two threads,But when the client disconnects, the thread the server just started doesn't disappear, actually i  want to kill the thread when the client exits.Please look at the picture below
![thread_total](https://user-images.githubusercontent.com/42801311/62446774-3396a980-b796-11e9-93ee-9a0c96081a34.png)
Here is a screenshot of some of my code
![code_detail](https://user-images.githubusercontent.com/42801311/62446806-4e691e00-b796-11e9-8c1c-23b5e9b695b2.png)

**Comment by Jmxmanman** [comment]
Excuse me, Does anyone know how to solve this problem?

**Comment by carltongibson** [comment]
Any chance you could narrow it down to a reproducible example, preferably with an example project. (Not clear yet what’s happening.)

**Comment by Jmxmanman** [comment]
> Any chance you could narrow it down to a reproducible example, preferably with an example project. (Not clear yet what’s happening.)

My server just accepts connections from clients and receive some data , I didn't do anything else,I found that every time my client connected to the server, django/channels will start two threads.
But when the client disconnect,These two threads were not killed, When I start two clients connections, django/channels will start four threads,When the two clients disconnect, None of the four threads were killed.When I start three clients connections...and so on...

#### Here is the code in `consumer.py`
```
import json
from asgiref.sync import async_to_sync
from channels.generic.websocket import AsyncJsonWebsocketConsumer
from threading import Event, Thread, current_thread, enumerate

class MeetingsConsumer(AsyncJsonWebsocketConsumer):
    def __init__(self, *args, **kwargs):
        super(MeetingsConsumer, self).__init__(*args, **kwargs)
        self.meeting_group_name = None
async def connect(self):
    cur_thread_alive = enumerate()
    print("connection established, The total number of threads:", len(cur_thread_alive), '\n', cur_thread_alive)
    self.id = self.scope['url_route']['kwargs']['id']
    self.role_id = self.scope['url_route']['kwargs']['role_id']
    self.meeting_group_name = 'meeting_' + self.id + '_' + self.role_id 
    await self.channel_layer.group_add(
        self.meeting_group_name,
        self.channel_name,
    )
    await self.accept()

async def disconnect(self, close_code):
    await self.channel_layer.group_discard(
        self.meeting_group_name,
        self.channel_name
    )
    await self.close()

async def receive(self, text_data=None, bytes_data=None):
    if text_data:
        text_data_json = json.loads(text_data)
        print(text_data_json)

    if bytes_data:
        print(bytes_data[:5])
```

**Comment by haloxzt** [comment]
I have the same problem,the more client connect to server the more thread will be launched(by django-channel),and those thread will not be killed,even the connection were broken...

**Comment by carltongibson** [comment]
Could either of you prepare a minimal project which reproduces this clearly? That allows easier investigation, making sure we're all looking at the same code. (Thanks!)

**Comment by Jmxmanman** [comment]
> Could either of you prepare a minimal project which reproduces this clearly? That allows easier investigation, making sure we're all looking at the same code. (Thanks!)

The code for this project  from "[channels tutorial](https://channels.readthedocs.io/en/latest/tutorial/index.html)" , I made it into a compression package
[mysite.zip](https://github.com/django/channels/files/3481219/mysite.zip)

**Comment by carltongibson** [comment]
Thanks @Jmxmanman. I shall have a play.

**Comment by Jmxmanman** [comment]
> Thanks @Jmxmanman. I shall have a play.

i am looking forward

**Comment by BruceMaggs** [comment]
Was this issue ever resolved?

**Comment by carltongibson** [comment]
Closing as stale. If someone can reproduce on latest versions, and provide that as a minimal example, happy to have a look,  but there's not enough to go on here.
