### ISSUE TITLE
Introduction documentation missing cross-process example

### ISSUE THREAD

**Issue by tim-schilling** [django/channels#1329]
The introduction's [Cross-Process Communication](https://github.com/django/channels/blob/master/docs/introduction.rst#cross-process-communication) documentation needs to replace the following with the cross-process example:

> (insert cross-process example here)

**Comment by carltongibson** [comment]
Hi @tim-schilling. Grrr. I thought I'd replied to this. Mustn't have hit send. Sorry! 

Yes! 

Fancy adding one? 🙂

**Comment by tim-schilling** [comment]
Unfortunately, I was hoping to have the example to understand that section.

**Comment by carltongibson** [comment]
OK, fine, no problem. 😀

**Comment by microHoffman** [comment]
@carltongibson Hey, any updates on this? I've also spotted the missing cross-process example today while trying to understand how to do this stuff.

**Comment by microHoffman** [comment]
Oh there is actually this #1346 PR.

**Comment by carltongibson** [comment]
Thanks @microHoffman
