### ISSUE TITLE
Get list of users connected to a group

### ISSUE THREAD

**Issue by mike-johnson-jr** [django/channels#1333]
So, I got as far as finding the `group_channels` function, but this doesn't seem to store user info. Example:

    channel_layer = get_channel_layer()
    context['players_list'] = channel_layer.group_channels('lobby')

I get `{'players_list': ['daphne.response.WbZyUfNixL!sbzfJEzdPp', 'daphne.response.KfDHQnHLdw!DpoOqdGute', 'daphne.response.JqlcVVMuny!xHLDSaCzUz', 'daphne.response.mWrYVXDKoI!AjkyadSsPe']}` as a response.

How can I list users connected to Group('lobby')? Thanks in advance

I'm using channels 1.x

**Comment by carltongibson** [comment]
Bottom line is I'm not sure. You have to map back from the data you've got, or maybe keep a list in a cache somewhere... 

> I'm using channels 1.x

Please see our support documentation (http://channels.readthedocs.io/en/latest/support.html)
for more information about where you can get general help.
