### ISSUE TITLE
My model @property function is not fetch in @database_sync_to_async queryset filter

### ISSUE THREAD

**Issue by zserdcxftydfsc** [django/channels#1336]
**pip freeze**
aioredis==1.0.0
asgiref==3.2.1
asn1crypto==0.24.0
async-timeout==3.0.1
attrs==19.1.0
autobahn==19.8.1
Automat==0.7.0
backcall==0.1.0
beautifulsoup4==4.7.1
cached-property==1.5.1
certifi==2019.6.16
cffi==1.12.3
channels==2.2.0
channels-redis==2.4.0
chardet==3.0.4
constantly==15.1.0
cryptography==2.7
daphne==2.3.0
decorator==4.4.0
Django==2.2
hiredis==1.0.0
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
ipdb==0.12
ipython==7.5.0
ipython-genutils==0.2.0
jedi==0.14.0
msgpack==0.6.1
mysqlclient==1.4.2.post1
parso==0.5.0
pexpect==4.7.0

**mymodel.py**
class Buy(models.Model):
     
    stop_price =  models.DecimalField(max_digits=16,decimal_places=8,verbose_name='Stop Price')
    price= models.DecimalField(max_digits=16,decimal_places=8,verbose_name='Price')
    amount= models.DecimalField(max_digits=16,decimal_places=8,verbose_name='Amount')
    total=models.DecimalField(max_digits=16,decimal_places=8,verbose_name='Total')
    
    def __int__self(self):
        return id
        
    @property
    def buyamount(self):
        amount = self.amount
        sum_remain_qs = TradeHistory.objects.filter(Q(buy_id__id=self.id) & Q(view_type = 1))
        sum_remain_amt = sum_remain_qs.aggregate(remain_amt =Sum('amount'))if sum_remain_qs else Decimal(0.00) 
        if sum_remain_amt:
            calculate_amt = (abs(amount - sum_remain_amt['remain_amt']))
        else:
            calculate_amt = amount
        #await asyncio.sleep(1)
        #time.sleep(1)
        return calculate_amt

**consumer.py**
@database_sync_to_async
    def get_buyorder_list(self):
       buyorder_qs = Buy.objects.filter(Q(status = 0) | Q(status = 4)).order_by('-price')     
       return buyorder_qs
**Note:**
get_buyorder_list return all fields but except buyamount (property field) not fetch.

**Comment by carltongibson** [comment]
The `buyamount` property won't be calculated until it's accessed. (I don't think this has anything to do with async vs sync no?)

Can you reduce the property down to an annotation? It looks a bit complicated but, if so you can add it to the QuerySet... See https://docs.djangoproject.com/en/2.2/ref/models/querysets#django.db.models.query.QuerySet.annotate

(I don't think this is a channels issue.)
