### ISSUE TITLE
Update Documentation For Tutorial To Use django.conf.urls

### ISSUE THREAD

**Issue by zimventures** [django/channels#1338]
Going through the tutorial, I hit an issue which resulted in no path being found while navigating to `/chat/lobby/`:

## Stacktrace
```
127.0.0.1:65111 - - [19/Aug/2019:19:34:41] "GET /chat/lobby/" 200 1415
2019-08-19 19:34:41,126 ERROR    [Failure instance: Traceback: <class 'ValueError'>: No route found for path 'ws/chat/lobby/'.
c:\program files\python37\lib\site-packages\autobahn\websocket\protocol.py:2844:processHandshake
c:\program files\python37\lib\site-packages\txaio\tx.py:429:as_future
c:\program files\python37\lib\site-packages\twisted\internet\defer.py:151:maybeDeferred
c:\program files\python37\lib\site-packages\daphne\ws_protocol.py:82:onConnect
--- <exception caught here> ---
c:\program files\python37\lib\site-packages\twisted\internet\defer.py:151:maybeDeferred
c:\program files\python37\lib\site-packages\daphne\server.py:200:create_application
c:\program files\python37\lib\site-packages\channels\routing.py:58:__call__
c:\program files\python37\lib\site-packages\channels\sessions.py:47:__call__
c:\program files\python37\lib\site-packages\channels\sessions.py:145:__call__
c:\program files\python37\lib\site-packages\channels\sessions.py:169:__init__
c:\program files\python37\lib\site-packages\channels\middleware.py:31:__call__
c:\program files\python37\lib\site-packages\channels\routing.py:154:__call__
]
127.0.0.1:65142 - - [19/Aug/2019:19:34:46] "WSDISCONNECT /ws/chat/lobby/" - -
2019-08-19 19:36:12,508 INFO     Killed 0 pending application instances
```
Turns out, I was hitting the issue that is documented here: https://channels.readthedocs.io/en/latest/topics/routing.html

```Please note that URLRouter nesting will not work properly with path() routes if inner routers are wrapped by additional middleware.```

Taking a quick peek at the tutorial, URLRouter is indeed wrapped in middleware...oh noes!!!
```
application = ProtocolTypeRouter({
    # (http->django views is added by default)
    'websocket': AuthMiddlewareStack(
        URLRouter(
            chat.routing.websocket_urlpatterns
        )
    ),
})
```

Thankfully, the fix is pretty easy! Within the `chat.routing.websocket_urlpatterns` list simply change the definition over to use url instead of path:

```
from django.conf.urls import url
from . import consumers

websocket_urlpatterns = [
    url(r'ws/chat/(?P<room_name>\w+)/$', consumers.ChatConsumer),
]
```
- Your OS and runtime environment, and browser if applicable
Windows 10 (running in a virtualenv for python 3.7) and Chrome

- A `pip freeze` output showing your package versions
```
asgiref==3.2.1
asn1crypto==0.24.0
attrs==19.1.0
autobahn==19.8.1
Automat==0.7.0
cffi==1.12.3
channels==2.2.0
constantly==15.1.0
cryptography==2.7
daphne==2.3.0
Django==2.2.4
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
pycparser==2.19
PyHamcrest==1.9.0
pytz==2019.2
six==1.12.0
sqlparse==0.3.0
Twisted==19.7.0
txaio==18.8.1
zope.interface==4.6.0
```
- What you expected to happen vs. what actually happened
Expected the websocket to connect, instead it timed out (client-side).

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
Tried both runserver & daphne: both produced the same error

- Console logs and full tracebacks of any errors
(see above)

**Comment by seregagavrilov** [comment]
You can just change url path to del '"$", it's seems typo in documentation

**Comment by matthiask** [comment]
Oh right, that was an "interesting" problem with no easy solution.

The commit adding the documentation note is here:
https://github.com/django/channels/commit/984e9dc9

The problem you're hitting was mentioned here (by me):
https://github.com/django/channels/pull/946#issuecomment-370163638

> I added additional tests. Unfortunately, path cannot be used for the outer URLRouter easily because the ASGI app is callable, and therefore Django thinks that it is a view and appends a $ to the regex.

`path()` seems to be the preferred thing in the Django world (with good reasons) but it may have been a bad idea to push for `path()` usage within `URLRouter` instances because of this edge case.

**Comment by carltongibson** [comment]
Yep, what's happened here is we've updated without thinking it through 100%. A change to `re_path` is the right way to go. (i.e. using the modern import locations and name but still a old-school `url()` under the hood.)

**Comment by carltongibson** [comment]
OK PR in #1354. Thanks @zimventures and @matthiask!
