### ISSUE TITLE
how to get django request instead of ASGI request in django

### ISSUE THREAD

**Issue by madu419** [django/channels#1347]
how to get django request instead of ASGI request in our normal function view request(like def index(request)) or if we install django channels every request become ASGI request? for more [reference](https://stackoverflow.com/questions/57801016/how-to-run-wsgi-along-the-side-of-the-daphne-asgi-for-django-channels)

**Comment by carltongibson** [comment]
`paco`'s [comment](https://stackoverflow.com/questions/57801016/how-to-run-wsgi-along-the-side-of-the-daphne-asgi-for-django-channels#comment102038592_57802600) is the correct answer. 

(SO is the place for this. Not here, which is for issues. Thanks.)

**Comment by madu419** [comment]
thank you
