### ISSUE TITLE
Development server: Low simultaneous connection limit

### ISSUE THREAD

**Issue by maxhowald** [django/channels#1360]
Background: I am using django channels to implement SSE in my app with [django_eventstream](https://github.com/fanout/django-eventstream).

When running the development server provided by django channels, there appears to be a fairly low limit (~6) to the number of simultaneous open HTTP connections. Since SSE holds an HTTP connection open while the page is open, this limits the number of pages of my app that I can open simultaneously.

Steps to reproduce: (tested on Debian 10 with python 3.7, django 2.2.5, django_eventstream 2.6.0)
1. Create a new django project and follow the steps for [setup with channels](https://github.com/fanout/django-eventstream) in the django_eventstream README
2. Run the development server
3. connect to the eventstream channel with multiple clients, e.g. by opening localhost:8000/events/ in 7+ browser tabs.

The seventh tab will not load until one of the first 6 is closed.

Is there any way to increase this limit? I frequently bump into it when developing locally, just by opening my app in multiple tabs and browsers at the same time.

**Comment by carltongibson** [comment]
Good question. I'd guess we're seeing `ThreadPoolExecutor`'s `max_workers` come into play.

https://docs.python.org/3.7/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor

What happens if you set `ASGI_THREADS` environment var to say 10?

See https://github.com/django/asgiref/blob/29a4652a3f7f8076568dee982062cad78bbd6855/asgiref/sync.py#L183-L188

**Comment by maxhowald** [comment]
Thanks for the tip!

But actually, on further inspection, this appears to be some kind of Chrome-specific maximum-connections-per-host limit and not something Django-related.

(In production, the SSE connections are proxyed through a CDN, so the issue doesn't happen there, which is why I originally thought it had something to do with the development server.)

For local development, I'll work around it by creating extra Chrome browser profiles, which appear to have separate connection limits.

**Comment by carltongibson** [comment]
Super. Thanks for the follow-up!
