### ISSUE TITLE
using django channels to send data from outside the consumer class did not work

### ISSUE THREAD

**Issue by encodingl** [django/channels#1365]
My consumer as follows：

    class pretask(AsyncWebsocketConsumer):
     
        async def connect(self):
            self.group_name = "group_test_01"
            await self.channel_layer.group_add(
                self.group_name,
                self.channel_name
            )
            await self.accept()
    
        async def receive(self, text_data):
            message = json.loads(text_data)
            await self.channel_layer.group_send(
                self.group_name,
                {
                    'type': 'show_in_windows',
                    'message': message
                }
            )
        async def show_in_windows(self,event):
            print("7")
            message = event["message"]
            print(message)
            await self.send(text_data=json.dumps({
                "message":message}))
        async def disconnect(self, close_code):
            pass

When I use the client to make a websocket request,the server log is as follws：it worked fine。

    INFO WebSocket HANDSHAKING /ws/skworkorders/WorkOrderCommit/pretask/ [127.0.0.1:57566]
    INFO WebSocket CONNECT /ws/skworkorders/WorkOrderCommit/pretask/ [127.0.0.1:57566]
    7
    {'csrfmiddlewaretoken': 'YhfDhjZxtPsRqSN8Mo0Nhybt8JY3KLyNWeQ84VBc6F0u8ff4F7npRI1hriSRMRiT', 'title': 'AnsibleCMD-DEV',......}

But when I change my consumer as follows ，the web_send function didnot work

    class pretask(AsyncWebsocketConsumer):
    
     
        async def connect(self):
            self.group_name = "group_test_01"
            await self.channel_layer.group_add(
                self.group_name,
                self.channel_name
            )
            await self.accept()
    
        async def receive(self, text_data):
            p1 = TestWebSend(self.group_name,"call out")
            p1.sendmsg()
            print(text_data)
           
        async def show_in_windows(self,event):
            print("7")
            message = event["message"]
            print(message)
            await self.send(text_data=json.dumps({
                "message":message}))
        async def disconnect(self, close_code):
            pass
   

 the TestWebSend class is as follows:
    
        from channels.layers import get_channel_layer
        from asgiref.sync import async_to_sync
        
        def web_send(group_name,msg):
            print("4")
            channel_layer = get_channel_layer()
            print("5")
            print(group_name)
        
            async_to_sync(channel_layer.group_send)(group_name,
                {
                    'type': 'show_in_windows',
                    'message': msg
                }
            )
            print("6")
            
        class TestWebSend():
            def __init__(self,group_name,msg):
                self.msg = msg
                print(self.msg)
                self.group_name = group_name
                print(self.group_name)
        
            def sendmsg(self):
                print("3")
                web_send(self.group_name, self.msg)
                print("8")
When I use the client to make a websocket request,the server log is as follws async_to_sync(channel_layer.group_send) did not work：

    INFO WebSocket HANDSHAKING /ws/skworkorders/WorkOrderCommit/pretask/ [127.0.0.1:58251]
    INFO WebSocket CONNECT /ws/skworkorders/WorkOrderCommit/pretask/ [127.0.0.1:58251]
    call out
    group_test_01
    3
    4
    5
    group_test_01
    INFO WebSocket DISCONNECT /ws/skworkorders/WorkOrderCommit/pretask/ [127.0.0.1:58251]

my env
```
windows 10
python3.7.4
django==2.2.5
channels==2.3.0
channels-redis==2.4.0
```
Is there something wrong with my usage?

**Comment by jheld** [comment]
Can you check if the consumer is logging/crashing on anything?
