### ISSUE TITLE
JsonRpcConsumer

### ISSUE THREAD

**Issue by millerf** [django/channels#1375]
Hi,

I developed a small module that could be beneficial for those who look to use Json-RPC over websockets or Http:

https://github.com/millerf/django-channels2-jsonrpc

there is aso one version for channels 1:

https://github.com/millerf/django-channels-jsonrpc

Anyone is invited to contribute if needed.

Cheers

**Comment by carltongibson** [comment]
Hi @millerf Super. Have you thought about posting to _Show & Tell_ on forum.djangoproject.com ?

**Comment by millerf** [comment]
@carltongibson Will do now! Thanks

**Comment by carltongibson** [comment]
Hi @millerf — I'm going to close this now, but if you wanted to make a PR to the docs/community.rst, that would be cool too. 👍
