### ISSUE TITLE
Django-Channels with 2 applications

### ISSUE THREAD

**Issue by playerDACC** [django/channels#1378]
Hello!

I tried first to ask for help in StackOverflow and in the Django Google Group, but was unsuccessful.
I'm trying to make an example to test if it is possible to have 2 independent django apps connected to the same channel from django-channels.
So far, I was able to make an example running on one machine and 2 other machines being able to access the first via a client.
But the goal is to be able to connect separate applications in a single channel to communicate. Is that possible?

Note: I'm also using redis, if that helps.

Thank you!

**Comment by carltongibson** [comment]
If both shared the same channel layer (perhaps with channel names for `app1:...`, `app2:...`) it would probably work. But there's no official pattern for that I can point you to.
