### ISSUE TITLE
Q filters not working with database_sync_to_async

### ISSUE THREAD

**Issue by cdrandin** [django/channels#1379]
I was trying to run this part 

    @database_sync_to_async
    def get_room_id(self, user1, user2):
        room = Room.objects.filter(Q(user1=user1) & Q(
            user2=user2) | Q(user1=user2) & Q(user2=use1)).first()
        return room.id

and calling it like 

    room_id = await self.get_room_id(...)

my workaround works just fine

    @database_sync_to_async
    def get_room_id(self, user1, user2):
        room = Room.objects.filter(user1=user1, user2=user2).first()
        if room is None:
            room = Room.objects.filter(user1=user2, user2=user1).first()
        return room

I am unsure if this also is a concern for the other complex query objects.

Maybe related to #1336 

- Your OS and runtime environment, and browser if applicable

    - OSX 10.14.6
	- Python 3.7.5
	- Chrome 78.0.3904.97 

- A `pip freeze` output showing your package versions

        
        aioredis==1.3.0
        appnope==0.1.0
        argon2-cffi==19.1.0
        asgiref==3.2.3
        asn1crypto==0.24.0
        async-timeout==3.0.1
        atomicwrites==1.3.0
        attrs==19.1.0
        autobahn==19.10.1
        Automat==0.8.0
        autopep8==1.4.4
        backcall==0.1.0
        beautifulsoup4==4.8.1
        blessings==1.7
        boto3==1.9.218
        botocore==1.12.218
        certifi==2019.6.16
        cffi==1.12.3
        channels==2.3.1
        channels-redis==2.4.1
        chardet==3.0.4
        Click==7.0
        constantly==15.1.0
        coreapi==2.3.3
        coreschema==0.0.4
        coverage==4.5.4
        cryptography==2.7
        daphne==2.3.0
        decorator==4.4.0
        dj-database-url==0.5.0
        Django==2.2
        django-appconf==1.0.3
        django-braces==1.13.0
        django-contrib-comments==1.9.1
        django-cors-headers==3.1.0
        django-debug-toolbar==2.0
        django-environ==0.4.5
        django-extensions==2.2.1
        django-filter==2.2.0
        django-imagekit==4.0.2
        django-js-asset==1.2.2
        django-model-utils==3.2.0
        django-mptt==0.10.0
        django-mptt-admin==0.7.1
        django-nose==1.4.6
        django-notifications-hq==1.5.0
        django-polymorphic==2.1.2
        django-rest-knox==4.1.0
        django-rest-polymorphic==0.1.8
        django-silk==3.0.2
        django-storages==1.7.1
        django-unique-upload==0.2.1
        djangorestframework==3.10.2
        djangorestframework-recursive==0.1.2
        docutils==0.15.2
        drf-yasg==1.16.1
        entrypoints==0.3
        factory-boy==2.12.0
        Faker==2.0.1
        flake8==3.7.8
        gprof2dot==2017.9.19
        gunicorn==19.9.0
        hiredis==1.0.0
        hyperlink==19.0.0
        idna==2.8
        importlib-metadata==0.19
        incremental==17.5.0
        inflection==0.3.1
        ipdb==0.12.2
        ipython==7.7.0
        ipython-genutils==0.2.0
        itypes==1.1.0
        jedi==0.15.1
        Jinja2==2.10.1
        jmespath==0.9.4
        jsonfield==2.0.2
        livereload==2.6.1
        lxml==4.4.1
        Markdown==3.1.1
        MarkupSafe==1.1.1
        mccabe==0.6.1
        metadata-parser==0.10.0
        mkdocs==1.0.4
        mock==3.0.5
        more-itertools==7.2.0
        msgpack==0.6.2
        netifaces==0.10.9
        newrelic==5.0.2.126
        nose==1.3.7
        nose-progressive==1.5.2
        numpy==1.17.1
        packaging==19.1
        parso==0.5.1
        pbr==5.4.2
        pexpect==4.7.0
        pickleshare==0.7.5
        pilkit==2.0
        Pillow==6.1.0
        pluggy==0.12.0
        prompt-toolkit==2.0.9
        psycopg2-binary==2.8.3
        ptyprocess==0.6.0
        py==1.8.0
        pyasn1==0.4.7
        pyasn1-modules==0.2.7
        pycodestyle==2.5.0
        pycparser==2.19
        pydot==1.4.1
        pyflakes==2.1.1
        Pygments==2.4.2
        PyHamcrest==1.9.0
        pyOpenSSL==19.0.0
        pyparsing==2.4.2
        pytest==5.1.1
        pytest-django==3.5.1
        pytest-factoryboy==2.0.3
        python-dateutil==2.8.0
        pytz==2019.2
        PyYAML==5.1.2
        requests==2.22.0
        requests-toolbelt==0.9.1
        ruamel.yaml==0.16.5
        ruamel.yaml.clib==0.1.2
        rules==2.1
        s3transfer==0.2.1
        service-identity==18.1.0
        simplegeneric==0.8.1
        six==1.12.0
        soupsieve==1.9.4
        sqlparse==0.3.0
        swapper==1.1.1
        text-unidecode==1.2
        tornado==6.0.3
        traitlets==4.3.2
        Twisted==19.7.0
        txaio==18.8.1
        uritemplate==3.0.0
        urllib3==1.25.3
        wcwidth==0.1.7
        Werkzeug==0.15.5
        whitenoise==4.1.3
        zipp==0.6.0
        zope.interface==4.6.0
       

- What you expected to happen vs. what actually happened

### Happened ###

Passed over the method and immediately disconnects

### Expected ###
Get a queryset of my filter.

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)

	- with `python manage.py runserver` default

- Console logs and full tracebacks of any errors

	- None

**Comment by carltongibson** [comment]
There's not enough here to reproduce.
