### ISSUE TITLE
ASGI/Channels development server turn all request method to GET

### ISSUE THREAD

**Issue by saber-solooki** [django/channels#1384]
Hi
I faced with some issue when run ASGI/Channels development server. When request with different method (POST, PATH ...) , Always get "GET" method in my code. I try to print my method with this sample code:

@csrf_exempt
def test(request):
    return JsonResponse({"method": request.method})

**Comment by carltongibson** [comment]
Sorry, there's not enough to go on here. Can you upload a minimal project demonstrating the issue? Thanks!
