### ISSUE TITLE
Are there plans to support Django 3.0?

### ISSUE THREAD

**Issue by aaronn** [django/channels#1385]
Are there plans to support Django 3.0?

**Comment by carltongibson** [comment]
Err... No incompatibility. Django's new ASGIHandler is more or less the same as Channel's. Channels also allows you to write async consumers, which, as views, aren't yet available in Django.

**Comment by carltongibson** [comment]
Right, that’s wrong. My bad, sorry.

Just set up with Django 3.0 and we have a failure from the session handling not correctly wrapping the DB calls in a `sync_to_async()`

So yes, as soon as we can get those issues fixed, I’ll throw out a new release.
