### ISSUE TITLE
Documentation does not cover type parameter when sending to another channel

### ISSUE THREAD

**Issue by andrew-houghton** [django/channels#1392]
I recently used Django channels for the first time and there was a gap in the documentation which made things a fair bit harder than it could have been.

I wanted to send a message to a single channel. Eventually I found the a section in the docs on this page. https://channels.readthedocs.io/en/latest/topics/channel_layers.html 
(where it says "To send to a single channel, just find its channel name (for the example above, we could crawl the database), and use channel_layer.send:")

However the code sample included the "type" parameter. I didn't realize for a long time that this type parameter has to match the name of a function of the consumer. I think it would really help if there was an extra sentence in the docs which could explain this.
I think I spent about 2-3 hours stumped by putting the wrong value into the "type" field, or getting "type" field missing errors.
If you want me to make a PR with a few sentences explaining the "type" field I'll give it a go.

PS. On the whole I had a very good experience using channels. The tutorial was especially good! Thanks for your work.

**Comment by carltongibson** [comment]
Hiya. Yes, OK, a PR with a suggestion would be welcome.
