### ISSUE TITLE
Unable to make channels to work in aws instance

### ISSUE THREAD

**Issue by ylnunez84** [django/channels#1397]
Hello, i am having a problem to make my chat app work in production. I am using Amazon EC2 instance. Locally works fine with python manage.py runserver, the problem is in prod environment.
I am using this configuration for nginx:
-----------------------nginx conf----------------------------
upstream app_server {
  server unix:/home/project/run/gunicorn.sock fail_timeout=0;
}

upstream channels_backend {
  server servername.com:8001;
}

server {
    listen       80;
    server_name  servername.com;
    root /home/project/templates;
    index homepage.html homepage.htm;
    client_max_body_size 4G;
    access_log /home/project/logs/nginx-access.log;
    error_log /home/project/logs/nginx-error.log;

    location / {		
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        if (!-f $request_filename) {
            proxy_pass http://app_server;
            break;
        }

    }

    location /static/ {
        alias   /home/project/assets/;
    }

    location /media/ {
        alias   /home/project/media/;
    }

    location /ws/ {
        proxy_pass http://channels_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }
}
------------------------------------------------------------

Supervisor programs:
[program:asgi_workers]
command = /home/project/worker.sh
user = root
stdout_logfile = /home/project/logs/worker.log
redirect_stderr = true
autorestart = true
stdout_logfile=/tmp/workers.out.log

[program:asgi_daphne]
command = /home/project/daphne.sh
user = root
stdout_logfile = /home/project/logs/daphne.log
redirect_stderr = true
autorestart = true
stdout_logfile=/tmp/daphne.out.log

[program:app]
command = /home/project/gunicorn_start.sh
user = www-data
stdout_logfile = /home/project/logs/gunicorn_supervisor.log
redirect_stderr = true  

-------------------Django Requirements ------------------

asgi-redis==1.1.0
asgiref==1.0.0
autobahn==0.12.1
channels==0.16.1
daphne==0.14.1
dj-database-url==0.4.0
haikunator==1.0.1
msgpack-python==0.4.7
psycopg2==2.6.1
redis==2.10.5
six==1.10.0
Twisted==16.2.0
txaio==2.2.1
wheel==0.24.0
zope.interface==4.1.3

------------------------django settings.py----------------------------------

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDISCLOUD_URL', 'redis://localhost:6379')],
        },
        "ROUTING": "conceptboard.routing.channel_routing",
    },
}

I am getting no logs in mi daphne.log file and in nginx-error log getting this
*750 connect() failed (111: Connection refused) while connecting to upstream, client: 152.207.249.13, server: servername.com, request: "GET /ws/chat/28 HTTP/1.1", upstream: "http://34.211.96.11:8001/ws/chat/28", host: "servername.com"

**Comment by carltongibson** [comment]
Sorry, this isn't something we can address here.
