### ISSUE TITLE
AsyncJsonWebsocketConsumer and channel redis doesn't work

### ISSUE THREAD

**Issue by Hyperian428** [django/channels#1401]
```
Django==2.2.6
django-heroku==0.3.1
daphne==2.4.0
gunicorn==19.9.0
requests==2.22.0
channels==2.3.1
channels-redis==2.4.1
```

I have a simple consumer program that I am testing my redis server, but I don't see the channel function executing.

```
from channels.generic.websocket import AsyncJsonWebsocketConsumer

class backEndConsumer(AsyncJsonWebsocketConsumer):

    async def websocket_connect(self, type):
        self.channel_name = "first"
        await self.channel_layer.group_add("link", self.channel_name)
        await self.accept()

    async def websocket_disconnect(self, close_code):
        await self.close()
        await self.channel_layer.group_discard("link", self.channel_name)
        # Called when the socket closes
        
    async def websocket_receive(self, text_data=None, bytes_data=None):
        await self.send("Connected")
        await self.channel_layer.group_send(
        "link",
            {
               "type": "link.send",
               "message": "msg from websocket",
            })       
        
#channel layer functions 
    async def link_send(self, event):
        print("got message: " + event["message"])
        await self.send("triggered!")
```

my settings.py has this
```
redis_host = os.environ.get('REDIS_HOST', 'localhost')
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(redis_host, 6379)],
        },
    },
}
```
I believe I followed most of the examples (including the multichat example). But my code doesn't seem to work. 
I have found people with issues similar to mine and it seems like they found work arounds, but it didn't apply to my code.

**Comment by hishnash** [comment]
how are you running the server, I see you have `gunicorn` are you running through Daphne or not?

**Comment by carltongibson** [comment]
Sorry, this isn't really addressable as is. There could be any number of things going on... — we can't really offer support here.

**Comment by Hyperian428** [comment]
I am using daphne my profile is:
web: daphne APbackend.asgi:application --port $PORT --bind 0.0.0.0

I unknownly somehow got channel redis to work (partly), I was able to get group_send from file A.py and B.py to message event in B.py. But I am unable to get group_send from A.py and B.py to message event in A.py.

Is there something under the hood that I should know about? does both side need to start with group_add of the same group first? (tried, doesn't work either)

i get this error.
raise ValueError("No handler for message type %s" % message["type"])

**Comment by Hyperian428** [comment]
Instead of being vague, I've pasted the files i've been working on.
my "A.py" is https://paste.ofcode.org/8Sa7xGW2DKiKV2FyngMP5j
my "B.py" is https://paste.ofcode.org/vgZ6wAH7mnA7E3dsFkTAwa
When i run my backendconsumer in B.py, line 53 should send an event to A.py.
I've created the handler for frontendconsumer in A.py line 70.
But when i run line 53, i get the error
ERROR    Exception inside application: No handler for message type webhook.reg
note that in B.py, all of my device handles work just fine, just not my handles in A.py

**Comment by hishnash** [comment]
@Hyperian428 your issue here looks like its down to the run-loop of the HTTP handler.

in channels v2 a consume will not get called while it is processing another call.

in your case:
 `line 19`  `async def http_request(self, request): #request is already a json object`

is still processing when the message to `webhook_reg` is sent so the message stays in the queue until `http_request` completes.

when `http_request` completes however you are sending a full http response so the consumer will close down and not get any more messages.

what you need to do instead is
* not send the `200` response in the `http_request` method (and not block)
* send your `200` response in the `webhook_reg`

**Comment by Hyperian428** [comment]
@hishnash 
if `http_request`'s 200 response is being completed before my webhook_reg is sent, then how come when i run this code, it works?
https://paste.ofcode.org/BWTmzrjDySKizhJJFSN3r9

What is happening when i use self.channel_layer.group_add()? from what i've seen, it would register all the events in my class so that any file anywhere else can use it. So that is why my A.py file can use functions in B.py file. But if i try to group_add() to the same group in my A.py file, my B.py file does not see them. Is it possible to add events from different places to a single group? So far I get errors when I try to do it.

**Comment by hishnash** [comment]
>  Is it possible to add events from different places to a single group

yes absolute you can have as many subscribers to a group as you like. 

> https://paste.ofcode.org/BWTmzrjDySKizhJJFSN3r9

re here you are getting the call to `webhook_reg` but that print statement is going to be called after `http_request` finishes. The reason you see the print is that the consumer has not yet died. 

With channels you are not sending messages between classes/files you are sending messages between instances of those consumers. Those instances are cleaned up quite quickly after the connection they are created for is closed.

**Comment by Hyperian428** [comment]
@hishnash I am trying to figure out a way to build an IOT device, with a http requests coming from DialogFlow and then using websocket to talk to my embedded device.

I still have questions about the inner workings of django-channels, I will probably reform my questions and put them on stackoverflow.

**Comment by Hyperian428** [comment]
I've moved my question to
https://stackoverflow.com/questions/59886447/interactions-between-http-and-websocket-connections-in-django-channels
