### ISSUE TITLE
Session Save Call for an AnonymousUser (AuthMiddlewareStack) Causes Orphan Sessions

### ISSUE THREAD

**Issue by thaxy** [django/channels#1402]
Let's assume we have a WebSocket consumer wrapped in a ``AuthMiddlewareStack`` (SessionMiddleware).

```
application = ProtocolTypeRouter({
    'websocket': AllowedHostsOriginValidator(
        AuthMiddlewareStack(
            URLRouter(
                # ...
            )
        ),
    )
})
```

As an anonymous user I ``connect()`` to my consumer, modify the session store and save it.
```
self.scope["session"]["test"] = 123
self.scope["session"].save()
```

This will create (default Django configuration) a new row in the database table ``public.django_session``. Doing this [in a traditional view](https://stackoverflow.com/questions/32458657/django-sessions-for-anonymous-users#answer-49709138) Django will take care to send the ``sessionid`` cookie back to the user by setting the corresponding host header in the response object. Channels (with a WebSocket consumer) behaves differently as the client will never get informed about his sessionid and therefore his corresponding store. The session for an anonymous user is lost when the user reconnects.

One hacky workaround could look like this:

```
 def connect(self):
    headers = {}
    if settings.SESSION_COOKIE_NAME not in self.scope['cookies']:
        session_store = self.scope['session']
        session_store['test'] = 123
        session_store.save()
        headers['Set-Cookie'] = f'{settings.SESSION_COOKIE_NAME}={session_store.session_key}'
        self.scope['cookies'][settings.SESSION_COOKIE_NAME] = session_store.session_key
     self.accept(subprotocol=(None, headers))
```

Any thoughts on that? Is there a better way to handle such a scenario?

_____
Update: Maybe the following code is a bit better:

```
        headers = {}
        session_store = self.scope['session']
        if not session_store.session_key:
            session_store.create()
            headers['Set-Cookie'] = f'{settings.SESSION_COOKIE_NAME}={session_store.session_key}'
        self.accept(subprotocol=(None, headers))
```

**Comment by carltongibson** [comment]
> Any thoughts on that?

No real thoughts no. (Does setting the cookie even work in a websocket context?) 

This isn't an issue per se, but if you come up with a good solution do come and we can review.
