### ISSUE TITLE
What configuration does redis need to do when using channels？

### ISSUE THREAD

**Issue by pppigg** [django/channels#1410]
When my project starts or when I connect to websocket, the following message is printed and the connection disconnects.

`Exception inside application: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
`

The following information appears when running on both different environments.

The environment：
`channels            2.4.0              
channels-redis      2.4.1                       
daphne              2.4.1              
decorator           4.4.1              
Django              3.0.3              
django-cors-headers 3.2.1              
djangorestframework 3.11.0  `

`channels            2.2.0              
channels-redis      2.4.0                         
daphne              2.3.0              
Django              2.2.5              
django-cors-headers 3.1.0                       
djangorestframework 3.10.3 
`
Whether redis needs to change the configuration?
Looking forward to your reply.

**Comment by carltongibson** [comment]
You should try searching for your error. 

Top hit for "Redis MISCONF" is this https://github.com/antirez/redis/issues/584

Looks like your issue. 

Redis config issues are out of scope for here I'm afraid.
