### ISSUE TITLE
[Question] Is it django channels on Conda?

### ISSUE THREAD

**Issue by fbove** [django/channels#1424]
Is there any official django channels build published in conda?

I've found [this one](https://anaconda.org/tethysplatform/django-channels) but I don't know if it's the official one.

Thanks!

**Comment by carltongibson** [comment]
No. PyPI yes, but we don’t publish anything to conda. (Is there even a package repository? Not heard of it till now.)

**Comment by fbove** [comment]
As far as I am aware, package repositories are called "Conda Channels" which are locations where conda look for packages, being conda-forge the main one.

In fact there is a hole Django environment published in conda-forge, just to mention a few:

- [Django](https://anaconda.org/conda-forge/django)
- [Django Rest Framework](https://anaconda.org/conda-forge/djangorestframework)
- [Django Extensions](https://anaconda.org/conda-forge/django-extensions)

And:
- [Websocket Client](https://anaconda.org/conda-forge/websocket-client)

It'd be great to also have Django Channels joined to the party :)

**Comment by carltongibson** [comment]
Who published these? They’re not published by the Django project itself.

**Comment by fbove** [comment]
This guys [https://conda-forge.org/](https://conda-forge.org/)

So, maybe we or I should ping them in order to get them noticed about Django Channels.
