### ISSUE TITLE
how can I create a server sent events?

### ISSUE THREAD

**Issue by ihakh** [django/channels#1440]
with this code:
```
class Events(AsyncHttpConsumer):
    async def handle(self, body):
        await self.send_headers(headers=[
            (b"Cache-Control", b"no-cache"),
            (b"Content-Type", b"text/event-stream"),
            (b"Transfer-Encoding", b"chunked"),
        ])
        await self.channel_layer.group_add('some_events',self.channel_name)
        print('hello')
        await self.send_body(b"retry: 400\n\n", more_body=True)
        while True:
            await asyncio.sleep(1000)

    async def disconnect(self):
        print('bye')
        await self.channel_layer.group_discard('some_events',self.channel_name)

    async def some_event_send(self, event):
        print(event)
        msg = '\n'.join(['%s: %s'%(k, v) for k, v in event['msg'].items()])
        await self.send_body(msg.encode(), more_body=True)
```

I have 2 question
1- how can I write a SSE using AsyncHttpConsumer? if I remove the `while True` part I see immediately `bye` after `hello` . is the connection closed this soon?
2- how can I send events to this group? I use this code:
`async_to_sync(self.channel_layer.group_send)("some_events", {"type": "some_event_send", 'msg': msg})`
but I never see the event printed
what is wrong?

**Comment by carltongibson** [comment]
Hi, this is a usage question, rather than an issue: best targetted at a support channel. Thanks. 

https://channels.readthedocs.io/en/latest/topics/consumers.html#asynchttpconsumer

**Comment by ihakh** [comment]
Hi
sorry
True
this is a usage question but I didn't know where to ask it
for websocket we add group in connect and leave it on disconnect
where should I join a group and where I should leave?

it seems to me this is a bug that the disconnect called immediately after handle function finished though `more_body=True` flage is used.

what is wrong with my code?
I want to send events through the group

**Comment by ihakh** [comment]
I Have read the doc.
but I cant get it right
