### ISSUE TITLE
New PyPI release timeline?

### ISSUE THREAD

**Issue by oTree-org** [django/channels#1443]
Just wondering if there is anything I could do to help with getting the next release out on PyPI. Would really like to use some of the new enhancements (and for deployment reasons, can't really use the GitHub-hosted code as a dependency).

**Comment by carltongibson** [comment]
Hi @oTree-org. As of now, there are only [small changes between master and the last release](https://github.com/django/channels/compare/2.4.0...master) — is there anything there that you're looking at in particular? 

The target is to update Channels to ASGI v3 compatibility throughout, and then release a new version with that. The target is (obviously) [around Django 3.1, so August](https://code.djangoproject.com/wiki/Version3.1Roadmap) — Any input updating middleware and such very welcome.

**Comment by oTree-org** [comment]
Hi @carltongibson, thank you for posting that diff, it made me realize that the changes I was waiting for were not part of channels but rather channels_redis and daphne, and that there are new releases of those packages. So, problem solved, thank you!
