### ISSUE TITLE
Feature Request: Raw TCP/UDP Socket Support

### ISSUE THREAD

**Issue by ChaseGuru** [django/channels#1449]
**Background and research findings:**

I used channels for a test app using websockets and it was great.  Based on your docs I saw:

> Channels is a project that takes Django and extends its abilities beyond HTTP - to handle WebSockets, chat protocols, IoT protocols, and more. It’s built on a Python specification called ASGI.

Seen elsewhere - though at this point I see this seems to have been removed in newer versions of docs. 
>Extendability to other protocols or event sources (e.g. WebRTC, raw UDP, SMS)

Which sounds really cool - having a high level abstract protocol like this supporting websockets, raw tcp/udp, and iot.

Once I went to actually implement this though I realized it doesn't seem to be a thing.

I see no consumers here: https://channels.readthedocs.io/en/latest/topics/consumers.html#generic-consumers, none here: https://github.com/django/channels/tree/master/channels/generic
And none on google - notably, SO has no answers: https://stackoverflow.com/questions/60523472/django-channels-listening-tcp-udp

At this point - I'm guessing the goal was to engineer the framework to be extensible for these use cases - but neither you nor any third party seems to have written support for any of these things.

**Feature Request**
Provide means to support a UDP or TCP consumer.  I'm open minded if we think it doesn't make sense for channels to support these vs websocket as websockets can start as an HTTP request - whereas UDP sockets are lower level and don't have the benefit of http packets to give some metadata.

I'm guessing this may be why you removed raw udp/sms from your docks.  IoT still seems like it could have similar complications - but I don't remember enough about it to feel confident in thinking it doesn't make sense for channels.

I'm happy to have this closed if you think it's better to leave UDP support to other frameworks - though I'd be a bit disappointed as it seemed like groups/channels could be nice to have in other forms of sockets.

**Comment by carltongibson** [comment]
Hi @ChaseGuru. I think this is out of scope for Channels itself, at least for the moment. I'm not even immediately sure where it might fit into [the wider ASGI landscape](https://github.com/florimondmanca/awesome-asgi) at the moment — short of someone keen, like yourself, working up some proofs-of-concept that is.  

> ...though I'd be a bit disappointed as it seemed like groups/channels could be nice to have in other forms of sockets.

I'm sure the channel layer and such can be adapted once the other components are in place.
