### ISSUE TITLE
Can a list of users connected to a channel ?

### ISSUE THREAD

**Issue by cihanerman** [django/channels#1451]
Hello, I'm new to django channels, I am curious about;
Can a list of users connected to a channel ?

I am sorry if I had a mistake in opening a issue.
Thank you. Good work.

**Comment by carltongibson** [comment]
Sorry, we can't really help with usage questions here. 

(You'd need to keep a list of the connected users, and then consult that — possible, but you'll need to work out the implementation yourself. Good luck!)

**Comment by cihanerman** [comment]
Thank you, good work.
