### ISSUE TITLE
how can I share instance variable between group users only

### ISSUE THREAD

**Issue by pankajsharma120** [django/channels#1452]
I am developing a online game on django, for real time connection I am using channels but unfortunately for every user I have a separate instance of game.

What I want is, for first user I start the game with object of `StartGame` and want to use this same instance object for other users also, because I want to share current state of game.

How can I, share game instance with other members of that group only ?

**Comment by carltongibson** [comment]
Sorry, this is a usage question we can't really help with on the issue tracker. 

(You'll need to keep a list of open games and consult that when a new user joins... — but you'll have to work that out for yourself I'm afraid. Good luck!)
