### ISSUE TITLE
login method cycles session key but doesn't update browser cookie

### ISSUE THREAD

**Issue by RyanRio** [django/channels#1453]
Background:
I am calling `login(self.scope, user)` with `user` being the user object I just created from a username in a websocket message.

Expected result:
If a user opens another window they are still logged in. (the `sessionid` cookie is set in the user's browser with the new session_key)

Actual result:
The `sessionid` cookie in the user's browser still corresponds to a session for an `AnonymousUser` (prior to when they logged in), however there no longer exists a session that corresponds to that key and so an entirely new session is made and essentially it appears the user has never logged in.

'solution':
I can 'solve' the problem by commenting out `else: session.cycle_key()` in `channels.auth.login`, this of course removes the (I believe) intended functionality of disassociating the anonymous user from the now logged in user...

OS is windows 10, python version is 3.8.1.

daphne==2.4.1
Django==3.0.4
channels==2.4.0
asgiref==3.2.7

I'm just running channels with runserver.

Thanks!
Ryan

**Comment by carltongibson** [comment]
Hi. There's not quite enough to go on here: can you provide a minimal project demonstrating your issue? 

I'm guessing that you're using a WebSocket consumer? Did you remember to save the session to persist? 

```
        # login the user to this session.
        await login(self.scope, user)
        # save the session (if the session backend does not access the db you can use `sync_to_async`)
        await database_sync_to_async(self.scope["session"].save)()
```

See [_How to log a user in/out_ in the docs](https://channels.readthedocs.io/en/latest/topics/authentication.html#how-to-log-a-user-in-out).

If that's not right, please do follow-up with more info, and we'll see if we can pin it down.
