### ISSUE TITLE
WebSocket connection to 'ws://18.222.139.20/ws/' failed: Error during WebSocket handshake: Unexpected response code: 502

### ISSUE THREAD

**Issue by AjayKarki** [django/channels#1470]
I am getting WebSocket connection to 'ws://18.222.139.20/ws/' failed: Error during WebSocket handshake: Unexpected response code: 502 in Browser Console. But when I run in Local it seems to be working fine. I am bit new to production I guess I have some bad conf somewhere 
My Nginx Conf File
server {
    listen 80;
    server_name 18.222.139.20;

    keepalive_timeout 5;
    client_max_body_size 4G;

    access_log /home/ubuntu/Kunyo/backend/logs/nginx-access.log;
    error_log /home/ubuntu/Kunyo/backend/logs/nginx-error.log;

    location /static/ {
        root /home/ubuntu/Kunyo/backend/;
    }

    # checks for static file, if not found proxy to app
    location / {
        try_files $uri @proxy_to_app;
    }

    location /ws/ {
        try_files $uri @proxy_to_ws;
    }

    location @proxy_to_ws {
       proxy_pass http://unix:/home/ubuntu/Kunyo/backend/kunyoback.sock;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $server_name;
    }

    location @proxy_to_app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://unix:/home/ubuntu/Kunyo/backend/kunyo.sock;

}
}

My Daphne Service File
[Unit]
Description=daphne daemon
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/Kunyo/backend
ExecStart=/home/ubuntu/venv/bin/daphne -u /home/ubuntu/Kunyo/backend/kunyoback.sock --fd 0 kunyo.asgi:channel_layer    
[Install]
WantedBy=multi-user.target

My Daphne Worker File
[Unit]
Description=python runworker server for kunyo
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/Kunyo/backend
ExecStart=/home/ubuntu/venv/bin/python /home/ubuntu/Kunyo/backend/manage.py runworker channels ws

[Install]
WantedBy=multi-user.target

My Gunicorn File
[Unit]
Description=gunicorn daemon
After=network.target
[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/Kunyo/backend
ExecStart=/home/ubuntu/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/home/ubuntu/Kunyo/backend/kunyo.sock kunyo.wsgi:application
[Install]
WantedBy=multi-user.target

routing.py
from channels.routing import ProtocolTypeRouter, URLRouter
from django.urls import path
from notification.consumers import EchoConsumer

application = ProtocolTypeRouter({
    "websocket": URLRouter([
        path("ws/", EchoConsumer),
    ])
})

Part of settings
ASGI_APPLICATION = "kunyo.routing.application"

**Comment by carltongibson** [comment]
Hi @AjayKarki — Can you post your solution for anyone following? Thanks.

**Comment by AjayKarki** [comment]
> Hi @AjayKarki — Can you post your solution for anyone following? Thanks.

Yeah Sure...But I think i made a mess in Configuration 😂

**Comment by AjayKarki** [comment]
Anyways this was my final configuration ... I doubt I did properly but still it worked for me...
## nginx-backend
server {
    listen 90;
    server_name 18.222.139.20;

    keepalive_timeout 5;
    client_max_body_size 4G;

    access_log /home/ubuntu/Kunyo/backend/logs/nginx-access.log;
    error_log /home/ubuntu/Kunyo/backend/logs/nginx-error.log;

    location /static/ {
        root /home/ubuntu/Kunyo/backend/;
    }

    # checks for static file, if not found proxy to app
    location / {
        try_files $uri @proxy_to_app;
    }
    location @proxy_to_app {
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_pass http://unix:/home/ubuntu/Kunyo/backend/kunyo.sock;

}
}
## nginx-back-socket

server {
    listen 91;
    server_name 18.222.139.20;

    keepalive_timeout 5;
    client_max_body_size 4G;

    access_log /home/ubuntu/Kunyo/backend/logs/nginx-access-socket.log;
    error_log /home/ubuntu/Kunyo/backend/logs/nginx-error-socket.log;

    location /ws/ {
        try_files $uri @proxy_to_ws;
    }

    location @proxy_to_ws {
        proxy_pass http://unix:/home/ubuntu/Kunyo/backend/kunyoback.sock;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;

    }
}

## Daphne 

[Unit]
Description=daphne daemon
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/Kunyo/backend
ExecStart=/home/ubuntu/venv/bin/daphne -u /home/ubuntu/Kunyo/backend/kunyoback.sock  kunyo.asgi:application

[Install]
WantedBy=multi-user.target

## Worker

[Unit]
Description=python runworker server for kunyo
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/Kunyo/backend
ExecStart=/home/ubuntu/venv/bin/python /home/ubuntu/Kunyo/backend/manage.py runworker channels ws

[Install]
WantedBy=multi-user.target

## Web Service Gunicorn

[Unit]
Description=gunicorn daemon
After=network.target
[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/Kunyo/backend
ExecStart=/home/ubuntu/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/home/ubuntu/Kunyo/backend/kunyo.sock kunyo.wsgi:application
[Install]
WantedBy=multi-user.target

## In Settings.py
ASGI_APPLICATION = "kunyo.routing.application"

## In asgi.py


import os
import django
from channels.routing import get_default_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "kunyo.settings")
django.setup()
application = get_default_application()
