### ISSUE TITLE
How to storage variable in consumer?(channels==1.x)

### ISSUE THREAD

**Issue by ZzzJing** [django/channels#1472]
I create a variable in connect consumer, i want to use this variable in receive consumer. But i find that this  variable can not be saved.

I read the source code of runserver & runworker, i found that every request will generate a new object, So what can i do? Does channels 1.x support variable storage?

channels version: 1.x

**Comment by jheld** [comment]
Would you be able to leverage creating a shared key via outside of channels' communication/constructs? Such as directly in redis, managing it wholly by your application code from both sides.

**Comment by ZzzJing** [comment]
> Would you be able to leverage creating a shared key via outside of channels' communication/constructs? Such as directly in redis, managing it wholly by your application code from both sides.

But it need to do serialization if i want to share an object. It is not very graceful, Any other method to solve this?

**Comment by carltongibson** [comment]
Closing as stale.
