### ISSUE TITLE
exception when initializing consumer is not reported

### ISSUE THREAD

**Issue by staschuk-bungalow** [django/channels#1477]
If calling a consumer's `__init__` raises an exception, that exception is not reported.

Here is a minimal example project and docker-compose configuration to demonstrate: https://github.com/livebungalow/channels-exception-example

Variations:
* The exception _is_ reported if runworker is running only one channel, and in this case the exception kills runworker.  (Presumably it's running in the main thread then?)
* An exception raised by an actual handler method (i.e., what `dispatch()` dispatches to) _is_ reported, and does not kill runworker.  (The `less-broken-consumer` in the linked minimal example demonstrates this.)

> Your OS and runtime environment, and browser if applicable

The minimal example is based on the docker image `python:3.7-slim`.  I have also reproduced it with `python:3.8-slim`.

> A `pip freeze` output showing your package versions

Using the linked minimal example as written:

    % docker-compose run django pip freeze
    aioredis==1.3.1
    asgiref==3.2.10
    async-timeout==3.0.1
    attrs==19.3.0
    autobahn==20.7.1
    Automat==20.2.0
    cffi==1.14.1
    channels==2.4.0
    channels-redis==2.4.2
    constantly==15.1.0
    cryptography==3.0
    daphne==2.5.0
    Django==2.2.13
    hiredis==1.1.0
    hyperlink==19.0.0
    idna==2.10
    incremental==17.5.0
    msgpack==0.6.2
    pyasn1==0.4.8
    pyasn1-modules==0.2.8
    pycparser==2.20
    PyHamcrest==2.0.2
    pyOpenSSL==19.1.0
    pytz==2020.1
    service-identity==18.1.0
    six==1.15.0
    sqlparse==0.3.1
    Twisted==20.3.0
    txaio==20.4.1
    zope.interface==5.1.0

Also, if I change the minimal example to _not_ specify versions in the `Dockerfile`, I get

    % git diff
    diff --git a/Dockerfile b/Dockerfile
    index 87b8018..06315cf 100644
    --- a/Dockerfile
    +++ b/Dockerfile
    @@ -1,5 +1,5 @@
     FROM python:3.7-slim
     RUN apt-get update
     RUN apt-get install -y build-essential
    -RUN pip install django==2.2.13 channels==2.4.0 channels_redis==2.4.2
    +RUN pip install django channels channels_redis
     WORKDIR /proj
    % docker-compose build
    [...]
    % docker-compose run django pip freeze
    aioredis==1.3.1
    asgiref==3.2.10
    async-timeout==3.0.1
    attrs==19.3.0
    autobahn==20.7.1
    Automat==20.2.0
    cffi==1.14.1
    channels==2.4.0
    channels-redis==3.0.1
    constantly==15.1.0
    cryptography==3.0
    daphne==2.5.0
    Django==3.0.8
    hiredis==1.1.0
    hyperlink==19.0.0
    idna==2.10
    incremental==17.5.0
    msgpack==1.0.0
    pyasn1==0.4.8
    pyasn1-modules==0.2.8
    pycparser==2.20
    PyHamcrest==2.0.2
    pyOpenSSL==19.1.0
    pytz==2020.1
    service-identity==18.1.0
    six==1.15.0
    sqlparse==0.3.1
    Twisted==20.3.0
    txaio==20.4.1
    zope.interface==5.1.0

and the behaviour is the same.

> What you expected to happen vs. what actually happened

I expected the exception to be reported.  Instead, nothing was reported.

> How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)

With runworker.  See the docker-compose.yaml file in the linked repository for exact details.

> Console logs and full tracebacks of any errors

The problem is that an expected error report is missing.

**Comment by carltongibson** [comment]
This should no-longer apply in Channels v3, as consumers are instantiated per-request (or per-connection)
