### ISSUE TITLE
how to connect django-channels websocket on ubuntu ssl deploy?

### ISSUE THREAD

**Issue by LukaTarkhn** [django/channels#1486]
I configure gunicorn and daphne:
**_gunicorn.service_**
```
[Unit]
Description=gunicorn daemon
After=network.target
[Service]
User=luka
Group=www-data
WorkingDirectory=/home/luka/itworkdir
ExecStart=/home/luka/itworkdir/env/bin/gunicorn --access-logfile - --workers 3 --bind unix:/home/luka/myproject.sock Career.wsgi:application
[Install]
WantedBy=multi-user.target
```
**_daphne.service_**
```
[Unit]
Description=itwork Daphne Service
After=network.target

[Service]
Type=simple 
User=luka
WorkingDirectory=/home/luka/itworkdir
ExecStart=/home/luka/itworkdir/env/bin/daphne -e ssl:9001:privateKey=/home/luka/itworkdir/privkey.pem:certKey=/home/luka/itworkdir/fullchain.pem Career.asgi:application

[Install]
WantedBy=multi-user.target
```
**_nginx file_**
```
upstream channels-backend {
 server localhost:9001;
}
server {
    server_name www.itwork.ge itwork.ge;
    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /home/luka/itworkdir;
    }
    location / {
        include proxy_params;
        proxy_pass http://unix:/home/luka/myproject.sock;
    }
    location / {
      proxy_set_header HOST $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_pass_request_headers on;
      proxy_pass http://<server ip="">:<server port="">;
      proxy_http_version 1.0;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/itwork.ge/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/itwork.ge/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = www.itwork.ge) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = itwork.ge) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    listen 80;
    server_name www.itwork.ge itwork.ge;
    return 404; # managed by Certbot
}
```
**_Javascript_**
```
var wsStart = 'ws://'
if (loc.protocol === 'https:'){
    wsStart = 'wss://'
}
var endpoint = wsStart + loc.host + loc.pathname
var socket = new ReconnectingWebSocket(endpoint)
```
in localhost on windows working correct and i get this:
[success image](https://i.stack.imgur.com/GM3CR.jpg)
but on deploy with this settings i get this:
[error image](https://i.stack.imgur.com/Lfd0s.jpg)

I have been looking for a solution to this problem for several weeks but I have not been able to solve this problem, I can not guess where I am wrong and how to solve this problem.

>**OS**
Ubuntu 18.04.3 (LTS) x64

>**pip freeze**
aioredis==1.3.1
asgi-redis==1.4.3
asgiref==3.2.7
astroid==2.0.4
async-timeout==3.0.1
attrs==19.3.0
autobahn==20.4.3
Automat==20.2.0
certifi==2020.4.5.2
cffi==1.14.0
channels==2.4.0
channels-redis==2.4.2
chardet==3.0.4
cloudinary==1.21.1
colorama==0.4.3
constantly==15.1.0
cryptography==2.9.2
daphne==2.5.0
defusedxml==0.5.0
Django==3.0.6
django-allauth==0.38.0
django-bootstrap-datepicker-plus==3.0.5
django-cors-headers==2.4.0
django-froala-editor==3.1.0
django-libs==2.0.3
django-multiselectfield==0.1.12
django-rest-auth==0.9.3
django-rest-framework==0.1.0
djangorestframework==3.9.0
gunicorn==20.0.4
hiredis==1.0.1
html5lib==1.0.1
hyperlink==19.0.0
idna==2.7
incremental==17.5.0
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
msgpack==0.6.2
msgpack-python==0.5.6
oauthlib==2.1.0
Pillow==7.1.2
psycopg2==2.8.5
psycopg2-binary==2.8.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyHamcrest==2.0.2
PyJWT==1.7.1
pylint==2.1.1
pyOpenSSL==19.1.0
PyPDF2==1.26.0
python3-openid==3.1.0
pytz==2020.1
redis==2.10.6
reportlab==3.5.42
requests==2.20.1
requests-oauthlib==1.0.0
service-identity==18.1.0
six==1.15.0
social-auth-app-django==4.0.0
social-auth-core==3.3.3
sqlparse==0.3.1
Twisted==20.3.0
txaio==20.4.1
urllib3==1.24.3
webencodings==0.5.1
whitenoise==5.0.1
wrapt==1.10.11
xhtml2pdf==0.2.4
zope.interface==5.1.0

**Comment by carltongibson** [comment]
Hi @LukaTarkhn — Please comment your solution for people that follow. Thanks,

**Comment by LukaTarkhn** [comment]
> Hi @LukaTarkhn — Please comment your solution for people that follow. Thanks,
Hi,
I could not solve the problem, so I decided to eliminate the need for ASGI from the project altogether
