### ISSUE TITLE
I want help concerning CORS

### ISSUE THREAD

**Issue by abdellatifLabr** [django/channels#1508]
I created an e commerce platform in which i am using django channels 2.0 to handle notifications, it works perfectly on my local machine, bu when i deploy it on heroku, (the frontend is a react app deployed on netlify), when i send requests from the app, i get response blocked by CORS policy., i used django channles OriginValidator , but nothing changed, so i want some help.
django backend: [https://github.com/abdellatifLabr/MyStore](https://github.com/abdellatifLabr/MyStore)

**Comment by carltongibson** [comment]
Sorry, but we can't help out with general support requests here - the issue tracker is for reproduceable bugs and
concrete feature requests only! Please see our support documentation (http://channels.readthedocs.io/en/latest/support.html)
for more information about where you can get general help.
