### ISSUE TITLE
database_sync_to_async hangs during the test

### ISSUE THREAD

**Issue by Bulbashful** [django/channels#1512]
I use pytest with plugins below:
`requests-mock-1.7.0, nameko-2.12.0, asyncio-0.14.0, django-3.9.0, celery-4.4.2`
And at the following test hangs on `database_sync_to_async` method for django orm
```
@pytest.mark.django_db(transaction=True)
@pytest.mark.asyncio
async def test1():
    await database_sync_to_async(Client.objects.count)()
    ...
```
But when i am trying to abort the test with `ctrl+c` hotkey, code execution going to the next line. Any idea?

**Comment by carltongibson** [comment]
Not really. This looks like a pytest issue. Happy to look into it if you can pin it down to something specific with Channels.
