### ISSUE TITLE
Tests relying on django.core.mail.outbox fail with channels

### ISSUE THREAD

**Issue by pydanny** [django/channels#152]
Testing of emails in Django's Unittest system is a bit more challenging when using Channels. When sending emails via channels, `django.core.mail.outbox` always is an empty list.

Also, outside of Unittest, we can see the emails in the console. Twice. Yes, in the console they appear twice. I don't know if that's somehow related.

**Comment by andrewgodwin** [comment]
Does this happen just when you have channels installed, or when you're sending things onto the channel system from inside tests?

**Comment by andrewgodwin** [comment]
Closing due to lack of response.
