### ISSUE TITLE
Users are logged out when connecting to websockets after upgrading to Django 3.1

### ISSUE THREAD

**Issue by sciyoshi** [django/channels#1524]
This is due to the [change in Django 3.1 to use SHA-256 for user session hashing](https://docs.djangoproject.com/en/3.1/releases/3.1/#django-contrib-auth). Within Django, [a legacy check for session hashes was added for compaitbility](https://github.com/django/django/blob/3f2821af6bc48fa8e7970c1ce27bc54c3172545e/django/contrib/auth/__init__.py#L189-L196) - a similar check should probably be added to the [equivalent check in channels](https://github.com/django/channels/blob/f834595e04131dc955e72acd388ed11b943b6983/channels/auth.py#L45).

Note that this only happens once - future sessions seem to work fine.

**Comment by carltongibson** [comment]
This isn't worth the overhead. Just have them log in again.
