### ISSUE TITLE
channel_layer.send not sync, only run after process end

### ISSUE THREAD

**Issue by justcby** [django/channels#1526]
class ChatConsumer(WebsocketConsumer):
    
    def connect(self):
        print(self.channel_name)
        self.accept()

    def disconnect(self, close_code):
        pass

    def receive(self, text_data):
        async_to_sync(self.channel_layer.send)(self.channel_name, {
            "type": "chat.message",
            "text": "1",
        })
        print("=============channel================")
        async_to_sync(self.channel_layer.send)(self.channel_name, {
            "type": "chat.message",
            "text": "2",
        })

    def chat_message(self, event):
        message = event["text"]
        print(message)
        self.send(text_data=json.dumps({'message': message}))
    

i call channel_layer.send twice in receive function , suppose should print like
1
========channel========
2

but it print
=========channel=======
1
2

anyone could help to tell me where have problem ?

**Comment by vladislavkoz** [comment]
I have the same issue

**Comment by vladislavkoz** [comment]
Ohh it was actually because of the AsyncConsumer.

**Comment by sevdog** [comment]
This is due to how messages are handled on the channel layer, there is no guarantee that they are delivered synchronously even if you do use a synch consumer.
