### ISSUE TITLE
Intermittent test failure on Python 3.8

### ISSUE THREAD

**Issue by carltongibson** [django/channels#1539]
e.g. https://github.com/django/channels/runs/1309406596?check_suite_focus=true#step:5:200

Added in: https://github.com/django/channels/commit/b285e1e29bba9c599cc607476af59cdf0114fddc
For the `as_asgi()` classmethod. 

Adjusted in: https://github.com/django/channels/commit/6362831502b0bd982a3d916ad60274988cbfb7e5
Was hoping `id()` would be more reliable than `repr()`. 

Need to dig in and see if there's a genuine issue here, or if it's just an artefact of the test, and if so why. 

@adamchainz — If you were to have a cycle, I'd be grateful for the eyes here. 🤹 

* Is the `as_asgi()` method sound? 
* Is the test flawed? 
   * How to best check two separate instances are used (if not this way)? 
   * It only comes up on Python 3.8. What's that about? 
        * Actions history: all the recent failures are this. https://github.com/django/channels/actions

**Comment by adamchainz** [comment]
Perahps store `time.time()` in `__init__` and use that as the unique identifier? Since `id()` is the memory location, it seems reasonable the same ID could be reused if an object is deallocated and another allocated immediately after.

**Comment by carltongibson** [comment]
> Since id() is the memory location... 

Yeah, that was the problem with `repr()`, but I've just done the same thing then. 🤔

> Perhaps store time.time()

OK. Thanks! I shall give that a run. 

👍
