### ISSUE TITLE
websocket connect message request wrapping

### ISSUE THREAD

**Issue by fmarani** [django/channels#154]
I was trying to access the cookies in the websocket.connect consumer function but, differently from http requests, the message parameter is pretty much a straight mapping from the ASGI spec.

I understand why http is different... it needs to be passed to the standard Django url router, but some of this parsing may be beneficial for the websocket connect phase.

I am mainly talking about this:

```
(Pdb) message.content
{'query_string': '', 'server': ['127.0.0.1', 8000], 'path': '/chat/undefined', 'reply_channel': 'websocket.send!mlUTqKIQFvij', 'order': 0, 'client': ['127.0.0.1', 46757], 'headers': {'sec-websocket-version': b'13', 'user-agent': b'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/48.0.2564.82 Chrome/48.0.2564.82 Safari/537.36', 'sec-websocket-key': b'X7xhsSTMeoYLGU3HIZGoRw==', 'connection': b'Upgrade', 'accept-encoding': b'gzip, deflate, sdch', 'cookie': b'_hjIncludedInSample=1; _hjUserId=83cdfaac-2a2d-410f-9be1-8c372b3ff0e9; ajs_user_id=181; ajs_anonymous_id=%22f0956d49-a23e-4a10-b6f1-7fffcdcbee68%22; rateapp=U7X0MP; __wzde93a2174222d=1448377220; __wzdaac6f3e9cb28=1449080161; __wzd051f8a0b0eb3=1449163449; cb-enabled=accepted; sessionid=85wza3rg8y5tt6jxkx6nvtc1spg92lf3; csrftoken=MXJKr7JROHyBSAIETFUMPXc42ejgopZc; email=l@gmail.com; fingerprint=xxx; _ga=GA1.1.1634703354.1444237866', 'cache-control': b'no-cache', 'accept-language': b'en-GB,en;q=0.8,en-US;q=0.6,it;q=0.4', 'host': b'localhost:8000', 'pragma': b'no-cache', 'upgrade': b'websocket', 'origin': b'http://localhost:8000', 'sec-websocket-extensions': b'permessage-deflate; client_max_window_bits'}}
```

is there a way to parse this and get something like a Django HttpRequest?

**Comment by andrewgodwin** [comment]
Potentially, but without the middleware wrapping around it it might end up in a weird uncanny valley where it looks like a HttpRequest but doesn't actually provide enough info to be useful.

Are you just looking for good cookie access, or are there other things you'd like too? It's possible that as part of the build-out of some more high-level WebSocket class-based views we could throw in some WsConnect class that looks kind of like a HttpRequest object at first glance.

**Comment by fmarani** [comment]
I was moving some code that was using data in the cookies to do a really lightweight authentication from a Django view to the websocket connect consumer, that's when I realized all the headers were unprocessed.

I got around this by changing a few things, but I was wondering whether this specific stage might benefit from a bit more processing in general... possibly not a middleware but an extra decorator for the consumer function to do this additional work.

As much as i like class-based views, I rather not use them if they are avoidable.

**Comment by andrewgodwin** [comment]
Hmm, the websocket auth decorator does actually make a fake Request object so there's something to get cookies off of, so it's not like this is unprecedented. I guess the question is if it should actually be a HttpRequest subclass with a weird method or something, or just a lookalike that has enough to use basic methods that are the same on both.

I think I lean towards the latter, mostly as people always overreach into HttpRequest and try to get body data or the stream or something, and none of that is there with a websocket connection.

**Comment by andrewgodwin** [comment]
Coming back to this, I don't think we should do this, so closing as a WONTFIX. Thanks for the suggestion, though.
