### ISSUE TITLE
TypeError in 3.0.0 when using HttpCommunicator

### ISSUE THREAD

**Issue by lobsterkatie** [django/channels#1549]
I'm not sure if this is a bug in `channels`, `asgiref`, or our tests, so forgive me if I'm putting this in the wrong place. (This is not an ecosystem I know well.)

In our tests we use `HttpCommunicator`, and since the version bump to `3.0.0`, we're getting this error:

```
tests/integrations/django/asgi/test_asgi.py:23: in test_basic
    response = await comm.get_response()
.tox/py3.7-django-3.0/lib/python3.7/site-packages/channels/testing/http.py:42: in get_response
    response_start = await self.receive_output(timeout)
.tox/py3.7-django-3.0/lib/python3.7/site-packages/asgiref/testing.py:78: in receive_output
    self.future.result()
.tox/py3.7-django-3.0/lib/python3.7/site-packages/channels/routing.py:71: in __call__
    return await application(scope, receive, send)
.tox/py3.7-django-3.0/lib/python3.7/site-packages/asgiref/compatibility.py:33: in new_application
    instance = application(scope)
E   TypeError: __init__() takes 1 positional argument but 2 were given
```

In the stacktrace above, `comm` is an instance of `HttpCommunicator` instantiated as `HttpCommunicator(ProtocolTypeRouter({"http": AsgiHandler}), "GET", "/async_message")`. I saw in your release notes two things:

1) `AsgiHandler` is deprecated (though it doesn't say it's broken - is it?)
2) `scope` needs to be moved from `__init__` to `__call__` for consumers

I see that we're violating the former, and that `asiref.compatibility` is violating the latter. Neither of those are you all, but since it's `channels` that requires `asgiref`, I think that means it's yours to fix until they fix theirs?

Other useful information:

1) We use tox to run tests, and these are the combinations which failed:

```
ERROR:   py3.7-django-2.0: commands failed
ERROR:   py3.7-django-2.1: commands failed
ERROR:   py3.7-django-2.2: commands failed
ERROR:   py3.7-django-3.0: commands failed
ERROR:   py3.7-django-3.1: commands failed
ERROR:   py3.7-django-dev: commands failed
ERROR:   py3.8-django-2.2: commands failed
ERROR:   py3.8-django-3.0: commands failed
ERROR:   py3.8-django-3.1: commands failed
ERROR:   py3.8-django-dev: commands failed
ERROR:   py3.9-django-2.2: commands failed
ERROR:   py3.9-django-3.0: commands failed
ERROR:   py3.9-django-3.1: commands failed
ERROR:   py3.9-django-dev: commands failed
```

2) This was run with `channels 3.0.0` and `asgiref 3.3.0`.

3) If you want to look at what our tests are doing, the failing ones are here: https://github.com/getsentry/sentry-python/blob/master/tests/integrations/django/asgi/test_asgi.py.

Please let me know if there's any other information you need.

Thanks!

**Comment by carltongibson** [comment]
Hi. 

So, yes, I'm expecting that you'd update that line to:

```
HttpCommunicator(ProtocolTypeRouter({"http": AsgiHandler()}), "GET", "/async_message")
```

Ideally if you can, update to use Django's version, but `AsgiHandler` should continue to work. 

(@bastbnl It's not actually a consumer subclass, so doesn't need the `as_asgi()` handling.)

Hopefully that helps?

**Comment by carltongibson** [comment]
@lobsterkatie I'm going to close this, as I think if you update the test it should work. If that's not the case, do come back.

**Comment by lobsterkatie** [comment]
Thanks, I'll let you know!
