### ISSUE TITLE
SessionMiddleware doesn't have set SameSite flag on the cookie.

### ISSUE THREAD

**Issue by gghildyal** [django/channels#1554]
I am AuthMiddlewareStack which wraps SessionMiddleware and CookieMiddleware, both of which does not set the SameSite flag on the cookie. This becomes an issue with Chrome as it interprets a missing flag as 'Lax' and would not store the cookies for cross-site requests.

**Comment by carltongibson** [comment]
Yes, OK. 

Probably this should be able to leverage [`CSRF_COOKIE_SAMESITE`](https://docs.djangoproject.com/en/3.1/ref/settings/#csrf-cookie-samesite)

**Comment by gghildyal** [comment]
Sorry, didn't mention it above, I was trying to leverage the `SESSION_COOKIE_SAMESITE`

**Comment by carltongibson** [comment]
Sorry, yes, copied the wrong link.

**Comment by carltongibson** [comment]
Closed in #1555
