### ISSUE TITLE
Turning BaseChannelLayer into an ABC?

### ISSUE THREAD

**Issue by robinharms** [django/channels#1556]
BaseChannelLayer doesn't contain things like send, group_send etc.
This seems to be part of the API, and to make type checking work it would be nice to add this to the BaseChannelLayer. 

Anyone writing a framework that uses channels wouldn't have to specify a specific layer implementation from the start.

```
class BaseChannelLayer(ABC):
    @abstractmethod
    async def send(self, channel, message):
        pass
```

If I do this as a PR, would that be acceptable? It wouldn't break anything, but make it easier for plugin developers to handle writing new layers.

**Comment by carltongibson** [comment]
I'm not sure this is worth it right now. Thanks.
