### ISSUE TITLE
Typo in docs code

### ISSUE THREAD

**Issue by KStenK** [django/channels#1561]
Hi,

I belive there is a missing new `.as_asgi()` method in docs example code, under that link:
https://channels.readthedocs.io/en/stable/introduction.html#django-integration

The code is:
```
from channels.routing import ProtocolTypeRouter
from django.core.asgi import get_asgi_application

application = ProtocolTypeRouter({
    "http": get_asgi_application(),
    "websocket": AuthMiddlewareStack(
        URLRouter([
            url(r"^front(end)/$", consumers.AsyncChatConsumer),
        ])
    ),
})
```

But should that WebSocket URL be like: `url(r"^front(end)/$", consumers.AsyncChatConsumer.as_asgi()),`.
And maybe add an import to the top where that `url` came from or change with `re_path` and that import path.

**Comment by carltongibson** [comment]
Hey @KStenK — yes, to both. Good spot. Fancy adjusting those?
