### ISSUE TITLE
The chat from tutorial doesn't work as described

### ISSUE THREAD

**Issue by nesvoboda** [django/channels#1566]
Hello,

I've tried following the Channels tutorial. However, the result of part 2, a chat prototype, is not functional.

The tutorial asks you to open the chat in two browser tabs and send a message. The message is supposed to appear in both tabs.

However, it appears twice, and only in the second tab (the one that is opened or refreshed last).

I'm absolutely sure to have followed the tutorial by the letter. I've uploaded
the resulting code here: https://github.com/nesvoboda/problem_with_channels

OS: Mac OS 10.15.6

Pip freeze:
asgiref==3.3.0
async-timeout==3.0.1
channels==3.0.0
channels-redis==3.2.0
daphne==3.0.0
Django==3.1.3

Console log from opening two tabs and sending one message:

```
> python3 manage.py runserver

Watching for file changes with StatReloader
Performing system checks...


System check identified no issues (0 silenced).
November 05, 2020 - 15:54:48
Django version 3.1.3, using settings 'guac_bac.settings'
Starting ASGI/Channels version 3.0.0 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
HTTP GET /chat/lobby/ 200 [0.04, 127.0.0.1:58923]
WebSocket HANDSHAKING /ws/chat/lobby/ [127.0.0.1:58924]
WebSocket CONNECT /ws/chat/lobby/ [127.0.0.1:58924]
WebSocket DISCONNECT /ws/chat/lobby/ [127.0.0.1:58924]
HTTP GET /chat/lobby/ 200 [0.01, 127.0.0.1:58927]
WebSocket HANDSHAKING /ws/chat/lobby/ [127.0.0.1:58928]
WebSocket CONNECT /ws/chat/lobby/ [127.0.0.1:58928]
HTTP GET /chat/lobby/ 200 [0.01, 127.0.0.1:58927]
WebSocket HANDSHAKING /ws/chat/lobby/ [127.0.0.1:58930]
WebSocket CONNECT /ws/chat/lobby/ [127.0.0.1:58930]
```

**How you're running Channels**: runserver

**Comment by carltongibson** [comment]
Please update to Channels 3.0.1

**Comment by nesvoboda** [comment]
@carltongibson Thank you so much! This solved the issue. Big thanks for your work!

**Comment by carltongibson** [comment]
Super. Thanks.

**Comment by daviddocteur** [comment]
I had the same issue. Updated and worked! Thanks a lot for solving it quickly!
