### ISSUE TITLE
InMemoryChannelLayer grows indefinitely

### ISSUE THREAD

**Issue by oTree-org** [django/channels#1574]
InMemoryChannelLayer has this in the `_clean_expired` method:

            # Is the channel now empty and needs deleting?
            if not queue:
                del self.channels[channel]

Queues are always truthy even if empty. So that `del` statement will not be reached. I believe the line should be changed to `if queue.empty():`. 

(I saw this while investigating a crash that seems to be due to the channel layer growing indefinitely bigger.)

**Comment by carltongibson** [comment]
Hmmm. The in memory channel layer is just for testing. It's explicitly it for real use.

**Comment by oTree-org** [comment]
OK, it's not that important to me; just wanted to bring it to your attention.

**Comment by oTree-org** [comment]
(Though I will add that letting the channel layer grow very large increases the chance of a race condition when 2 Daphne threads access it simultaneously: `RuntimeError: dictionary changed size during iteration`)

**Comment by carltongibson** [comment]
Yes, OK. Did you want to make the change in a PR? Thanks.
