### ISSUE TITLE
Requests hanging 

### ISSUE THREAD

**Issue by iw108** [django/channels#1576]
Hi, 

I have a Django view which loads a React app. Upon loading, the react apps calls two API endpoints. With Channels 2.4 + Django 2.2 everything works as expected, and I get responses from both the endpoints. However, when using Channels 3.0 I only ever get a response from one of the endpoints, with the other always hanging. Does anyone have any ideas as to what causes this?

Everything works as expected when I run things via WSGI. Things also work when I upgraded to Django 3 and use Django's `get_asgi_application`, but not when I use Channel's `AsgiHandler`.

**Comment by jamiegau** [comment]
Yes, I think this is connected to #1491
I am upgrading an app, and pushed everything to current release..
Once I add channels to the application..
When I do concurrent requests I will get pending forever starting to happen on browser requests.
If I do a request one at a time, it deals with it, only when I start to send concurrent requests.  i.e. multiple requests at the same time, then I get requests hanging.

I am surprised there is not more users observing this problem.  Its a show stopper when developing and typically using mange.py runserver.  I have to disable channels to do any work.

From my understanding, once you go live with a gunicorn deployment, for example, the problem should not be there.

**Comment by carltongibson** [comment]
Hey @iw108. Thanks for the report. 

Unfortunately, both here and on the related issue @jamiegau mentions, there's not enough information to see what's going on. 

Any chance you can put together a minimal sample project that reproduces the issue? 

> Things also work when I upgraded to Django 3 and use Django's get_asgi_application...

In the meantime I'd do that then. 🙂

**Comment by iw108** [comment]
This is an example of what i mean: https://github.com/iw108/channels

If I upgrade to Django 3, I don't have a problem.

**Comment by carltongibson** [comment]
@iw108 Thanks for the project 👍 As you say, must be an issue in `AsgiHandler`. Just a question of time to look into that...

> If I upgrade to Django 3, I don't have a problem.

👍

**Comment by carltongibson** [comment]
Closing as stale. If you hit this with latest versions please open a new issue.
