### ISSUE TITLE
HttpStreamingResponse works with the deprecated AsgiHandler but block db request as if it was async from django's AsgiHandler

### ISSUE THREAD

**Issue by Christophe31** [django/channels#1579]
Hello, I use the HttpStreamingResponse as suggested in django doc for CSV generation.
These views are common syncronous django views returning HttpStreamingResponse.

Since channels 3, I udated my project:
```python
application = ProtocolTypeRouter({
    "http": get_asgi_application(),  # the presence of this line trigger the crash below
    "websocket": AuthMiddlewareStack(
        URLRouter(ws_routes)
    ),
})
```

Since then I get this issue on ORM request:
```
SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
  File "channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "django/core/handlers/asgi.py", line 168, in __call__
    await self.send_response(response, send)
  File "django/core/handlers/asgi.py", line 242, in send_response
    for part in response:
  File "dj_utils/views.py", line 180, in build_csv
    for obj in self.get_queryset():
  File "django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor = self.connection.cursor()
  File "django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
```

I rolled back to the channel's default handler and it's ok again.

I can share privately a sentry's stacktrace if wanted.
(Maybe this issue should be in django but I thought the right people would be better targeted here)

tested with channel 3, django both 3.0 & 3.1

**Comment by edthrn** [comment]
Thanks a lot for this info, I was not aware of this Django ticket.

As of now, I'll just continue using the default ASGI handler from Channels, even though it's deprecated. I'm gonna follow the Django ticket carefully.

**Comment by Christophe31** [comment]
I freezed to channels 2… As when I had this issue with channels 3 I had some sessions mixing issues which if I recall has been fixed…
