### ISSUE TITLE
Sending to two different channel layer throws aioredis.errors.ConnectionForcedCloseError error 

### ISSUE THREAD

**Issue by ashmlk** [django/channels#1596]
Hello, I am trying to send a message to two different instances of my application with different layer names in one `async` function, however, it seems that whenever I send them together either only one of them works (Only one WebSocket receives the message) or none work at all and I get the error below. 

Currently, I have a ChatCOnsumer which inside the `send_chat_message()` function I send the message to two different layers:

```
    async def send_chat_message(self, message):
        await self.channel_layer.group_send(
            self.room_group_name,
            {
                'type': 'chat_message',
                'message': message
            }
        )
        await self.channel_layer.group_send(
            self.user2_notification_layer,
            {
                'type':'chat_message',
                'message':message
            }
        )
```

When I use either separately the seems to work fine, however, whenever I use them consecutively in the same context it does not work and I get the error:

```
python3.8/site-packages/channels_redis/core.py", line 666, in group_send
    await connection.zremrangebyscore(
aioredis.errors.ConnectionForcedCloseError
```

I am using Python 3.8, with Django channels version 3.0.2.

**Comment by aryan340** [comment]
Hello @ashmlk 
I am not sure if I understood you properly,
but as far as I know, your application has two channel layers.

However, in this block of code,
```py
        await self.channel_layer.group_send(
            self.user2_notification_layer,
            {
                'type':'chat_message',
                'message':message
            }
        )
```
you are assuming the layer to be a group and sending a message to the group.
What you should actually be doing is:
```py
another_layer = get_channel_layer('user2_notification_layer')
await another_layer.group_send(...)
```
Correct me if I am wrong.
Moreover, could you provide more information on your consumer?

**Comment by carltongibson** [comment]
Closing as stale.
