### ISSUE TITLE
Update Documentation for Background Tasks

### ISSUE THREAD

**Issue by benjaminbecker** [django/channels#1607]
According to https://github.com/django/channels/issues/514#issuecomment-275931766 it is not possible to run background tasks if using the in-memory channel layer.

This is not mentioned in the documentation for workers and background tasks: https://channels.readthedocs.io/en/latest/topics/worker.html#worker-and-background-tasks

In my opinion this should be added to the note in the beginning of the linked documentation page.

**Comment by benjaminbecker** [comment]
I can add a pull request if that helps.

**Comment by auvipy** [comment]
please proceed
