### ISSUE TITLE
Django 3.1.5 and Channels 3.0.3 websocket problem

### ISSUE THREAD

**Issue by mizamae** [django/channels#1627]
I am migrating an app to Django 3.1.5 and channels 3.0.3 and I am having problems with websockets getting disconnected around 2 seconds after being connected. This happens on  development environment using WIndows, Eclipse, PyDev...

On the browser console, I see that the websocket connects (executes the onopen routine) and a couple of seconds later, it executes the onclose event with error code 1011 (and sometimes 1006). During that time, I do not send or receive anything, just execute the consumer connect routine where I accept the connection.

Do I need to install uvicorn or anything similar for this to work properly??

kind regards for the help!!

**Comment by carltongibson** [comment]
I'm am sorry, there's really very little information to go on here, and certainly not enough to help you. It could be literally anything going wrong... — you'll need to come up with something specific before it will be possible to advise.
