### ISSUE TITLE
Django 3.1.5 and channels 3.0.3

### ISSUE THREAD

**Issue by mizamae** [django/channels#1628]
I am migrating an app to Django 3.1.5 and channels 3.0.3 and I am having problems with websockets getting disconnected around 2 seconds after being connected. This happens on  development environment using WIndows, Eclipse, PyDev...

On the browser console, I see that the websocket connects (executes the onopen routine) and a couple of seconds later, it executes the onclose event with error code 1011 (and sometimes 1006). During that time, I do not send or receive anything, just execute the consumer connect routine where I accept the connection.

Do I need to install uvicorn or anything similar for this to work properly??

Here is the django setup:

        # Channels
        ASGI_APPLICATION = 'MainAPP.asgi.application'
        
        #CHANNELS CONFIGURATION
        REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
        REDIS_PORT=6379
        # Channel layer definitions
        # http://channels.readthedocs.org/en/latest/deploying.html#setting-up-a-channel-backend
        CHANNEL_LAYERS = {
            "default": {
                # This example app uses the Redis channel layer implementation asgi_redis
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [(REDIS_HOST, REDIS_PORT)],
                },
            },
        }

Here is my asgi file:

        import os
        
        import django
        from django.conf.urls import url
        from django.core.asgi import get_asgi_application
        os.environ.setdefault("DJANGO_SETTINGS_MODULE", "MainAPP.settings.development")
        django.setup()
        django_asgi_app = get_asgi_application()
        
        from channels.auth import AuthMiddlewareStack
        from channels.security.websocket import AllowedHostsOriginValidator,OriginValidator
        from channels.routing import ProtocolTypeRouter, URLRouter
        
        from MainAPP.consumers import SystemConsumer
        
        application = ProtocolTypeRouter({
            # Django's ASGI application to handle traditional HTTP requests
            "http": django_asgi_app,
        
            # WebSocket chat handler
            "websocket": AllowedHostsOriginValidator(
                AuthMiddlewareStack(
                    URLRouter([
                        url(r"^ws/System/$",SystemConsumer.as_asgi()),
                    ])
                )
            ),
        })

Here is the consumer:

        from channels.generic.websocket import JsonWebsocketConsumer
        from channels.exceptions import DenyConnection
        
        from django.utils import timezone
        from django.contrib.auth.models import AnonymousUser
        from asgiref.sync import async_to_sync
        
        
        import logging
        logger = logging.getLogger("project")
        
        
        class SystemConsumer(JsonWebsocketConsumer):
            groups = ["WSbroadcast","WSsystemAPP"]
            
            def connect(self):
                # Called on connection.
                if self.scope['user'] == AnonymousUser():
                   raise DenyConnection("Invalid User")
        
                async_to_sync(self.channel_layer.group_add)(
                        self.groups[0],
                        self.channel_name
                    )
                
                if self.scope['user'].is_authenticated:
                    try:
                        # To accept the connection call:
                        self.accept()
                        print('Websocket accepted: ' + str(self.scope))
                    except Exception as ex:
                        print("Error accepting connection " + str(ex))
                else:
                    raise DenyConnection("User not authenticated")
                    
            def disconnect(self, close_code):
                # Called when the socket closes
                print('Websocket disconnected: ' + str(close_code))
                pass

And here the JS:

        var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
	        const path = ws_scheme + '://' + window.location.host + "/ws/System/";
	        let wsSystem = new WebSocket(path);
	        console.log("Connecting to " + path);
	        
	        wsSystem.onmessage = function (message) {
		        // Handle different actions
		        var payload = JSON.parse(message.data);
		        if (payload.action == "query_datetime") {
			        console.log("System UTC datetime is " + payload.date + " " + payload.time);
			        label=document.getElementById('systemTime');
			        system_hours=parseInt(payload.time.split(":")[0]);
			        system_minutes=parseInt(payload.time.split(":")[1]);
			        var currentdate = new Date();
			        if ((currentdate.getUTCHours()!=system_hours)||(currentdate.getUTCMinutes()<=system_minutes-2)||(currentdate.getUTCMinutes()>=system_minutes+2))
			        {	label.style.color="Red";
				        label.innerHTML= payload.date + " " + payload.time;
				        restart_NTP();
			        }
			        else{label.innerHTML="";}
		        }else if (payload.action == "loading_status") { 
			        var loading_status = payload.loading;
			        loading(loading_status);
		        }else {
			        console.log("Unknown action " + payload.action);
		        }
	        };
	         // Helpful debugging
	        wsSystem.onopen = function (event) { 
			        console.log("Connected to "+path); 
			        $("body").removeClass("no_websockets");
			        query_system_datetime();
	        };
	        wsSystem.onclose = function (event) { 
			        console.log("Disconnected to system socket: " + event["code"]); 
			        $("body").addClass("no_websockets");
	        };

kind regards for the help!!

**Comment by carltongibson** [comment]
Duplicate of #1627

**Comment by mizamae** [comment]
FOund the solution, I installed Redis 5.1 for Windows and it seems to work smooth now...
