### ISSUE TITLE
[Documentation] AttributeError: 'NoneType' object has no attribute 'group_add' & Solution

### ISSUE THREAD

**Issue by emilepetrone** [django/channels#1634]
**Problem**

I was just following the documentation when on [Step 3](https://channels.readthedocs.io/en/stable/tutorial/part_3.html#rewrite-the-consumer-to-be-asynchronous), I hit the following error:

`AttributeError: 'NoneType' object has no attribute 'group_add'`

**Solution**
Thus far, the instructions did not include adding a setting for the `CHANNEL_LAYERS` but I found that in the rest of the documentation.

In my local settings, I added `InMemoryChannelLayer` : 

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
```

That resolved the issue. 

**Question**

It seems like this is a step to add to the documentation? Just checking before submitting a PR (in case this was user error).

**Comment by yedpodtrzitko** [comment]
hi, 
`CHANNEL_LAYER` is documented in [Step 2 - Enable a channel layer](https://channels.readthedocs.io/en/stable/tutorial/part_2.html#enable-a-channel-layer):

> (...) Before we can use a channel layer, we must configure it. Edit the `mysite/settings.py` file and add a `CHANNEL_LAYERS` setting to the bottom. It should look like: *example code*


Looks good enough to me.
