### ISSUE TITLE
Scalability and extensive usage (kafka integration)

### ISSUE THREAD

**Issue by CosmicReindeer** [django/channels#1637]
So my project architecture is like this. I have models called boxes and users can join these boxes. Whenever an user creates something related to the box, an event regarding the same is sent via the websockets framework.

(Inspired by discord's architecture where clients do CRUD operations via the RESTful api and receive events via websockets). When the application scales, there would be lots of users joining boxes. I need to send box specific events.

My initial solution was to create groups per box I'd and to connect the user to respective groups based on box ids when they websocket-connect.

I would then group send the box specific events.

However, I have come to know that channels is meant for lightweight and smaller applications only. It isnt really suitable for extensive usage. In one of the issues I saw @andrewgodwin suggest to use kafka instead, which can horizontally scale.

I understand how kafka works perfectly.
However I have trouble integrating it with django and channels. How can I connect individual clients to kafka clusters when they connect via websocket?

How can my producers and the cluster run in parallel with the django application itself (without any blockage)? 

I failed to find any tutorials regarding this.
It would be really nice giving reference on where to start, or include integration with kafka in the docs.

(I mean like kafka has been around for a long time and it is what anyone would choose to use when  they want extensive usage).

**Comment by carltongibson** [comment]
HI @CosmicReindeer — This sounds like a great opportunity to write up what you learn as you go.

**Comment by CosmicReindeer** [comment]
Right then! The first thing I can think of is implementing a custom channel layer that links creating and sending to groups to kafka topics, partitions and brokers. I will let you know when I make more progress.

**Comment by CosmicReindeer** [comment]
However, the groups api and other conventional tools would be removed, in support of what kafka offers natively like `subscribe`.

The channel layer will be having an inner producer initialized which will send events. Every Consumer class from the django-channels framework will have their own kafka consumer class initialized on ws connect.

I will try to post an implementation of the same as soon as possible here when time permits, or make it a reusable extension.

**Comment by CosmicReindeer** [comment]
here is a rough implementation.
The core channel layer would be having a producer. When the application scales, we can also add more producers. But at the baseline, we need only one. We send messages or flush them via the producer. When the channel layer closes, we also close the channel layer.

As for the consumer, every channels-consumer instance has it's own kafka consumer on the inside.
these consumers only listen for `topics` they are subscribed to.
The groups API is gone with this implementation, and we cannot add consumers to topics via the channel layer.
this can be done only from the client side.
### Dependencies
- [`channels`](https://github.com/django/channels)
- [`kafka-python`](https://github.com/dpkp/kafka-python)
### Implementation
```py
from channels.exceptions import (
    StopConsumer,
    AcceptConnection,
    DenyConnection,
)
from channels.generic.websocket import WebsocketConsumer
from kafka import KafkaProducer, KafkaConsumer


# kafka channel-layer
class KafkaChannelLayer:
    """
    apache kafka channel layer implementation.
    """

    def __init__(self):
        self.producer = KafkaProducer()

    def topic_send(self, topic, *args, **kwargs):
        # send is asynchronous although not
        # a coroutine. pykafka takes care of
        # adding the task to the event loop
        self.producer.send(topic, *args, **kwargs)

    def flush(self, timeout=None):
        # flush the producer. However, we do
        # not have any guarantee that every single
        # replica or topic has been flushed
        self.producer.flush(timeout=timeout)

    def close(self, timeout=None):
        # kill the active producer instance
        self.producer.close(timeout=timeout)


# kafka websocket-consumer
class KafkaWebsocketConsumer(WebsocketConsumer):
    """
    Kafka integration with the websockets
    consumer. Removes the groups api and replaces
    it with the kafka message distribution system.
    """
    topics = None
    pattern = None

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.consumer = KafkaConsumer()
        self.stop_listening = False
        if self.topics is None:
            self.topics = []

    def start_listener_loop(self):
        """
        Starts a loop which listens for
        messages from the kafka consumer and
        sends the same if any is found.
        Called after websocket-connect.
        """
        while not self.stop_listening:
            for record in self.consumer:
                self.send(text_data=str(record))
                if self.stop_listening:
                    break
        # set the stop-listening variable
        # to false so that we can start the
        # listener loop immediately next time
        self.stop_listening = False

    def stop_listener_loop(self):
        """
        sets the `stop_listening attribute
        to break the listener loop.
        """
        self.stop_listening = True

    def set_topics(self, topics: list = None, pattern=None):
        """
        subscribes to a list of topics or a
        regex pattern from the consumer end.
        Because of kafka's architecture, topics
        are not incremental. They replace each
        other naturally.
        """
        if topics is not None:
            self.topics = topics
        if pattern is not None:
            self.pattern = pattern
        self.consumer.subscribe(
            self.topics,
            self.pattern
        )

    def websocket_connect(self, message):
        """
        Called when a WebSocket connection is opened.
        """
        try:
            # connect the consumer to
            # predefined topics or regex
            # patterns on ws connect
            self.consumer.subscribe(
                self.topics,
                self.pattern
            )
            self.connect()
        except AcceptConnection:
            self.accept()
        except DenyConnection:
            self.close()

    def close(self, code=None):
        """
        Closes the kafka consumer
        as well as the listener loop.
        """
        self.stop_listener_loop()
        self.consumer.close()
        super(KafkaWebsocketConsumer, self).close(code)

    def websocket_disconnect(self, message):
        """
        Called when a WebSocket connection is closed. Base
        level so you don't need to call super() all the time.
        """
        # remove the consumer from
        # all topics subscribed earlier
        self.consumer.unsubscribe()
        self.disconnect(message["code"])
        raise StopConsumer()

    def connect(self):
        # initialize the listener loop
        super(KafkaWebsocketConsumer, self).connect()
        self.start_listener_loop()

    def disconnect(self, code):
        """
        Called when a WebSocket connection is closed.
        """
        self.consumer.close()
```

**Comment by CosmicReindeer** [comment]
btw I think that I can discard the custom channel layer and avoid using it at all. I might initialize the producer in the `wsgi.py` file and then use it to send messages. That's what we were doing earlier, but the channel layer was redundant.

**Comment by CosmicReindeer** [comment]
there is no channel layer for kafka. Just initialize a producer when the application starts and then use it throughout the project to send events. You probably want to define it inside the `wsgi.py` file.

**Comment by CosmicReindeer** [comment]
I might as well as make a detailed write-up on this if this looks good. Might help others in the future.

**Comment by CosmicReindeer** [comment]
I wrote a detailed tutorial on kafka integration here @carltongibson 
https://gist.github.com/CosmicReindeer/da071d027050cfe0a03df3b500f2f44b

Hope this helps someone else!

**Comment by aryan340** [comment]
gist changed to https://gist.github.com/aryan340/da071d027050cfe0a03df3b500f2f44b
because of username change 😬

**Comment by carltongibson** [comment]
@aryan340 Just submit a pr for the change, no problem 😉
