### ISSUE TITLE
Improve BaseMiddleware class docstring

### ISSUE THREAD

**Issue by SuperNascher** [django/channels#1640]
The class docstring of [BaseMiddleware](https://github.com/django/channels/blob/master/channels/middleware.py#L3) should be updated to explain that `__call__` (and `__init__`) must be changed for the middleware.

>  Base class for implementing ASGI middleware. Inherit from this and
>  override the setup() method if you want to do things before you
>  get to.

Also the purpose of the middlewares could also added to the docstring that they add additional information's in the scope with a reference to the ASGI reference or channels documentation (consumers scope section). This would help to understand the purpose of this to new users, what they can expect from the middlewares and what not.

**Comment by Incred** [comment]
Sure, very confusing that suggestion to override the setup() method which one is never invoked at all.
