### ISSUE TITLE
Should AllowedHostsOriginValidator be in default examples for security?

### ISSUE THREAD

**Issue by collinanderson** [django/channels#1657]
Hi All,

Thanks for maintaining channels!

If we want channels to be secure by default, should `AllowedHostsOriginValidator` be included in all of the examples in the documentation whenever `AuthMiddlewareStack` is used? Otherwise as the security page says there's risk of cross-site request forgery. Currently the docs make `AllowedHostsOriginValidator` seem like an after thought.

I created a websocket application last fall, but I didn't realize websocket origins need to be validated for security so having `AllowedHostsOriginValidator` be more visible in the examples would help make the internet be a more secure place.

Thanks!
Collin

**Comment by aryan340** [comment]
Hello @collinanderson
My opinion is that the `AllowedHostsOriginValidator` is only going to be needed if we want host-based validation.
As this wouldn't be needed in every case and the documentation examples have to be as concise and simple as possible (for better understanding), I think that this isn't necessary.

https://channels.readthedocs.io/en/latest/topics/security.html
addresses for host-specific use cases.

**Comment by carltongibson** [comment]
Hi both 👋 — thanks for the discussion. 

A couple of thoughts: 

* I don't know about _every example_ but, maybe we could raise the visability with a suitably places admonition? 🤔
* A slightly bigger stick... — what about a `--deploy` system check? We could make that an error, that people could silence to opt-out of (assuming that if they did that, they'd know what they were about…)

**Comment by k3an3** [comment]
I think this deserves more attention. I was also surprised when going through the docs at how it seemed like an afterthought, while not using it effectively opens up Channels to CSRF. Any time WebSockets are used to perform authenticated actions or retrieve sensitive data, this is absolutely required for security. I imagine there are more cases where you'd want it than those where you wouldn't.

**Comment by carltongibson** [comment]
@k3an3 Would you fancy making a PR to the docs to address this?

**Comment by collinanderson** [comment]
I created a PR https://github.com/django/channels/pull/1825

**Comment by carltongibson** [comment]
Closed by #1825

**Comment by collinanderson** [comment]
(PR is still open/unmerged)

**Comment by carltongibson** [comment]
Doh! 🤦 

Thanks @collinanderson.
