### ISSUE TITLE
runtime error TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'

### ISSUE THREAD

**Issue by harshilsuthar** [django/channels#1670]
I was following the django-channels document and create a new conda env with python, Django and channels. there is no issue with dependency.

when i add 'channels' in installed apps then call view i got TypeError: call() missing 2 required positional arguments: 'receive' and 'send'
internal server error (500)

![Screenshot from 2021-04-07 18-16-25](https://user-images.githubusercontent.com/54183045/113869030-e6ba7000-97cd-11eb-9bb1-520e0ff2014a.png)

![Screenshot from 2021-04-07 18-17-41](https://user-images.githubusercontent.com/54183045/113869042-e9b56080-97cd-11eb-86f7-652c0aff8f52.png)

I don't know what to do

**Comment by carltongibson** [comment]
Duplicate of https://github.com/django/daphne/issues/366
