### ISSUE TITLE
on linux,channels intallation error

### ISSUE THREAD

**Issue by zsx151** [django/channels#1676]
linux  installation,pip install channels==2.0.2 ,error:centos Failed building wheel for cryptography,
how can i solve it?

**Comment by smithdc1** [comment]
If you're building cryptography you'll need rust. See link below.

https://github.com/pyca/cryptography/issues/5771

.

**Comment by zsx151** [comment]
already install rust ,but show&nbsp;error: command 'gcc' failed with exit status 1,and i already insatll extension about gcc
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "django/channels"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 下午2:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [django/channels] on linux,channels intallation error (#1676)





 
If you're building cryptography you'll need rust. See link below.
 
pyca/cryptography#5771
 
.

**Comment by zsx151** [comment]
already install rust ,but show error: command 'gcc' failed with exit status 1,and I already install extension about gcc

**Comment by zsx151** [comment]
failed with error code 1 in /tmp/pip-install-1rbfw1yy/cryptography/

**Comment by smithdc1** [comment]
Hmm, in that case I suggest you try a Cryptography support channel. I'm not sure you'll find an expert in building Cryptography wheels here.

**Comment by zsx151** [comment]
does channels support linux installations

**Comment by yedpodtrzitko** [comment]
Channels supports Linux installation, but as already explained above, this is not an issue of Channels. Your problem is its dependency called Cryptography, which you can find here: https://github.com/pyca/cryptography/
