### ISSUE TITLE
ASGI issues when using web sockets

### ISSUE THREAD

**Issue by djpimp2010** [django/channels#1680]
There has been a massive debugging session done, with the code of channels, and during this, we found out that to access any settings in any modules within the ASGI load script, you must create the application first, see below:

```
import os
from django.core.asgi import get_asgi_application
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "joinedup.settings")
http_app = get_asgi_application()

## logic that import things using Django settings

application = ProtocolTypeRouter({
    "http": http_app,
    'websocket': ####
})
```

it would be very very helpful to many people if this was added to the docs,

thanks

**Comment by carltongibson** [comment]
This is the exact structure of the [example in the deployment guide](https://channels.readthedocs.io/en/stable/deploying.html#configuring-the-asgi-application).

**Comment by djpimp2010** [comment]
Correct. But my point is that it could do with a bold header explaining that you MUST call the application at that exact point, otherwise it just looks like a standard fuction that can be moved around and called when needed

But unless it is called at the top of the file, it throws stack traces about apps not being loaded and settings env variable not being set
So it was very very hard to track down the cause of the problem, in some code that did work, then had settings being accessed, which broke it, due to the location of the above function

**Comment by carltongibson** [comment]
So the three line comment in the example is not sufficient? Happy to look at PR suggesting a wording improvement.

**Comment by yedpodtrzitko** [comment]
@djpimp2010 you didnt provide any traceback nor any details about the "logic that import things using Django settings", so it's impossible to reason about the exact issue here. My guess is that you triggered import of models from your app before `django.setup()` was called in `get_asgi_application()`, which is a no-go, as described [here in Django docs of Initialization process](https://docs.djangoproject.com/en/3.2/ref/applications/#initialization-process). Seems pretty well documented and self-explanatory to me. So is Channels really to blame here?

**Comment by djpimp2010** [comment]
The problem was, I moved get_asgi_application() into the protocol type router, thinking it was just another class that could be thrown around like normal python

There is no blame on channels whatsoever, but the documentation should explain very clearly that you need to actually execute the function and set it as a variable, before importing other modules that may access ORM or settings

@yedpodtrzitko in your tests that you commented on the PR, you are still assigning the function to a variable, try calling it within the router, and observe the unexpected results.

**Comment by yedpodtrzitko** [comment]
again - provide your error traceback, otherwise there's no point discussing anything
