### ISSUE TITLE
Test failures with in-memory layer. 

### ISSUE THREAD

**Issue by carltongibson** [django/channels#1682]
```
tests/test_inmemorychannel.py::test_send_receive FAILED                                                                                              [ 65%]
tests/test_inmemorychannel.py::test_send_capacity FAILED                                                                                            [ 67%]
tests/test_inmemorychannel.py::test_process_local_send_receive FAILED                                                                    [ 68%]

...
E       AttributeError: 'AsyncGenerator' object has no attribute 'send'
```

This has recently popped up. e.g. https://github.com/django/channels/actions/runs/770786127

It's a change in `pytest-asyncio` from 0.14.0 to 0.15.0

**Comment by carltongibson** [comment]
Looks like this might be Resolved is 0.15.1 https://github.com/pytest-dev/pytest-asyncio/issues/209 — need to test that out.

**Comment by smithdc1** [comment]
@carltongibson -- works for me if I install `pytest-asyncio` from github. 👍

**Comment by carltongibson** [comment]
Thanks for confirming @smithdc1, that was on my list. 🤹

We can unpin when it's released.
