### ISSUE TITLE
Response is received by the wrong user

### ISSUE THREAD

**Issue by KarlSayle** [django/channels#1731]
#### Production
- Ubuntu 18.04 within Dokku container
- Browser: unknown
#### Local
- Manjaro 21.0.7
- Browser: Firefox 89.0.1

---

### A `pip freeze` output showing your package versions
aioredis==1.3.1
amqp==2.6.1
asgiref==3.3.1
astroid==2.4.2
async-timeout==3.0.1
attrs==20.3.0
autobahn==20.12.2
Automat==20.2.0
billiard==3.6.3.0
boto3==1.16.37
botocore==1.19.37
bump2version==1.0.1
cairocffi==1.2.0
CairoSVG==2.5.0
celery==4.4.6
certifi==2020.12.5
cffi==1.14.4
channels==3.0.2
channels-redis==3.2.0
chardet==3.0.4
constantly==15.1.0
cryptography==3.3.1
cssselect2==0.4.1
daphne==3.0.1
defusedxml==0.6.0
dj-database-url==0.5.0
Django==2.2.4
django-appconf==1.0.4
django-crispy-forms==1.10.0
django-debug-toolbar==3.2
django-filebrowser==3.13.2
django-filter==2.4.0
django-grappelli==2.14.3
django-heroku==0.3.1
django-model-utils==4.1.1
django-notifications-hq==1.6.0
django-recaptcha==2.0.6
django-select2==7.5.0
django-storages==1.10.1
django-tinymce==3.2.0
djangorestframework==3.12.2
flake8==3.8.4
future==0.18.2
gunicorn==20.0.4
hiredis==1.1.0
html5lib==1.1
hyperlink==20.0.1
icalendar==4.0.7
idna==2.10
importlib-metadata==3.4.0
incremental==17.5.0
isort==5.6.4
jmespath==0.10.0
jsonfield==3.1.0
kombu==4.6.11
lazy-object-proxy==1.4.3
Markdown==3.3.3
mccabe==0.6.1
msgpack==1.0.1
pep8==1.7.1
Pillow==8.0.1
psycopg2==2.8.6
psycopg2-binary==2.8.6
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycparser==2.20
pyflakes==2.2.0
PyHamcrest==2.0.2
PyJWT==1.7.1
pylint==2.6.0
pylint-django==2.3.0
pylint-plugin-utils==0.6
pyOpenSSL==20.0.1
Pyphen==0.10.0
python-dateutil==2.8.1
pytz==2020.4
redis==3.5.3
requests==2.25.0
s3transfer==0.3.3
service-identity==18.1.0
six==1.15.0
sqlparse==0.4.1
stripe==2.34.0
swapper==1.1.2.post1
tinycss2==1.1.0
toml==0.10.2
twilio==6.50.0
Twisted==20.3.0
txaio==20.4.1
typing-extensions==3.7.4.3
urllib3==1.26.2
vine==1.3.0
WeasyPrint==52.2
webencodings==0.5.1
whitenoise==5.2.0
wrapt==1.12.1
zipp==3.4.0
zope.interface==5.2.0

---

#### Expected
The user to receive the correct response.
#### Actual
Under load, users receive a response intended for another user.

The Django app in question uses Channels to provide chat functionality with users, however, all other views are standard Django views. The example below briefly outlines the issue whereby responses are received by the wrong user. The issue was first reported by an authenticated user when they requested a detail view for a record (that they do have access to) but received another authenticated users (who was also actively using the site at the time) profile details (that they do not have access to).
#### Brief outline
- User A requests view/x
- User B request view/y at the same time
- User A receives the response from view/y (user B's response) and vice versa

I am not 100% sure that Channels is at fault here but this is the first Django app I have experienced this with and the only Django app that uses Channels which led me to try commenting out `channels` from `INSTALLED_APPS`. After commenting out `channels`, I am so far unable to reproduce the issue. This app has been in production for a couple of years but has only recently started receiving any consistent load.

---

### Steps taken to reproduce this locally
By using `django-notifications-hq` with the `refresh_period` set to `1` and then repeatedly opened the landing page in numerous tabs, I was able to simulate 'load' (I'm sure there is a more elegant solution for doing this but it seemed to get the job done). A number of the responses ended up being 'swapped'. The browser tab displayed the JSON response intended for `django-notifications` and when checking Firefox's network tab, could see that the AJAX request received the HTML response (the landing page).

---

#### Production
- Daphne with Nginx in front
#### Local
- `runserver`

---

### Console logs and full tracebacks of any errors
No errors found in logs both in production and local so far.

**Comment by carltongibson** [comment]
[Please update to Channels >=3.0.3](https://github.com/django/channels/blob/main/docs/releases/3.0.3.rst#303-release-notes).
