### ISSUE TITLE
Logged In User not being saved to session.

### ISSUE THREAD

**Issue by astarrh** [django/channels#1745]
This issue has been minimally reproduced here:
https://github.com/astarrh/django_channels_login/tree/ff3df1dc790d855aad7bd3bb087f06b4619c3893

My understanding from the [docs](https://channels.readthedocs.io/en/stable/topics/authentication.html#how-to-log-a-user-in-out) is that when a user is logged in through the following method:

```
from asgiref.sync import async_to_sync
from channels.auth import login

class SyncChatConsumer(WebsocketConsumer):

    ...

    def receive(self, text_data):
        ...
        async_to_sync(login)(self.scope, user)
        self.scope["session"].save()
```

The user should be logged into the session and should remain logged in if they refresh the page or navigate to other pages. However, this is not the case when I implement it. The user is successfully logged in and the user object can be used as long as the page is open, but on refresh or navigation the user is once again anonymous.

I have observed that Django's sessionid does change upon refreshing the page after login, which seems to be a behavior consistent with a successful login. However, the login status itself isn't preserved. 

This has been tested on multiple systems & browsers. 

https://github.com/astarrh/django_channels_login/tree/ff3df1dc790d855aad7bd3bb087f06b4619c3893

**Comment by JD99** [comment]
I join. exactly the same problem
