### ISSUE TITLE
On linux, pip failed to install channel and websocket will automatically disconnect 

### ISSUE THREAD

**Issue by zsx151** [django/channels#1754]
cryptography Failed to install all the time . The environment is centos7.6 django2.2 python3.6 .
So I put the windows package on linux, it can run normally, but the websocket will automatically disconnect the link in less than a day,
the error on the console: Failed to execute'send' on'WebSocket': Still in CONNECTING state. WebSocket connection to'ws://---------' failed:

**Comment by carltongibson** [comment]
Duplicate of https://github.com/django/daphne/issues/383
