### ISSUE TITLE
Django StreamingHttpResponse stops work when usind django channels

### ISSUE THREAD

**Issue by zhangzhao1114** [django/channels#1761]
```
def gen(camera):
    while True:
        frame = camera.get_frame()
        yield(b'--frame\r\n'
        b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@gzip.gzip_page
def index(request): 
    try:
        return StreamingHttpResponse(gen(VideoCamera()),content_type="multipart/x-mixed-replace;boundary=frame")
    except HttpResponseServerError as e:
        print("aborted")
```

settings.py:

```
ASGI_APPLICATION = 'photon.asgi.application'
```

asgi.py

```
application = ProtocolTypeRouter({
'http': get_asgi_application(),
'websocket': AuthMiddlewareStack(URLRouter(ws_urlpatterns))
})
```

I need a solution that will allow me to stream images from cv2 and in the same time use django channels or something Similar. Thanks you all!

**Comment by Simanas** [comment]
Same need here!

**Comment by carltongibson** [comment]
This will need to be fixed in Django. (Channels will drop the old `AsgiHandler` this summer, in favour of Django's, which has been available since Django v3.0.) 

Relevant tickets are: 

* [#33735 (Add Asynchronous Responses for Use With an ASGI Server) – Django](https://code.djangoproject.com/ticket/33735)
* [#32798 (StreamingHttpResponse Raises SynchronousOnlyOperation in ASGI Server) – Django](https://code.djangoproject.com/ticket/32798)

Both of these are 🎯Django 4.2.

**Comment by agusmakmun** [comment]
Any updates for this? I'm facing the same issue.
Using Django 4.12, Uvicorn, ASGI, Nginx, Python 3.10

This is my code:

```python
try:
    response = requests.post(
        settings.EXPLAIN_TO_ME_API_URL,
        headers={
            "Authorization": f"Token {settings.XXXX}",
            "Content-Type": "application/json",
        },
        json={"command": command},
        stream=True,
        timeout=60 * 5,
    )
    if response.status_code == status.HTTP_200_OK:
        # Define a generator function to yield chunks of data
        # https://github.com/adamchainz/django-browser-reload/blob/main/src/django_browser_reload/views.py#L166
        # https://blog.pecar.me/django-streaming-responses
        async def generate_chunks() -> AsyncGenerator[bytes, None]:
            for line in response.iter_lines():
                yield line + b"\n"

        stream_response = StreamingHttpResponse(
            generate_chunks(),
            content_type="text/event-stream",
        )
        # Disable caching for client
        stream_response["Cache-Control"] = "no-cache"
        # Disable buffering in nginx
        stream_response["X-Accel-Buffering"] = "no"
        # Set a content-encoding to bypass GzipMiddleware etc.
        stream_response["Content-Encoding"] = "identity"
        return stream_response
```

And this one is my `nginx.conf`;

```
location /api/ai-tools {
    proxy_pass http://ai-tools:8005;
    proxy_set_header Host localhost:3001;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_redirect off;
}
```

**Comment by carltongibson** [comment]
Update Django, where improvements here have been implemented.

**Comment by agusmakmun** [comment]
Yes, I'm specifically using `django==4.2.13` where the `__aiter__` has been updated, but still not resolve.

**Comment by agusmakmun** [comment]
The weird things is, when adding the `sleep(1)` it's working but slow as it using 1 seconds for each line.

```python
async def generate_chunks() -> AsyncGenerator[bytes, None]:
    for line in response.iter_lines():
        yield line + b"\n"
```

to;

```python
async def generate_chunks() -> AsyncGenerator[bytes, None]:
    for line in response.iter_lines():
        yield line + b"\n"
        await asyncio.sleep(1)
```

**Comment by carltongibson** [comment]
You need to use an async iterator (`async for`) in order to release control back to the event loop no?

**Comment by agusmakmun** [comment]
hmm, I'm facing the issue when implementing using `async for`;

```python
async def generate_chunks() -> AsyncGenerator[bytes, None]:
    async for line in await sync_to_async(response.iter_lines)():
        yield line + b"\n"
```

Error:

```
File "/usr/local/lib/python3.10/site-packages/asgiref/sync.py", line 520, in thread_handler
     return func(*args, **kwargs)
TypeError: 'async_generator' object is not iterable
```

**Comment by carltongibson** [comment]
Ok, but the point is you're using a sync iterator when you need to using an async iterator to return control to the event loop I think. 

See the Django docs for Streaming Responses here https://docs.djangoproject.com/en/5.0/ref/request-response/

**Comment by fengjian1993** [comment]
> ```python
> 0.0001
> ```

hi, i am now Django==4.1.13 and i could not upgrade to 4.2 because i need mysql 5.7. for this issue i copy CLASS StreamingHttpResponse and use it in my code:

async def async_generator():
    for i in range(5):
        await asyncio.sleep(0.0001)
        yield str(i)

def sse_test(request):
    stream_response = StreamingHttpResponse(
        async_generator(),
        content_type="text/event-stream",
    )
    return stream_response

but error shows:
Traceback (most recent call last):
  File "/root/anaconda3/envs/archery/lib/python3.11/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/root/anaconda3/envs/archery/lib/python3.11/wsgiref/handlers.py", line 183, in finish_response
    for data in self.result:
  File "/root/anaconda3/envs/archery/lib/python3.11/site-packages/django/utils/text.py", line 350, in compress_sequence
    for item in sequence:
TypeError: 'async_generator' object is not iterable

any advice for me? thanks ;)

**Comment by carltongibson** [comment]
@fengjian1993 This required changes in Django's ASGI handler too. You'll need to backport that as well. 

(I'd suggest you're better off updating to supported versions of MySQL and then Django...)

**Comment by fengjian1993** [comment]
> @fengjian1993 This required changes in Django's ASGI handler too. You'll need to backport that as well.
> 
> (I'd suggest you're better off updating to supported versions of MySQL and then Django...)

thanks for the reply ;)
i have upgrade to django 4.2 and my code:

async def stream_response_generator():
  count = 0
      start_time = time.time()
      while time.time() - start_time < 5:
          await asyncio.sleep(1)
          count += 1
          data = f'data: {count}\n\n'
          yield data

def sse_test(request):
  stream_response = StreamingHttpResponse(
  stream_response_generator(),
  content_type="text/event-stream",
  )
  return stream_response
  
  still same issue and it occur error:
  /root/anaconda3/envs/archery/lib/python3.11/site-packages/django/http/response.py:514: Warning: StreamingHttpResponse must consume asynchronous iterators in order to serve them synchronously. Use a synchronous iterator instead.
  warnings.warn(

**Comment by fengjian1993** [comment]
> @fengjian1993 This required changes in Django's ASGI handler too. You'll need to backport that as well.
> 
> (I'd suggest you're better off updating to supported versions of MySQL and then Django...)

in my business code it shows error:
  File "/root/anaconda3/envs/archery/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/archery/lib/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/archery/lib/python3.11/site-packages/django/middleware/gzip.py", line 20, in process_response
    if not response.streaming and len(response.content) < 200:
           ^^^^^^^^^^^^^^^^^^
AttributeError: module 'django.http.response' has no attribute 'streaming'

**Comment by fengjian1993** [comment]
> ```python
> async def generate_chunks() -> AsyncGenerator[bytes, None]:
>             for line in response.iter_lines():
>                 yield line + b"\n"
> 
>         stream_response = StreamingHttpResponse(
>             generate_chunks(),
>             content_type="text/event-stream",
>         )
>         # Disable caching for client
>         stream_response["Cache-Control"] = "no-cache"
>         # Disable buffering in nginx
>         stream_response["X-Accel-Buffering"] = "no"
>         # Set a content-encoding to bypass GzipMiddleware etc.
>         stream_response["Content-Encoding"] = "identity" # or "no"
>         return stream_response
> ```

hi, i upgrade to django 4.2, still same issue can you help me with it?

**Comment by carltongibson** [comment]
`StreamingHttpResponse must consume asynchronous iterators in order to serve them synchronously. Use a synchronous iterator instead.
warnings.warn(`

You need to use ASGI to properly serve async streaming responses. Please see the Django docs.
