### ISSUE TITLE
Question: Is there any auto generate Websocket documentation for channels??

### ISSUE THREAD

**Issue by usefss** [django/channels#1762]
We want to develop a complex messaging communication over sockets, clearly, we want a simple to use documentation tool like Drf-spectacular for the Django rest framework.  
For example, writing a class-based event catcher for {'event': 'ehhh', 'msg': 'yoo'} message, and documenting it automatically...
Consider this class:
```
    class EhhhEvent(SocketEventHandler):
        request_serializer = EhhhRecieverSerializer
        response_serialzier = EhhhResponseSerializer
        def handle(self, event):
            # serialize request and return response 
            # (we can send serializer exceptions through socket too)
```
Solution one:  using parent class to find out Events and generate schema for something like [https://www.asyncapi.com/](https://www.asyncapi.com/), then using the tool to see the documentation.
Solution two: using rest_framework and altering Drf-spectacular itself to be compatible with channels...  

I am thinking about doing it in an open-source way because I think it is needed so much in real life any advice?? or can you help me if there are any replacements for this use case...

**Comment by johnthagen** [comment]
Related: https://github.com/hishnash/djangochannelsrestframework

**Comment by johnthagen** [comment]
Related feature requests:

- https://github.com/LostMoa/djangochannelsrestframework/issues/116
- https://github.com/tfranzel/drf-spectacular/issues/667
