### ISSUE TITLE
TypeError: An asyncio.Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by dima-dmytruk23** [django/channels#1773]
*Requirements*
- Python 3.8
- asgiref                           3.2.0
- channels                          2.4.0
- channels-redis                    2.4.2
- Django                            3.0.9, 
- gunicorn                          20.1.0
- redis                             3.5.3
- uvicorn                           0.11.5
- websockets                        8.1

I run channels as `gunicorn -w 5 -b 0.0.0.0:8000 --log-level debug -k uvicorn.workers.UvicornWorker config.asgi:application`. 
Also I have `nginx` as proxy-server.

*Logs*
![image](https://user-images.githubusercontent.com/76110682/145238847-d7e64f1e-0c7d-4c3e-8bd8-541aab6244b6.png)

```python
class TokenAuthMiddleware:
 
    def __init__(self, inner):
        self.inner = inner
 
    def __call__(self, scope):
        return TokenAuthMiddlewareInstance(scope, self)
 
 
class TokenAuthMiddlewareInstance:
    def __init__(self, scope, middleware):
        self.middleware = middleware
        self.scope = dict(scope)
        self.inner = self.middleware.inner
 
    async def __call__(self, receive, send):
        try:
            token_key = (dict((x.split("=") for x in self.scope["query_string"].decode().split("&")))).get(
                "token", None
            )
        except ValueError:
            token_key = None
        if token_key is None:
            self.scope["user"] = AnonymousUser()
        else:
            token_data = await get_token_data(token_key)
            self.scope["user"] = await get_user(token_data["user_id"])
 
        inner = self.inner(self.scope)
        return await inner(receive, send)
````

**Comment by YegorDB** [comment]
Working version of your TokenAuthMiddleware could look like this
```python
class TokenAuthMiddleware:
 
    def __init__(self, inner):
        self.inner = inner
 
    async def __call__(self, scope, receive, send):
        instance = TokenAuthMiddlewareInstance(scope, self)
        return await instance(receive, send)


class TokenAuthMiddlewareInstance:
    ...

    async def __call__(self, receive, send):
        ...

        # inner = self.inner(self.scope)
        # return await inner(receive, send)
        return await self.inner(self.scope, receive, send)
```
Also it is't necessarily to use TokenAuthMiddlewareInstance. All logic you need could be handled by TokenAuthMiddleware.

PS
If you are interested of auth token middleware you are welcome to [discussion](https://github.com/django/channels/discussions/1771)

**Comment by dima-dmytruk23** [comment]
> Working version of your TokenAuthMiddleware could look like this
> 
> ```python
> class TokenAuthMiddleware:
>  
>     def __init__(self, inner):
>         self.inner = inner
>  
>     async def __call__(self, scope, receive, send):
>         instance = TokenAuthMiddlewareInstance(scope, self)
>         return await instance(receive, send)
> 
> 
> class TokenAuthMiddlewareInstance:
>     ...
> 
>     async def __call__(self, receive, send):
>         ...
> 
>         # inner = self.inner(self.scope)
>         # return await inner(receive, send)
>         return await self.inner(self.scope, receive, send)
> ```
> 
> Also it is't necessarily to use TokenAuthMiddlewareInstance. All logic you need could be handled by TokenAuthMiddleware.
> 
> PS If you are interested of auth token middleware you are welcome to [discussion](https://github.com/django/channels/discussions/1771)

@YegorDB Thnx. You added `receive` and `send` parameters to `TokenAuthMiddleware .__ call__`. It won't break anything?

**Comment by YegorDB** [comment]
> You added `receive` and `send` parameters to `TokenAuthMiddleware.__ call__`. It won't break anything?

Since it is similar to BaseMiddleware [__call__](https://github.com/django/channels/blob/main/channels/middleware.py#L18) method  it would work normally I guess.

**Comment by dima-dmytruk23** [comment]
> > You added `receive` and `send` parameters to `TokenAuthMiddleware.__ call__`. It won't break anything?
> 
> Since it is similar to BaseMiddleware [**call**](https://github.com/django/channels/blob/main/channels/middleware.py#L18) method it would work normally I guess.

@YegorDB But I use channels v2.4.0)
https://github.com/django/channels/blob/56bb2b9afc9207d19a66d78f39a8e337cde93551/channels/middleware.py#L21

**Comment by YegorDB** [comment]
> But I use channels v2.4.0)

Try this out. It made like [AuthMiddleware](https://github.com/django/channels/blob/56bb2b9afc9207d19a66d78f39a8e337cde93551/channels/auth.py#L149) from same commit.
```python
from django.contrib.auth.models import AnonymousUser

from channels.auth import UserLazyObject
from channels.middleware import BaseMiddleware


class AuthTokenMiddleware(BaseMiddleware):

    def populate_scope(self, scope):
        if "user" not in scope:
            scope["user"] = UserLazyObject()

    async def resolve_scope(self, scope):
        scope["user"]._wrapped = await self.get_user(scope)

    async def get_user(self, scope):
        # your initial post logic (slightly changed)
        try:
            token_key = (dict((x.split("=") for x in self.scope["query_string"].decode().split("&")))).get(
                "token", None
            )
        except ValueError:
            return AnonymousUser()
        token_data = await get_token_data(token_key)
        user = await get_user(token_data["user_id"])
        return user
```
