### ISSUE TITLE
Django 4 support

### ISSUE THREAD

**Issue by astrikov-d** [django/channels#1781]
Hello channels team. 
Do you have any plans to support Django 4? 
Thanks.

**Comment by carltongibson** [comment]
Is there something specific that's not working?

**Comment by astrikov-d** [comment]
@carltongibson for now everything works fine, but, as I understand, there is no official support for Django 4. If you think that it will work fine, then let's close this issue :) Thanks.

**Comment by carltongibson** [comment]
@astrikov-d If you'd like to make a PR adding what's missing to declare _official support_ that'd be welcome.

**Comment by carltongibson** [comment]
@astrikov-d This would start filling the missing line in the _tox_ config: 

https://github.com/django/channels/blob/6af1bc3ab45f55e3f47d0d1d059d5db0a18a9581/tox.ini#L18

We're testing against `main` which will be Django 4.1, but 4.0 itself needs adding.

**Comment by carltongibson** [comment]
Begun this in #1782

**Comment by johnthagen** [comment]
This can be closed as of #1782 and #1816
