### ISSUE TITLE
Channels 3 Memory Leak / Overconsumption

### ISSUE THREAD

**Issue by alamorre** [django/channels#1789]
Every Django Channels project, including the Channels Tutorial project, has a memory leak. 

Specifically, the `MEM %` used in a Docker image keeps rising, and it assumes you run them on Daphne.

To reproduce, I Dockerized the Tutorial project in [this repo](https://github.com/alamorre/channels_3_leak) and the memory consumption issues are still present.

Steps to reproduce:

```
git clone https://github.com/alamorre/channels_3_leak.git
cd channels_3_leak
docker-compose build
docker-compose up -d
docker stats channels_3_leak_web_1
```

Stress test with the following command:

```
brew install chrome-cli
for i in {1..100}; do chrome-cli open http://127.0.0.1:8000/chat/lobby/; done
```

The `MEM %` will keep going up!

Personally, it starts around `2.5%` and will go up to `4%` with lots of tabs open. Then never goes back down once the tabs close.

Again, this project precisely follows the Tutorial and Deploying sections from the Docs. And it also seems like a popular discussion amongst users.

**Comment by alamorre** [comment]
You can stress test the project yourself by running `for i in {1..80}; do chrome-cli open http://127.0.0.1:8000/chat/lobby/; done` in another terminal 👍  Watch `MEM %` keep going up!!

**Comment by carltongibson** [comment]
Do you have any insight as to where the leak may be?

**Comment by Archmonger** [comment]
Not sure where the leak is occurring in the stack, but I'm suspecting I've detected this leak in my deployment scenarios as well.

**Comment by carltongibson** [comment]
> ...will go up to 4%... 

If it's stable at 4%, rather than keeps going up, it would look like Python's GC deciding to step in, rather than a memory leak _per se_. Apps (Python apps) often consume an amount of memory that doesn't fall from a stable level. 

It would be good if someone could try to identify something more concrete.

**Comment by Archmonger** [comment]
In my scenario, memory usage starts at around ~300 MB for 3 Hypercorn workers. Over time, it inflates to ~600 MB and sits there (in a range of +-30 MB).

**Comment by alamorre** [comment]
Once these deps were upgraded the mem leak went away!

```
asgiref==3.5.0
daphne==3.0.2
Django==3.2.11
```
