### ISSUE TITLE
Deploying channels with azure cache for redis as host - redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by vishwakarma0** [django/channels#1806]
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

-  OS used is Ubuntu
- packages used
    channels-redis==3.3.1
    hiredis==2.0.0
    redis==2.10.6
    channels==3.0.4
    channels-redis==3.3.1
When running with the localhost it runs smoothly, but when I try to use azure cache for redis which is password protected, it throws the below error
`redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
`
channel configuration in settings.py
`CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [("redis://:mypassword@mysite.redis.cache.windows.net:6380/0")],
                    },
        },
    }`

It would mean a lot, if anyone can provide with a source or docs that could be helpful

**Comment by carltongibson** [comment]
@vishwakarma0 Grrr. Sorry, no idea... — it's an Azure Redis connection issue. 

Do you need to use the `'rediss://...'` scheme for SSL maybe? 🤔

This isn't something we can help you with here I'm afraid. Good luck!
