### ISSUE TITLE
drf simple-jwt auth middleware

### ISSUE THREAD

**Issue by nasir733** [django/channels#1811]
Hi I have written an Auth middleware for one of my projects that uses Channels Can I add that middleware to The channels itself 
https://django-rest-framework-simplejwt.readthedocs.io/en/latest/
let me know I would love to contribute to this package @carltongibson  @andrewgodwin

**Comment by nasir733** [comment]
https://stackoverflow.com/questions/65297148/django-channels-jwt-authentication/67147270#67147270

**Comment by carltongibson** [comment]
HI @nasir733 — very happy to take add a link to your package on the Community Projects page. 

* [Community Projects — Channels 3.0.4 Documentation](https://channels.readthedocs.io/en/stable/community.html)

I'll close this pending a PR for that. 
Thanks!
