### ISSUE TITLE
Authentication Hash Problem

### ISSUE THREAD

**Issue by MrR1pp3r** [django/channels#1823]
Hi Dev,
I'm use Django 4.0.3 & i see some error.. well we can;t say error but its bug

Django = 4.0.3
Linux x64
![1](https://user-images.githubusercontent.com/48425460/157379188-5a51997c-14c7-4d0a-94aa-f9d2ce3df6ef.png)
In this.. Create user generate password field with encryption.
So, we can auth & login successfully

![2](https://user-images.githubusercontent.com/48425460/157379271-e092647c-e553-44fe-9ec5-a9b004a228e5.png)

Column 2 & 3 created by python manage.py shell
Column 1 created by view.py

Default User.object.create_user() in view.py dont make hash password & save plain text.. 
So, it's unsuccessful when we do login.

Please Fix

**Comment by almazkun** [comment]
Good day!

Proper way of setting password for Django User is: 'user.set_password("password")'and 'user.save()'. This way the password will be hashed. 

For more information: https://stackoverflow.com/questions/30466191/django-set-password-isnt-hashing-passwords

**Comment by MrR1pp3r** [comment]
> Good day!
> 
> Proper way of setting password for Django User is: 'user.set_password("password")'and 'user.save()'. This way the password will be hashed.
> 
> For more information: https://stackoverflow.com/questions/30466191/django-set-password-isnt-hashing-passwords


okay.. i use make_password 😅😅
but Django need to be fix this.. like if we use shell then work & if we use in view.py then we need to add extra stuff.. not fair

**Comment by MrR1pp3r** [comment]
> Good day!
> 
> Proper way of setting password for Django User is: 'user.set_password("password")'and 'user.save()'. This way the password will be hashed.
> 
> For more information: https://stackoverflow.com/questions/30466191/django-set-password-isnt-hashing-passwords

Nope.. I try this.. not working in Django 4.0.3. Also check my post again.. for better understanding

**Comment by almazkun** [comment]
@MrR1pp3r, could you please take a look at this example: [git@github.com:almazkun/django_password_hash.git](https://github.com/almazkun/django_password_hash)?

There are 2 endpoint to create a user. It is saving hashed passwords. 

Or please share your code. It will be easier to debug. 

Thank you! =)

**Comment by MrR1pp3r** [comment]
@almazkun, i see your repo.. i use the same method
here u go
![user](https://user-images.githubusercontent.com/48425460/159628841-ed7077bf-35c2-4e18-ad7c-7b89e425df27.png)
i send you video too.. wait for 10 minutes

**Comment by MrR1pp3r** [comment]
https://user-images.githubusercontent.com/48425460/160585005-6c6c3d36-c533-44fe-a0d7-0f5b1bbf3886.mp4

**Comment by MrR1pp3r** [comment]
> @MrR1pp3r, could you please take a look at this example: [git@github.com:almazkun/django_password_hash.git](https://github.com/almazkun/django_password_hash)?
> 
> There are 2 endpoints to create a user. It is saving hashed passwords.
> 
> Or please share your code. It will be easier to debug.
> 
> Thank you! =)

![carbon](https://user-images.githubusercontent.com/48425460/161377457-bb21d949-d669-44c4-b47c-3816c6954fc6.png)

**Comment by almazkun** [comment]
Good day! =) 

Maybe this is the problem:
<img width="475" alt="Screen Shot 2022-04-04 at 6 50 27 PM" src="https://user-images.githubusercontent.com/20808565/161519463-856f551b-ca78-4344-8e06-08027d9903bf.png">
Could you try this instead: `user.set_password(raw_password)`?

like here: https://github.com/almazkun/django_startapp/blob/05eb1f9b4177346fb92170b3651ca5b5a756558d/apps/accounts/models.py#L23

**Comment by MrR1pp3r** [comment]
> Good day! =)
> 
> Maybe this is the problem: <img alt="Screen Shot 2022-04-04 at 6 50 27 PM" width="475" src="https://user-images.githubusercontent.com/20808565/161519463-856f551b-ca78-4344-8e06-08027d9903bf.png"> Could you try this instead: `user.set_password(raw_password)`?
> 
> like here: https://github.com/almazkun/django_startapp/blob/05eb1f9b4177346fb92170b3651ca5b5a756558d/apps/accounts/models.py#L23

I try every think.. set_password(password), make_hash(password) & user.password = make_hash(password)

I find the solution but.. i need to call create_user() twice ....


First, models.py where i make custom user method.. & the next call in Serializer.. when create user.

Actually i use ModelSerializer So, i predict.. i need to just use META & FIELDS,, but later i override CREATE() & BOOOOOM its working. 

`def create(self, validated_data):
    username = validated_data.pop('username')
    password = validated_data.pop('password')
   
   user = get_user_model().objects.create_user(username=username, **validated_data)
   user.set_password(password)
   user.save()
   return user
`

**Comment by almazkun** [comment]
Would you mind closing the issue? :)
