### ISSUE TITLE
Current version on Pypi is incompatible with Django 4.0+

### ISSUE THREAD

**Issue by d9pouces** [django/channels#1859]
The current version available on Pypi, channels-3.0.4 still use the providing_args keyword for signals.
Since this keyword has been removed from Django 4.0+ (December 2021), you cannot use channels with an up-to-date Django.

Is a version 3.0.5 planned for Pypi?

**Comment by carltongibson** [comment]
Here you go: https://pypi.org/project/channels/3.0.5/

Let me know if you hit issues. Thanks.
