### ISSUE TITLE
Add contributing document

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#186]
Somehow tie it into django status?

**Comment by lwm** [comment]
Was this covered in https://github.com/django/channels/commit/5969bbd0f30953f1d55cb63b524e7d1ab3ae1dc3 and the now existing [CONTRIBUTING.rst](https://github.com/django/channels/blob/master/CONTRIBUTING.rst) or?

**Comment by andrewgodwin** [comment]
Yup.
