### ISSUE TITLE
Broken readthedocs links in CHANGELOG.txt

### ISSUE THREAD

**Issue by marcosox** [django/channels#1864]
Hello,
[the release notes file](https://github.com/django/channels/blob/main/CHANGELOG.txt) currently reads:

> Please see the `Version 3.0.5 release notes
<https://channels.readthedocs.io/en/latest/releases/3.0.5.html>`_ for full
details.

But that url returns a 404. The correct URL is `https://channels.readthedocs.io/en/stable/releases/3.0.5.html`

I can fix this, but I'm not sure if that URL is populated by a script, or a simple `sed s/latest/stable/` is enough

**Comment by carltongibson** [comment]
Thanks for the report @marcosox. 

For some reason 🤔 [RTD didn't build the last commits to `main`](https://readthedocs.org/projects/channels/builds/), which is the `latest` version. 

I've just run the build for that. It's working now. 

🤔
