### ISSUE TITLE
Docs kafka-integration broken link.

### ISSUE THREAD

**Issue by nrbnlulu** [django/channels#1866]
### Reproduce
___ 
https://channels.readthedocs.io/en/stable/community.html

Try to open kafka-integration

**Comment by carltongibson** [comment]
Yes... Hmmm.... the user @aryan340 seems to have disappeared. 🤔

**Comment by carltongibson** [comment]
Renamed to @aryaniyaps I think. But the updated gist URL still 404s... 

https://gist.github.com/aryaniyaps/da071d027050cfe0a03df3b500f2f44b

@aryaniyaps — Is the guide still available? thanks!
