### ISSUE TITLE
Planning Channels v4.0

### ISSUE THREAD

**Issue by carltongibson** [django/channels#1898]
🚨 Testing wanted: see the comment below 🚨

I've begun work on the next major version, which will be v4.0. 
I'm looking to release early-September 2022. 

The main highlights will be: 

* Removal of the old `AsgiHandler`, and related code. All of this now lives in Django, and you should be using that. 
* Removal of support for ASGI v2 double-callables. Your apps should all be ASGI v3 single-callables by now. 
* A move of the `runserver` command to Daphne, so that folks using other ASGI servers don't have that import overhead to use Channels. 
* And then various tidy-ups and other fixes that we've got time for. 

The hope is this leaves Channels nice and tight as the Consumers, Channel Layer stuff, and not too much else. The use-case is: "_I want to do Websockets, or lower-level ASGI with my Django app_" It should be that we can evolve through point-releases for a while from now after this. 🤞

Matching updates to Daphne and `channels_redis` will come at the same time. 

See the recent additions to [Closed Pull Requests](https://github.com/django/channels/pulls?q=is%3Apr+is%3Aclosed) and the [WIP CHANGELOG](https://github.com/django/channels/blob/main/CHANGELOG.txt) until I can draft the full release announcements for the details.   

I've begun with the code changes. You'll need to install the repos from `main` in order to test (e.g. the `runserver` move) Any feedback appreciated. 

Next up, I want to go through the docs and tutorials and get those into place, then I'll look at updating the packaging, and we'll see where we're at.

**Comment by carltongibson** [comment]
OK, I've release a beta 4.0.0b1, and there's matching betas for Daphne and channels-redis too:

* https://pypi.org/project/channels/4.0.0b1/
* https://pypi.org/project/daphne/4.0.0b1/
* https://pypi.org/project/channels-redis/4.0.0b1/ 

Testing this is appreciated, particularly with the new optional `daphne` dependency:

    pip install 'channels[daphne]==4.0.0b1'

... and adding `daphne` to `INSTALLED_APPS` for the `runserver` implementation: 

```
    INSTALLED_APPS = [
        'daphne',
        ...
    ]
```

As well as running without Daphne, for those of you who wanted that. 

Please see the above comment for the links to changes, and the closed PRs. 

Goal now is to pick up any issues, knock off a few extras, and do final releases for ≈14th Sept.

**Comment by DmytroLitvinov** [comment]
I have been using channels-redis==4.0.0b1 for ~2-3 weeks in production and it works fine :+1:

**Comment by collinanderson** [comment]
I just tried `pip install 'channels[daphne]==4.0.0b1'` and it seemed to work fine for me and upgrade daphne. I got the warning when I put it below staticfiles and it went away when I moved it above.

I'll start using `4.0.0b1` in production for an internal dashboard (without daphne, thank you! :)

```
Django version 4.2.dev20220825080357 ....
Starting ASGI/Daphne version 4.0.0b1 development server
```

I did notice on pypi it says "The author of this package has not provided a project description". Not sure if that's an issue or not. I do see it's been blank since 1.1, (1.0.3 was the last to have a description) so probably unrelated.
https://pypi.org/project/channels/4.0.0b1/

**Comment by carltongibson** [comment]
Hey @collinanderson super, thanks. 

Yes, something is amiss on PyPI with the rendered Readme. 🤔

**Comment by DmytroLitvinov** [comment]
Hi everyone,
A small update after [my previous update](https://github.com/django/channels/issues/1898#issuecomment-1227372366). 

We have installed [channels==4.0.0b1](https://pypi.org/project/channels/4.0.0b1/) approximatly 1 week ago (when [compatibility with channels-redis beta version was fixed](https://github.com/django/channels_redis/issues/324) and we are running smoothly in production.

**Comment by carltongibson** [comment]
Great thanks @DmytroLitvinov. 


I had a slight delay this week but am working on the releases and they'll be out shortly. (It's DjangoCon this week coming up so I should have a moment to sit down and do it at some point. 😜)

**Comment by lunika** [comment]
Hi,
If we are not using daphne in production, we just have to install it in developement for the `runserver` usage ? Same thing for `INSTALLED_APPS` ? It's only needed to do that in the environment using daphne with the `runserver` ?

Thanks

**Comment by carltongibson** [comment]
@lunika that sounds right yes.
