### ISSUE TITLE
took too long to shut down and was killed

### ISSUE THREAD

**Issue by kreimben** [django/channels#1903]
I know, I know, This question is too common but That's not kind of that.

The problem is, Whenever I'm trying to login to django admin, There is very long loading and nginx spit 504 error!
and command line said, `2022-08-16 03:25:25,053 WARNING  Application instance <Task pending name='Task-1' coro=<ProtocolTypeRouter.__call__() running at /usr/local/lib/python3.10/site-packages/channels/routing.py:71> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.10/asyncio/futures.py:384, Task.task_wakeup()]>> for connection <WebRequest at 0x7f8d7e7d3190 method=POST uri=/admin/login/?next=/admin/ clientproto=HTTP/1.0> took too long to shut down and was killed.`

I have only one consumer about chatting and I even added [`raise StopConsumer()`](https://github.com/Team-Discipline/Xlack-Backend/blob/b21fdb220f9a3a53e2cda2dd277010f68a300931/chat/consumers.py#L71)

What should I do further?
Please help...

**Comment by carltongibson** [comment]
Can you put together a minimal project that reproduces this issue?

**Comment by kreimben** [comment]
https://github.com/Team-Discipline/Xlack-Backend/tree/deploy
Here it is.
This project is not big enough so I submitted this as whole.

**Comment by carltongibson** [comment]
@kreimben — That's not really what I'd call a _minimal reproduce_... 🤔

At the least, exact steps to follow to get the error would help (otherwise I don't have time to guess what I'm meant to do) but there seems like way too much code there to be able to show that it's an issue in Channels. 

Are you able to reduce it please? 
Thanks.

**Comment by kreimben** [comment]
Oh I didn't know, Thanks to heads me up.

OK.
First, I have a chat consumer and set routing as many examples like
```
websocket_urlpatterns = [
    re_path(r'ws/chat/(?P<channel_id>\w+)/$', consumers.ChatConsumer.as_asgi()),
]
```

and Second, `asgi.py` covered about above url patterns.
```
application = ProtocolTypeRouter({
    'http': get_asgi_application(),
    'websocket': AuthMiddlewareStack(
        URLRouter(
            chat.routing.websocket_urlpatterns
        )
    )
})
```

And I built docker image.

Third, Whenever I'm trying to login to django admin (when I click login button), My site is not responding as far as it's connection timeout and nginx spit 504.

**Running the image in local normally worked.**

I have many of containers about django (without channels) and They work super normally with same nginx settings.

The problem is "I don't know why django admin is not able to login.".
because `took too long to shut down and was killed.` is supposed to be problem of my chat consumer or etc but not django admin.

I didn't fix anything about django admin.

My question is "Why I can't login to django admin whereas my terminal said about problem to channels whenever I run docker image on nginx."

**Comment by JshPngnbn** [comment]
Did you find any solution?

**Comment by kreimben** [comment]
> Did you find any solution?

I just deployed to heroku instead of deploying on my nginx.

**Comment by huyxdong** [comment]
Do we have any "real" solution?

**Comment by carltongibson** [comment]
This looks like a docker/Nginx issue rather than Channels per se. It needs someone to dig into that. 

Maybe wrap your ASGI in a middleware (another ASGI app) that prints at various points to verify the lower level communications. 

Short of something concrete it's hard to know what to say.
