### ISSUE TITLE
RuntimeError due to setting multiprocessing start method

### ISSUE THREAD

**Issue by adamchainz** [django/channels#1921]
Regression in #1906, found whilst testing beta release.

Setting the multiprocessing start method at import time is not supported if it has already been set, leading to a `RuntimeError`:

```
ImportError: Failed to import test module: example.tests.test_something
Traceback (most recent call last):
  File "/.../lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/.../lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/.../example/core/tests/test_something.py", line 5, in 
<module>
    from channels.testing import WebsocketCommunicator
  File "/.../lib/python3.10/site-packages/channels/testing/__init__.py", line 4, in 
<module>
    from .live import ChannelsLiveServerTestCase  # noqa
  File "/.../lib/python3.10/site-packages/channels/testing/live.py", line 13, in 
<module>
    multiprocessing.set_start_method("fork")
  File "/.../lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
Error:     raise RuntimeError('context has already been set')
```

This is in a test process that has the start method already set to `fork` (Django 4.0, compatibility as per [my post](https://adamj.eu/tech/2020/07/21/how-to-use-djangos-parallel-testing-on-macos-with-python-3.8-plus/)).

I would suggest that instead of trying to set the start method, the test case should check the start method with `get_start_method(allow_none=True)`. If it’s `None`, it could be set to `fork`, else the test case should fail. This would also be better done later than import time, to avoid importing having surprising side effects, perhaps in `setUpClass`.

**Comment by carltongibson** [comment]
Thanks @adamchainz. Give me a moment to get my head above water again and we'll look at this. 🏅

**Comment by adamchainz** [comment]
Of course, take your time.

**Comment by carltongibson** [comment]
Fixed by https://github.com/django/daphne/pull/440 and #1921

**Comment by carltongibson** [comment]
Thanks for this @adamchainz
