### ISSUE TITLE
Spelling mistake in release notes

### ISSUE THREAD

**Issue by mzoeller** [django/channels#1935]
In release notes for 4.0.0, i.e. https://channels.readthedocs.io/en/latest/releases/4.0.0.htm "daphne" is spelled wrong:
`pip install -U 'channels[dapne]' channels-redis`
it should be
`pip install -U 'channels[daphne]' channels-redis`

**Comment by vanschelven** [comment]
Fixed in the source code, but as of today this persists in the version which is here: https://channels.readthedocs.io/en/stable/releases/4.0.0.html

**Comment by vanschelven** [comment]
I should have probably tagged @carltongibson in that last remark

**Comment by carltongibson** [comment]
How about the `latest`: https://channels.readthedocs.io/en/latest/releases/4.0.0.html

**Comment by vanschelven** [comment]
Fair enough... to bad my favorite search engine led me to te other one but
I see how updating that one would be a pain

**Comment by carltongibson** [comment]
`stable` is linked to the tag of the last release. I'm pottering on the next one now so... 🤷
