### ISSUE TITLE
Make channels runserver easier to inherit from

### ISSUE THREAD

**Issue by eukreign** [django/channels#194]
It would be really nice if there was a simple way to integrate a custom interface handler into the reactor loop created by daphne Server().run() from channels' runserver command.

**Comment by andrewgodwin** [comment]
By interface handler you mean interface server, as in another server? Shouldn't be too hard, but it would have to run using Twisted to make any sense, so that seems less than ideal extensibility wise when running the server alongside works the same.

Do you have a concrete example of where this might be useful?

**Comment by eukreign** [comment]
Possibly something like:
```
python manage.py runserver --add-interface=module.func_name
```

Then daphne will add this function to the reactor, with lets say a 2 second initial time out, after line 50 in server.py: https://github.com/andrewgodwin/daphne/blob/master/daphne/server.py#L50

It would probably make sense to support multiple `--add-extra-handler=`s.

Another option is instead of adding the `module.func_name` directly to reactor, you could instead just call the function right away (passing in the reactor for convenience) and it would do any reactor registration on its own.

Another option is to split the `inner_run` function so that the channel setup and the call to Server.run() are separate. This way someone can inherit from the `channels.manage.runserver.Command` and add whatever code they need with access to the channel_layer but before the reactor starts running.

https://github.com/andrewgodwin/channels/blob/master/channels/management/commands/runserver.py#L32

For most simple cases I think this would be very convenient.

**Comment by andrewgodwin** [comment]
I'd much rather make it easier to inherit from than add special command line arguments for adding things in; that way people can do setup however they like.

**Comment by globophobe** [comment]
+1 for this. While using Twisted/Autobahn in production, I've found it useful to use reactor.callLater instead of cron. Also, it's been useful to connect a Twisted server via websocket with another Twisted server.

**Comment by eukreign** [comment]
I've had to take a break from integrating this in my project but it is still on the radar. Once I have a working implementation of this I can do a better proposal/suggestion based on actual experience.

**Comment by andrewgodwin** [comment]
Channels 2 has a much cleaner runserver that you can definitely do a bit more with as long as you're still doing ASGI, so closing.
