### ISSUE TITLE
404 not found broken pipe after upgrading to 4.0.0

### ISSUE THREAD

**Issue by bluesurfer** [django/channels#1940]
After upgrading to 4.0.0. the channel layer has stop working. I keep getting 404 and "broken pipe" errors when connecting to the Websockets.

To reproduce the issue have a look at [this](https://github.com/bluesurfer/django-channels-example) test project. 

Downgrading to 3.x.x fix the issue.

**Comment by carltongibson** [comment]
@bluesurfer can you bisect your find the issue or reduce the example at all? Do you have any indication of the issue? Thanks.

**Comment by bluesurfer** [comment]
@carltongibson thanks for replying... ehm the problem I'm facing is macroscopic to me :) 
Connecting to any WebSocket result in "404 not found broken pipe" (I am using `redis` as channel layer).

I fork the `testdrivenio` example project because it resemble my situation and it looked to me small enough (it's the same good old chat app). The [requirements](https://github.com/testdrivenio/django-channels-example/compare/main...bluesurfer:django-channels-example:main) are the only thing I changed from the original project

If you visit http://127.0.0.1:8000/chat/ and send a message you should get the 404 errors. Same issue with a bigger project of mine and the solution is the same: downgrading.

I also tried upgrading `redis-server` but it changes nothing (from 6.2.4 to 7.0.5).

**Comment by carltongibson** [comment]
So this is a channels redis issue? v4 changes to redis-py, but without being able to sit on your machine it's hand to say more...

**Comment by bluesurfer** [comment]
@carltongibson yes, probably it's a `channels-redis` issue. But is the test project working on your machine?

**Comment by carltongibson** [comment]
I didn't test with the linked project. I have the tutorial project working fine with the new dependencies. As well as other projects. 

Dropping connections to redis isn't really a channels issue... it's likely your setup. 🤔

**Comment by carltongibson** [comment]
At a quick glance the test example looks fine. Can't see anything obvious. If I get a moment I will try to give it a run, but ideally you'd be able to dig into the 404.

**Comment by bluesurfer** [comment]
@carltongibson I tested on different machines and get the same errors. Can you link your tutorial project?

**Comment by carltongibson** [comment]
Here you go:

https://github.com/carltongibson/notes/tree/main/examples/channels_tutorial

**Comment by bluesurfer** [comment]
@carltongibson aaaaaah of course.. I miss to include `daphne` in my local settings. Indeed, in my production environment there are no errors since I am using `uvicorn` as the server.

Closing.. thanks :)

**Comment by carltongibson** [comment]
Super. Thanks for confirming.
