### ISSUE TITLE
Cannot install channels["daphne"]

### ISSUE THREAD

**Issue by alosultan** [django/channels#1945]
I'm trying to install the app as instructed:

```
python -m pip install -U channels["daphne"]
```

but the app won't install.

```
(.envs) username@username-iMac channels-tutorial % python -m pip install -U channels["daphne"]         
zsh: no matches found: channels[daphne]
```

- My OS: macOS Monterey v. 12.6
- Python 3.9.13
- pip 22.3

**Comment by carltongibson** [comment]
This is a zsh issue. (Try Googling it for more detail)

You need to quote the square brackets. 

python -m pip install -U 'channels[daphne]'

**Comment by alosultan** [comment]
That works perfectly thank you.
