### ISSUE TITLE
How to send data from a background worker to the frontend client?

### ISSUE THREAD

**Issue by richardARPANET** [django/channels#1957]
This does not seem to be documented here https://channels.readthedocs.io/en/stable/topics/worker.html

Client sends a message via web socket, 
consumer launches a background worker, 
worker does some work and forwards a message back to the client on the web browser via web socket.

How can I do this?

---

I did try

```python
await self.send_json(content)
```

from within the method of my background worker. However this results in:
```
    raise NotImplementedError("You must implement application_send()")
  You must implement application_send()
```

**Comment by carltongibson** [comment]
Since you closed it, I'm assuming you worked it out. In general the answer would be to go via the channel layer again. 

Questions are better targeted to the Discussions tab if possible.
