### ISSUE TITLE
Feature Request: use multiprocessing for an inbuild channel layer in addition to InMemoryChannelLayer

### ISSUE THREAD

**Issue by devkral** [django/channels#1962]
# Why
Currently the official way is to use channels_redis for layer functionality but this requires an extra service
which adds complexity to setups.

Python has already some wonderful infrastructure to do this without extra services:
the multiprocessing module.

It would be really nice to have an full fledged implementation of layers on base of multiprocessing.

# Initial work
I experimented a bit and this is some initial work (basing on InMemoryChannelLayer and tests for it).
I am currently short in time to develop it myself

https://github.com/devkral/channels-multiprocessing

State:
Non-functional, hangs up. Combining multiprocessing with async is hard.

**Comment by carltongibson** [comment]
Hi there. 

This isn't something we'd add to Channels itself. Happy to link to an external package if you get it all working though! 

Thanks
