### ISSUE TITLE
RuntimeError: Event loop is closed when following tutorial

### ISSUE THREAD

**Issue by sean-reed** [django/channels#1966]
I get the following error when following the official Channels tutorial at [this step](https://channels.readthedocs.io/en/stable/tutorial/part_2.html#enable-a-channel-layer) (specifically, when checking the channel layer can communicate with Redis using the Django shell): 

```
Task exception was never retrieved
RuntimeError: Event loop is closed
```
I was using the current channels-redis version (4.0.0) that is installed when following the tutorial. Seems to be related to this issue [https://github.com/django/channels_redis/issues/332](https://github.com/django/channels_redis/issues/332).

Downgrading to channels-redis version 3.4.1 fixes the issue. I suggest updating the tutorial to 

`python3 -m pip install channels-redis===3.4.1
  `
until channels-redis fix the issue.

**Comment by carltongibson** [comment]
Thanks for the report. 

You can run the shell with `python -m asyncio` to give you a concurrent context, and then not use `async_to_sync()`. 

That's probably a nicer rewrite to have anyway, if you fancied making that. 

Out of interest, what happens if you use `asyncio.run()` rather than `async_to_sync()`?

**Comment by sean-reed** [comment]
> Out of interest, what happens if you use asyncio.run() rather than async_to_sync()?

This gives the same error.

> You can run the shell with python -m asyncio to give you a concurrent context, and then not use async_to_sync().

Nice! This works. The drawbacks are that you need to manually add the DJANGO_SETTINGS_MODULE environment variable and calling asynchronous functions with `await` is not introduced until the next part of the tutorial (Part 3). Maybe the small section on using the Django shell to check the channel layer can communicate with Redis can just be removed altogether from the tutorial? I don't see that it adds that much, since if it's not working then you'll find out in the next step anyway and, at the moment, that check is failing when everything is fine.

**Comment by carltongibson** [comment]
Hi @sean-reed. 

I've tracked it down. The move to [redis-py requires closing connections explicitly](https://redis-py.readthedocs.io/en/stable/examples/asyncio_examples.html#Connecting-and-Disconnecting) 

> Utilizing asyncio Redis requires an explicit disconnect of the connection ...

So to get the shell example to pass cleanly we need to do something like this: 

```pycon
>>> import channels.layers
>>> from asgiref.sync import async_to_sync
>>>
>>> channel_layer = channels.layers.get_channel_layer()
>>>
>>> async def closing_send(channel_layer, channel, message):
...     await channel_layer.send(channel, message)
...     await channel_layer.close_pools()
>>>
>>> async_to_sync(closing_send)(channel_layer,'test_channel', {'type': 'hello'})
>>> async_to_sync(channel_layer.receive)('test_channel')
{'type': 'hello'}
```

Even then we should do the same for the receive call really. (A further call would hit the same issue.)

**Comment by carltongibson** [comment]
This should be resolved by channels-redis 4.1, which will automatically close the redis connection at loop shutdown.

**Comment by lunika** [comment]
Great news. Do you know when this release will be available ?
Thanks

**Comment by carltongibson** [comment]
It's already out.

**Comment by lunika** [comment]
I see no tag nor release on github and on pypi it's still the version 4.0.0: https://pypi.org/project/channels/

Am I missing something ?

**Comment by carltongibson** [comment]
Channels-redis.

**Comment by lunika** [comment]
oh my bad. Sorry 🙂
