### ISSUE TITLE
Is it possible to run websockets with uWSGI?

### ISSUE THREAD

**Issue by mostaszewski** [django/channels#1968]
Has anyone managed to run Django Channels' websockets with uWSGI instead of Daphne?

The only information I found is this pull request, but it does not help too much (https://github.com/django/channels/pull/55).

I know I can use both the uWSGI and the Daphne simultaneously, but I can not add the Daphne to my stack right now.

Thank you

**Comment by carltongibson** [comment]
Sorry, I don't have any information to add. (As far as I am aware uWSGI is unmaintained... 😬) 


Best not to spread discussions on the same topic: I'm going to close as a duplicate of #55.
