### ISSUE TITLE
how to add middleware for one consumer, but not all

### ISSUE THREAD

**Issue by Motasem20007204978** [django/channels#1980]
I have created notifications app and chats app, I want to add the middleware for chats app only

**Comment by FattyMango** [comment]
I don't know if this is the right way to do it, but here is a workaround.

create a custom middleware and check if the request's path applies to the middleware.
```
class TokenAuthMiddleWare:
    def __init__(self, app):
        self.app = app
        
    async def __call__(self,scope, receive, send):
        if "my app" in scope["path"].split('/'):
            <your logic>

        return await self.app(scope, receive, send)
        
```

**Comment by Afeez1131** [comment]
Let's say I have a middleware with the name `CustomMiddleWare`, 

You can wrap the consumer for the chats app only with the middleware like below. 
```bash
#... other asgi codes

application = ProtocolTypeRouter({
    'http': get_asgi_application(),
    'websocket': AuthMiddlewareStack(
        URLRouter([
            path('ws/lobby/<str:lobby>/', LobbyRoomConsumer.as_asgi()),
            path(r'ws/chatroom/', CustomMiddleWare(consumers.ChatRoomConsumer.as_asgi())),
        ]),
    ),
})
```

By such, the middleware `CustomMiddleWare` will only works on the `ChatRoomConsumer`.
