### ISSUE TITLE
Make chatsocket.send send the data to all of the instances at the same time?

### ISSUE THREAD

**Issue by edfink234** [django/channels#1982]
In a typical consumers class, we would have the following:

```python
class SomeConsumer(AsyncWebsocketConsumer):
    async def connect(self):
        ...
    async def disconnect(self, close_code):
        ...
    async def receive(self, text_data):
        ...
    async def chat_message(self, event):
        await self.send(text_data=json.dumps({"event": event}))
```
In this example, self.send is called once for each instance of SomeConsumer. However, I don't think all of the chat_message methods get called concurrently, at the same time for each instance, since I notice a delay in the display of the javascript data when I have multiple windows open. Ideally, I would like the data to display at the exact same time across X number of windows. Is there a way to make this work? I tried to create tasks and then await them once number_of_chat_message_calls = number_of_instances, like this:

```python
async def chat_message(self, event):
    SomeConsumer.count+=1
    SomeConsumer.tasks.append(asyncio.create_task(self.send(text_data=json.dumps({"event": event}))))
    if SomeConsumer.count == SomeConsumer.consumers:
        done, pending = await asyncio.wait(SomeConsumer.tasks)
        SomeConsumer.tasks.clear()
        SomeConsumer.count = 0
```
but it still doesn't display the data synchronously. Is there any way to achieve this?

**Comment by carltongibson** [comment]
> I don't think all of the chat_message methods get called concurrently, at the same time for each instance…

Concurrent doesn't mean parallel. I think [Rob Pike gave the canonical talk on this topic](https://go.dev/blog/waza-talk). 

Maybe #825 would enable you to do this, but I'm not sure that's likely to happen.
