### ISSUE TITLE
Reuse redis connection

### ISSUE THREAD

**Issue by bast-ii** [django/channels#1993]
Is there any way to reuse the connection to redis that channels sets up?
I would like to store data in redis independently of channels, without establishing another connection with redis-py.

**Comment by carltongibson** [comment]
There's no public API for it, but the channel layer maintains a reference to the connection. 

e.g. 

https://github.com/django/channels_redis/blob/8b4ed2d3b03a03dc792ee80142e891efabb5bbd6/channels_redis/core.py#L81
