### ISSUE TITLE
Question regarding code in tutorial part 1

### ISSUE THREAD

**Issue by ElijahQuiazon** [django/channels#2010]
Hi,

In [Part 1 of the Djano Tutorial](https://github.com/django/channels/blob/42760f9be5f66fd2dbf9b2e77fc84800a481b905/docs/tutorial/part_1.rst#add-the-index-view), 

I noticed that  `keyCode` was used in the `index.html` chat template.

```javascript
document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };
```

MDN web docs mentions this property being [depreciated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). 

Was wondering if there's any issues leaving it this way, or if it should be updated with lets say the `key` [property](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#browser_compatibility).

**Comment by carltongibson** [comment]
Hi @ElijahQuiazon, good question. 

It's still supported by all the main browsers https://caniuse.com/?search=keycode — but if you'd like to submit an updated version that would be cool. Fancy it? 

Thanks.

**Comment by ElijahQuiazon** [comment]
Yup sure thing! I've gone ahead to submit a PR. It's my first time doing this so kindly let me know if I've missed anything out.

Cheers!
