### ISSUE TITLE
Receiving bytes and string data on the same consumer

### ISSUE THREAD

**Issue by Fernando473** [django/channels#2013]
Hi, how can I receive data of type bytes and strings on the same consumer, Actually I have this function but the bytes data is missing.
![image](https://github.com/django/channels/assets/74788563/10d38204-d122-4d6f-bc7a-c47f5794d5d1)

I hope, you can help me with this truoble.

**Comment by carltongibson** [comment]
The client will either send bytes or text. Not both in the same frame. No? 🤔
