### ISSUE TITLE
AsyncConsumer listening via group_send() never recieves, when two browser tabs are open

### ISSUE THREAD

**Issue by richardARPANET** [django/channels#2046]
**Your OS and runtime environment, and browser if applicable**
Docker, Python 3.8, Debian distro (Also happen on Ubuntu without docker)
Browser Firefox and Chrome.

**A `pip freeze` output showing your package versions:**
See [here](https://github.com/VeemsHQ/veems/blob/f6147317c777f35c84b337cfea5bd9d249d09d5f/requirements.txt#L10)

**How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)**
Tested with daphne and uvicorn, same result, nothing in front. Running on local machine.
See [here](https://github.com/VeemsHQ/veems/blob/f6147317c777f35c84b337cfea5bd9d249d09d5f/entrypoints/webserver.sh#L4).

**Console logs and full tracebacks of any errors**
There are no errors.

**What you expected to happen vs. what actually happened**
I'm seeing the following behavior myself, with this setup.

JS client. Python server. Client sends to server, it hits AsyncJsonWebsocketConsumer, that does 
```python
self.channel_layer.send('background-tasks', content)
```

(using Redis backend)

then background is handled by a `AsyncConsumer` which 
sends back 
```python
self.channel_layer.group_send(group_name, message)
# (the group_name is `f'client-updates-{self.scope["user"].id}'`)
```

this is then forwarded by the original AsyncJsonWebsocketConsumer to the client.

1. Start 1 browser window, 2 way websockets working.
2. Open another browser tab, client is able to sent but not recieve anything, they never reach the background `AsyncConsumer`.

[Here's the full project source code](https://github.com/VeemsHQ/veems/blob/9623309b762b988d18dcfcb8b32135eaeb0e5433/veems/consumers.py)

What I expected to happen:

- Expected when two browser windows send messages to the back-end, both windows should receive replies from the server. Rather than just one.

**Comment by carltongibson** [comment]
Hi. Can I ask you to reduce this to a minimal example please? There's **way too much** in the linked repo for me to be able to see what's going on. 

> Expected when two browser windows send messages to the back-end, both windows should receive replies from the server. Rather than just one.

This is the scenario from the tutorial chat application — which generally you'd test by having two tabs open — so maybe you could reproduce there? 

Thanks.

**Comment by carltongibson** [comment]
I'm going to close as needsinfo for now. Please follow up if you can provide a minimal reproduce.
