### ISSUE TITLE
"group_add" is not a known member of "None"

### ISSUE THREAD

**Issue by Emmaotiki5** [django/channels#2049]
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

**Comment by carltongibson** [comment]
This is not an actionable error report. At the least you need to provide more detail. 

Almost certainly you have a local configuration error. Check you can connect to Redis, and so on.
