### ISSUE TITLE
Question about versions

### ISSUE THREAD

**Issue by Tein1337** [django/channels#2055]
Can you write the versions of all libraries, languages, etc. or just indicate where it is written, maybe I missed it. When writing chat on tutorial there were problems with version conflict, so I would like to know exactly what versions and what are used in the tutorial (I am a complete zero in programming, for information).

**Comment by wenyuan** [comment]
Here's  the package(including version ) I used when writing the tutorial chat server.
```
channels==3.0.5
channels-redis==4.0.0
Django==4.1.2
```
For reference only.
