### ISSUE TITLE
initkwargs wasn't set in result consumer

### ISSUE THREAD

**Issue by J4CKVVH173** [django/channels#2057]
I read about `as_asgi` classmethod for AsyncConsumer and I've tried to use this method like Django's as_view. My purpose is passing extra classes from outside into my consumer like this `MyConsumer.as_asgi(extra_class=my_instance)` and I've expected that I can get `extra_class` inside MyConsumer's methods as `self.extra_class`, but I've got an error `AttributeError: 'MyConsumer's ' object has no attribute 'extra_class'`. I understand that this error means that my instance wasn't passed successfully but I can't find another option to do this. 
I am wondering if I have any other options to send this instance inside `MyConsumer`? I read source code and `as_asgi` has doc string 
```
Return an ASGI v3 single callable that instantiates a consumer instance
        per scope. Similar in purpose to Django's as_view().

        initkwargs will be used to instantiate the consumer instance.
```
but my initkwargs wasn't used to instantiate the consumer instance.

**Comment by carltongibson** [comment]
You can only set attributes that exist on the class already. Set them as empty attributes on your class and then you can pass them as kwargs to as_asgi()

**Comment by J4CKVVH173** [comment]
> You can only set attributes that exist on the class already. Set them as empty attributes on your class and then you can pass them as kwargs to as_asgi()

I did it of course
It looks like 
```
class My consumer(AsyncWebSocketConsumer):

     extra_class = None

```

I've tried with None and without. With None I got error that extra class is none. Without None I wrote above

**Comment by carltongibson** [comment]
You can see the code here: 

https://github.com/django/channels/blob/2db92ccb57ff75b8f7535c3bc818f47d43a1b8bf/channels/consumer.py#L84-L101

The initkwargs are passed to the consumer on line 93: 

https://github.com/django/channels/blob/2db92ccb57ff75b8f7535c3bc818f47d43a1b8bf/channels/consumer.py#L93

**Comment by J4CKVVH173** [comment]
I didn't get it, could you please explaene your idea ?

I can show you what I'm trying to do.

This is my `urls.py`

```
from uuid import UUID

from django.urls import path

from .classes import SessionConsumer
from .repositories import InMemorySessionRepository, WebsocketClientRepository

# Move to redis
session_map: dict[UUID, str] = {}
repositories = {
    'client_repository': WebsocketClientRepository(session_map),
    'session_repository': InMemorySessionRepository(session_map),
}



websocket_urlpatterns = [
    path('session/', SessionConsumer.as_asgi(**repositories)),
]
```
As you can see I have two extra exteranl class  - `WebsocketClientRepository, InMemorySessionRepository` and I am trying to pass them inside `SessionConsumer`.

and this is `SessionConsumer`

```
from channels.generic.websocket import AsyncJsonWebsocketConsumer
from django.conf import settings
from core.application.classes import Viewer
from core.application.repositories import ClientRepository
from core.infrastructure.repositories import HttpPresenterRepository

from .repositories import SessionRepository


class SessionConsumer(AsyncJsonWebsocketConsumer):

    client_repository: ClientRepository
    session_repository: SessionRepository

    async def connect(self):
        await self.accept()

    async def receive_json(
        self, content: dict | None = None, bytes_data: bytes | None = None
    ):
        access_token = content['credentials']['access']
        presenter_repository = HttpPresenterRepository(
            access_token, settings.PRESENTER_URL
        )
        # Error here
        viewer = Viewer(self.client_repository, presenter_repository)  # noqa
```

And I can't get access to client repository inside `SessionConsumer`

This is the error.
`AttributeError: 'SessionConsumer' object has no attribute 'client_repository'`

If I use None as default state for client_repository I get error that self.cloent_session is None.

**Comment by J4CKVVH173** [comment]
And yeah I checked the source code and I got the idea that I can rewrite the `__init__` method for chanels' consumer. But I want to use out of box solution if it's posible of course.

**Comment by J4CKVVH173** [comment]
My solution 
```
from channels.generic.websocket import AsyncJsonWebsocketConsumer

class AsyncJsonConsumer(AsyncJsonWebsocketConsumer):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, value in kwargs.items():
            setattr(self, key, value)
```
