### ISSUE TITLE
error in channel layer explanations 

### ISSUE THREAD

**Issue by Twintersh** [django/channels#2065]
```
await self.channel_layer.group_send(
    room.group_name,
    {
        "type": "chat.message",
        "room_id": room_id,
        "username": self.scope["user"].username,
        "message": message,
    }
)
```

should be

```
await self.channel_layer.group_send(
    room.group_name,
    {
        "type": "chat_message",
        "room_id": room_id,
        "username": self.scope["user"].username,
        "message": message,
    }
)
```

it is not calling the right function name (**chat.message** -> **chat_message**)

**Comment by carltongibson** [comment]
The `.` is mapped to `_` by the consumer when determining which method to call, so the `chat.message` format is correct, just as `http.request` works for ASGI, mapping to `http_request`.

**Comment by carltongibson** [comment]
From the docs: 

> Consumers are structured around a series of named methods corresponding to the
``type`` value of the messages they are going to receive, with any ``.``
replaced by ``_``.

- https://channels.readthedocs.io/en/latest/topics/consumers.html
