### ISSUE TITLE
adding a check if group_name exists method for channel_layer

### ISSUE THREAD

**Issue by ninjia0** [django/channels#2066]
I have been searching the internet, but I couldn't find a way to check if a specific group name exists in the channel_layer. Are there any methods or approaches to accomplish this?

**Comment by carltongibson** [comment]
It's not part of the Channel Layer API. 

Assuming you're using the PubSub Redis Layer, you could (as one idea) build something around the [PUBSUB CHANNELS command](https://redis.io/commands/pubsub-channels/). (Apply similar to your needs.)
