### ISSUE TITLE
Session Data Corrupted

### ISSUE THREAD

**Issue by c-rei** [django/channels#2099]
I tried to update my application from python 3.6, Django 2.0 to python 3.10, Django 5.0, and it worked in development environment. But when I deploy it to production with Apache 2.4, it don't response any thing, just output a message "Session Data Corrupted"
And I tried to downgrade Django version to 3.0, or 4.0, I got a same message "Session Data Corrupted".
I want to known what's wrong with my approach? What's I have to do?

Thanks any advise.

My environment:
OS        -> Windows 10
Server -> Apache/2.4.59
Python -> 3.10.10
Django -> 5.0.6
WSGI   -> mod_wgsi 5.0.0.0

**Comment by carltongibson** [comment]
Sorry, this isn't an addressable issue report. I'm not able to assist. Please try a support channel such as the [Django Forum](https://forum.djangoproject.com) but you'll need to provide much better information to have any chance of getting help.
