### ISSUE TITLE
Trying to run testproject/benchmark.py with default values endless loop...

### ISSUE THREAD

**Issue by ssteinerx** [django/channels#211]
I am writing some documentation about how to run testproject/benchmark.py:

[README.rst](https://github.com/ssteinerx/channels/blob/update-channels-test-readme/testproject/README.rst)

Unfortunately, once the docker image is running, running the benchmark code using default parameters goes into space (after ramping up), repeating:

```
10 open, 17 total
```

Endlessly.

Is this maintained and expected to work?  I didn't really delve into the code as my focus at the moment is on understanding _how_ to run things, not to be digging into the code until I can at least run it successfully.

**Comment by andrewgodwin** [comment]
No, that's not how it's supposed to work; have you tried running it locally rather than via Docker?

**Comment by andrewgodwin** [comment]
(I haven't touched it in the last few months so it might also be broken, but I don't have time to check till next week)

**Comment by ssteinerx** [comment]
It runs against the server started with ```manage.py runserver``` and completes.

The Docker version endlessly loops.

I updated [ README.rst](https://github.com/ssteinerx/channels/blob/update-channels-test-readme/testproject/README.rst) with the instructions for running locally as well.

**Comment by hackedd** [comment]
I was able to reproduce this issue, and found that the `MyClientProtocol` generates a new fingerprint when the connection does not succeed, leaving the original entry in `stats`. This leads to `spawn_connections` not creating any new connections, and the benchmark never completes.

**Comment by andrewgodwin** [comment]
Ah, lovely! Thanks for looking into this.
