### ISSUE TITLE
Ability to deny websockets during handshake phase

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#327]
It would be nice to have a way to accept or deny sockets during the handshake phase (before the connection is opened) based on the HTTP attributes/cookies/etc.

This would require the interface server to send a message during handshaking with the same details as `websocket.connect`, and then wait for a reply with either an "accept" or "drop" message so that the interface server could either continue with the handshake or drop it with an appropriate error code.

We could even potentially override `websocket.connect` to do this, but there would need to be some system in place for channels that caught connect handlers that did not send accept/deny and warn users that they need to, as it would be a backwards incompatible change.

Making `connect` do this also has the advantage that `enforce_ordering` would be needed way less, as there would be no way to receive messages before `connect` had returned a yes or no result.

**Comment by yatishb** [comment]
👍  i'd love to have this in here as well

**Comment by andrewgodwin** [comment]
This is actually in the master branch now in a mostly-complete form, just needs some polish before I call it done.

**Comment by yatishb** [comment]
Any idea when this would go out as a release tag? I noticed that the latest tag released a couple of days back doesn't have this yet

**Comment by andrewgodwin** [comment]
It depends when things are fully tested and settled. The release a few days ago was just to get out all the changes before that landed into a release - so no idea of timeframe, sorry.

**Comment by tyler46** [comment]
Hi :)

knowing that this is an ongoing process, I would like to ask if the appropriate way, for current stable version, to close a websocket connection for unauthenticated client is the following:

`message.reply_channel.send({'text': json.dumps({'code': 4401}), 'close': True})`
This will send a message with the error code right before closing the websocket connection. 
Do you propose a better handling of this kind of cases?

finally, many thanks for this awesome library :100:

**Comment by andrewgodwin** [comment]
There's no way to specify the close code in the spec right now - that might be something that we add at a later date, but right now it's fixed to be whatever the appropriate one is. If you'd like a close code option, open a new issue for that feature and we'll prioritise it as appropriate.

Also, what you suggest isn't quite the same as the code in master, as you may still get `websocket.receive` messages that came through straight after `websocket.connect` (the new code waits until the connect response for that stuff)

**Comment by tyler46** [comment]
thanks for your reply. 

I have created it here #414
