### ISSUE TITLE
Traceback - ChannelFull

### ISSUE THREAD

**Issue by Tom-Gorup** [django/channels#329]
Getting a "ChannelFull" on send_reply. I've seen other issues saying to update daphne; however, it seems I'm already using the latest and greatest. Also, made sure Channels was up to date. I'm wondering if maybe I'm using consumers.py (https://dpaste.de/MH5u) incorrectly... I'm not entirely sure where else the issue could be.

I'm essentially watching a queue and sending the content of the queue as it's received by the handler. I'm using the below "SendReply" class to do the reply_channel.send() inside of the for loop. 

Appreciate any assistance you can provide.

**SendReply**

```
class SendReply:
    def __init__(self, message):
        self.reply_channel = message.reply_channel

    def send(self, input_data):
        self.reply_channel.send({
            'text': json.dumps(input_data)
        })
```

**Daphne Up-to-date**

```
$ pip install daphne --upgrade
Requirement already up-to-date: daphne in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

**Channels Up-to-date**

```
$ pip install channels --upgrade
Requirement already up-to-date: channels in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```

**Traceback**

```
2016-08-30 21:38:39,243 - ERROR - worker - Error processing message with consumer app.signals.changes_feed:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/channels/worker.py", line 111, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/channels/sessions.py", line 64, in inner
    return func(message, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/channels/auth.py", line 42, in inner
    return func(message, *args, **kwargs)
  File "/opt/app_name/app_name/app/signals.py", line 51, in changes_feed
    changes
  File "/opt/app_name/app_name/app/utils.py", line 18, in send
    'text': json.dumps(self.return_data)
  File "/usr/local/lib/python2.7/dist-packages/channels/channel.py", line 38, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python2.7/dist-packages/asgi_redis/core.py", line 103, in send
    raise self.ChannelFull
ChannelFull
```

**Comment by andrewgodwin** [comment]
ChannelFull is always caused by the other end not consuming - in this case, Daphne is not sending back the replies to the websocket clients. Couple of questions:

* Do you see anything in the Daphne output?
* Do any of the replies you're sending make it to a browser?
* How many replies are you sending at once (in one overall consumer call)? Is it more than 10? More than 100?

**Comment by Tom-Gorup** [comment]
I was running everything together using `python manage.py runserver 0.0.0.0:8000`. To break this further out I switched to running daphne and `runworker` in separate screens. Now I'm actually seeing that the server is continuing to send data even after I attempt to refresh my browser where the socket was created (via browser console). I eventually received the 503 error below and I see the server is still sending data despite the socket being closed on the client-side (no data being received in the browser after the 503.

**Browser Error**
```
503 Service Unavailable
Worker server failed to respond within time limit.
Daphne
```

`WSDISCONNECT` sent with page refresh
```
10.1.1.2:62449 - - [31/Aug/2016:17:47:51] "WSCONNECT /" - -
10.1.1.2:62432 - - [31/Aug/2016:17:50:01] "GET /admin/login/" 503 470
10.1.1.2:62449 - - [31/Aug/2016:17:50:01] "WSDISCONNECT /" - -
```

To address your question:
- Do you see anything in the Daphne output?

I was using `runserver`, but the output of `runserver` seemed to stop when the ChannelFull error hit.
- Do any of the replies you're sending make it to a browser?

All replies up to failure show up in the browser.
- How many replies are you sending at once (in one overall consumer call)? Is it more than 10? More than 100?

I would say more than a 100. I ran a counter this time and I hit nearly 300 without failure, but I'm thinking maybe the ChannelFull was caused by browser refreshes from the app... Primarily because I'm seeing that my socket is being held open on the server side even though the browser had been refreshed. This leads me to believe I'm not tearing down the socket properly. Possible this is something to do with how I'm handling `websocket.connect` and `websocket.disconnect`?

I'm also seeing that I can't kill the worker with `ctrl-c`. I get the following error.
```
^C2016-08-31 18:04:34,719 - INFO - worker - Shutdown signal received while busy, waiting for loop termination
```

I'm assuming I'm mostly certainly doing something incorrect...

Appreciate your help!

**Comment by andrewgodwin** [comment]
Ah, so the third answer is the interesting one - channels have a capacity, and the default is 100. If you're generating messages into the channel faster than Daphne can consume them out, you're going to get ChannelFull to warn you that you're overloading the channel (as a backpressure system).

In this case, I would say that if you see ChannelFull, you should make your consumer wait for a little bit (say 0.1 seconds) and then try again, as by that point the channel should have drained a bit to have space - this will set you in good standing software design wise. If you like, you can then raise the capacity of the channels in the CHANNEL_LAYERS setting, but this will increase your memory usage, and I think slowing your consumer down when it sees backpressure will work fine long-term.

**Comment by Tom-Gorup** [comment]
I ran the handler with `timeit` and I'm seeing that the sends are mostly pretty well spaced apart. There are two within a second, then ~10 seconds for the next set. 

Also, I'm still not able to `ctrl-c` to quit the worker. I'm having to `ctrl-z` and `kill -9 ....`. Is it because the handler (below) is in a for loop?

```
$ python manage.py runworker
2016-08-31 18:18:01,244 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2016-08-31 18:18:01,244 - INFO - worker - Listening on channels app_name.receive, http.request, websocket.connect, websocket.disconnect, websocket.receive
1
7.02991008759
2
7.39184617996
3
17.2963120937
4
17.655269146
5
27.5653970242
6
27.9180240631
7
37.841987133
8
38.2001390457
9
48.1190190315
10
48.400698185
```

**Handler**
```
def changes_feed(message):
    host = settings.get("rethinkdb", "host")
    port = settings.get("rethinkdb", "port")

    conn = r.connect(host, port)
    sent_count = 0

    start_time = time.time()
    for changes in r.table("test_data").changes().run(conn):
        if changes is not None:
            sent_count += 1
            SendReply(message).send(
                changes
            )

            print sent_count
            print time.time() - start_time
```

**Comment by andrewgodwin** [comment]
Aha, so, first off, your consumer looks to never exit? That's not good, and will block up the channels framework (and is why ctrl-c isn't working, as it does a graceful exit where it waits for consumers to stop running).

Consumers are meant to be short-lived and act in response to an event; in your example, you could make a custom channel and push events onto that channel from a save method in Django or other hook, rather than doing a blocking call as you are there. If you have to use a blocking call, you'll have to write your own separate process outside of the consumer framework that pushes into Channels instead.

**Comment by tijazatrook** [comment]
I am also experiencing a ChannelFull error. Since the app has grown in size perhaps the number of replies are now getting bigger than the default of 100. You mentioned that one could change the CHANNEL_LAYERS capacity under settings, could you please provide more insight into that. Following is what my settings look like: 

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(XXX, XXX)],
        },
        "ROUTING": "XXXXXchannel_routing"
    },
} 

Would really appreciate your help

**Comment by andrewgodwin** [comment]
Like this: 
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(XXX, XXX)],
            "channel_capacity": {
                "http.request": 200,
                "websocket.send*": 20,
            },
        },
        "ROUTING": "XXXXXchannel_routing"
    },
}
```

Bear in mind though that increasing capacity is almost never the answer unless your throughput is higher than 100 messages a second.

Closing the ticket as there was no response from the original poster.

**Comment by tijazatrook** [comment]
Thank you Andrew!

**Comment by tijazatrook** [comment]
Hi Andrew, 

Hope you are well. I have been experiencing some ChannelFull errors and wanted to request you for some guidance. I know that you mentioned that the default Channel capacity is a 100 messages/second, could you tell what the constraints are on the size of each of the messages. Just wanted to know that could large messages (even if they are less than a 100/second) could potentially cause ChannelFull errors. 

The application I am working on primarily relies on Django Channels and just has 3-4 RESTful endpoints. As such I have set the channel_capacity as follows:

```javascript
"channel_capacity": {
	"http.request": 100,
	"websocket.send*": 200,
}
```

Since I have drastically increased the websocket capacity drastically, wanted a second opinion on this. Do you see any with such a configuration?

Thank you once again for Django Channels! :)

**Comment by andrewgodwin** [comment]
Replied to this in #658.

**Comment by toni88x** [comment]
It seems when testing with channels.test.Client that the limit is 10 and the settings for CHANNEL_LAYERS, e.g.

`CHANNEL_LAYERS = {
	"default": {
		"BACKEND": "asgi_redis.RedisChannelLayer",
		"CONFIG": {
			"hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
			# https://github.com/django/channels/issues/329
			"channel_capacity": {
				"http.request": 1000,
				"websocket.send*": 1000,
			},
			"capacity": 100,
		},
		"TEST_CONFIG": {
			"hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
			# https://github.com/django/channels/issues/329
			"channel_capacity": {
				"http.request": 1000,
				"websocket.send*": 1000,
			},
			"capacity": 100,
		},
		"ROUTING": "vali.routing.channel_routing",
	},
}`

do not have any effect. Is there any way to increase the limit for tests?

Here is the stack trace:

`ERROR: test_copy_component (app.tests.test_connected_copies.ConnectedCopiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/vali/vali/app/tests/test_connected_copies.py", line 201, in test_copy_component
    response = self.client.get("/component/{}/copy/".format(c1_s1.id))
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 500, in get
    **extra)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/vali/vali/app/views/component_views.py", line 382, in copy_component
    copy = component.make_copy(deep_copy)[0]
  File "/vagrant/vali/vali/app/models.py", line 740, in make_copy
    deep_copy=deep_copy, new_parent=c, user_copy=False)
  File "/vagrant/vali/vali/app/models.py", line 740, in make_copy
    deep_copy=deep_copy, new_parent=c, user_copy=False)
  File "/vagrant/vali/vali/app/models.py", line 637, in make_copy
    c.save(autovalis=False, make_instance_children=False)
  File "/vagrant/vali/vali/app/models.py", line 522, in save
    self.set_unique_name()
  File "/vagrant/vali/vali/app/models.py", line 262, in set_unique_name
    self._set_unique_name()
  File "/vagrant/vali/vali/app/models.py", line 212, in _set_unique_name
    vc.save(set_unique_name=False)
  File "/vagrant/vali/vali/app/models.py", line 516, in save
    super(Component, self).save(*args, **kwargs)
  File "/vagrant/vali/vali/app/models.py", line 339, in save
    m.save()
  File "/vagrant/vali/vali/app/models.py", line 2411, in save
    calculate_valis(to_be_recalculated)
  File "/vagrant/vali/vali/app/models.py", line 4917, in calculate_valis
    new_valis,
  File "/vagrant/vali/vali/app/models.py", line 4941, in start_background_calculation
    "user_id": user_id,
  File "/usr/local/lib/python2.7/dist-packages/channels/channel.py", line 44, in send
    self.channel_layer.send(self.name, content)
  File "/usr/local/lib/python2.7/dist-packages/asgiref/inmemory.py", line 52, in send
    raise self.ChannelFull(channel)
ChannelFull: vali-background-calculations`

**Comment by proofit404** [comment]
`TEST_CONFIG` is used only in the `channels.test.liveserver.ChannelLiveServerTestCase`. In regular `TestCase` your actual layer will be substituted with inmemory version.

What code in your application cause this error?

**Comment by toni88x** [comment]
The problematic test is a `ChannelTestCase` from `channels.test`. 

We have a function in a model that adds several (>10) messages to a single channel within one call (it is a somewhat complex function that triggers various background calculations). Usually we call a consumer in the test case that empties the channel, but in this case we do not have a chance to call it before the channel overflows. By now we fixed it by reducing the number of messages the function sends but in general it would be nice if there would be a way to increase the limit also for ChannelTestCases.
