### ISSUE TITLE
How to write unittest for WebSocketConsumer class?

### ISSUE THREAD

**Issue by cambridge0427** [django/channels#330]
Hi there,

I am trying to write some test cases for my websocket consumer class (which inherits JsonWebsocketConsumer ) But I keep getting an error saying "AssertionError: Channel name not valid".  Could you kindly provide some help about where went wrong?

Here is approximately my test code:
```
class MyTestCase(ChannelTestCase): 
       def test_a_thing(self):
            with apply_routes([route_class(WSConsumer)]):
                    client = Client()
                    consumer = client.send_and_consume('websocket.receive', {'METHOD': 'subscribe'})
```

Is there any examples about how to unittest websocket consumer class? I was looking at the code under channels.tests.test_generic.

**Comment by andrewgodwin** [comment]
Hmm, that looks like a valid use of it. Could you post the full traceback?

**Comment by cambridge0427** [comment]
Traceback (most recent call last):
  File "my_app_root_folder/my_app/consumers/tests.py", line 26, in testConnect
    consumer = client.send_and_consume('websocket.receive', {'method': 'SUBSCRIBE'})
  File "my_app_root_folder/venv/lib/python2.7/site-packages/channels/tests/base.py", line 126, in send_and_consume
    self.send(channel, content)
  File "my_app_root_folder/venv/lib/python2.7/site-packages/channels/tests/base.py", line 105, in send
    self.channel_layer.send(to, content)
  File "my_app_root_folder/venv/lib/python2.7/site-packages/asgiref/inmemory.py", line 45, in send
    assert self.valid_channel_name(channel), "Channel name not valid"
AssertionError: Channel name not valid

**Comment by Krukov** [comment]
Channels are identified by a unicode string name.... 
So use "`u`" string prefix for channels names or just import  unicode_literals at the
```python
from __future__ import unicode_literals
```

**Comment by andrewgodwin** [comment]
Aha, yes, that's probably it. We should improve the error message.

**Comment by cambridge0427** [comment]
Yes, putting the 'u' prefix fixed the invalid channel name issue.

I am still confused about how to test my websocket consumer class. client.send_and_consume() returns an object of MyWebSocketConsumer, but doesn't trigger the consumer method itself. How should I trigger it?

My code looks like this:
```
 def testSubscribe(self):
        with apply_routes([route_class(MyWebSocketConsumer)]):
            client = Client()
            data = {
                'text': {'method': 'SUBSCRIBE'},
                'path': '',
                'order': 1
            }
            consumer = client.send_and_consume(u'websocket.receive', data)
            print consumer
```
Should I just call this after send_and_consume()?
```
consumer({'method': 'SUBSCRIBE'})
```

**Comment by Krukov** [comment]
By default when you call `send_and_consume` method client just put new message to the channel_layer, then trying to find consumer for this message and **call** this consumer at success (otherwise `AssertionError` will be called). Usually you don't need to look at a result of `send_and_consume` method, because it return result of consumer (consumers as function usually return nothing and classbased consumers return result of `__init__ ` method - self as you see ). Often we expect some replying at `receive` action, so in this case use `client.receive` method to check an answer. For consumers with other actions you must check your expectations in other ways.
By the way, use `HttpClient` for easy testing websocket consumers.
More suitable example:
```python
from channels.tests import ChannelTestCase
from channels.tests import apply_routes, HttpClient


class MyConsumer(JsonWebsocketConsumer):

    def receive(self, content, **kwargs):
        self.send({'result': 'ok', 'task': content['task']})


class MyTestCase(ChannelTestCase):

    def test_consumer(self):

        with apply_routes(route_class(MyConsumer, path='/')):
            client = HttpClient()
            client.send_and_consume(u'websocket.receive', path='/', text={'task': 'test'})
            self.assertEqual(client.receive(), {'result': 'ok', 'task': 'test'})
            self.assertFalse(client.receive())  # check that is nothing to receive

```

**Comment by cambridge0427** [comment]
I figured out that in my case it didn't trigger the consumer because I passed in 'order' as 1...
Changing it to 0 fixed it.
Thank you very much for the help!
