### ISSUE TITLE
Authentication decorators not working under 1.9?

### ISSUE THREAD

**Issue by houbysoft** [django/channels#337]
Not sure what I could be doing wrong. This is a very similar question to https://github.com/andrewgodwin/channels/issues/176; I am also seeing only an `AnonymousUser` instead of the logged in user. 

I described how I'm calling stuff here : http://stackoverflow.com/questions/39314097/channel-session-user-from-http-not-working-on-heroku-working-locally 

When running locally everything works fine. But when running on Heroku with the exact same code, I only ever get an AnonymousUser.

I also checked the headers as suggested in issue 176; they seem to be forwarded fine to heroku -- message['headers'] contains a ['cookie', X] tuple where X are the exact same cookies as a normal view gets in request.COOKIES. 

Any ideas what could be going on? Again, exact same code is running on both local and heroku, I don't know what else to try.

Thanks :)

**Comment by houbysoft** [comment]
Sigh, finally figured it out. I was using django 1.9.x on heroku, after changing it to 1.10 it works as expected.

**Comment by andrewgodwin** [comment]
We actually advertise compatibility with 1.8 and up, so reopening this so I can investigate.

**Comment by houbysoft** [comment]
Sounds good; in case it ends up mattering, the exact version that I am seeing it broken under is `-Django==1.9.2`.

**Comment by andrewgodwin** [comment]
I just tried this locally and it works fine on 1.9, so I'm not sure what's going on here. Going to close for now unless someone can reproduce it.
