### ISSUE TITLE
Documentation/Example of Inbound Data Binding Unit Test

### ISSUE THREAD

**Issue by rctoris** [django/channels#343]
There are some great examples in the tests of how to create a test for outbound messages with data binding, but none for the inbound ones. It would be great to have some added or documentation added to the test page on a clean way to do this.

**Comment by andrewgodwin** [comment]
Agreed.

**Comment by Krukov** [comment]
Now we have unit tests for inbound binding and some documentation about it, maybe we can close this issue?
