### ISSUE TITLE
Documentation class based views authentification

### ISSUE THREAD

**Issue by AMontagu** [django/channels#344]
Hello,

I just working around some time for accessing to the logged in user in class based view.

In the documentation (http://channels.readthedocs.io/en/latest/generics.html#sessions-and-users) it said we need to set channel_session_user to True.

But if you're user is logged in with http sessions that don't work.

Maybe just remplace channel_session_user = True to http_user = True in the documentation or adding a new part for the difference between the two level.

I was forced to look in generic code source for pointing this out (There is only one reference of http_user in the documentation and I didn't seen it because not in the authentification part).

**Comment by andrewgodwin** [comment]
Closed by #354.
