### ISSUE TITLE
In-page debugging for WebSockets

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#345]
Right now, exceptions raised in WebSocket handlers print to the console and are not visible on the web page as you're developing it. Ideally, there would be some system that forwards errors through to either the developer console in a browser or some other display area, so errors that happen are more visible without having to look in two windows.

The mechanism by how this is done might be tricky, however. Most options I can think of involve having to inject additional JavaScript into the page to open a separate connection to transport debug information over, and it may not be in scope of the Channels project.

**Comment by Krukov** [comment]
So https://github.com/Krukov/django-channels-panel can  catch errors at consumers and send debug info to the panel  (Now this feature is broken, but I will fix it soon). 
But It will be nice to have mechanism like django error page with detail information about exceptiont. I mean that channels can catche exceptions end send some info by close frame with framework spesific status codes (https://tools.ietf.org/html/rfc6455#section-7.4.2).  
Client can handle it with `onclose` method 
```js
websocket.onclose = function (event) {
        alert(event.code);
        if (event.code == 3001) {
       ....
```

**Comment by alican** [comment]
What is the best place to catch all incoming and outgoing websocket messages with django channels? I try to make a tool to catch and process all messages, to visualize them on a page together with all information like reply_channel, errors etc.

**Comment by andrewgodwin** [comment]
You cannot catch all incoming and outgoing messages from a single process due to the design of channels meaning that they're not all going to be on the same server at once. You could catch all the ones in a single process (or in the entire system providing it's in one process like `runserver`) by wrapping the channel layer with another one that logs messages, then forwards to the lower layer.

**Comment by andrewgodwin** [comment]
Closing this as "we're not going to do this in Channels itself". If someone wants to try doing it separately... good luck.

**Comment by fmalina** [comment]
How does one debug a channels websocket? In dev I would understand, but I am having wss: issue only present in staging with Error during WebSocket handshake: Unexpected response code: 500 and not sure how to get more info
