### ISSUE TITLE
Second ASGI HTTP/WS Server

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#347]
Having just Daphne as an ASGI HTTP and WebSocket server is somewhat fragile in terms of keeping a healthy specification; it would be nice to have at least one other server capable of speaking ASGI natively.

This could be either an existing WSGI server modified to also support ASGI (ideally), or alternatively a new from-scratch implementation (on something like asyncio/aiohttp).

**Comment by mjkillough** [comment]
I am intermittently working on a module for IIS that allows it to function as an ASGI interface server, which currently supports HTTPS/WS. It's quite niche, so probably isn't the second implementation you're looking for. I also haven't had a chance to catch up with recent changes to the ASGI spec, so it's a little out of date.

The code is available https://github.com/mjkillough/iis-asgi-handler/ if you'd like to take a look. There's a lot more code to it than I originally anticipated there being... it isn't as simple as I'd hoped it would be. :)

**Comment by andrewgodwin** [comment]
Yes, it's not quite what fits this, but I'm still glad you're doing it anyway!

I'm going to change the spec a little more before 1.0, in particular so websocket connects wait for a response before doing receive stuff (so people can deny access during connect, and the need for slight_ordering is dropped), so keep a look out for that. Not sure where's best to put down those kind of changes.

**Comment by JohnDoee** [comment]
I'm implementing it as a Twisted Resource mostly from the specifications. Currently only missing HTTP2 push and test cases. It'll show up here https://github.com/JohnDoee/txasgiresource when I'm happy with it.

**Comment by andrewgodwin** [comment]
Cool. HTTP/2 push is not implemented in Daphne yet, either, so don't worry about that, but there is one change coming which is that websocket.connect will need a response back to the server to say if it should continue the handshake and accept or drop it. I'll have the new spec and daphne code up soonish.

**Comment by quiasmo** [comment]
Hi, 

I have been I'm catching up on the state of channels and Daphne in order to gauge the feasibility of getting Django to speak [grpc](http://www.grpc.io).

At first, I thought I simply had to create a custom channel type, but I started looking closely and it seems that running a grpc server as asgi would require me to translate incoming protobufs to dicts. 

I'm guessing I would need to write a new asgi server as well as alter the specs to fit my requirements...
Maybe considering this use can can enrich the asgi spec?

Cheers

PS, Has anyone else considered this square-peg-round-hole django-grpc? Haven't found the right google search terms.

**Comment by andrewgodwin** [comment]
Yes, you'd need a custom server that translated to and from protobufs and ASGI messages, based on something like Twisted or asyncio. It would be nice to see, but wouldn't be a second HTTP implementation like this asks for :)

**Comment by matthiask** [comment]
https://github.com/ostcar/geiss 

Geiß was already mentioned once or twice in this issue tracker. It is an ASGI HTTP/WS server written in Golang and works quite well.

**Comment by andrewgodwin** [comment]
Geiss is interesting, but since it doesn't use the ASGI libraries directly but has to reimplement them in Go it's not quite the level I am looking for on this ticket (for example, if the Redis protocol changes slightly as I am doing at the moment, it needs separate updating). I would like to look into standardising the Redis interaction in future though, as everything else in ASGI is designed to be pretty portable across languages.

**Comment by snoepkast** [comment]
Would this one meet the requirements?

https://github.com/encode/uvicorn

**Comment by JohnDoee** [comment]
I'm still keeping up and now got support for the new ASGI specifications. The new specifications are so much simpler than the first ASGI :smile:

**Comment by andrewgodwin** [comment]
Yes, they are much easier, and hopefully that means much better adoption :)

**Comment by andrewgodwin** [comment]
`uvicorn` has support for both HTTP and WS now, so closing this!
