### ISSUE TITLE
File upload issue in cluster

### ISSUE THREAD

**Issue by qnub** [django/channels#350]
I have cluster like that:

![cluster](https://cloud.githubusercontent.com/assets/496270/18411578/53a172d0-77a4-11e6-814a-965117e6242d.png)

and when user uploads file in first django instance is often that file saved in second django instance and vice versa. Of course later this files syncing between nodes and all OK but user can't see file on first page load (until it'll be synced). Can it be because of channels or i do something wrong?

Python 3.5
Django 1.10.1
Channels 0.17.2

**Comment by andrewgodwin** [comment]
If you have file uploads and more than one server, you have to have a networked file store - you can't just use the local file storage. This is a problem with Django in general, unless I'm missing something?

**Comment by qnub** [comment]
No it's OK without channels. File saves on same server, then sicn to others and each have own copy. So user can see theyr uploaded image or file on same node where it was uploaded. But when i've started to use channels i've catch this issue — file saves on any node in cluster, not on same node where it was uploaded…

**Comment by qnub** [comment]
So i think daphne send file to workers and worker on nay node serve this file — no matter which node it is…

**Comment by andrewgodwin** [comment]
Yes, the worker that handles the upload will save it locally to that server, not the Daphne instance that handles the HTTP connection. This is part of the Channels design - you should either restrict the workers to certain machines, or change your file storage strategy.
