### ISSUE TITLE
Document safe usage of Twisted vis a vis Channels

### ISSUE THREAD

**Issue by ssteinerx** [django/channels#355]
It sure would be handy to document exactly how Twisted can be used now that it's in Django in any app using Channels.  

Mostly, it would be good to bring out any caveats about when it's safe to use twisted etc.

Things that could be done with e.g. Celery can be done easily and cheaply with Twisted.

**Comment by andrewgodwin** [comment]
Closing as Channels 2 uses asyncio, not Twisted, and you can just use it in a normal fashion inside any `AsyncConsumer`.
