### ISSUE TITLE
Getting Started docs example is broken

### ISSUE THREAD

**Issue by richardcornish** [django/channels#357]
The JavaScript in the "[Getting Started](http://channels.readthedocs.io/en/latest/getting-started.html)" example is broken.

`socket = new WebSocket("ws://" + window.location.host + "/chat/");` results in `WebSocket connection to 'ws://127.0.0.1:8000/chat/' failed: Error during WebSocket handshake: Unexpected response code: 404`.

All the other examples online I could find online were broken, so I assume it's something common to WebSockets in general. I searched for awhile, but I'm new to WebSockets, so I wasn't sure what to look for to move forward for something so basic.

**Comment by navyad** [comment]
@richardcornish  I tried that example it didn't raise any error, it worked for me.

![selection_003](https://cloud.githubusercontent.com/assets/1172317/18429526/72bf234e-78f1-11e6-8380-345713fe5836.png)

Probably some other issue is there.

**Comment by andrewgodwin** [comment]
The example is fine, your setup is likely what's broken. A `404` response likely means that you're not running a WebSocket capable server - you might not be using `runserver` with channels installed or `daphne`, maybe?

**Comment by richardcornish** [comment]
Thanks, @navyad and @andrewgodwin. My routing file was in the app directory instead of the project directory. Some of the structure wasn't clear to me the first time reading it through.

**Comment by japrogramer** [comment]
Im getting the same error except the error code is 200, And I can connect on the host machine to the websocket but from a different machine on the same network i cant.

**Comment by proofit404** [comment]
@japrogramer Please provide full instructions you use to run channels in your environment.

**Comment by japrogramer** [comment]
@proofit404 this was an error related to runserver_plus, once i switched back to runserver it worked. I em using daphne and the inmemory store 
 "BACKEND": "asgiref.inmemory.ChannelLayer"

**Comment by proofit404** [comment]
Hi, so this is expected behavior as its described in #170
