### ISSUE TITLE
Channels may "complete" before a transaction is finished

### ISSUE THREAD

**Issue by LegoStormtroopr** [django/channels#362]
From here: http://stackoverflow.com/questions/39480848/timing-channels-and-transactions-in-django-channels

So bare with me, this isn't a bug or a question, its more of a gotcha and I'm curious to hear responses.

> 
> I think its possible in Channels for a channel to be completed at the wrong time, and I'm not sure how to resolve it.
> 
> In my use case, I'm trying to run a search index updater via channels on save of an item. Synchronously it works like so:
> 
>     A1. item saved -> post_save signal thrown
>     A2. post_save caught by function that sets a channel
>     A3. channels processes messages and triggers a search index updater
>     A4. updater queries database for updated object and updates index
> 
> However, if the item being saved is wrapped in a transaction it can happen like so:
> 
>     B1. Transaction opened
>       A1. item saved -> post_save signal thrown
>       A2. post_save caught by function that sets a channel
>       A3. channels processes messages and triggers a search index updater
>       A4. updater queries database for and see the *old object* and updates index
>     B2. Tranasction closed
>     B3. new object hits the database
> 
> I'm not sure how to get around this, but it came up when trying to run channels code in a test suite where all tests (and thus all object changes) are wrapped in transactions which meant that no changes were being picked up by the workers as they couldn't see inside the transaction.
> 
>

**Comment by andrewgodwin** [comment]
Yes, this is true of anything that runs out of process in Django (e.g. Celery). There's not a lot of ways around it, unless you delay sending of the messages until the end of the view/consumer run - I've considered that, but it's quite hard to implement cleanly.

**Comment by LegoStormtroopr** [comment]
Any advice on how to get around it?
Channels has been really great so far, I just want to make sure I don't get bitten by this down the line.

**Comment by akaariai** [comment]
Send to channel in post_commit.

**Comment by andrewgodwin** [comment]
Or, you can manage transactions yourself and send messages only after you exit an `Atomic` block.

**Comment by carljm** [comment]
@LegoStormtroopr to expand on @akaariai 's suggestion, this is what you want to use in this situation: https://docs.djangoproject.com/en/1.10/topics/db/transactions/#performing-actions-after-commit

**Comment by LegoStormtroopr** [comment]
Thanks for all the suggestions folks. After reviewing my code, I realised this isn't as huge an issue as I had assumed.

However, I'm still not sure how to test channels in a test suite - where everything is wrapped in transactions. I'll review the test code for channels itself and keep trying.

Cheers for all the good work, its legitimately amazing work!
