### ISSUE TITLE
You cannot use channels session functionality with signed cookie sessions!

### ISSUE THREAD

**Issue by arkadiybag** [django/channels#363]
Hi!
i make REST API and on backend i use 
`SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'`

and when i try use `@channel_session` decorator - i receive error with this message: 
_**ValueError: You cannot use channels session functionality with signed cookie sessions!**_

for me need use this `SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'` backend

what me do?

**Comment by andrewgodwin** [comment]
As it says, you can't use channel sessions with signed cookies (as there's no HTTP client to give cookies to). You want to set `CHANNELS_SESSION_ENGINE` to a different session backend and set that up so it can be used for persistence.

**Comment by arkadiybag** [comment]
okay...

in my settings: 
```
# Session
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
CHANNELS_SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
```

in channels.sessions.py

```
def session_for_reply_channel(reply_channel):
    reply_name = reply_channel
    hashed = hashlib.md5(reply_name.encode("utf8")).hexdigest()
    session_key = "chn" + hashed[:29]

**why settings.SESSION_ENGINE, but not settings.CHANNEL_SESSION_ENGINE**
    session_engine = import_module(getattr(settings, "CHANNEL_SESSION_ENGINE", settings.SESSION_ENGINE))

    if session_engine is signed_cookies:
        raise ValueError("You cannot use channels session functionality with signed cookie sessions!")

    instance = session_engine.SessionStore(session_key=session_key)
    instance._session.keys()
    instance._session_key = session_key
    return instance
```

**Comment by andrewgodwin** [comment]
Sorry, you and I both misspelled the setting - it is `CHANNEL_SESSION_ENGINE`, not `CHANNELS_SESSION_ENGINE`

**Comment by arkadiybag** [comment]
Just noticed, thank you for the speed, you're the best!
