### ISSUE TITLE
Cookie based authentication

### ISSUE THREAD

**Issue by hdt91** [django/channels#364]
Hi Andrew,

I tried asking a question on the IRC channel but got logged out so I move the question here. I am working on some tasks and trying to follow your authentication section in the official doc. Can I verify that the part where session_key is taken from the request's cookie (https://github.com/django/channels/blob/master/channels/sessions.py#L171) is vulnerable to https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html ? Thank you.

**Comment by andrewgodwin** [comment]
It is, as Daphne right now does not have Origin header checking that would let you fix this kind of attack (though you can implement it on something like nginx in front). I'll close this issue and open a new one that will allow connection denial based on Origin header value.

**Comment by andrewgodwin** [comment]
Also, for reference, if you have a suspected security issue like this, please follow the Django security procedures (https://docs.djangoproject.com/en/dev/internals/security/) in future so it can be handled appropriately.
