### ISSUE TITLE
Transport WebSocket Origin header through ASGI

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#365]
This is so it can be used at connection time to deny the connection via #327, mitigating cross-site websocket forgery attacks.

(Issue was first mentioned as #364)

**Comment by dhepper** [comment]
I wonder if this is still an issue. After all the `allowed_hosts_only` decorator introduced in #593 uses the origin header

**Comment by andrewgodwin** [comment]
It is no longer an issue since we have the accept flow, yes.
