### ISSUE TITLE
request.META['SERVER_PORT'] should be a string (?)

### ISSUE THREAD

**Issue by txels** [django/channels#366]
Found while debugging an issue with Opbeat: https://github.com/opbeat/opbeat_python/issues/131

ASGI request in django channels initialises `request.META['SERVER_PORT']` using an integer value: https://github.com/django/channels/blob/master/channels/handler.py#L68

```
ipdb> self.message['server']
['127.0.0.1', 7000]
```

This later results in:
```
ipdb> request.META['SERVER_PORT']
7000
```

This appears to be in contradiction with the django docs (https://docs.djangoproject.com/en/1.10/ref/request-response/#django.http.HttpRequest.META) that state:

> SERVER_PORT – The port of the server (as a string).

Which causes the mismatch and failure to validate when posting to opbeat.

To me it feels that port should be handled as an integer rather than a string, but I see that using a string goes back to the WSGI spec https://www.python.org/dev/peps/pep-0333/#environ-variables and probably is a heritage from CGI times.

I wonder which is the correct way forward. If this should be a string in ASGI requests as well, I'm happy to volunteer a PR.

**Comment by andrewgodwin** [comment]
The correct response to this is to just change the handler to make it a string in the `META` dictionary for backwards-compat; there's no need to change ASGI, it uses an int because it's not basing directly off CGI and it's string-based interface.

**Comment by txels** [comment]
Yeah, makes sense. I'll look at making a PR tomorrow.

**Comment by txels** [comment]
I see there is an open PR for this in #370

**Comment by navyad** [comment]
@andrewgodwin  Is this issue is fixed ?

**Comment by andrewgodwin** [comment]
Indeed it is! Forgot to cross close.

**Comment by txels** [comment]
Are you sure it is? The PR with a preliminary fix was closed unmerged, and I don't see a relevant change in the [history of `handler.py`](https://github.com/django/channels/commits/master/channels/handler.py) where you suggested the fix should go.

**Comment by andrewgodwin** [comment]
Urgh, sorry, I saw it was closed and forgot how it had been. Re-opening - and my comment about text types on that ticket still applies if you'd like to have a crack at it!

**Comment by txels** [comment]
Sure, I'll give it a go tomorrow.
