### ISSUE TITLE
Github docs link

### ISSUE THREAD

**Issue by adamchainz** [django/channels#373]
On github the docs link is http://channels.readthedocs.org but it should be https://channels.readthedocs.io

**Comment by ssteinerx** [comment]
So take the three seconds and make the pull request and don't leave the work to someone else?

**Comment by andrewgodwin** [comment]
Fixed by PR 374.

**Comment by adamchainz** [comment]
I meant this link: 
<img width="586" alt="screen shot 2016-09-22 at 22 20 33" src="https://cloud.githubusercontent.com/assets/857609/18766583/dcb81db8-8112-11e6-8c81-6e06d6512886.png">

**Comment by andrewgodwin** [comment]
Ah, right. Will do that now!
