### ISSUE TITLE
Binding create/update doesn't do validation

### ISSUE THREAD

**Issue by levavakian** [django/channels#376]
When using DataBindings, the inbound methods don't seem to do any sort of validation or sanitizing, which means that simple things like missing fields or extra fields in the payload cause DeserializationErrors or IntegrityErrors and a crash, rather than a failure. 

I may be missing something and that could be intended behavior, but there also doesn't seem to be a single recommended point to put in custom validators and deserializers for inbound, like there is for outbound with serialize_data.

**Comment by andrewgodwin** [comment]
The current inbound set is meant to be very basic and swapped out for something like Django REST Framework - I should probably modify the docs to stress this more. It's a framework rather than a drop-in solution.

That said, there should be a way to have validation trigger the client, so I've made  #377.

**Comment by levavakian** [comment]
Thanks for the quick reply!

I figured that was the intention, but I'm still confused as to the best way of swapping in a different serializer. The cleanest way I can think of is to override hydrate to use a custom serializer, and also overriding serialize_data to use that same custom serializer,  but that still feels like I am missing the intended way to swap in a serializer (for example, mimicking how models are swapped in, and being able to say serializer = MyModelSerializer like we can say model = MyModel)

**Comment by andrewgodwin** [comment]
It's not amazing right now, which is why that feature is not considered finalised just yet. The problem is that inbound and outbound serialisation are a bit different, and have to happen in different places, so I'm not sure of the best way to bridge both.

**Comment by levavakian** [comment]
Ah ok, that makes sense. Thanks again!
