### ISSUE TITLE
WebSocket connection denied: origin 'null' not allowed

### ISSUE THREAD

**Issue by BeerChicken** [django/channels#381]
I'm trying to run the examples on this getting started page
http://channels.readthedocs.io/en/latest/getting-started.html

But the javascript examples do not work. From an IE console, I get "WebSocket Error: Incorrect HTTP response. Status code 400, WebSocket connection denied: origin 'null' not allowed"

Firefox: "Firefox can't establish a connection to the server at ...."

Chrome: "WebSocket connection to... failed: Error during WebSocket handshake: Unexpected response code: 400"

The django/runserver error logs: "ws_protocol - WebSocket closed before handshake established
2016-09-30 07:01:34,442 - DEBUG - http_protocol - Connection http.response!Fimiifon did not get successful WS handshake."

**Comment by andrewgodwin** [comment]
Could you get the full HTTP response body with headers out of one of those 400 responses for me? The Daphne logs look like it couldn't even parse the WebSocket request properly.

Are you connecting to daphne/runserver directly? What versions do you have of channels, daphne, twisted, autobahn, and Django?

**Comment by BeerChicken** [comment]
I forgot to add, I was connecting remotely to a url with port 8000, so like the instructions, the connection was ws://xxx.xxx.xx.xx:8000 My django server is on a hosted VPS without a gui and I work on it from remote desktops.

I've tried connecting directly (by way of remote windows or linux host) to the runserver instance at port 8000. Then I've also tried connecting remotely the the normal-config apache reverse proxy (which means I then try ws://xxxx.xxxx.xxxx.xxx at port 80.

Let me see if I can figure out how to get the info you asked. I'm also going to just setup a fully local test and see. This is all a bit new to me. My immediate need is to connect django/websocket to a different remote host running windows and a custom c++ application. I have it working through REST but wanted an easier and more immediate two-way communication method between the 2 systems.

**Comment by andrewgodwin** [comment]
It might well be a configuration setup with the remote server then. I've never heard of this happening locally, so I want the response info to verify if there's some server in the middle between you and the VPS that doesn't support WebSockets properly.

**Comment by BeerChicken** [comment]
Thanks for your help. I'd really like to get this to work. I tried locally with fresh setup and same results. I'll admit it was a rushed test, but I think I followed all the basic setup steps for django and channels. I believe the only difference between this and the production VPS is for some reason my local test environment stuck on python3.

Anyway, same error locally with this javascript console command:

socket = new WebSocket("ws://127.0.0.1:8000");

headers:

GET / HTTP/1.1
Host: 127.0.0.1
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: null
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: kyPExa2hR/2Z/JX418coHw==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

The next 400 code line has these headers:

GET / HTTP/1.1
Host: 127.0.0.1:8000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: null
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: H1fXMDCGBjS4/zCX8OdwUg==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

**Comment by BeerChicken** [comment]
For the VPS connection, it's entirely possible I don't have my Apache reverse proxy setup correctly. I found it hard to find good instructions for my particular implementation. I have ubuntu 16.04 on vps and using webmin/virtualmin to segment the host into a reseller-style hosting arrangement, although I'm not reselling; these are other co-developers on other projects.

Anyway, I wanted to have daphne handle http & websockets connections as it seemed from the channels documentation this is the best arrangement. And I already had a fairly sohpisticated Apache install on this server supporting a few other django and other framework websites. So I figured I could use Apache reverse proxy for the daphne http & websockets on the same port and have Apache serve the static content. I use supervisord to start and manage the interface and workers. Let me know if you want to see those configs.

Here's my virtualserver configuration for this domainname. It is the only website or url configured on that name.

<VirtualHost xxx.xxx.xxx.xxx:80>
SuexecUserGroup "#1024" "#1024"
ServerName x.x.com
ServerAlias x.x.com
ErrorLog /var/log/virtualmin/x.x.com_error_log
CustomLog /var/log/virtualmin/x.x.com_access_log combined
DirectoryIndex index.html index.htm index.php index.php4 index.php5

ProxyPreserveHost On
    # Servers to proxy the connection, or;
    # List of application servers:
    # Usage:
    # ProxyPass / http://[IP Addr.]:[port]/
    # ProxyPassReverse / http://[IP Addr.]:[port]/
    # Example: 
ProxyPass /static !
ProxyPass "/ws/"  "ws://127.0.0.1:8000/"
ProxyPass "/wss/"  "wss://127.0.0.1:8000/"
ProxyPassReverse "/ws/"  "ws://127.0.0.1:8000/"
ProxyPassReverse "/wss/"  "wss://127.0.0.1:8000/"
ProxyPass / http://127.0.0.1:8000/
ProxyPassReverse / http://127.0.0.1:8000/

Alias /static /home/ps/interface/static
<Directory /home/ps/interface/static>
  Require all granted
</Directory>


Everytime I try to connect to the daphne websocket from the root URL, it always assumed http. 
socket = new WebSocket("ws://queue.key1337.com/");

This is why I changed the reverse proxy to use the /ws/ suffix and now tested with:
socket = new WebSocket("ws://queue.key1337.com/ws/");

And the headers from that websocket error I get:

GET /ws/ HTTP/1.1
Host: x.x.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: null
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: yzn2zYHPf97qa3MzMqykmw==
Cookie: csrftoken=YoyDrrgCbd8pflrzrRx6xWVcsi4AzeV7Ehp9t1JGkiP0Yf2YiRFZCXGMcxdncQXY; sessionid=3anxpukkqyimwrczactc44bmmu8dx440
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

**Comment by BeerChicken** [comment]
And during my testing. I also stopped the VPS supervisord port 80 channels and runserver the port 8000 one. Same kind of "origin" errors.

**Comment by andrewgodwin** [comment]
If it's failing locally I want to focus just on that one so we can eliminate some variables!

What versions of the following packages do you have installed locally? Django, channels, daphne, asgiref, twisted, autobahn.

**Comment by BeerChicken** [comment]
OK, after some more testing, I've found out why this is happening. My original testing effort started from Google.com homepage. I could run the JS test code because it complained about something like "running non-ssl websock from ssl website" Google.com being https

So I then tried running the JA code from an about:blank page, which is why I was getting the origin null problem.

I think the django channels intro instructions might need to be updated to reflect that you need to run the JS test code while browsing a valid, non-SSL webpage.

For me it works if I just F12 into the console while browsing my main django website.

**Comment by andrewgodwin** [comment]
Oh, yes, it's meant to be run from a window on the same page, not just a random JS console. I'll update the docs.
