### ISSUE TITLE
API proposal: consumer class demultiplexing

### ISSUE THREAD

**Issue by raphael-boucher** [django/channels#383]
# Current situation on demultiplexing

At the moment, we can't use consumer classes with the websocket demultiplexer.

If actions needs to be performed on connection or disconnection, it has to happen in the demultiplexer.
It forces some coupling between the channel and the demultiplexer, does not give reusability and goes beyond what a demultiplexer should do (transfer messages to the specified channel).

``` python
# Example of a demultiplexed channel for a presence use case
#
# Demultiplexer and consumer are coupled, connection and disconnection happen in the demultiplexer, 
# the rest in functions. Group management happens in the demultiplexer, which should not be the case.

class Demultiplexer(WebsocketDemultiplexer):
    mapping = {
        "presence": "presence.receive",
    }
    http_user = True
    slight_ordering = True
    groups = ['presence-all']

    def connect(self, message, **kwargs):
        """Called when a WebSocket connection is opened."""

        # This is related to the presence consumer and can not be reused easily
        self.group_send('presence-all', {
            message.user.id: 'welcome a new user'
        })
        message.user.online = True
        message.user.save()

    def disconnect(self, message, **kwargs):
        """Inform other users of the disconnection"""

        # This is related to the presence consumer and can not be reused easily
        self.group_send('presence-all', {
            message.user.id: 'Bye by to a user'
        })
        message.user.online = False
        message.user.save()


@channel_session_user
def presence_receive(message):
    # simple echo
    Demultiplexer.send('presence', message)


# Add routing for both classes
channel_routing = [
    route_class(Demultiplexer, path=r'^/ws/$'),
    route('presence.receive', presence_receive),
]
```
# New proposed API: the class consumer demultiplexer

I offer to implement a websocket demultiplexer that handle classe consumers, based on the `WebsocketDemultiplexer`. This demultiplexer would forward all messages, including connection and disconnection to the channels of all given consumer classes.

This would work with a new consumer class, called `DemultiplexedConsumer` based on the JsonWebsocketConsumer. 
A new attribute `stream_name` gives the name of the demultiplexed stream. This name would be used to generate dynamically the `method_mapping`:

``` python
# Default mapping for a websocket class
method_mapping = {
    "websocket.connect": "raw_connect",
    "websocket.receive": "raw_receive",
    "websocket.disconnect": "raw_disconnect",
}

# Dynamic mapping for the demultiplexed consumer class
method_mapping = {
    "{}.connect".format(cls.stream_name): "raw_connect",
    "{}.receive".format(cls.stream_name): "raw_receive",
    "{}.disconnect".format(cls.stream_name): "raw_disconnect",
}
```

This kind of channels would simply not be plugged directly to the websocket, but use the demultiplexer to do so. It also means they can be given messages directly from others sources without going through the layers handling websocket messages. 
# Initial example with the consumer demultiplexer

``` python
# Example using the proposed consumer demultiplexer API
#
# Demultiplexer and consumer are not coupled, everything happens in the consumer.
# Group management is as simple as in the WebsocketConsumer.

class PresenceConsumer(DemultiplexedConsumer):
    stream_name = 'presence'

    # http user is already found by the demultiplexer, but it can also be used if
    # the consumer is used outside of it
    channel_session_user = True
    groups = ['presence-all']

    def connect(self, message, **kwargs):
        """Called when a WebSocket connection is opened."""
        self.group_send('presence-all', {
            message.user.id: 'welcome a new user'
        })
        message.user.online = True
        message.user.save()

    def disconnect(self, message, **kwargs):
        """Inform other users of the deconnection"""
        self.group_send('presence-all', {
            message.user.id: 'Bye by to a user'
        })
        message.user.online = False
        message.user.save()

    def receive(self, message):
        # Simple echo
        self.send(message)


class MyClassDemultiplexer(WebsocketConsumerDemultiplexer):
    http_user = True
    slight_ordering = True

    consumers = [
        PresenceConsumer,
    ]

# Add routing
channel_routing = [
    route_class(MyClassDemultiplexer, path=r'^/ws/$'),
    route_class(PresenceConsumer),
]
```

**Comment by BeerChicken** [comment]
This would be very useful to me. I'm currently trying to use the Demultiplexer for a single websock channel having composite incoming commands to a server. Would you mind telling me what is the correct format for the incoming websock frame for the demultiplexer? I know there is supposed to be stream and payload keys, but I'm having difficulty formatting it correctly. I'm getting the "Multiplexed frame payload is not a dict" error. The sending websock is C++ using MS cpprestsdk. My websock frame looks like this when received by channels:

{'order': 1, 'text': '{"payload":"{data: none}","stream":"SYNC"}', 'reply_channel': 'websocket.send!FqGLqzNodmXb', 'path': '/server/game/2/'}

Thanks for any help.

**Comment by BeerChicken** [comment]
Go it working with a structure like this from C++ sending websocket:

{'order': 1, 'text': '{"payload":{"DATA":"none"},"stream":"SYNC"}', 'reply_channel': 'websocket.send!DZmHjKkLsGeQ', 'path': '/server/game/2/'}

Apologies if I somewhat hijacked your thread. I am very interested in seeing the multiplexing capabilities enhanced in channels though. Seems like it is an essential part of making a complex overall system using websockets work effectively, especially with a command structure being sent between the client(s) and server(s).

**Comment by andrewgodwin** [comment]
@raphael-boucher: My current thought is, would it be possible to have the consumer classes be the same as the normal ones and not need a new subclass? The stream name would need to be moved into the demulitplexer and make consumers a dict, but I think I'd prefer that anyway. Are there other problems you forsee?

**Comment by raphael-boucher** [comment]
Currently, I register new channels with a method mapping generated from the stream name, and I'm forwarding the message content to these registered channels. 
I could forward the message content to the `raw_*` methods instead and remove the stream names from the consumer, but I can't send a reply if the consumer does not know it's demultiplexed. Even if it knows, it needs to override the `send` method to give the message to the demultiplexer. I don't see another solution than a new consumer right now, or maybe a mixin...

**Comment by andrewgodwin** [comment]
Well, you could just instead use the routing interface of the consumers - pass the message onto the `dispatch` method on the sub-consumer and it'll handle the rest for you, and avoid registering the sub-consumers' channels out onto the wider routing altogether.

**Comment by raphael-boucher** [comment]
Yes, it would be better.

There is still the problem of sending replies from the consumer, because they can't be formatted without access to the demultiplexer, or at least knowing the stream name.

**Comment by andrewgodwin** [comment]
Hm, that's very true. Can't even use a new channel for the reply as routing doesn't work like that.

Couple of ideas:
- Make the base consumer class provide a way to override send formatting from the outside (it would only need to be send, not send_group)
- Pass the demultiplexer through to the handlers as a kwarg - people would have to add it in themselves, but that's probably quite nice due to its explicitness. Downside is that self.send doesn't work right.
- Make message.reply_channel be an object that's not actually a channel but still has a `.send` method, just no `.name`. I think none of the existing code would be effected in this case.

**Comment by raphael-boucher** [comment]
Thanks for the ideas. I think I will go with the first option because it feels easier to use than the second and less hacky than the third.

**Comment by andrewgodwin** [comment]
My only issue with the first is that won't effect people who use `message.reply_channel.send` directly in the consumer like a lot of the examples say, while the third one would catch this. I'd say we need to make sure `message.reply_channel` is set to `None` in that first case, and it should be OK and error properly when someone tries!

**Comment by raphael-boucher** [comment]
Added in #420
