### ISSUE TITLE
ChannelsTestCase not working as expected

### ISSUE THREAD

**Issue by carn1x** [django/channels#384]
So I have the following routing/consumers:

routing.py
```
channel_routing = [
    route("websocket.connect", feed_connect, path=r'^/feed/'),
]
```

consumers.py
```
def feed_connect(message):
    Group('fixture_feed').add(message.reply_channel)
    websocket_send(message.reply_channel, message_text='Fixture feed connected.')
```

And the following test that is working as expected
test_routing.py
```
class RoutingTests(TransactionTestCase):
    def test__websocket_connect_fixture_feed(self):
        channel_layer = channel_layers['default']
        message = Message({'path': '/fixtures/feed/'}, 'websocket.connect', channel_layer='fake channel layer')
        self.assertEqual(channel_layer.router.match(message), (feed_connect, {}))
```

However my consumer test is not working:
test_consumers.py
```
class ConsumerTests(ChannelTestCase):
    def test__sends_success_message_to_reply_channel(self):
        Channel('websocket.connect').send({'path': '/fixtures/feed/'})
        message = self.get_next_message('websocket.connect', require=True)
        self.assertIsNotNone(message.reply_channel)  # Fails
```
Fails with:
```
======================================================================
FAIL: test__sends_success_message_to_reply_channel (fixture.tests.test_consumers.ConsumerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/www/apps/fixture/tests/test_consumers.py", line 16, in test__sends_success_message_to_reply_channel
    self.assertIsNotNone(message.reply_channel)
AssertionError: unexpectedly None
```

It's not clear to me from the example code at http://channels.readthedocs.io/en/latest/testing.html#channeltestcase whether I'm really understanding or if there is a bug, etc.

**Comment by andrewgodwin** [comment]
Your code is incorrect in this case, but I'm not sure what your intentions were, so I need to know that to help you fix it!

In the example you provided, you send an incomplete connect message onto the `websocket.connect` channel and then receive off of that same channel one line later.

Either you want to:
* Send a complete connect message including reply_channel so that your second line has a reply_channel to look at, or;
* Send a reply_channel in your initial message and then run `get_next_message` on that reply channel to get the response from the consumer, which you can then look at.

**Comment by carn1x** [comment]
Ahh yes, details! My end goal is to produce something like the following:

```
    def test__sends_success_message_to_reply_channel(self):
        Channel('websocket.connect').send({'path': '/fixtures/feed/',
                                           'reply_channel': 'test__sends_success_message_to_reply_channel'})
        message = self.get_next_message('websocket.connect', require=True)
        self.assertIsNotNone(message.reply_channel)
        result = self.get_next_message(message.reply_channel.name, require=True)
        self.assertEqual(result.content, json.dumps({'message_text': 'Fixture feed connected.'}))
```

It might help if I provided the code for `websocket_send()` too:
```
def websocket_send(channel, **kwargs):
    channel.send({'text': json.dumps(kwargs)})
```

I've integrated sending the `reply_channel` as you suggested, and I'm now seeing the following failure:
```
======================================================================
FAIL: test__sends_success_message_to_reply_channel (fixture.tests.test_consumers.ConsumerTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/www/apps/fixture/tests/test_consumers.py", line 18, in test__sends_success_message_to_reply_channel
    result = self.get_next_message(message.reply_channel.name, require=True)
  File "/virtualenv/myapp/local/lib/python2.7/site-packages/channels/tests/base.py", line 67, in get_next_message
    self.fail("Expected a message on channel %s, got none" % channel)
AssertionError: Expected a message on channel test__sends_success_message_to_reply_channel, got none
```

Thanks for the help so far!

**Comment by andrewgodwin** [comment]
I still don't understand what exactly you're trying to test. Are you just trying to test the code for `websocket_send`? If you are you're doing way more than you need to.

Also, you're consuming off of `websocket.connect`, and somehow expecting a reply to have been sent. If you're consuming then something else isn't (channels are just pipes) so there's no way your consumer code will get run.
