### ISSUE TITLE
How to access ipaddress in headers from connect overload in WebsocketDemultiplexer

### ISSUE THREAD

**Issue by BeerChicken** [django/channels#385]
I'm trying to extract the ip address of an incoming websocket connect coming into a WebsocketDemultiplexer I can see it in the 'headers' key of message.content["headers"] but cannot figure out how to extract it. The index position of these fields seem to change per connection.

`
class Demultiplexer(WebsocketDemultiplexer):
    mapping = {
        "SYNC": "sync.receive",
    }
    http_user = True

    def connect(self, message, **kwargs):
        logger.info(message.content["headers"])`

[[b'upgrade', b'WebSocket'], [b'x-forwarded-server', b'xx.xx.com'], [b'host', b'queue.key1337.com'], [b'connection', b'Upgrade'], [b'user-agent', b'WebSocket++/0.5.1'], [b'x-forwarded-host', b'xx.xx.com'], [b'sec-websocket-key', b'7v1ryYQg7VhrxPolaoe1jg=='], [b'x-forwarded-for', b'123.123.123.123'], [b'sec-websocket-version', b'13']]

**Comment by andrewgodwin** [comment]
You should feed that list into a dict and look it up by key.

**Comment by BeerChicken** [comment]
Thought there must be an easy way but I'm pretty new to py/dj/chan world

**Comment by BeerChicken** [comment]
Well, I gotta imagine there was an easier way to do this, but here's how I finally isolated and extracted the ip address.

`
hdr_utf8 = message.content["headers"]
hdr_utf8[:] = [[item.decode('utf8') for item in subl] for subl in message.content["headers"]]
logger.info(dict(hdr_utf8)["x-forwarded-for"])
`

**Comment by andrewgodwin** [comment]
You could also do:

```
xff = dict(message.content["headers"])["x-forwarded-for"].decode("utf8")
```

**Comment by BeerChicken** [comment]
That's a nice concise line but I get an error when using it:

AttributeError: 'str' object has no attribute 'decode'

**Comment by andrewgodwin** [comment]
Are you using Python 3 or Python 2?

**Comment by BeerChicken** [comment]
3.5.2 inside a virtualenv where django script is running. 2.7.12 outside on host, if that matters

**Comment by andrewgodwin** [comment]
Weird, the headers are meant to be `bytes`, and your previous snippet has a `decode` in it as well. No idea how it got to be a `str`.

**Comment by BeerChicken** [comment]
Yeah, I had to convert them in order for the key lookup to work. Along the way of figuring it all out, I did get the same kind of error message before finding my solution.

What's weird is if I run the sequence like this:

        logger.info(dict(message.content["headers"]))

        hdr_utf8 = message.content["headers"]
        hdr_utf8[:] = [[item.decode('utf8') for item in subl] for subl in message.content["headers"]]

        logger.info(dict(message.content["headers"]))

        logger.info(dict(hdr_utf8)["x-forwarded-for"])

I get this output:

{b'host': b'xx.xx.com', b'connection': b'Upgrade', b'x-forwarded-for': b'xxx.xxx.xxx.xxx', b'x-forwarded-host': b'xx.xx.com', b'x-forwarded-server': b'xx.xx.com', b'user-agent': b'WebSocket++/0.5.1', b'sec-websocket-key': b'PB2o6rDaCgh+c+QPzQICwA==', b'upgrade': b'WebSocket', b'sec-websocket-version': b'13'}

{'host': 'xx.xx.com', 'connection': 'Upgrade', 'x-forwarded-for': 'xxx.xxx.xxx.xxx', 'x-forwarded-host': 'xx.xx.com', 'x-forwarded-server': 'xx.xx.com', 'user-agent': 'WebSocket++/0.5.1', 'sec-websocket-key': 'PB2o6rDaCgh+c+QPzQICwA==', 'upgrade': 'WebSocket', 'sec-websocket-version': '13'}

xxx.xxx.xxx.xxx

It's like somehow doing the decoding in-place in the original "headers" area of message.content

**Comment by andrewgodwin** [comment]
It's because you're assigning to `hdr_utf8[:]` not `hdr_utf8` - you're updating the list in place rather than replacing it with a new value,

**Comment by BeerChicken** [comment]
Oh that's probably not good to alter the original data structure. I would have thought since I made a copy of the headers portion into hdr_utf8 it was just working on that var.

I think my understanding of python is less than ideal because even if I change the lines to:

        hdr_utf8 = message.content["headers"]
        hdr_utf8[:] = [[item.decode('utf8') for item in subl] for subl in hdr_utf8]

It has the same output, like changing the original "headers" in message.content.

**Comment by andrewgodwin** [comment]
You really don't ever want to assign to `sequence[:]` - I can't think of a good reason to do it unless you specifically need to mutate a list in-place, which is usually not what you want.

**Comment by BeerChicken** [comment]
Ahh, this does the trick of keeping it separate:

hdr_utf8 = list(message.content["headers"])

**Comment by BeerChicken** [comment]
This is your line that works!

xff = dict(message.content["headers"])[b'x-forwarded-for'].decode("utf8")

**Comment by KimSJ** [comment]
It's possible that what you really want (or want as well) is `message.content['client'][0]`, which is the IP address that Django is interacting with. afaik that can't be spoofed, but of course it can be the address of a proxy server. You may wish to log the port too, which is the [1] value.

**Comment by andrewgodwin** [comment]
If you wish to use x-forwarded-for, you can start Daphne with `--proxy-headers` and then it'll parse the X-Forwarded-For header and put it into `client` for you. It's off by default for security reasons as you need to make sure you have a proxy that strips it out from further downstream if you use it.

**Comment by KimSJ** [comment]
Andrew: Forgive me if I'm missing the obvious, but I was puzzled by your "It's off by default for security reasons as you need to make sure you have a proxy that strips it out from further downstream if you use it." Why is that a security risk?

As a wider question, when would `--proxy-headers` be useful? As a responsible host site, surely logging `client`, `X-Forwarded-For`, and possibly rfc7239's `Forwarded` headers is the best (and right) thing to do. Anything else is possibly throwing away interesting information.

**Comment by andrewgodwin** [comment]
If you don't configure your webserver/load balancer to strip out the `X-Forwarded-For` header (which many do not by default), then clients can just pass it along in their requests and overwrite what your server thinks the remote IP is, which is Bad.

`--proxy-headers` is so that you can, if you wish, have Daphne treat those headers as the canonical source of information and pass that as the `client` value in the messages. It's not especially useful for normal Django views as there's middleware that can parse `X-Forwarded-For` anyway, but it is useful for websocket connections where there's no such thing and it's way nicer to be able to use `message['client']`.

**Comment by Mavi32** [comment]
logger.info(dict(message.content["headers"]))
AttributeError: 'str' object has no attribute 'content'

@generationtech  I got this error .. help me through this
