### ISSUE TITLE
Improved options for runserver

### ISSUE THREAD

**Issue by RockHoward** [django/channels#386]
It should be possible to specify selected daphne settings from the runserver command line and/or from django settings. The http_timeout setting is the key one for me, but other options might also deserve improved support as well.

(Apologies if there is a straightforward way to do this already. If that is the case, then treat this issue as a call for improved documentation about this capability.)

I am using direct invocations of 'daphne' and 'runworker' as a work around and so this is not a high priority request. However runserver is more convenient for development given the auto-restart logic and so this request still stands.

**Comment by andrewgodwin** [comment]
I've just been advising people to use daphne directly, but I agree autoreload is nice. I'd want these done as command line options to runserver, not settings, but it's not a high prority compared to other stuff I have to look at  - patches welcome, however.

**Comment by RockHoward** [comment]
Given that useful feedback, it was a snap to add --http_timeout (and it works).

Attached is the git diff output for the runserver.py management command.

[runserver.py.diffs.txt](https://github.com/django/channels/files/514957/runserver.py.diffs.txt)

**Comment by andrewgodwin** [comment]
Is there a way you could push it up as a pull request? That will make it a lot easier to review.

**Comment by RockHoward** [comment]
Done.

**Comment by andrewgodwin** [comment]
I'm going to close this after the PR was accepted - if more options need exposing we can add them as people request them.
