### ISSUE TITLE
I/O Bound Workers

### ISSUE THREAD

**Issue by hassa** [django/channels#390]
Hi all,

Is there a recommended strategy for heavily I/O bound consumers?

Let me elaborate: A lot of our current standard Django code spends a lot of time calling external APIs. We currently use gunicorn with gevent.

From reading the code, I can see that we can run multiple worker threads per worker process, but since these are just python threads, they would still block the whole worker process on I/O.

Has anyone attempted to run green workers via gevent/eventlet or anything like that?

**EDIT**: So I just went ahead and tried running gevented workers by adding this to the top of manage.py:

```
from gevent import monkey
from psycogreen.gevent import patch_psycopg

monkey.patch_all()
patch_psycopg()
```

and our tests pass, but I am still very keen to hear thoughts/opinions.

**Comment by andrewgodwin** [comment]
You may try and use gevent if you wish, but it's not officially supported (as making a correctly greenthread-compatible version would prove difficult) and you may have errors. You might want to consider configuring one set of workers to run under gevent and one not, and run different channels via the `--only-channels` or `--exclude-channels` `runworker` arguments.
