### ISSUE TITLE
Very naive checking __all__ fields in WebsocketBinding

### ISSUE THREAD

**Issue by approxit** [django/channels#394]
Currently making bindings to render all fields are done with [single-element-list checking](https://github.com/django/channels/blob/075897d9107b89edadcb5aca34d371df46370820/channels/binding/websockets.py#L58):

```python
def serialize_data(self, instance):
    """
    Serializes model data into JSON-compatible types.
    """
    if self.fields == ['__all__']:
        fields = None
    else:
        fields = self.fields
    data = serializers.serialize('json', [instance], fields=fields)
    return json.loads(data)[0]['fields']
```

We have couple of problems here:

1. Forces to use only `list`. Many peoples (including me) are using `tuples` for constant data like fields definition in classes. 

        # python console
        > ('__all__',) == ['__all__']
        False

2. It's not django-like. Django uses [`fields = '__all__'`](https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/#selecting-the-fields-to-use) for all fields. Not `['__all__']`. Let's make it the same!

3. Using `tuple` results empty `payload.data` pushed via websocket (is it necessary anyways?) which is hard to debug for developers that are not so advanced to browse libraries source code.

**Comment by andrewgodwin** [comment]
I agree - I should have caught that one in code review. Happy to change it if you want to send in a PR, or I'll queue it up to get fixed later on.

**Comment by andrewgodwin** [comment]
Fixed by #399.

**Comment by approxit** [comment]
@jtiki @andrewgodwin 
I'm glad to see someone made fix. It will work not with `tuple`, yay.

But how about django-like approach `fields = '__all__'`? It would be simpler and... it would be breaking change. But hey, better now, in this stage of project, than later, with stable API.

**Comment by jeremytiki** [comment]
@approxit Did you download the channels code straight from Github or through PyPi? If you only used pip to install channels the fix may not have been pushed along that far yet.

The fix I submitted simply wrapped the field value in a `list()` function and `list(('__all__',)` does in fact work.

**Comment by approxit** [comment]
@jeremytiki Oh, I'm sorry. Typo, "not" was totally unnecessary. Code work just fine. Thx for fix.

Whats you say about unifying `__all__` fields with django?

**Comment by jeremytiki** [comment]
Using '__all__' will also work. As I said the channels function now converts whatever value is given to a list, so any string or iterable will work.

**Comment by approxit** [comment]
Will work...?

Python `list` constructor takes argument as iterable. Giving string to that argument will iter over that string and make separate element for character.

Let's go to python console:
```
>>> fields_tuple = ('__all__',)
>>> fields_list = ['__all__']
>>> fields_string = '__all__'
>>> list(fields_tuple) == ['__all__']
True
>>> list(fields_list) == ['__all__']
True
>>> list(fields_string) == ['__all__']
False
>>> list(fields_tuple)
['__all__']
>>> list(fields_list)
['__all__']
>>> list(fields_string)
['_', '_', 'a', 'l', 'l', '_', '_']
```

So `fields = '__all__'` will not work as expected and that's why I'm a little inquiring.
