### ISSUE TITLE
Can multiple channels deployments share a Redis DB?

### ISSUE THREAD

**Issue by oTree-org** [django/channels#395]
I want to run multiple Django/channels projects on the same server, using separate instances of daphne (binding to different ports). Is it OK to have all these projects share the same Redis DB ``redis://localhost:6379``? Or should I separate into ``redis://localhost:6379/0``, ``redis://localhost:6379/1``, ``redis://localhost:6379/2``, or run multiple Redis instances on separate ports, etc.

My first instinct was to use multiple databases as I would with Postgres, but Redis seems to discourage using multiple databases: https://code.google.com/archive/p/redis/issues/662#c4

**Comment by andrewgodwin** [comment]
You should use the `prefix` setting instead to make sure the various instances don't clash: https://github.com/django/channels/issues/391#issuecomment-252524065

**Comment by oTree-org** [comment]
Great thanks!
