### ISSUE TITLE
path matching in multiple steps as with urls?

### ISSUE THREAD

**Issue by pcompassion** [django/channels#405]
for url, I can match `^my_app/path_after_my_app/` with the following set up

in my root url
`url(r'^my_app/', include(my_app.urls))`

in my app url
`url(r'^path_after_my_app/$', my_view, name='my_view')`

The url is matched first by first rule, and then matched by next rule.
I couldn't find an example how to do this with routing.py

**Comment by andrewgodwin** [comment]
Routing works in exactly the same way, though of course the way you specify path is different:

`include(foo.bar, path='^my_app/')`

`route(baz.bang, path='^after_my_app/)`

Bit more about it in the docs: http://channels.readthedocs.io/en/stable/routing.html#filters
