### ISSUE TITLE
Various route functions to websocket.disconnect

### ISSUE THREAD

**Issue by krailler** [django/channels#406]
If posible to route websocket.disconnect, to various functions? Y use various urls, which include functions, and some urls has websocket.disconnect, but only first is called.

Some help? Or is it not possible?
Thx.

**Comment by andrewgodwin** [comment]
It will route to the first match in the routing (http://channels.readthedocs.io/en/latest/routing.html) list. If you need to call multiple functions for each disconnect, call all of them from a single disconnect consumer.
