### ISSUE TITLE
How to write a "middleware" for custom processing of exceptions?

### ISSUE THREAD

**Issue by oTree-org** [django/channels#407]
In my app I have a middleware that uses ``process_exception`` to catch all instances of `OperationalError`, and reraise them with a custom error message. However, this is not catching exceptions that are occurring in my channels consumers. How can I do this? Is there a special middleware technique or something similar?

**Comment by andrewgodwin** [comment]
You'd need to either hook into the logging system to catch exceptions, or write your own decorator and apply it to consumers - there is no middleware concept. See #180
