### ISSUE TITLE
Bindings.serialize_data and Multiple-Table-Inheritance

### ISSUE THREAD

**Issue by AlexejStukov** [django/channels#409]
Since the ``serialize_data`` function of ``WebSocketBinding`` uses the standard serializer of django, you can't get the fields of the parent by serializing the child. This makes [sense](https://docs.djangoproject.com/en/dev/topics/serialization/#inherited-models) for django, but not for the bindings in channels. 
Example:
````python
# models.py
class Parent(models.Model):
    value_parent = models.FloatField()

class Child(Parent):
    value_child = models.IntegerField(default=3)

# consumers.py
class ChildBinding(WebsocketBinding):
    fields = ["value_child", "value_parent"]

# output of serialize_data: {"value_child": 3}
````
Maybe an own serializer like [this](https://github.com/zmathew/django-backbone/blob/351fc75797bc3c75d2aa5c582089eb39ebb6f19a/backbone/serializers.py) should be used or one could call ``serialize_data`` on the parent instance. At least a hint about this should be in the docs and/or a warning/error could be raised if the fields specified are not on the child class.
I'm unsure which approach should be taken...

**Comment by andrewgodwin** [comment]
At the moment the current stance is that you should probably swap out the default serialiser for one from Django REST framework, so any issues about extending its functionality I would usually close (as I will this, as I don't believe in adding this right now). There is a more overarching need for documentation about bindings, though, including examples like this.
