### ISSUE TITLE
How to determine if a particular message is over 1MB in size before sending

### ISSUE THREAD

**Issue by Key1337** [django/channels#410]
How are we to avoid trying to send a message over 1MB in size? Is there some way to determine message size beforehand in the manner in which channels calculates it? If not, is there some provision to reject or otherwise provide feedback that a message is too large when sending? If so (I guess also if not) does the entire message fail or just a portion or is it unpredictable? Thanks for the help

**Comment by andrewgodwin** [comment]
There's an exception provisioned for backends to raise if it's too high, but generally the idea is for anything sending messages over the wire to chunk them to a much smaller size (I think daphne/channels goes for 256kb right now?)
