### ISSUE TITLE
query_string as bytes rationale.

### ISSUE THREAD

**Issue by tomchristie** [django/channels#411]
Where most parts of an incoming HTTP request are decoded into unicode, and paths are percent escapes, the same is not true of `query_string`. Wondering what the rationale is here, and if it's worth a sentence in the documentation or not.

**Comment by andrewgodwin** [comment]
It's actually already covered in another issue, but basically it's because query string decoding is entirely down to the application and can't be done at the server level automatically: https://github.com/django/channels/issues/210
