### ISSUE TITLE
`more_body` / `body_channel` mismatch

### ISSUE THREAD

**Issue by tomchristie** [django/channels#412]
The ASGI docs cite [`"more_body"`](http://channels.readthedocs.io/en/stable/asgi.html#request) as the key with which to obtain the body channel,  but the Django channels implementation uses [`"body_channel"`].(https://github.com/django/channels/blob/1673be5b75ddf1f2b6de5687c7de85a4d20ffcb2/channels/handler.py#L110)

Presumably the documentation needs updating here, rather than the other way around.

**Comment by andrewgodwin** [comment]
Yes, the docs even use `body_channel` in one place but not another. Fixed in c16de0e.
