### ISSUE TITLE
Enable server specify code and reason when closing a websocket connection

### ISSUE THREAD

**Issue by tyler46** [django/channels#414]
Hi, 

It would be nice to have a way to specify the close code or close reason when server decides to close a web socket connection.

(Issue was first mentioned as #327)

**Comment by rixx** [comment]
I'm working on this at DUTH sprints right now. ✨

We decided to go with the closing code, but not the optional additional reason.

**Comment by tyler46** [comment]
Hi all, many thanks for the effort. I will try to implement the the optional additional reason and come back to you!
:+1:

**Comment by andrewgodwin** [comment]
Closing this as we indeed added in closing code, and I'm fine leaving reason out.
