### ISSUE TITLE
How to separate http.request, some handle by django urls.py, some handle by consumer?  

### ISSUE THREAD

**Issue by 1msoft** [django/channels#415]
I have a web app to control large file uploads.

1. client request a token to upload file.
2. web app return token to client or not.
3. client upload file to another worker process with token.

**Comment by andrewgodwin** [comment]
Run both Daphne and a WSGI server and have a webserver in front configured to route to different backends by path (you can find examples around for nginx easily)

**Comment by 1msoft** [comment]
Run two server, app can't send message by channels or share models. so maybe use websocket channel to upload files.

**Comment by pplonski** [comment]
You can find example how to configure nginx here: https://github.com/pplonski/simple-tasks
