### ISSUE TITLE
Filter data for specific channels

### ISSUE THREAD

**Issue by timofurrer** [django/channels#419]
Let's assume I have some reporting UI with some channels open to the backend where data updates are sent to the clients. 
The client has the option to filter for only some specific data. In our case it makes sense to filter those data in the backend and not ignore them in the client if we are not interested in those updates.

The thing is that if we pass the filter option in the URI query string and create a group for that we could end up having a huge amount of groups. In the worst case we'd have one group per client which doesn't make sense at all ..

What is the recommended way to implement such a functionality without having to implement a concept on top of channel groups?

**Comment by andrewgodwin** [comment]
I would invert what you're saying and do one group per kind of update (assuming it's a discrete set of options), and then only add the channel to the groups of the types of messages it needs.

If the set of possible message types is large or unbounded, that's not possible and you'll instead have to do your own tracking of what client wants what, using a custom channel to pass messages into a consumer that reads a table of reply channels and their filters and dispatches appropriately.
