### ISSUE TITLE
How to handle Video/Audio streaming using Django Channels?

### ISSUE THREAD

**Issue by sandro-salles** [django/channels#423]
Can't find any documentation on how to handle video/audio streaming using Django Channels.

I've found an incomplete tutorial here:
https://artandlogic.com/2016/06/django-channels-ground-part-1/
https://artandlogic.com/2016/06/django-channels-ground-part-2/

But as i said, it's incomplete... 

Can someone give-me a hand here?

Thanks in advance!

**Comment by andrewgodwin** [comment]
Please submit questions about using Channels to django-users@googlegroups.com (https://groups.google.com/forum/#!forum/django-users), not the issue tracker - thanks!

(as an aside, I have not done this personally so can't help unless you have a specific question)
