### ISSUE TITLE
JsonWebsocketConsumer drops session, and user between connect and receive

### ISSUE THREAD

**Issue by boydjohnson** [django/channels#433]
I am using channels==0.17.3, daphne==0.15.0, asgiref==1.0.0 and have seen an error where http_user=True and the correct user is there in connect, but AnonymousUser in receive. I reworked the testproject in [channels to show this error](https://github.com/boydjohnson/channels/commit/c3762fb0ea8f441488b184ecd83236c862465926). My test sends a message from the javascript client onopen to the server. In receive the consumer asserts that the user is not an instance of Anonymous user and then sends a message back to the client. If the client receives the message the assertion holds. I run that setup in the test 20 times (and usually ~10 times pass) and then assert that all the tests pass. To run the test you need ChromeWebDriver in your PATH.

**Comment by andrewgodwin** [comment]
Your consumer does not enforce ordering, so connect will sometimes run at the same time as receive, giving you this error. Set `strict_ordering=True` for now to get it to work on the released version, and the master branch already enforces this all the time.
