### ISSUE TITLE
how to  cofing logger of the channel async task

### ISSUE THREAD

**Issue by dhcn** [django/channels#436]
I want to send email for error in async task of channel.
I do'nt know the error logger name.

Please submit **questions** about usage to django-users@googlegroups.com (https://groups.google.com/forum/#!forum/django-users) and about development to django-developers@googlegroups.com (https://groups.google.com/forum/#!forum/django-developers).

If you're submitting a feature request, please try to include:

- Detailed description of the overall behaviour
- Reasoning why it should be in Channels rather than a third-party app
- Examples of usage, if possible (it's easier to discuss concrete code examples)

If you're submitting a bug report, please include:

- Your OS and runtime environment, and browser if applicable
- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally)
- What you expected to happen vs. what actually happened
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
- Console logs and full tracebacks of any errors

**Comment by andrewgodwin** [comment]
Any uncaught error in consumers will bubble up to the `django.channels` logger. Please ask questions like this in the right mailing list next time as the text in the issue template suggests.
