### ISSUE TITLE
Add reference documentation for all decorators

### ISSUE THREAD

**Issue by ericholscher** [django/channels#443]
I've seen a few different decorators used (like `channel_session`) in the docs, but don't have good reference information for them.

**Comment by Skorpyon** [comment]
@ericholscher You're welcome, bro. If you have a time, just make docs and pull request )))

**Comment by andrewgodwin** [comment]
Agreed, this would be good to have.

**Comment by mikebarkas** [comment]
I would like to work on this issue. I will make a list of the decorators and an overview of what each one does.

This will be a good exercise for me as I am building my experience and knowledge of Python and Django. I am open to constructive criticism.

**Comment by andrewgodwin** [comment]
I can't assign people who aren't contributors, annoyingly, but feel free to take it and open a PR when you're ready.

**Comment by andrewgodwin** [comment]
Reference docs are all in place for these now.
