### ISSUE TITLE
Can't see change log description for version 0.17.3 and it has breaking changes

### ISSUE THREAD

**Issue by mwaaas** [django/channels#446]
Have upgraded to version 0.17.3 and it had breaking changes. 

File "/usr/src/app/core/consumers.py", line 28, in connect
web_worker_1  |     AccountBinding.trigger_outbound(
web_worker_1  | AttributeError: type object 'AccountBinding' has no attribute 'trigger_outbound'

Can't find any documentation on changelog regarding version 0.17.3

**Comment by andrewgodwin** [comment]
Ah, yes, I had to rush that out as 1.0 is taking a long time. Unfortunately, that isn't considered a breaking change as the databinding is still alpha; I'm trying my best to keep the API very similar, but that method was not publicly documented and so it's not going to stay the same.

I'd wait until the 1.0 release at least until building anything on databinding, and even then it may have a few future changes.

I've added 0.17.3 to the changelog too.
