### ISSUE TITLE
Data binding in custom management command

### ISSUE THREAD

**Issue by zeezdev** [django/channels#447]
I start work with django channels. I need bind data of my model Device. I do it. When I change Device object in admin interface I get message about changing on client (web browser) but I also run simple  custom django management command. And when Device-object has been changed in custom command process I don't receive any message on client. How I can fix it?

**Comment by vanikin** [comment]
Do you use 'save' method in your management command?

**Comment by zeezdev** [comment]
Yes, I use save method after changing of data of object in my management command. I describe my problem on stackoverflow:

http://stackoverflow.com/questions/40995897/databinding-with-django-channels-in-custom-command

**Comment by zeezdev** [comment]
I accidentally discovered that if add this code in begin of my management command, subsequent changes to the objects come to the client:

```python
from channels import Channel
Channel("binding.devices").send({})

```

It's like some kind of initialization. What it is work?! 
It is my workaround) but I would like to know the right solution. Thanks!

**Comment by andrewgodwin** [comment]
Did you add `channels` to INSTALLED_APPS? It might be that it's never being imported until you do so, triggering the hooks.

Closing this as questions like this should be asked on django-users.

**Comment by zeezdev** [comment]
Yes. I add 'channels' app in to INSTALLED_APPS in settings of my project.
