### ISSUE TITLE
KeyError and then @enforce_ordering causes ValueError: No `order` value in message

### ISSUE THREAD

**Issue by Key1337** [django/channels#450]
I think I'm having the case where the connect message is processed after my consumer. Occasionally I get the KeyError message, but most of the time it works. I tried adding @enforce_ordering but that only causes the "ValueError: No `order` value in message; @enforce_ordering can only be used on messages containing it." I am using a demultiplexer

    from django.db import transaction
    from channels.routing import route, route_class
    from channels.generic.websockets import WebsocketDemultiplexer
    from channels.sessions import channel_session, enforce_ordering
    from one_database.models import Server
    import logging

    from one.consumers import game_command_RQ

    channel_routing = [
        route_class(GameDemultiplexer, path=r"^/server/(?P<server_key>[a-zA-Z0-9]+)$"),
        route("game_ready.receive", game_command_ready),
        route("game_RQ.receive", game_command_RQ),

________________________________________________________

    class GameDemultiplexer(WebsocketDemultiplexer):
        mapping = {
            "READY": "game_ready.receive",
            "RQ": "game_RQ.receive",
        }
        http_user = True

        @transaction.atomic
        @channel_session
        def connect(self, message, **kwargs):
            skey = kwargs["server_key"]
            message.channel_session["server_key"] = skey
            logger.info("Server key:  " + skey)
            sip = dict(message.content["headers"])[b'x-forwarded-for'].decode("utf8")
            logger.info("Server IP:   " + sip)
            try:
                srv = Server.objects.select_for_update().get(server_key=skey, server_ipaddress=sip)
                logger.info("Server Name: " + srv.server_name)
                srv.server_game_channel=message.reply_channel
                srv.save()
            except Server.DoesNotExist:
                logger.info("Server not found!")
                self.close()
            pass
        
        @transaction.atomic
        def disconnect(self, message, **kwargs):
            logger.info("\n<game>: Disconnected")
            skey = kwargs["server_key"]
            logger.info("Server key:  " + skey)
            try:
                srv = Server.objects.select_for_update().get(server_key=skey)
                logger.info(srv.server_name)
                srv.server_game_channel=""
                srv.save()
            except Server.DoesNotExist:
                logger.info("Server not found!")
                self.close()
            pass

________________________________________________________

    import json
    from django.core import serializers
    from enum import Enum
    from channels.sessions import channel_session, enforce_ordering
    from one_database.models import Player

    import logging

    @channel_session    
    @enforce_ordering
    def game_command_RQ(message):
        skey = message.channel_session["server_key"]
        logger.info("Server key:  " + skey)
        queryset = Player.objects.values("player_id").filter(data__player__server_key=skey)
        json_res = []
        json_res.append({"REPLY": "R"})
        for qset in queryset:
            json_res.append(qset)
        message.reply_channel.send({
            "text": json.dumps(json_res)
        })
________________________________________________________
The standard occasional message is below. Most of the time, it all works fine and the server_key is found
________________________________________________________

    [2016/12/10 16:07:21] WebSocket CONNECT /server/1234567890 [127.0.0.1:48146]
    2016-12-10 16:07:21,793 - ERROR - worker - Error processing message with consumer one.consumers.game_command_RQ:
    Traceback (most recent call last):
    File "/home/github/interface/environment/lib/python3.5/site-packages/channels/worker.py", line 111, in run
    consumer(message, **kwargs)
    File "/home/github/interface/environment/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
    return func(message, *args, **kwargs)
    File "/home/github/interface/environment/lib/python3.5/site-packages/channels/sessions.py", line 45, in inner
    return func(message, *args, **kwargs)
    File "/home/github/interface/environment/lib/python3.5/site-packages/channels/sessions.py", line 91, in inner
    "can only be used on messages containing it."
    ValueError: No order value in message; @enforce_ordering can only be used on messages containing it.

________________________________________________________
If I try to use @enforce_ordering this is the error I get
________________________________________________________

[2016/12/10 16:07:21] WebSocket CONNECT /server/1234567890 [127.0.0.1:48146]
2016-12-10 16:07:21,793 - ERROR - worker - Error processing message with consumer one.consumers.game_command_RQ:
Traceback (most recent call last):
  File "/home/github/interface/environment/lib/python3.5/site-packages/channels/worker.py", line 111, in run
    consumer(message, **kwargs)
  File "/home/github/interface/environment/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
    return func(message, *args, **kwargs)
  File "/home/github/interface/environment/lib/python3.5/site-packages/channels/sessions.py", line 45, in inner
    return func(message, *args, **kwargs)
  File "/home/github/interface/environment/lib/python3.5/site-packages/channels/sessions.py", line 91, in inner
    "can only be used on messages containing it."
ValueError: No `order` value in message; @enforce_ordering can only be used on messages containing it.

**Comment by andrewgodwin** [comment]
This is because your `enforce_ordering` is on the `game_command.RQ` channel, and I presume the messages inside there don't have `order` keys like the WebSocket raw ones do, which is what's used to, well, enforce ordering.

Connect/receive separation for websockets and demultiplexers based on them is also already implemented in master.

**Comment by Key1337** [comment]
OK, thanks. What does that mean for my error? Can I not pass variables from the kargs through the demultiplexer to the consumer? I've added debugging messages to tell most of the time this error happens when the consumer message is processed before the connect. But not always.

**Comment by andrewgodwin** [comment]
It means that the multiplexing is incompatible with the old-style ordering enforcement - it was just a poor design decision. It'll be fixed in the next major release, but change the API a bit along the way.

And yes, it works most of the time, as most of the time your server will be fast enough to process the messages as they come in! It's when there's network buffering or something else on the system that causes them to be processed at the same time that ordering errors happen.

**Comment by Key1337** [comment]
When I run

    runserver --noworker

in one terminal window and

    runworker

in another, I never get the unintended sequencing and never get a keyerror, so I'm thinking it's an ordering problem for sure when running multiple workers.

In addition, why did you mention "Connect/receive separation for websockets and demultiplexers based on them is also already implemented in master." ? Does my solution to this problem relate to that? Do I need to stop doing connect/disconnect processing in the demultiplexer and do it somewhere else?

Thanks for your help. I'm kind of stuck on this and have to find a predictable fix.

**Comment by Key1337** [comment]
"It means that the multiplexing is incompatible with the old-style ordering enforcement" So I assume this means I cannot use demultiplexing at all if I need to have kargs that are used later in the consumer.

Is there any other way, with the current code, you might recommend to get the kargs to pass through the demultiplexer to the consumer?

If not, I guess I'll have to re-think the whole implementation without using the built-in demultiplexer. I hope not, because I have a a lot of client-side code that uses the demultiplexer json control logic. I suppose I could move my karg to a portion of the demux json "data" field, but I really, really like the simplicity of the current demux/karg method.

**Comment by andrewgodwin** [comment]
Oh, I've just noticed something - have you tried setting `strict_ordering = True` in the body of the demultiplexer? That should turn on the built-in ordering decorators at the right level of the stack (before it gets demultiplexed), and then you can remove the decorator from elsewhere.

**Comment by Key1337** [comment]
FIXED. Thanks so much for that.

If I could ask one last clarification: what is the long-term impact of using `strict_ordering = True` there?

1) For each separate websocket, I'm assuming all incoming messages, even those beyond the initial connect message, are processed sequentially, by only one (of many) worker threads at a time?

2) For multiple websockets, do they all maintain a separate notion of `strict_ordering = True` ? Meaning that although each websocket is using the same demultiplexer for logic, these separate websockets can run on different worker threads simultaneously?

I want to know: by using `strict_ordering = True`, I realize I'm losing multi-threaded worker functionality for a single websocket connection, but I'm curious now if all websockets using that demultiplexer would be forced to run sequentially together and therefore my system would effectively only ever be using one worker thread.

**Comment by andrewgodwin** [comment]
Yes, both of your clarifications are correct. There's also a mode called `slight_ordering = True`, which just enforces this one-worker-per-socket behaviour for the `connect` message and then the first `receive` message; other `receives` after that might run out of order in parallel.

If that's good enough for you, then you can switch to using that instead - it runs a bit faster. Slight ordering is what will come turned on by default in the next major release for WebSockets, without any of the performance penalties incurred by the ordering logic at the moment.
