### ISSUE TITLE
My routing and consumer stops responding to incoming messages during high traffic

### ISSUE THREAD

**Issue by Key1337** [django/channels#451]
Is there some reason why my routing and consumer would stop working (listening) to incoming websocket messages after a period of high traffic (lots of incoming messages)?

I have an application that works correctly and I use it for sending and receiving websocket messages. Whenever I greatly increase the rate of incoming messages, eventually the routing & consumer stop responding. These messages are coming into the server from a non-local host. I can tell the messages are still being received at the front end by monitoring redis with this terminal command:

     redis-cli monitor|grep -v EVALSHA | grep -v LPOP

When this condition occurs, I can still send outgoing websocket messages from my django channels application. That code is in another area not included here. This is all occurring over the same websocket connection which never drops.

routing.py

    from django.db import transaction
    from channels.routing import route, route_class
    from channels.generic.websockets import WebsocketDemultiplexer
    from channels.sessions import channel_session, enforce_ordering
    from one_database.models import Server
    import logging

    logger = logging.getLogger(__name__)

    from one.consumers import command_gRQAXFR

    class GameDemultiplexer(WebsocketDemultiplexer):
        mapping = {
            "gRQAXFR": "gRQAXFR.receive",
        }
        http_user = True
        strict_ordering = True

        @transaction.atomic
        @channel_session
        def connect(self, message, **kwargs):
            logger.info("\n[one] GameDemultiplexer: Connected")
            skey = kwargs["server_key"]
            message.channel_session["server_key"] = skey
            logger.info("Server key:  " + skey)
            sip = dict(message.content["headers"])[b'x-forwarded-for'].decode("utf8")
            logger.info("Server IP:   " + sip)
            try:
                srv = Server.objects.select_for_update().get(server_key=skey, server_ipaddress=sip)
                logger.info("Server Name: " + srv.server_name)
                srv.server_game_channel=message.reply_channel
                srv.save()
            except Server.DoesNotExist:
                logger.info("\n[one] GameDemultiplexer: Server not found!")
                self.close()
            pass
        
        @transaction.atomic
        def disconnect(self, message, **kwargs):
            logger.info("\n[one] GameDemultiplexer: Disconnected")
            skey = kwargs["server_key"]
            logger.info("Server key:  " + skey)
            try:
                srv = Server.objects.select_for_update().get(server_key=skey)
                logger.info(srv.server_name)
                srv.server_game_channel=""
                srv.save()
            except Server.DoesNotExist:
                logger.info("\n[one] GameDemultiplexer: Server not found!")
                self.close()
            pass
          
        
    channel_routing = [
        route_class(GameDemultiplexer, path=r"^/server/(?P<server_key>[a-zA-Z0-9]+)$"),
        route("gRQAXFR.receive", command_gRQAXFR),
    ]

channels.py

    import json
    from django.core import serializers
    from channels.sessions import channel_session
    from one_database.models import Player

    import logging

    logger = logging.getLogger(__name__)

    @channel_session    
    def command_gRQAXFR(message):
        logger.info("\n[one] command_gRQAXFR: Request database intialization")
        skey = message.channel_session["server_key"]
        logger.info("Server key:  " + skey)
        queryset = Player.objects.values("player_steamid").filter(player__server__server_key=skey)
        json_res = []
        json_res.append({"COMMAND": "cAXFR"})
        for qset in queryset:
            json_res.append(qset)
        logger.info("[one] command_gRQAXFR: Sending cAXFR database intialization")
        message.reply_channel.send({
            "text": json.dumps(json_res)
        })

**Comment by andrewgodwin** [comment]
What do your console logs show? Sounds like you're filling up the channel and getting backpressure.

**Comment by Key1337** [comment]
I let it sit overnight in the same condition without any traffic to see if somehow the system would calm down or recover or whatever. But nope, still won't respond to new incoming messages hours later.

How could I determine the possible backpressure problem? I see from the channels config I could increase the redis capacity.

For now, I've just been starting everything with runserver. My terminal console logs doesn't show any errors. A normal sequence looks like:

    [one] cloud_panel_function: Initializing database
    [2016/12/13 06:09:56] HTTP POST /one_test/cloud_panel_function/ 200 [0.01, 127.0.0.1:57402]

    [one] command_gRQAXFR: Request database intialization
    Server key:  1234567890
    [one] command_gRQAXFR: Sending cAXFR database intialization

    [one] cloud_panel_function: Initializing database
    [2016/12/13 06:09:56] HTTP POST /one_test/cloud_panel_function/ 200 [0.02, 127.0.0.1:57402]

    [one] command_gRQAXFR: Request database intialization
    Server key:  1234567890
    [one] command_gRQAXFR: Sending cAXFR database intialization

When it gets stuck, only the outgoing request messages are sent:

    [one] cloud_panel_function: Initializing database
    [2016/12/13 06:09:56] HTTP POST /one_test/cloud_panel_function/ 200 [0.01, 127.0.0.1:57402]

    [one] cloud_panel_function: Initializing database
    [2016/12/13 06:09:56] HTTP POST /one_test/cloud_panel_function/ 200 [0.01, 127.0.0.1:57402]

    [one] cloud_panel_function: Initializing database
    [2016/12/13 06:09:57] HTTP POST /one_test/cloud_panel_function/ 200 [0.01, 127.0.0.1:57402]

    [one] cloud_panel_function: Initializing database
    [2016/12/13 06:09:57] HTTP POST /one_test/cloud_panel_function/ 200 [0.01, 127.0.0.1:57402]

    [one] cloud_panel_function: Initializing database
    [2016/12/13 06:09:57] HTTP POST /one_test/cloud_panel_function/ 200 [0.01, 127.0.0.1:57402]

At this stage, the system is designed to:

1) initiate a command from a web page button, which sends a json websocket message to a remote system

2) which then replies back with a json request to update it's internal database

3) that request is reply'd back from django with the database info as json.

When the thing gets stuck, I only see the 1) outgoing request after I click the button. In the redis monitor, there is shown the incoming 2) reply requesting the database information, but I never see the 3) action again.

**Comment by Key1337** [comment]
Dropping and re-connecting the websocket always recovers the problem. Either restarting the remote process (which is a C++ websocket) or restarting the django channels runserver.

I know this makes a fresh websocket connection and id. But I'm not restarting redis, so that is the same instance.

**Comment by andrewgodwin** [comment]
From what you're describing then it sounds like the strict ordering is missing something and then blocking. If you can take it, I'd switch to `slight_ordering`, which is a lot less likely to fail.

**Comment by Key1337** [comment]
Ok I switched to 

    slight_ordering = True

In the demultiplexer definition and ran some tests for a few hours. I've not been able to get it stuck again, so it looks like that change fixed my problem. Thanks.

Hope my reports are at least somewhat useful and not troublesome. I really enjoy using your library while also learning more about Django & Python!
