### ISSUE TITLE
Test HTTP client method may generate invalid cookies `HttpClient.set_cookie`

### ISSUE THREAD

**Issue by rectangletangle** [django/channels#452]
When writing unit-tests around the test HTTP client, my cookies seem to be getting mangled when adding an additional field.

Example:
```
from channels.tests import ChannelTestCase, HttpClient

class MyTests(ChannelTestCase):
    def test(self):
        httpclient = HttpClient()
        httpclient.set_cookie('foo', 'bar')
        ...
```

The culprit appears to be this routine, where it joins the cookie fields on `&`.
https://github.com/django/channels/blob/f4f45dbb9f63c4085d65331dd534740978ab6623/channels/tests/http.py#L126

I discovered this while trying to parse the test client's cookies with Django's parsing routine. 
``` 
from django.http.cookie import parse_cookie
```

I believe replacing the function with this should do the trick (note the join on `'; '`):
```
def _encoded_cookies(cookies):
    """Encode dict of cookies to ascii string"""
    return ('; '.join('{0}={1}'.format(k, v) for k, v in cookies.items())).encode("ascii")
```

Anyone know if there's a cookie serialization routine in Django core, or Python's stdlib? 

I can implement a PR, if necessary.

**Comment by Krukov** [comment]
You right. I don't know why I used `&` :suspect:  and I could not find a simple method to do a cookie serialization by 'standart' way. Anyway I sure that PR is welcome

**Comment by rectangletangle** [comment]
Reminds me of URL params or something lol. Great work on channels BTW!

I'll try to get a fix PR up soon.

**Comment by Krukov** [comment]
Let's close it.
