### ISSUE TITLE
@channel_session_user does not return authenticated user

### ISSUE THREAD

**Issue by xtrinch** [django/channels#456]
@channel_session_user does not return my authenticated user. I can get my user from @channel_session_user_from_http, but it is somehow not transferred to channel session.

I am not sure if this is somehow related, but I am using token authentication on the frontend. This is my test code (Upon every message sent from server there is a test message sent back from frontend. Basically ping pong):

```from channels import Group
import time
from channels.auth import http_session_user, channel_session_user, channel_session_user_from_http

send = True

def loop():
    i = 0
    while send:
        print ("Sending test data")
        Group("test").send({
            "text": "Test message" + str(i)
        })
        i = i + 1

        time.sleep(1)

# Connected to websocket.connect
@channel_session_user_from_http
def ws_add(message):
    print(message.user)
    Group("test").add(message.reply_channel)
    global send
    send = True
    loop()

# Connected to websocket.receive
@channel_session_user
def ws_message(message):
    print(message.content['text'])
    print(message.user)

# Connected to websocket.disconnect
def ws_disconnect(message):
    Group("test").discard(message.reply_channel)
    global send
    send = False
```

And this is my console output:

> [2016/12/29 17:46:03] WebSocket CONNECT /test [127.0.0.1:46384]
> root
> Sending test data
> {"text":"hello"}
> AnonymousUser
> Sending test data
> {"text":"hello"}
> AnonymousUser
> Sending test data
> {"text":"hello"}

As you can see, the user (root) is defined upon connect, but not when receiving messages.
I am using:

> asgiref==1.0.0
> autobahn==0.17.0
> channels==0.17.3
> constantly==15.1.0
> daphne==0.15.0
> Django==1.10.4
> djangorestframework==3.5.3
> incremental==16.10.1
> pkg-resources==0.0.0
> psycopg2==2.6.2
> six==1.10.0
> Twisted==16.6.0
> txaio==2.5.2
> zope.interface==4.3.3

I am also running django through runserver with inmemory asgi.

If this is in any way relevant, frontend javascript code (I am using React):

```
  constructor(props) {
    super(props);
    this.state = {
      websocketObject: new ReconnectingWebSocket('ws://localhost:8000/control'),
    }
    let ws = this.state.websocketObject
    this.state.websocketObject.onmessage = function(msg) {
      console.log("on message")
      ws.send(JSON.stringify({
        'text': 'hello'
      }));

      console.log(msg);
    }
  }

```
Is this somehow an error on my side? Because I am not sure where to start looking.

**Comment by andrewgodwin** [comment]
That code works via cookie sharing, so it only works if that's what you're using for authentication and if the website and websocket are on the same host. You said you're using token authentication - what does that mean?

**Comment by xtrinch** [comment]
I see now that my http session user was defined because I was logged in via django admin. When I log out, the user is never defined.

Token auth is stateless, so I'm not sure how it would work with it, but it would be nice if it was somehow supported. (Token auth in the sense that I add a header field with my authorization token upon each request)

All I need is initial connect authentication, so my idea is to simply never add the reply_channel to a group. But then the would have to somehow drop the connection, and I'm not sure how to.

**Comment by andrewgodwin** [comment]
Ah, OK. You can implement that yourself, but Channels only ships with support for the cookie-based sessions and authentication at the moment, so this isn't a bug in Channels directly.

For reference, you can see headers in the `connect` handler, and then assign an object to `message.session['user']`, and handle things that way.
