### ISSUE TITLE
Deprecation error when running channels via docker-compose

### ISSUE THREAD

**Issue by xtrinch** [django/channels#465]
I get the following exception when running runserver via docker-compose:

> django_1            | Unhandled exception in thread started by <function wrapper at 0x7f068a02cd70>
> django_1            | Traceback (most recent call last):
> django_1            |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
> django_1            |     fn(*args, **kwargs)
> django_1            |   File "/usr/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 84, in inner_run
> django_1            |     ws_protocols=getattr(settings, 'CHANNELS_WS_PROTOCOLS', None),
> django_1            |   File "/usr/local/lib/python2.7/site-packages/daphne/server.py", line 41, in __init__
> django_1            |     ''' % self.__class__.__name__)
> django_1            | Performin
g system checks...

I have no idea where to go from here, as django is not running serving requests after this exception.

When I run it locally on my machine, everything works okay.

Here's my requirements.txt:

> Django==1.10.4 
> psycopg2==2.6.2 
> channels==0.17.3 
> asgi-redis==1.0.0

And here's my docker-compose file:

    version: '2' 
      services:
        redis:
          image: redis:3.0-alpine
        postgres:
            image: postgres
        django:
            build: ../backend
            command:  python backend/manage.py runserver 0.0.0.0:8000
            volumes:
                - ../backend:/backend
            ports:
                - "8000:8000"
            depends_on:
                - postgres
                - redis
                - django-migration
        django-migration:
            build: ../backend
            command: python backend/manage.py migrate
            volumes:
              - ../backend:/backend
            depends_on:
              - postgres
        client:
            image: node
            command: bash -c "cd src && npm start"
            ports:
                - "3000:3000"

Any ideas?

**Comment by andrewgodwin** [comment]
That doesn't seem to be a full traceback. Can you provide one that includes the exception name and type?

**Comment by xtrinch** [comment]
This is all I have:

> django_1            | 2017-01-09 08:45:02,127 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
> django_1            | 2017-01-09 08:45:02,127 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
> django_1            | 2017-01-09 08:45:02,129 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
> django_1            | 2017-01-09 08:45:02,130 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
> django_1            | Unhandled exception in thread started by <function wrapper at 0x7f14f90add70>
> django_1            | Traceback (most recent call last):
> django_1            |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
> django_1            |     fn(*args, **kwargs)
> django_1            |   File "/usr/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 84, in inner_run
> django_1            | Performing system checks...
> django_1            | 
> django_1            | System check identified no issues (0 silenced).
> django_1            | January 09, 2017 - 08:45:02
> django_1            | Django version 1.10.4, using settings 'backend.settings'
> django_1            | Starting Channels development server at http://0.0.0.0:8000/
> django_1            | Channel layer default (asgi_redis.core.RedisChannelLayer)
> django_1            | Quit the server with CONTROL-C.
> django_1            |     ws_protocols=getattr(settings, 'CHANNELS_WS_PROTOCOLS', None),
> django_1            |   File "/usr/local/lib/python2.7/site-packages/daphne/server.py", line 41, in __init__
> django_1            |     ''' % self.__class__.__name__)
> django_1            | DeprecationWarning: 
> django_1            |                 The host/port/unix_socket/file_descriptor keyword arguments to Server are deprecated.
> django_1            |

**Comment by andrewgodwin** [comment]
What version of Daphne do you have? It looks like you may have upgraded to Daphne 1.0.0 but not Channels 1.0.0 - they need to match.

**Comment by xtrinch** [comment]
Okay, you are correct - inside the docker container, daphne was 1.0.0. I had only channels version specified in requirements.txt, as daphne is a dependency, it would probably be normal to expect a compatible version would be installed?

**Comment by andrewgodwin** [comment]
Unfortunately the old Channels versions specify a lowest Daphne version but not a highest one, and I can't retroactively fix this. The newest version of Channels will bring in the right dependency when you install it - I'm going to close this for now, unless something else comes up that isn't existing dependency stuff.

**Comment by xtrinch** [comment]
@andrewgodwin 

So I updated both daphne and channels to 1.0.0, now I can't run it locally anymore:

> Unhandled exception in thread started by <function wrapper at 0x7f3c7b3755f0>
> Traceback (most recent call last):
>   File "/home/trinch/repos/zinc/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
>     fn(*args, **kwargs)
>   File "/home/trinch/repos/zinc/env/local/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 89, in inner_run
>     root_path=getattr(settings, 'FORCE_SCRIPT_NAME', '') or '',
>   File "/home/trinch/repos/ledinek-klh-zinc/env/local/lib/python2.7/site-packages/daphne/server.py", line 96, in run
>     ep = serverFromString(reactor, socket_description)
>   File "/home/trinch/repos/zinc/env/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1522, in serverFromString
>     return _serverFromStringLegacy(reactor, description, _NO_DEFAULT)
>   File "/home/trinch/repos/zinc/env/local/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1438, in _serverFromStringLegacy
>     return plugin.parseStreamServer(reactor, *args, **kw)
> AttributeError: 'unicode' object has no attribute 'parseStreamServer'
> 

Requirements.txt:

> asgi-redis==1.0.0
> asgiref==1.0.0
> autobahn==0.17.1
> channels==1.0.0
> constantly==15.1.0
> daphne==1.0.0
> Django==1.10.4
> django-filter==1.0.1
> djangorestframework==3.5.3
> djangorestframework-jwt==1.9.0
> incremental==16.10.1
> msgpack-python==0.4.8
> pkg-resources==0.0.0
> psycopg2==2.6.2
> PyJWT==1.4.2
> redis==2.10.5
> six==1.10.0
> Twisted==16.6.0
> txaio==2.6.0
> zope.interface==4.3.3
>
