### ISSUE TITLE
'multichat' project in 'channels-examples' is not working

### ISSUE THREAD

**Issue by ugultopu** [django/channels#471]
[Project](https://github.com/andrewgodwin/channels-examples/tree/master/multichat)

## Issue
Websocket connection to `ws://localhost:8000/chat/stream/` is being dropped with code 1006 shortly after connection.

## Version Information
* macOS Sierra
* Python 3.6.0
* Firefox 50.1.0

* Django-1.10.5
* asgi-redis-1.0.0
* asgiref-1.0.0
* autobahn-0.17.1
* channels-1.0.1
* constantly-15.1.0
* daphne-1.0.1
* incremental-16.10.1
* msgpack-python-0.4.8
* redis-2.10.5
* six-1.10.0
* twisted-16.6.0
* txaio-2.6.0
* zope.interface-4.3.3

## Issues

1. Clicking on a room does not open a room.
2. An error is not shown when a non-staff user tries to join a staff only room.
3. As soon as I click on a room, entries in the 'django_session' table starts being created and they keep on.

## Steps to reproduce
1. `git clone https://github.com/andrewgodwin/channels-examples.git`
2. `cd channels-examples`
3. `python -m venv multichat-ENV`
4. `mv multichat multichat-ENV`
5. `cd multichat-ENV`
6. `source bin/activate`
7.  `cd multichat`
8. `pip install -r requirements.txt`
9. `redis-server &`
10. `python manage.py migrate`
11. `python manage.py runserver`
12. `python manage.py createsuperuser`. Create the super user.
13. Then, log into `http://localhost:8000/admin/` and make a couple of Room objects. Be sure to make one that is set to "staff-only".
14. Go to `http://localhost:8000/admin/` and click on a staff only or common room. The room won't open.

## Notes
1. The project used to work with version 0.17.3. I see that Channels 1.0.1 is recently released. Maybe it is related to that?

Regards

**Comment by adamteale** [comment]
I seem to be experiencing this too

**Comment by germanjoey** [comment]
I believe it's due to the 1.0 change requiring websocket.connect to send
back an {'accept': true} packet on the reply_channel. See the release notes:

http://channels.readthedocs.io/en/latest/releases/1.0.0.html#websocket-accept-reject-flow

Joe

**Comment by andrewgodwin** [comment]
It is indeed. I'll fix it up over the next day or two.

**Comment by ugultopu** [comment]
@andrewgodwin Is it about what Joe said in the previous comment?

**Comment by andrewgodwin** [comment]
Yup, probably - I haven't checked yet but the symptoms fit.

**Comment by andrewgodwin** [comment]
This should be fixed with the PR I just merged (andrewgodwin/channels-examples/#19)

**Comment by ugultopu** [comment]
@andrewgodwin Nitpick: Wrong PR is linked. It should be: https://github.com/andrewgodwin/channels-examples/pull/19
