### ISSUE TITLE
Logout does not remove the entry from 'django_session' table

### ISSUE THREAD

**Issue by ugultopu** [django/channels#477]
## Version Information
* Python 3.6.0
* Django-1.10.5
* asgi-redis-1.0.0
* asgiref-1.0.0
* autobahn-0.17.1
* channels-1.0.1
* constantly-15.1.0
* daphne-1.0.1
* incremental-16.10.1
* msgpack-python-0.4.8
* redis-2.10.5
* six-1.10.0
* twisted-16.6.0
* txaio-2.6.0

## Issue
In the [multichat project](https://github.com/andrewgodwin/channels-examples/tree/master/multichat), logging out removes only the Django session from the 'django_session' table. Channels session still persists in the 'django_session' table.

I have tried logging out from the Channels session using this code:

`consumers.py`:
```python
import json
from channels import Channel
from channels.auth import channel_session_user_from_http, channel_session_user
from django.http import HttpRequest

from .settings import MSG_TYPE_LEAVE, MSG_TYPE_ENTER, NOTIFY_USERS_ON_ENTER_OR_LEAVE_ROOMS
from .models import Room
from .utils import get_room_or_error, catch_client_error
from .exceptions import ClientError
from .views import logout_view

@channel_session_user
def ws_disconnect(message):
    # Unsubscribe from any connected rooms
    for room_id in message.channel_session.get("rooms", set()):
        try:
            room = Room.objects.get(pk=room_id)
            # Removes us from the room's send group. If this doesn't get run,
            # we'll get removed once our first reply message expires.
            room.websocket_group.discard(message.reply_channel)
        except Room.DoesNotExist:
            pass
    request = HttpRequest()
    request.session = message.channel_session
    request.user = message.user
    logout_view(request)
```

`views.py`:
```python
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def logout_view(request):
    logout(request)
```

But this doesn't remove the Channels session from 'django_session' table. It only truncates the Channels session to 60 bytes.

Is this by design? Are Channels sessions not removed from the 'django_session' table? Or am I not logging out the right way?

If this is by design, how can I tell if an entry in the 'django_session' table is a logged in entry or a logged out entry?

Regards

**Comment by andrewgodwin** [comment]
Yes, sessions are not removed from the sessions table until they expire and the cleanup step gets them; that's how it's designed. If you wish, you can try calling `message.channel_session.flush()` in disconnect and that may delete it, but Django session stores do not have a guaranteed deletion method on them.

**Comment by ugultopu** [comment]
`message.channel_session.flush()` didn't work as well. It only clears the session data but doesn't remove the session from the table.

My question is, we can remove a Django session with logout. Why can't we remove a Channels session with logout?

**Comment by andrewgodwin** [comment]
I don't see anything in the Django logout function that deletes the session, it just calls flush: https://github.com/django/django/blob/master/django/contrib/auth/__init__.py#L160

**Comment by ugultopu** [comment]
@andrewgodwin But the Django session is immediately deleted upon logging out. You may try and observe it with the [multichat project](https://github.com/andrewgodwin/channels-examples/tree/master/multichat) if you like.

**Comment by andrewgodwin** [comment]
Right, but I don't know how it is done at the moment. If you can find out how the session is deleted in terms of code (maybe there's a signal?), then you can do that in Channels as well.

**Comment by ugultopu** [comment]
@andrewgodwin  OK, I will try to find it.

**Comment by ugultopu** [comment]
@andrewgodwin Found something. I have removed the `self._session_key = None` line of the `flush` method from `django/contrib/sessions/backends/base.py` and the session row is removed from the database after calling ` message.channel_session.flush()`. Not sure why though.

**Comment by germanjoey** [comment]
I assume you are using the @channel_session or @channel_session_user decorators? If so, your problem may be because @channel_session checks to see if the session is modified after the decorated function has been called, and if so proceeds to call .save(). Try setting channel_session.modified to False after your call to flush() in disconnect, and see if that works with that  "self._session_key = None" line reverted back to its original form.

**Comment by ugultopu** [comment]
@germanjoey It worked. But is this a bug or a feature? Having to use `message.channel_session.modified = False` in order to get the Channel session deleted after a logout feels like this is a bug. Am I right?

**Comment by andrewgodwin** [comment]
Well, if you're manually calling the flush method then you also need to manually fix the modified parameter so it won't resave. What Channels could do here is offer a decorator that would do both these steps for you; we can't bake it into `channel_session` as other code that wants things to persist uses that.

**Comment by germanjoey** [comment]
Is there anything like an is_flushed method on sessions? @channel_session could check that flag when it wants to save, and then like, not save if the session has been flushed.

**Comment by andrewgodwin** [comment]
There isn't, though arguably this might be seen as a bug in Django as a flushed session is not modified. I'll raise it over there and see what the thought is.

**Comment by germanjoey** [comment]
Right on, just saw this myself. Related to ugultopu's original issue, .save() will call create() if _session_key is None, which is done by .flush(). That is definitely not what I'd call the expected behavior of calling .save() on a deleted session. (I'd expect either nothing to happen (you'd be "saving" the deletion) or else an exception to be raised)
