### ISSUE TITLE
WebsocketConsumer/JsonWebsocketConsumer session data?

### ISSUE THREAD

**Issue by bastianh** [django/channels#478]
Maybe I miss something, but how do you access session (or user) data in the `receive` functions? It looks like there is no way to access the data.

**Comment by andrewgodwin** [comment]
You need to use `@channel_session` - see http://channels.readthedocs.io/en/stable/getting-started.html#persisting-data

**Comment by bastianh** [comment]
I know how to enable the session.. but how do I get access to the data in the function... the `message` object is not passed to the functions.

```    def receive(self, text=None, bytes=None, **kwargs):
        """
        Called with a decoded WebSocket frame.
        """
        pass
```

and

```
    def receive(self, content, **kwargs):
        """
        Called with decoded JSON content.
        """
        pass
```

**Comment by bastianh** [comment]
oh sorry.. I missed that.

**Comment by bastianh** [comment]
it's a bit unclear... Why is `message` passed to `def raw_receive(self, message, **kwargs):` when it's availabel as `self.message`?

**Comment by andrewgodwin** [comment]
It's to reflect the design of non-class-based consumers as closely as possible. The top level `receive` (raw in this case) gets the raw socket message, the lower one down gets the decoded JSON.

**Comment by bastianh** [comment]
Ok .. I can understand this decision but I have to admit that I don't like it.
I would have preferred the more pythonic way if would be only one obvious way to access the data. When I looked at the code of the superclass it looked like that access to the message object is lost at this point.

**Comment by andrewgodwin** [comment]
I understand, but it's meant to mirror class-based views in Django, which pass the `request` into `GET` but also set `self.request` in the handler.

**Comment by bastianh** [comment]
Yeah.. it's like it is in the class based views.. I mixed it up completely ;)
