### ISSUE TITLE
The 1.0.0 release channels.websockets.WebsocketConsumer needs to implement connect() method

### ISSUE THREAD

**Issue by ipartola** [django/channels#479]
In the 1.0.0 tag this is just an empty `pass`, but in the master branch it's implemented properly:

https://github.com/django/channels/blob/master/channels/generic/websockets.py#L71

This results in WebsocketConsumer-derived consumers in not being able to process any connections without explicitly defining a custom `connect()` method that would also do `self.message.reply_channel.send({"accept": True})`

The immediate solution seems to be to create a new release with this bug fixed.

I think the long term solution would actually be to separate the "accept or reject the connection" into a separate method of the generic consumer so it's not as easily overwritten.

Regardless, the documentation at https://channels.readthedocs.io/en/stable/generics.html#websockets needs to be updated to reflect the fact that a no-op `connect()` method will not work.

**Comment by andrewgodwin** [comment]
This was released in version `1.0.1` yesterday, specifically because it was a nasty thing to have in there! I'll update the docs right now too.

**Comment by ipartola** [comment]
Thanks. I didn't see 1.0.1 mentioned anywhere in the docs, so I didn't look into it.

**Comment by ipartola** [comment]
Not sure how this process works, but the docs at https://channels.readthedocs.io/en/stable/generics.html#websockets haven't been updated, and 1.0.0 is still the "stable" release. My actual problem is now solved, just wanted to save others the pain. Thanks!

**Comment by andrewgodwin** [comment]
The changelog for the minor releases was just in the repo. I'll move it online too.
