### ISSUE TITLE
Data Binding documentation on WebsocketBinding.group_names() inconsistent with implementation

### ISSUE THREAD

**Issue by devmapal** [django/channels#482]
Channels version: 1.0.1
According to the documentation, `WebsocketBinding.group_names()` dropped the `action` argument, however in the implementation it is still required.

Documentation:
https://github.com/django/channels/blob/1.0.1/docs/binding.rst

Implementation:
https://github.com/django/channels/blob/1.0.1/channels/binding/base.py#L189

Thanks for looking into it.

**Comment by andrewgodwin** [comment]
Released in `1.0.2`

**Comment by devmapal** [comment]
Cool, thanks for fixing the issue!
