### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'status_code'

### ISSUE THREAD

**Issue by ostcar** [django/channels#483]
In the current master of channels (also in the version 1.0.2) [line 208 of handler.py](https://github.com/django/channels/blob/master/channels/handler.py#L208) is 
```python
response = HttpResponse("408 Request Timeout (upload too slow)", status_code=408)
```
But HttpResponse does not have an argument ```status_code```. You probably meant ```status```.

See: https://github.com/django/django/blob/master/django/http/response.py#L41

**Comment by andrewgodwin** [comment]
Yup, thanks for spotting that!
