### ISSUE TITLE
Channel_session data seems to disappear between messages in class-based consumer.

### ISSUE THREAD

**Issue by germanjoey** [django/channels#484]
Hello,

I'm currently working on re-implementing the multichat example using class-based Consumers as a way to prep myself (i.e. learn Channels) for my actual project, and I've run into an issue with channel-sessions that I can't figure out. 

My setup is this:

1.) the ws_connect function is identical (decorated with @channel_session_user_from_http and routed the same way). it sets message.channel_session['rooms'] = []
2.) chat_join/chat_leave/chat_send are now part of a ChatConsumer class, connected inside of a Demultiplexer class. 

The user connects just fine, and is able to successfully call chat_join. So, at least something in the session code is working correctly. That is to say, the lines:

   rooms = self.message.channel_session['rooms']
   rooms_set = set(rooms)

do not create any error; the session recognizes that 'rooms' was initialized to an empty list in ws_connect. However, immediately after this, I try to chat_leave the room, and I get a "TypeError: NoneType is not iterable" on the equivalent "rooms_set = set(rooms)" line in chat_leave, meaning that the 'rooms' key is now undefined in the channel_session for some reason.

At this point, I'm stuck because I don't really understand how the sessions are implemented here. I've confirmed that the same session_key is used both times for chat_join and chat_leave, and AFAIK there should be no connection issues with the user that might cause a new session to start. So, what I'm wondering is: when can the session be cleared and/or recreated? Does using demux/mux cause anything goofy to happen with the reply_channels such that session data might be dropped?

As an aside, I also noticed that when I tried to create the 'rooms' key in a ChatConsumer.connect method, the session would "forget" before I was able to join. It was only after I moved the connect code back to ws_connect that I was able to join the room. So I suspect that something in the class-based-consumer code is causing a session flush? Maybe?

Any ideas?

**Comment by andrewgodwin** [comment]
I don't know of anything that is meant to cause a flush, but it's possible there's an interaction with the demultiplexer that's causing things to go awry. First, though, try setting `strict_ordering = True` on the class and see if that fixes it (there's a chance it might be things running in parallel).

If not, is there any way you could reduce this into steps to reproduce or a small test project that shows the symptom every time?

**Comment by germanjoey** [comment]
Ah, I ended up figuring it out myself. The patch is really simple, but it took me quite awhile to get there, heh.  The bug is in the definition for the channels.sessions.channel_session wrapper and only shows up when used with WebsocketDemultiplexer connect and disconnect. Here's the relevant code, comments removed for brevity:

    def channel_session(func):
        @functools.wraps(func)
        def inner(message, *args, **kwargs):
            if hasattr(message, "channel_session"):
                return func(message, *args, **kwargs)
            ...
            
this needs to be:

    def channel_session(func):
        @functools.wraps(func)
        def inner(message, *args, **kwargs):
            if hasattr(message, "channel_session"):
                try:
                    return func(message, *args, **kwargs)                
                finally:
                    if message.channel_session.modified:
                        message.channel_session.save()
                        
with the try/finally code taken from the bottom of channel_session.inner. 
                        
This is because WebsocketDemultiplexer will loop through all connected consumers' connect/disconnect methods. For the first consumer, everything is fine, because the <if hasattr> block will be false, and thus func(message, *args, **kwargs) will get run in the bottom try/finally block and the channel_session will get saved if modified. However, for the second and subsequent consumers, the <if hasattr> will be true and thus the session would not be saved if any of these consumers had modified it.

**Comment by andrewgodwin** [comment]
Ah, great tracking down! Did you want to submit that as a pull request, or shall I patch it in manually?

**Comment by germanjoey** [comment]
Sure. Also patched a seemingly analogous construct in http_session.

**Comment by raphael-boucher** [comment]
Maybe related to #421
Sorry, I had no time to dive into it again.

**Comment by andrewgodwin** [comment]
Fixed in #486
