### ISSUE TITLE
Sometimes Django throws 404 when using Redis backend with remote Redis server

### ISSUE THREAD

**Issue by javiermatos** [django/channels#489]
I'm running a test django project to learn more about channels. I am using latest django version (1.10.5) and also latest channel version (1.0.2). My test project works fine but sometimes I get a 404 error even on django admin page when using runserver. If I disabling channels then runserver works fine.

I have been changing my settings file and I have found where the problem is. I am having this issue when using `asgi_redis.RedisChannelLayer` backend for CHANNEL_LAYERS while using a remote server. If I change the backend it works fine. If I use the Redis backend but with a local Redis server it works fine. I am only having this issue with remove Redis servers.

I have tried doing ssh -L 6379:localhost:6379 user@server for local port forwarding to the remote Redis server but I also have the issue when doing this. My remote server is a LXD container in my local network (no latency issue), but I don't think that will be the issue because the database connection works fine and the issue is not happening when changing the channels backend.

You can reproduce the issue using a remote redis server with the example project that is in the channels documentation site. I can reproduce the issue in two independent projects that I have done.

**Comment by andrewgodwin** [comment]
`404` is not the sort of error Channels would raise in such a situation, and I've successfully run Channels against a remote server with the example project (in fact this is how I normally run it).

Are there any tracebacks or errors in the console when this happens? What does the access log that's printed for `runserver` say?

**Comment by javiermatos** [comment]
Runserver was fine and there were no tracebacks.

I found the issue. There was something wrong in the remote Redis server installation. I thought it was something related with the version 3.2.6 vs 3.0.2 or the configuration Ubuntu package default vs no configuration.

After removing the redis-server package and installing it again now it is working. Sorry, my laptop and my desktop had the same issue with the project and they were using different remote Redis servers so I thought they were not the problem. Both remote Redis servers had the same issue but now everything works as expected.

Thank you for your time and your help ;)
Great project!
