### ISSUE TITLE
https://channels.readthedocs.io/en/stable/getting-started.html

### ISSUE THREAD

**Issue by dilyanpalauzov** [django/channels#491]
At https://channels.readthedocs.io/en/stable/getting-started.html#authentication 6th paragraph, replace "which IS works if you want to keep" with "which works if you want to keep"; and in the following code snippet remove "http_session_user, " from "from channels.auth import http_session_user, channel_session_user, channel_session_user_from_http".

Likewise for the code snippet at https://channels.readthedocs.io/en/stable/getting-started.html#enforcing-ordering .

**Comment by andrewgodwin** [comment]
Fixed by #493.
