### ISSUE TITLE
Some questions regarding Channels' message reliability

### ISSUE THREAD

**Issue by germanjoey** [django/channels#492]
Hello,

I'm currently trying to wrap my head around message and session reliability with Channels. I know from the FAQ that Channels makes no guarantees about message delivery, which is fine - I'm just trying to understand what exactly happens when various failures occur so that I can incorporate that into my design. 

Here's what I worked out so far - is this right? I think I've got the first three of these situations down, but am unsure about the fourth. And is there any other situation that I'm missing?

Thanks for your help!

1.) The client attempts to send a message to the server, and no disconnection occurs. Or vice-versa. No errors occur on the server.

- message: Even if some hiccups happen along the way, as long as the connection is not broken the delivery is guaranteed by TCP/IP. There is no guarantee on latency or ordering relative to other messages sent by either side, however.
- server: Will not know about any hiccups along the way. If strict_ordering is used on the consumer, replies to messages will be emitted by daphne in the same order that they were received, but there is no guarantee that they will be received in this same order.
- client: see above

2.) Network hiccup causes client to disconnect, with no messages pending from either client or server.

This is the ordinary disconnect situation.

- messages: none
- server: consumers on the 'websocket.disconnect' channel are called. If/when the client reconnects, their channel_session will be lost as they are actually connected on a new websocket. If using http_session, they server will still be able to correctly set message.user. In addition, any Groups that the original websocket was a member of will not know about this new websocket that reconnected.
- client: If using the Javascript ReconnectingWebsocket library, will automatically reconnect on a timeout. The client is responsible for resyncing its state to the server, such as rejoining any groups, etc.

3.) The client attempts to send a message at the same instant a network hiccup occurs.

- messages: a client-side Exception will be thrown indicating that the message was not sent. The client is responsible for resending the message when appropriate after reconnection.
- server: see #2
- client: see #2

3.) The server's consumers complete processing of an incoming message, but a network hiccup occurs that disconnects the client before the outgoing response can be emitted by daphne, or while it is emitted.

- incoming message: successfully consumed
- outgoing message: will be lost
- server: see #2
- client: see #2. Since the message was successfully sent before the disconnect occurred, the client will not know why it did not get a response. 

4.) Server 1 and 2 are workers running consumers, while Server 3 is running daphne. Server 1, in the midst of processing an incoming message, suddenly and instantaneously explodes in spectacular fashion. 

- server 1: in flames
- message: ASGI guarantees at-most-once delivery, but I don't know when a message is considered "delivered." There's two possibilities: if a.) "success" is defined as once the consumer takes the message, then it is lost. If b.) "success" is defined once the consumer replies, then I believe that according to ASGI, an error will be thrown by daphne and the message will instead be sent to server 2. I  suspect that a.) is most likely the case, however.
- server 2: Only processes the message in scenario b.) above. In scenario a.), it will be oblivious.
- server 3: Only emits a response in scenario b.) above. In scenario a.) it forgets about the message as soon as it is taken by the consumer.
- client: Completely oblivious to the situation, in either case.

**Comment by andrewgodwin** [comment]
So the key thing is that "guarantees at most once delivery" strictly only means "we won't deliver it twice or more". In your fourth scenario, the a) branch is correct - the message is delivered once the consumer reads it from the queue (this is done atomically so only one process can do it).

If b) were the case, you'd get duplication, as both server 1 and server 2 would have at least started running consumer code against the same message.

**Comment by germanjoey** [comment]
Ok, cool, thank you. So 1.) through 3.) are a correct understanding then? And there's no other scenarios to consider?

**Comment by andrewgodwin** [comment]
1 through 3 are fine, yes. There are myriad other scenarios to consider - this is distributed systems, after all:

5) The Redis server dies after a message is pushed to it
6) The Redis server dies before a message is pushed to it
7) All workers die and the message expires
8) Network latency spikes between the servers causing timeouts
9) The Redis server runs out of disk space/memory
10) Either the worker or the consumer run out of memory
11) Lots of clients hit Daphne at once and overload it
12) Lots of clients hit Daphne, it copes, but your OS runs out of file handles

And many more. Needless to say, in all of these you get the message 0 or 1 time, which is why that's the guarantee that's in place.

**Comment by germanjoey** [comment]
Ah, I was grouping all the above into my 4.) - in all the above cases, from the client's point of view, is that the message was apparently lost for mysterious reasons. (and the solution is that the client would need to resend it, if it was something important and it was waiting for an ack). The idea wasn't so much to look for all potential points of failure in the entire system, but more so about looking at points of failure from just the perspective of the websocket itself.

Well, actually I guess 11.) and 12.) are more like subsets of my 3.), where a disconnect (which would be what happens if daphne gets overloaded and needs to be restarted) prevents delivery of a successfully processed message. In this event, then, once the reconnection is established, then the client will need to ask the server if there were any important messages that it missed. (and thus that these messages need to be cached somewhere on the server for such an event).
