### ISSUE TITLE
PyPi talks about "still beta software"..

### ISSUE THREAD

**Issue by sebhaase** [django/channels#496]
Hi,
on https://pypi.python.org/pypi/channels   it is stated that
`This is still beta software: the API is mostly settled, but might change a bit as things develop. Once we hit 1.0, it will be stablized and a deprecation policy will come in.`

But the current version (there) is 1.0.2 ... so this doen't make sense  does it ?

**Comment by andrewgodwin** [comment]
Ah yes, I forgot to remove the classifier. I'll do that now and it'll be fixed next release.

**Comment by andrewgodwin** [comment]
Oh, right, it's in the description. Let me work out how to fix that.
