### ISSUE TITLE
Channels fails on Windows server

### ISSUE THREAD

**Issue by LegoStormtroopr** [django/channels#498]
The error is being raised from twisted, but all three test runs use `Twisted==16.6.0`.
I'm not 100% sure this is a channels specific thing, but thats what raised the issue.

I'm going to do some more investigation, but would the project be interested in including an `appveyor.yml` to add Windows testing file if one was put together?

If you're submitting a bug report, please include:

- Your OS and runtime environment, and browser if applicable - **Windows server 2016, Python 3**
- The versions of Channels, Daphne, Django, Twisted - **see below**
- What you expected to happen vs. what actually happened - **channels runserver fails to start**
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?) - **runserver**
- Console logs and full tracebacks of any errors - **see below**

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python35\lib\site-packages\django\core\management\__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "C:\Python35\lib\site-packages\django\core\management\__init__.py", line 328, in execute
    django.setup()
  File "C:\Python35\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python35\lib\site-packages\django\apps\registry.py", line 115, in populate
    app_config.ready()
  File "C:\Python35\lib\site-packages\channels\apps.py", line 22, in ready
    monkeypatch_django()
  File "C:\Python35\lib\site-packages\channels\hacks.py", line 10, in monkeypatch_django
    from .management.commands.runserver import Command as RunserverCommand
  File "C:\Python35\lib\site-packages\channels\management\commands\runserver.py", line 5, in <module>
    from daphne.server import Server, build_endpoint_description_strings
  File "C:\Python35\lib\site-packages\daphne\server.py", line 6, in <module>
    from twisted.internet.endpoints import serverFromString
  File "C:\Python35\lib\site-packages\twisted\internet\endpoints.py", line 36, in <module>
    from twisted.internet.stdio import StandardIO, PipeAddress
  File "C:\Python35\lib\site-packages\twisted\internet\stdio.py", line 30, in <module>
    from twisted.internet import _win32stdio
  File "C:\Python35\lib\site-packages\twisted\internet\_win32stdio.py", line 9, in <module>
    import win32api
ImportError: No module named 'win32api'
```

Three test instances are below, the only differences is how channels/daphne are installed.
* Tests work with channels, daphne latest (channels==0.17.3, daphne==0.15.0) - https://ci.appveyor.com/project/LegoStormtroopr/aristotle-metadata-registry-361e5/build/1.0.128/job/ll7ki03epqqhi0hg
* Tests failed channels, daphne latest (channels==1.0.1, daphne==1.0.1) - https://ci.appveyor.com/project/LegoStormtroopr/aristotle-metadata-registry-361e5/build/1.0.129/job/e06hdvcc6j817bn0
* Tests work, pinned channels==0.17.3, daphne==0.15.0 - https://ci.appveyor.com/project/LegoStormtroopr/aristotle-metadata-registry-361e5/build/1.0.140

**Comment by andrewgodwin** [comment]
The reason it fails with a newer Channels build (specifically, it's failing on Daphne 1.0) is because that version imports from a part of Twisted we never previously imported from - specifically `twisted.internet.endpoints`.

Unfortunately, this is an open bug in Twisted (http://twistedmatrix.com/trac/ticket/6032), so I can't fix it. The workaround is to manually install the `pypiwin32` package alongside the install, and then things should, I believe, work correctly. Thus, I'll close this.

As for including an appveyor.yml, I'm not super keen on including something if I don't have the means to maintain it (while I do partially develop Channels on Windows, I do so in the Windows Subsystem for Linux rather than the Win32 subsystem), so I'd probably take a PR for one but not have it set up to block pull requests and the like.

**Comment by LegoStormtroopr** [comment]
Thanks for the help on that. I thought it wasn't a channels issue, but its good to have proof. PR coming soon.

**Comment by luxaritas** [comment]
FYI it looks like the Twisted bug has been resolved, though I have no idea how that fits into their release schedule (or yours)

**Comment by rahimnagori** [comment]
I'm getting this error when I add 'channels' to my DJango **INSTALLED_APPS** variable.
I have also done : 

> pip install pypiwin32
