### ISSUE TITLE
are channel workers multithreaded?

### ISSUE THREAD

**Issue by saurabhkumargangwar** [django/channels#503]
continuing discussion from django daphne issue ;
https://github.com/django/daphne/issues/69

We have 7 workers running on production. We see linear time increase as the number of request per second increases.
If suppose there are X workers, does that mean only X number of request can be handled at a time and all other requests will be queued which in turn will increase the response time ?

**Comment by andrewgodwin** [comment]
As mentioned in that ticket, no, they are not multithreaded, they are synchronous and only handle a single message at a time. Notice that this does not equate to a connection; each worker can only handle one traditional HTTP connection, but many more WebSockets, as they only run code when a connected socket connects, disconnects or sends a message.

Given that Python's threading framework often makes things perform worse, and the worker pattern is designed to have no idle time (as any idling would be handled by the design of Channels), I don't see an advantage to adding threading on top of what is already a multi-process worker system.
