### ISSUE TITLE
setup.py: Declare classifiers specifying that python 3 is supported

### ISSUE THREAD

**Issue by NotSqrt** [django/channels#505]
Hi !

`channels` does not declare particular `classifiers` in the setup.py, which prevents requires.io, djangopackages.org etc to detect that indeed, python 3 is supported, by adding the classifier `'Programming Language :: Python :: 3'`.

Thanks !

**Comment by andrewgodwin** [comment]
I've added them in; they'll appear with the next release on pypi.
