### ISSUE TITLE
Generic Consumers > WebSocketMultiplexing: def connect(self, multiplexer=None, **kwargs)

### ISSUE THREAD

**Issue by dilyanpalauzov** [django/channels#506]
In section Generic Consumers > WebSocketMultiplexing:
```
def connect(self, multiplexer=None, **kwargs):
  multiplexer.send(["status": "I just connected!"})
```
is not written well, as it crashed when ```multiplexer is None```, and clearly ```multiplexer``` can be ```None```, according to the method signature.

Likewise for ```def disconnect``` and ```def receive``` in the same snippet.

**Comment by andrewgodwin** [comment]
Are you using Channels 1.0.2? It sounds like you might be on an older version - multiplexer is definitely passed through. I'll correct the docs to remove the `=None` part though.
