### ISSUE TITLE
enforce_ordering

### ISSUE THREAD

**Issue by dilyanpalauzov** [django/channels#509]
According to the implementation of enforce_ordering it is wrong to call ```@enforce_ordering(slight=True)```, however the sample in docs/getting-started.rst line 681 do exactly this.

Please update the documentation to state, that no ```@enforce_ordering``` decorator implies slight ordering.

The sentence "There’s a cost to using enforce_ordering, which is why it’s an optional decorator, and the cost is much greater in strict mode than it is in slight mode. " is also misleading.  The cost of not using the decorator is the same as the cost of using the decorator in the impossible slight=True mode.

Do I understand correctly, that in slight mode a receive is called only after the connect has returned?

The code snippet under Generic Consumers > WebSockets is also misleading, as it states
```
class MyConsumer(WebsocketConsumer):
  # Set to True if you want them, else leave out
  slight_ordering = False

class MyConsumer(JsonWebsocketConsumer):
  # Set to True if you want them, else leave out
  slight_ordering = False
```

Under Generic Consumers > Websockets 1st paragraph, replace "serializes all messages sent and receives using JSON" to "received".

```self.close() is also provided to easily close the WebSocket``` shall be mentioned right after self.path, to indicate that it applies to Websocketconsumer and derived classes.  Putting it when JsonWebSocketConsumer is described suggests, that self.close() applies only to the latter class.

**Comment by andrewgodwin** [comment]
Thanks for that - I've rewritten the getting started section and fixed the second doc.
