### ISSUE TITLE
API to check for channel existence?

### ISSUE THREAD

**Issue by edevil** [django/channels#511]
I'm developing a long polling endpoint that signals when there are new "events" for a given user. It has 2 behaviours:

- If there are new events, return immediately indicating this fact
- else:
    - schedule a 30s delayed message, include the reply_channel, to cause a HTTP response to be written indicating there were no new messages
    - add the current reply_channel to a user specific group

Meanwhile, whenever a new "event" arrives, I write HTTP responses to the user-specific group, which will be delivered to the subscribed channels and thus to the browsers indicating new events.

In order to make this process more clean, I would like to be able to do 2 things:

- check, while responding to the delayed message, if the browser is still waiting for a response or if an event has arrived in the meantime. I know that I can just write it even when there is no one listening but at least I would be able to log correctly the event. Basically I want to be able to check if a channel still exists or, alternatively, delete the delayed message before it is triggered.
- delete the group whenever a new event arrives and all channels are notified. Right now I'm thinking of iterating through layer.group_channels(GROUP) and issuing group.discard(CHANNEL) but it doesn't seem very efficient.

**Comment by andrewgodwin** [comment]
Unfortunately the architecture and design of Channels means there is no way to check for "existence" of a channel, nor can there be. Additionally, `group_channels` is incredibly inefficient and should not be used in production code.

You will likely need to do a bit of custom management of the HTTP reply_channels with a database table, where you keep both a list of pending events and a list of waiting channels in there and dispatch accordingly.

**Comment by edevil** [comment]
When groups have typically 0-1 channels attached - they are user specific channels so either they are listening or not - is ```group_channels``` still that bad of a performance hit?

**Comment by germanjoey** [comment]
Are you just trying to figure out which groups a user is a part of? You
could just track this yourself with redis.

**Comment by andrewgodwin** [comment]
It's more that, depending on the backend, it may not be optimised very well _and_ it may not be accurate (group_channels might include ones that are already gone, in particular, as channels have no closed state so it doesn't track that)

**Comment by edevil** [comment]
As for ```Channel.exists()```, I can work around it by storing state in the DB or Redis to check if it has already been serviced.

However, for ```Group.discard_all()```, I see no other option but to iterate over its channels and discard them individually. This is because the Group is used to send the HTTP response, and then these channels are done. Is there some hook that I can implement to trigger when a http.response! channel has been used and discard it there?

**Comment by edevil** [comment]
Or a one-time use Group? :)

**Comment by andrewgodwin** [comment]
You should instead discard from Groups from within the `http.disconnect` channel consumer, as at that point you know the response channel is done (it'll get triggered right after you send the response). Don't worry too much about having "invalid" (closed) channels in Groups; they'll just send into nowhere without an error and the messages will expire away.
