### ISSUE TITLE
Configurable delay sleep

### ISSUE THREAD

**Issue by edevil** [django/channels#512]
I've been playing with the delay protocol server and I have already found a use for it. However, it sports a tight loop with a, IMHO, very small sleep value (0.01s). Running the protocol server produces a noticeable load on my machine.

I think this sleep value should be configurable, or at least set higher (I propose 1 second).

**Comment by andrewgodwin** [comment]
Yes, that sleep would be fine for an idle loop, but it looks like it's also doing a database query. I'll increase it to one second and make it configurable somehow.

Could you confirm for me the load is on the database connection?

**Comment by edevil** [comment]
Yes, the load was caused by the 100 DB queries per second. In this case I was running the db server on the same machine and I had the log level at "debug", which meant that all queries were being written to the terminal...

Still, having the possibility to configure this value seems the best option, in my case I don't need sub-second precision on my delays.

**Comment by andrewgodwin** [comment]
All done - there'll be a `--sleep` option in the next release, and it'll be one second by default anyway.

**Comment by edevil** [comment]
Thanks!

**Comment by edevil** [comment]
I only now looked at the changes and it seems there are two sleep delays this time, one for the DB (configurable) and another for Redis (0.1s). TBH I was expecting the configurable delay to be used for both subsystems. Is there really a use case for polling Redis 10 times per second? :) It's not like this is a hard realtime system.

**Comment by andrewgodwin** [comment]
10 times a second is rather low compared to Daphne's full speed right now, and it's not to prevent the channel becoming full (the delay is not used if a message is present so any backlog is drained at full speed). Instead, it felt like a good compromise between delay accuracy and efficiency; if there was a second between each request, then potentially it could add a second to any given delay.

The overhead of this on the Redis backend is quite minor, too. We can probably make it configurable if it gets to be an issue.
