### ISSUE TITLE
Issue a new release

### ISSUE THREAD

**Issue by camilonova** [django/channels#517]
There are some fixes on the testing suite that is blocking me to run tests on my project, would be great if you could release a new version on Pypi with the current master status so we all can use it properly.

Thanks.

**Comment by proofit404** [comment]
New release already planned, if I understand correctly. Until then you can install channels from git with pip. So this won't block you right now.

**Comment by camilonova** [comment]
You're right. Where I can find the planned schedule?

**Comment by proofit404** [comment]
I don't think there is a schedule. I remember Andrew Godwin mention new release in near issue.

**Comment by camilonova** [comment]
@andrewgodwin Can you give us a hint?

**Comment by andrewgodwin** [comment]
A planned schedule implies that I know when I will have free time! Wednesday is my normal full day for working on Channels so by then at the latest, though I will try and do one tonight if there's time.

**Comment by camilonova** [comment]
Thank you
