### ISSUE TITLE
Type annotations - PEP 484

### ISSUE THREAD

**Issue by Sgiath** [django/channels#518]
Hi all I want to ask if you would welcome PR improving the code base according the [PEP 484](https://www.python.org/dev/peps/pep-0484/).
I think it could really helps the newcomers to figure out what is going on in the code and also it will helps the code editors to better suggest options.
If you would like it I will be happy to provide such a PR.

**Comment by proofit404** [comment]
Personally I don't like this PEP. And I hope that you PR will change API layer only.

**Comment by andrewgodwin** [comment]
Unfortunately @Sgiath the nice type annotations are Python 3.5 and up only; we currently also support 2.7 and 3.4 as well, so this isn't even possible to implement right now. The mypy comment style ones might work, but they'd be much more noise than they're worth at the moment.
