### ISSUE TITLE
Finding that slight_ordering fails occasionally upon runserver restart

### ISSUE THREAD

**Issue by germanjoey** [django/channels#525]
The scenario is this:

1.) Client connects to server, does some stuff, all is well. Consumers are fed through a Demultiplexer
2.) I ctrl-c my runserver, then restart it
3.) client then reconnects via its ReconnectingWebsocket
4.) The Client waits until status is WebSocket.OPEN, then sends some messages to re-establish its state
5.) At this point, *sometimes* the websocket.connect message is processed via its consumer first, but sometimes a websocket.receive message becomes processed first. (and my application relies on always being able to process connect first, to set up the channel session, etc. so this is kinda bad for me.)

I thought this sort of thing was impossible now that slight_ordering was ubiquitously enforced? If I'm misunderstanding something, I can add an extra handshake step in my connection process, but I just wanted to check to see if this was a bug or not first.

I am up-to-date with the latest versions of channels, asgi_redis, asgiref, and daphne.

**Comment by andrewgodwin** [comment]
If you are on the latest version of Channels/Daphne this isn't possible, as the connect consumer must return either a `send` or `accept` message back to Daphne before daphne continues to open the connection, _and_ channels delays sends until after a consumer exits.

Are you completely sure this is what's happening? Can you add logging with the reply_channel to the start and end of each of the consumers and check?

**Comment by germanjoey** [comment]
Here's some logs that demonstrate the issue:

http://imgur.com/a/Eze3Q

Sometimes message.user becomes AnonymousUser when this happens, but not in this instance. (I'm not 100% sure that it's a related problem, although it seems that way)

**Comment by andrewgodwin** [comment]
It's possible the demultiplexing is somehow messing with it - could you try it without that and just a single consumer hooked straight up and see what happens?

**Comment by germanjoey** [comment]
Hmmm, I can't easily hook up the consumer without the Demux, but I did try removing all but one of the Demux's consumers, and, interestingly, I could not duplicate the problem. But why would the demux be an issue? The only thing I can think of is that each of my consumers, as well as the demux, are emitting accept:true messages... would that do it?

**Comment by germanjoey** [comment]
Ah, it was my problem after all! The issue was this line in my demux subclass:

` self.message.reply_channel.send({'accept': True, immediately=True})`

With the `immediately=True` removed, I don't have an issue any more. Honestly, I don't even remember why I added that to begin with, d'doh!

**Comment by andrewgodwin** [comment]
Ah yes, `immediately` is only if you really know what you're doing, otherwise, as you've seen, it breaks the contract! Glad it got sorted.
