### ISSUE TITLE
No module named decorators on manage.py runserver virtualenv

### ISSUE THREAD

**Issue by monk8800** [django/channels#529]
Hi guys am trying out django channels running on Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32 seem to be getting the following error 

 raise ImproperlyConfigured("Cannot import channel routing %r: %s" % (routing, e))
ngo.core.exceptions.ImproperlyConfigured: Cannot import channel routing 'mynewsfeed.routing.channel_routing': No module named decorators

requirements.txt as follows 
appdirs==1.4.0
asgi-redis==1.0.0
asgiref==1.0.0
attrs==16.3.0
autobahn==0.17.1
Automat==0.5.0
channels==1.0.3
constantly==15.1.0
daphne==1.0.3
Django==1.9.12
incremental==16.10.1
msgpack-python==0.4.8
packaging==16.8
pyparsing==2.1.10
redis==2.10.5
six==1.10.0
Twisted==17.1.0
txaio==2.6.1
zope.interface==4.3.3

I also installed pypiwin32 as i was getting ImportError: No module named win32api
setting.py 

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
        },
        "ROUTING": "mynewsfeed.routing.channel_routing",
    },
}
```

routing.py 

```
from channels.routing import route
from feed.consumers import ws_add, ws_keepalive, ws_message, ws_disconnect

channel_routing = [

	route("websocket.connect", ws_add),

	route("websocket.keepalive", ws_keepalive),

	route("websocket.receive", ws_message),

	route("websocket.disconnect", ws_disconnect),
]

```

**Comment by andrewgodwin** [comment]
Could you provide the full traceback with line numbers please?

**Comment by monk8800** [comment]
```
(venv) C:\channels>python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x0392F1F0>
Traceback (most recent call last):
  File "C:\channels\venv\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\channels\venv\lib\site-packages\channels\management\commands\runserver.py", line 40, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "C:\channels\venv\lib\site-packages\channels\asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "C:\channels\venv\lib\site-packages\channels\asgi.py", line 48, in make_backend
    routing=routing,
  File "C:\channels\venv\lib\site-packages\channels\asgi.py", line 80, in __init__
    self.router = Router(self.routing)
  File "C:\channels\venv\lib\site-packages\channels\routing.py", line 25, in __init__
    self.root = Include(routing)
  File "C:\channels\venv\lib\site-packages\channels\routing.py", line 201, in __init__
    self.routing = Router.resolve_routing(routing)
  File "C:\channels\venv\lib\site-packages\channels\routing.py", line 75, in resolve_routing
    raise ImproperlyConfigured("Cannot import channel routing %r: %s" % (routing, e))
django.core.exceptions.ImproperlyConfigured: Cannot import channel routing 'mynewsfeed.routing.channel_routing': No modu
le named decorators
```

**Comment by andrewgodwin** [comment]
I suspect the underlying import error is in the `feed.consumers` module - try importing that directly from a Python shell. Alternately, Python 3 would show you all layers of exceptions including the import error that Channels is catching here.

**Comment by monk8800** [comment]
@andrewgodwin  your right The cluprit seems to be my import statements in consumers.py note to self always check throughly. I think might have mixed yup the code, i was referencing examples from Channels 0.8 while using channels 1.0.3. decorators.py has been dropped?

currently 
`from channels.decorators import channel_session, linearize`

Changed to 
`from channels.sessions import channel_session`

How about the linearize decorator is this still valid in 1.0.3?

```
def linearize(func):
    """
    Makes sure the contained consumer does not run at the same time other
    consumers are running on messages with the same reply_channel.
```

**Comment by andrewgodwin** [comment]
Oh, those _are_ old. Linearize is replaced partially by the default handling of `connect` before `receive` in 1.0, and if you still want full linearization you now want the `strict_ordering` decorator (http://channels.readthedocs.io/en/stable/getting-started.html#enforcing-ordering)

**Comment by monk8800** [comment]
@andrewgodwin Thanks appreciate the assistance
