### ISSUE TITLE
Old versions of code are used with Redis as a channel layer

### ISSUE THREAD

**Issue by GRLeo** [django/channels#540]
When I use remote redis server as a channel layer some of requests are processed using the old versions of deployed code.
It affects all deployed files, not only urls (as mentioned in [489](https://github.com/django/channels/issues/489)).

I use Amazon Elasticache instance as a remote Redis 3.2.4 server. Recreation of cache server helps only for a little time.

When I use asgiref.inmemory.ChannelLayer there is no problems.

I think that it could be the problems of Elasticache itself but maybe someone has some thoughts about it

**Comment by davidmarquis** [comment]
What exactly do you mean by "requests are processed using the old versions of deployed code"?

From your explanation, I would assume you are running a version of your system using Redis as a backend. You then deploy a new version and observe that your old code is being executed when you request URLs from the ASGI server.

If that is the case, I'd say the most likely possibility is that an old version of your worker instance is still running and processing messages from that same Redis backend.

**Comment by GRLeo** [comment]
@davidmarquis you've understand my problem right. 

When I want to deploy new version of code I stop the server, deploy the code and start my server again using manage.py runserver. I thought that worker restarts after it with the new version of code, doesn't it?

**Comment by proofit404** [comment]
Do you use single runserver command with DEBUG setting enabled?

**Comment by GRLeo** [comment]
@proofit404 yes

**Comment by proofit404** [comment]
Check redis connection list. You can have some runserver instances running old code.

**Comment by davidmarquis** [comment]
You might as well inspect the list of running processes on the host(s) you're running this. Look out for lingering `python` processes...

**Comment by andrewgodwin** [comment]
Your problem is runserver likely not exiting cleanly; it's not designed for production use so don't use it. Instead, deploy a separate daphne and runworker instance as described in the docs (http://channels.readthedocs.io/en/latest/deploying.html), and then runworker should cleanly exit when you ask it to.

**Comment by GRLeo** [comment]
@andrewgodwin @davidmarquis @proofit404 thank you!

P.S. I didn't use runserver for production, I wrote about deployment to my dev server.
