### ISSUE TITLE
How to exclude certain socket_ids from websocket_group when sending a message

### ISSUE THREAD

**Issue by intellisense** [django/channels#545]
Hi,

As far as I have understood `websocket_group.send` (`Group(group_name).send({"text": json.dumps(data))`) will send a message to all subscribers. Is it possible to exclude some subscribers?

Scenario (not my actual scenario):
   - Consider a chat room where three users A, B and C are connected.
   - User A muted user B
   - User A sends a message in room which should only be received by User C as User B is muted by User A

Thanks!

**Comment by andrewgodwin** [comment]
No, it is not possible to exclude certain channels from a particular send. Either make more groups or handle sending to each user individually (using a group per user).

**Comment by CosmicReindeer** [comment]
Umm this is late but is sending to individual channel layers advisable?

I have a case where I have to check role based permissions for the user but every time I do it I need to make a trip to the database

**Comment by CosmicReindeer** [comment]
Say a user has role 1 with permissions X Y Z

And another user has role 2 with permissions A Y C

I need to check and send the message to users who have permissions A
