### ISSUE TITLE
when i receive a message, how can i get the client ip address?

### ISSUE THREAD

**Issue by belongwqz** [django/channels#546]
I use nginx as proxy, when I receive a wsgi(or asgi) request, I can get the client ip address from the HTTP_X_REAL_IP or HTTP_X_FORWARDED_FOR header, but when receive a websocket message, how can I get the client ip address? It‘s’ recommended to add similar support when need a security log audit.

**Comment by andrewgodwin** [comment]
You can either retrieve it from the same headers (HTTP headers are forwarded to `websocket.connect` handlers) or use the `--proxy-headers` option for Daphne.

**Comment by belongwqz** [comment]
Maybe add "--proxy-headers" to channels's management commands and run like "python manage.py runserver --noworker **--proxy-headers**" is a good idea.Compared to “daphne xxx”, I prefer “python manage.py xxx” here.

**Comment by andrewgodwin** [comment]
Well, `manage.py runserver` is not suitable for use in production, so it is deliberately not present as there isn't a scenario where you would want to use runserver behind a proxy.
