### ISSUE TITLE
Impossible to create a WS connection Handshake not working

### ISSUE THREAD

**Issue by Marblepunk** [django/channels#549]
Hi !

I'am trying to make channel working and I have an error. Other people doesn't have this error on their computer (it's a group project).

When I am trying to connect to a websocket: 
`var socket = new WebSocket("ws://" + window.location.host + "/ws/tts/");`

The server Side print that until connection time out:

```
[2017/02/28 20:02:52] WebSocket DISCONNECT /ws/tts/ [127.0.0.1:50120]
connection Chat groups json
disconnect Chat json
[2017/02/28 20:02:52] WebSocket HANDSHAKING /ws/tts/ [127.0.0.1:50121]
connection Chat groups json
connect Chat json
[2017/02/28 20:02:57] WebSocket DISCONNECT /ws/tts/ [127.0.0.1:50121]
connection Chat groups json
disconnect Chat json
[2017/02/28 20:02:57] WebSocket HANDSHAKING /ws/tts/ [127.0.0.1:50122]
connection Chat groups json
connect Chat json
[2017/02/28 20:03:02] WebSocket DISCONNECT /ws/tts/ [127.0.0.1:50122]
connection Chat groups json
disconnect Chat json
[2017/02/28 20:03:02] WebSocket HANDSHAKING /ws/tts/ [127.0.0.1:50128]
connection Chat groups json
connect Chat json
[2017/02/28 20:03:07] WebSocket DISCONNECT /ws/tts/ [127.0.0.1:50128]
connection Chat groups json
disconnect Chat json
```

and after connection time out javascript console print:
`WebSocket connection to 'ws://127.0.0.1:8000/ws/tts/' failed: Error during WebSocket handshake: net::ERR_CONNECTION_RESET`

The code is working on other computer so I think the error is because a firewall, other service, asgi... But I disable all service and my anti-virus so I run out of idea.

I use:
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "headServer.routing.channel_routing",
    },
}

In Windows 10 64 bits
Django 1.10.5
Twisted 16.6.0
asgiref 1.0.0
daphne 1.0.1

runing with runserver

Thank for any help.

**Comment by andrewgodwin** [comment]
It looks like you aren't sending an acceptance message back to Daphne in your connect handler (http://channels.readthedocs.io/en/stable/releases/1.0.0.html#connect-consumers) - maybe the other members of the group have different versions of Channels?

**Comment by Marblepunk** [comment]
Indeed you were right, i've got an old version of channels and i add "self.message.reply_channel.send({"accept": True})". 
Now it works good.
Thank you very much for you help!
