### ISSUE TITLE
how to configure client automatically disconnect time

### ISSUE THREAD

**Issue by hanchen999** [django/channels#550]
Hello, guys
 I have one problem about group channels. Suppose I want to keep one client alive for 

more  than 3 mins. How should I configure the disconnect function? Now my client can not stay 

longer than 90 seconds. When they send a new message, I saw a new ip address....

**Comment by hanchen999** [comment]
Hello, guys

         I have one problem about group channels. Suppose I want to keep one client alive for more than 3 mins. How should I configure the disconnect function? Now my client can not stay longer than 90 seconds. When they send a new message, I saw a new ip address....

**Comment by andrewgodwin** [comment]
Channels doesn't control disconnects - that's purely down to your browser and how long they hold the socket open for.
