### ISSUE TITLE
Slow with very limited number of connections. Why?

### ISSUE THREAD

**Issue by LadaBr** [django/channels#552]
Hi, im using django-1.10 + channels + asgi_redis + daphne + uwsgi + nginx but i have problem with workers+daphne being slow. 

Im developing chat and I tried how fast its by holding ENTER button (spamming messages one after one and it doesn't even respond until i stop sending messages.

When i try to test performance (sending message to websocket every 10 ms) i get kicked after 5 seconds..when i try to do it every 100 ms, nobody else can connect. I checked CPU usage and when i set runworker --threads 500 there is running like 250 threads of workers...when i set 10 threads then its like no way to use it
One client sending message every 100ms: https://i.imgur.com/5F4mKAI.png

Yesterday i tried to use it in production and when there were 15 clients connected (each one pinging server every 2 seconds) nobody else could connect.

I have default settings and I followed Getting started tutorial.

Am I doing something wrong? Why are workers so slow in processing of one websocket message that is empty string?

How should I setup channel_layer to be able to handle at least 50 connections that ping server every 2 seconds and recieve group messages on some event?

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 121, in send
    client=connection,
  File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 2694, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 1944, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/redis/connection.py", line 582, in read_response
    raise response
redis.exceptions.ResponseError: full

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
>     self.run()
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 164, in run
>     worker.run()
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/worker.py", line 151, in run
>     consumer_finished.send(sender=self.__class__)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 191, in send
>     response = receiver(signal=self, sender=sender, **named)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/message.py", line 93, in send_and_flush
>     sender.send(message, immediately=True)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/channels/channel.py", line 44, in send
>     self.channel_layer.send(self.name, content)
>   File "/var/www/django/dotaleague.cz/env/lib/python3.5/site-packages/asgi_redis/core.py", line 126, in send
>     raise self.ChannelFull
> asgiref.base_layer.BaseChannelLayer.ChannelFull
>

**Comment by andrewgodwin** [comment]
Please don't cross-post both here and the mailing list. I will answer there (https://groups.google.com/forum/#!topic/django-users/J-rJavW0spk)

**Comment by maxchannels** [comment]
Hi, the above link is down.
