### ISSUE TITLE
WebSocket is closed before the connection is established

### ISSUE THREAD

**Issue by susejreina** [django/channels#553]
Hi! I'm very sad, because I have more than 2 weeks trying to put on production my site on AWS, and it was impossible to me. I'm work with DJANGO CHANNELS, ussing Redis as channel layer and Dphane as protocol server. Now, I put everything on my AWS; and It was ok, but my chat isn't working.
I created an ALB(Application Load Balancer) with two targets group, point one to port 80 and the other to port 5000; then I redirected by rules, in order if the url has the /ws/ it come to 5000port. I also, add to supervisord file the commands to add Daphne(using port 5000 and asgi.py) and a few workers. But, It hasn't worked, appear the next error "WebSocket connection to 'ws://xxxxxxx/ws' failed: WebSocket is closed before the connection is established". 
I tryed to call EC2 instance, directly, because i thoguth that maybe was a ALB configuration, but I get the next error: "WebSocket connection to 'ws://xxxxx.compute-1.amazonaws.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 404".
I put as my redis conection, the end point that give me AWS, I have my asgi.py file; and my site work very good on local enviroment.
hank you in advance for your attention to my request.

**Comment by andrewgodwin** [comment]
Hi, please direct general support requests like to the django-users mailing list in future.

As for your error, "unexpected response 404" means you are not talking to Daphne but to a normal webserver (or you are going through a proxy that does not support WebSocket). I would fix that first so you can make it work directly and then solve the ALB problem.
