### ISSUE TITLE
Trying to send to a group doesn't work from outside of Channels

### ISSUE THREAD

**Issue by cjds** [django/channels#556]
Bug Report:

- Ubuntu 14.04, Python 2.7

- Software versions

     asgi-redis==1.0.0
     channels==1.0.3
      daphne==1.0.3
      Django==1.10.5

I'm trying to send message to a group from a Redis backend

This is my consumer

    class AWebSocketConsumer(JsonWebsocketConsumer):
          channel_session_user = True

         def connection_groups(self):
             return ["ros_messages"]
 
        def connect(self, message):
                 Group("ros_messages").add(self.message.reply_channel)
                 message.reply_channel.send({"accept": True})

          def send(self, content, close=False):
                   print "I'm trying to send something"

Somewhere else in my code. Specifically, on an HTTP Request, I run this command

    Group("ros_messages").send({
             "text": message
     })

I get no failure message, but I can't see the message being sent out via the consumer

I was reading through the docs, and I was wondering if I misunderstood this: 

>Note that this (JSONWebSocketConsumer) subclass still can’t intercept Group.send() calls to make them into JSON automatically, but it does provide self.group_send(name, content) that will do this for you if you call it explicitly.

Or if I misunderstood how groups worked

- Running Channels with Daphne and runworker

**Comment by andrewgodwin** [comment]
What channel layer are you using?

**Comment by cjds** [comment]
Sorry, I meant the standard Redis backend

**Comment by andrewgodwin** [comment]
Yes, that should work - I don't know why it isn't, but this part is pretty well tested so it's probably a configuration or timing thing. Does a group send done inside `connect` next to the group add work?

**Comment by cjds** [comment]
Nope. I just made my connect look like this:

        def connect(self, message):
        Group("ros_messages").add(self.message.reply_channel)
        Group("ros_messages").send({ "text": "{'why':'hello'}"})
        message.reply_channel.send({"accept": True})

Am I correct in thinking that it should go to the send function and print "I'm trying to send something"

**Comment by andrewgodwin** [comment]
No, the send function is not called when you send to a group, it's done directly into the channel layer (in this case, Redis), so you won't see anything happening. I'm not really sure what the problem is, you might want to run `MONITOR` in redis to make sure it's doing stuff.

**Comment by cjds** [comment]
Made a mistake somewhere in my Javascript which was why it appeared as if it wasn't sending. Thanks for all the help :-)

**Comment by jamiecounsell** [comment]
I had the same issue, and if anyone comes across it, my problem was that it appears you cannot send a message where `'text'` is empty. For 

```
Group(get_message_group(self.user)).send({
    'text': "New Message"
})
```

Worked, but 

```
Group(get_message_group(self.user)).send({
    'text': ""
})
```

did not.
