### ISSUE TITLE
websocket.connect more explicit docomentation

### ISSUE THREAD

**Issue by sebhaase** [django/channels#557]
I just had a problem with `websocket.connect`.
I finally found the answer in
https://channels.readthedocs.io/en/stable/releases/1.0.0.html#backwards-incompatible-changes

Also here:
http://channels.readthedocs.io/en/stable/releases/1.0.0.html?highlight=websocket%20connect#websocket-accept-reject-flow

I would suggest mentioning this more prominently in the docs:

>    Rather than be immediately accepted, WebSockets now pause during the handshake while they send over a message on websocket.connect, and your application must either accept or reject the connection before the handshake is completed and messages can be received.

Also it should be stated *how* this is done ...  

You can see what I mean by searching the docs:
https://channels.readthedocs.io/en/stable/search.html?q=websocket+connect&check_keywords=yes&area=default

(The relevant info is hidden ...)

Regards, Sebastian

**Comment by sebhaase** [comment]
#549

**Comment by sebhaase** [comment]
I located what I think is the first place in the docs where an explicit `connect` consumer is being defined:
http://channels.readthedocs.io/en/stable/getting-started.html#groups
defines 
```
def ws_add(message):
    message.reply_channel.send({"accept": True})
    Group("chat").add(message.reply_channel)
```
I would suggest adding a one-sentence note that 

> the first code line is required (since 1.0.0) for the websocket handshake to complete successful. Other options and further detail on the `websocket.connect` consumer are discussed in ...(link to reference)...

(Ok, two sentences ...)

**Comment by sebhaase** [comment]
http://channels.readthedocs.io/en/stable/concepts.html
is even missing the respective line
```
# Connected to websocket.connect
def ws_connect(message):
    # Add to reader group
    Group("liveblog").add(message.reply_channel)
```
almost at the end of that page.

**Comment by andrewgodwin** [comment]
I've updated the docs a bit more in cad6345, but it won't show up on the "stable" docs until the next release unfortunately (that's also why you can't see the changes I already added to e.g. the group example). Hopefully I can get a release out soon, just waiting on some pull requests.
