### ISSUE TITLE
Websockets giving 404 in production over nginx

### ISSUE THREAD

**Issue by kosiraljaz** [django/channels#558]
Hi, I deployed django channels app on my production server using daphne, nginx and supervisor. However connecting to socket is giving me 404.

python package versions:
```
channels==1.0.3
daphne==1.0.2
```

routing file:

```
channel_routing = [
	route_class(APIDemultiplexer, path=r'^/api/(?P<user_id>[0-9]+)/$')
]
```

nginx config:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream rest {
        server 127.0.0.1:8001 fail_timeout=0;
}

server {
        listen 80;
        client_max_body_size 4G;
        server_name rest

        keepalive_timeout 5;

        access_log  /home/rest/restapi/logs/rest.access.log;

        root /home/rest/restapi;

        location /static/ {
                 root /home/rest/restapi;
        }

        location /media/ {
                 root /home/rest/restapi;
        }
"/etc/nginx/sites-available/restapi.conf" 92L, 2649C                                                                                     1,1           Top



        location /api/{
            proxy_pass http://rest;
            proxy_redirect off;
            proxy_buffering off;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

        }
}
```

I run daphne with:

`command=/home/rest/restapi/env/bin/daphne -b 127.0.0.1 -p 8001 --root-path='/api' restapi.asgi:channel_layer`

when I try to connect to my server via websocket with:
`var socket = new WebSocket("wss://mydomain.api.com/api/")`

I get a: `failed: Error during WebSocket handshake: Unexpected response code: 404`

I also noticed that If i try to connect to websocket via nginx my django logs shows this:
`[2017/03/13 15:48:31] HTTP GET /api/ 404 [0.02, 127.0.0.1:55294]`

But if I connect directly runserver's port I'll get a:
```
[2017/03/13 15:50:38] WebSocket HANDSHAKING /api/ [10.30.1.31:50029]
[2017/03/13 15:50:38] WebSocket CONNECT /api/ [10.30.1.31:50029]
```
It feels like my nginx configuration is broken, because I think there should be `WebSocket `instead of `GET `but I don't think I missed something. I didn't find anything related to nginx in the docs, maybe it would be good idea to add some?

Thanks! :)

**Comment by andrewgodwin** [comment]
Getting a HTTP error code back from a WebSocket connection like that means that something between you and Daphne is downconverting it to HTTP. Could be your nginx, could be something else along the way. Unfortunately I can't help debug nginx - there's so many different variations that it's nigh impossible to get it all figured out remotely.

I should add some examples to the docs, I'll look at doing it when I get time.
