### ISSUE TITLE
Is there any way to remove an entire channel Group?

### ISSUE THREAD

**Issue by germanjoey** [django/channels#559]
Is there any way to remove a whole Group? That is to say, I have a Group with N number of channels added to it. I'd either like to a.) remove all users from this group or preferably b.) remove the group entirely. Is there any way to do that?

**Comment by andrewgodwin** [comment]
Not efficiently. Your only option would be to use the (very slow) `group_channels` method on the underlying ASGI layer and then remove channels from the group one by one.

The better question is, why are you trying to do this? There's probably a better way to architecture your application so this is unnecessary.

**Comment by germanjoey** [comment]
I have some channels named after rooms. The rooms have unique names but these names are provided by the user. When a room has finished its business, the channels subscribed to the room should be removed so that if a user then creates a new room with the same name, the users who were subscribed to the old room wouldn't get messages for the new one.

But, you're right - I can just name the channels after the room's primary key instead of the name. room-73 instead of room-whatevername. Just an extra lookup, not a big deal I guess.

Thanks for the tip about group_channels though - that will still be useful for kicking a user from a room, which hopefully shouldn't happen often enough for that command's inefficiency to affect the overall application too much.

**Comment by germanjoey** [comment]
What does setting close=True on a group sent message do?

e.g. Group('whatever').send({close=True})

Will that close the current connection for every member of the group? Or just empty out the group?

**Comment by andrewgodwin** [comment]
It will trigger all group connections that are still open and active to close themselves, yes. That might then result in the group emptying if you have disconnect handlers that remove things from the group, and they all run, but it's likely there would be at least one or two stale channels in a group (which is fine for sending, the logic handles that)
