### ISSUE TITLE
Idea: websocket handshaking should be done in/following a Django view

### ISSUE THREAD

**Issue by Microserf** [django/channels#560]
I'm fairly new to Channels, so my understanding of the way the code is designed is quite limited.

I was going through the Channels tutorial exercise, but got hung up on the authentication step. I am integrating websockets into my project, and in order to make my API completely stateless, I've switched off sessions. Therefore, using the `@channel_session_user_from_http` decorator (as suggested in the tutorial) wasn't going to work for my project, as it depends on sessions.

The solution I came up with for handling authentication looks like this:
   1. The `websocket.connect` consumer is decorated with the `@channel_session` decorator.
   2. The consumer looks for the JSON Web Token (JWT) in the websocket HTTP request, which has been included in the initial `message.content`.
   3. I construct a mock request object, which holds just enough properties, so that I can pass it into the appropriate Django Rest Framework authentication functions. This returns a user.
   4. The user is put into a fake session via the `django.contrib.auth.login()` function.
   5. The user information is then transferred into the channel session via `channels.auth.transfer_user()` function.
   6. Finally, my connect consumer refuses the connection if no valid user is found in the session, and accepts the connection otherwise.

This solution was designed based on the patterns I saw in `channels.auth`.

As I understand it, the duck-typing in (3), (4) and (5) above is necessary because the initial HTTP request which initiates the Websocket connection is first cloned into `message.content` and then reconstructed in order to fit into the authentication flow, which expects HTTP-like session and request objects. Basically, the Channels/Websocket stack is "borrowing" code from the HTTP stack.

So my idea is this: would it make sense to make the websocket handshaking flow pass through the HTTP stack first? This way, the decision on whether to initiate or refuse a websocket connection is made within an HTTP context, where session, request, middleware and authentication mechanisms can all be called upon to advise, or set-up the channel session, etc.

I see the flow going something like this:
  1. HTTP request with "Upgrade: websocket" comes in
  2. Request is routed to the HTTP server
  3. Request passes through URL resolution, middleware, DRF pre-processing, authentication, etc.
  4. Request arrives at a view. View makes determination as to whether websocket should proceed.
  5. If rejected, request responds with `return HttpResponse(status=400)` or whatever.
  6. If accepted, request responds with `return WebsocketSession(session_dict)`
  7. A middleware class intercepts this response, and transitions the connection to a websocket. The contents of the `session_dict` object, if present, are used to boostrap the channel session object.

**Comment by andrewgodwin** [comment]
The problem we face here is that WebSocket requests are not quite like HTTP requests; there is no method, for example, and in addition before you even hit the accept/reject code you have to do a complex handshake dance to make sure it's a websocket client on the other end.

That said, what you propose is possible in theory, and I am not yet sure if it would make sense or not; I need to ponder on if the abstraction is good or harmful in that it hides too much stuff. Turning the connect message into a Request-alike is certainly possible, and we already have most of the code for this in `ASGIHandler`. I would probably want to instead design this as being able to wrap a view in a decorator to turn it into a `connect` consumer + middleware being run.

**Comment by jeduden** [comment]
@andrewgodwin what do you think about solving authentication via subprotocols ?
In the past i have included an oauth2 token via special named subprotocol (prefix+token), that is being checked server side when the client connects. 
Also see http://stackoverflow.com/questions/36323743/oauth2-authentication-for-websockets-pass-bearer-token-via-subprotocols

**Comment by andrewgodwin** [comment]
At the moment our support for subprotocols is just limited to direct support in Daphne for accepting a certain list of them - we should probably move that up to the application, and that would then allow something like this. There's no massive advantage over putting the token in a GET parameter, though, apart from cleanliness and better security for logs.

**Comment by andrewgodwin** [comment]
Closing this as we went a very different way with the Channels 2 design (but that does support subprotocols). But I don't think the as-views thing is going to work well in the new world.
