### ISSUE TITLE
Cannot find `websocketbridge.js` in 1.1.0

### ISSUE THREAD

**Issue by prokher** [django/channels#561]
Dear Colleagues,

I've just installed Channels 1.1.0 with: `pip install channels` in empty (new) virtualenv and cannot find any JavaScript code in it. Here are details:

```
# I am on Mac
>>> sw_vers -productVersion
10.12.3

# Python 3.6
>>> python --version
Python 3.6.0

# Channel installation details
>>> pip show channels
Name: channels
Version: 1.1.0
Summary: Brings event-driven capabilities to Django with a channel system. Django 1.8 and up only.
Home-page: http://github.com/django/channels
Author: Django Software Foundation
Author-email: foundation@djangoproject.com
License: BSD
Location: /Users/prokher/Dev/VirtEnvsPy/PPP/lib/python3.6/site-packages
Requires: daphne, asgiref, Django

# No JavaScript installed
>>> find /Users/prokher/Dev/VirtEnvsPy/PPP/lib/python3.6/site-packages/channels -name "*.js"
```

Last line returns nothing and I cannot find `websocketbridge.js` manually. Looks like something went wrong with 1.1.0.

**Comment by senden9** [comment]
Confirmed. To fix this issue i would recommend to append a line like this
`recursive-include channels/static/channels/js/ *`
into MANIFEST.in.

**Comment by andrewgodwin** [comment]
Yup, can't believe I missed that. `1.1.1` is released and includes that file.

**Comment by andrewgodwin** [comment]
The Javascript client was unmaintained and is now officially removed - sorry!

**Comment by robsdedude** [comment]
Seems like a valid decision. But there are two problems:
 - it breaks backwards compatibility -> should have been a major version update
 - it's not mentioned in the change log

**Comment by andrewgodwin** [comment]
That's true, apologies for that, but the JS library had separate releases over on npm that we ceased doing a while back, so I didn't elect to follow the versioning policy here, which was maybe a mistake. I will call it out in the next changelog.
