### ISSUE TITLE
Is python 3.6 supported?

### ISSUE THREAD

**Issue by anton-white** [django/channels#562]
python 3.6
pip 9.0.1
Django 1.11b1

`$ pip install channels`
```
Collecting channels
  Using cached channels-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: Django>=1.8 in /home/anton/venv/pl/lib/python3.6/site-packages (from channels)
Collecting asgiref>=1.0.1 (from channels)
  Using cached asgiref-1.0.1-py2.py3-none-any.whl
Collecting daphne>=1.0.0 (from channels)
  Using cached daphne-1.1.0-py2.py3-none-any.whl
Requirement already satisfied: pytz in /home/anton/venv/pl/lib/python3.6/site-packages (from Django>=1.8->channels)
Collecting six (from asgiref>=1.0.1->channels)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting twisted>=17.1 (from daphne>=1.0.0->channels)
  Could not find a version that satisfies the requirement twisted>=17.1 (from daphne>=1.0.0->channels) (from versions: )
No matching distribution found for twisted>=17.1 (from daphne>=1.0.0->channels)
```

**Comment by anton-white** [comment]
Pardon me, I've looked at readme and it doesn't have 3.6 yet.
However is it only Twisted blocking to use 3.6?

**Comment by anton-white** [comment]
Twisted says it supports Python 3.3+

**Comment by proofit404** [comment]
Try to install Twisted from sources. Check out 17.1 tag and run setup.py

**Comment by andrewgodwin** [comment]
I have no idea why that wouldn't work, Twisted definitely has a 17.1 release that you can install. Try installing it direct from the tarball link: https://pypi.python.org/packages/d2/5d/ed5071740be94da625535f4333793d6fd238f9012f0fee189d0c5d00bd74/Twisted-17.1.0.tar.bz2#md5=5b4b9ea5a480bec9c1449ffb57b2052a

**Comment by proofit404** [comment]
Maybe because of python version classifiers. Just a guess.

**Comment by anton-white** [comment]
I was using self-compiled Python 3.6.
After I followed this: http://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get
the issue has gone.

Thanks guys!

**Comment by anton-white** [comment]
For those who don't trust non-official PPAs, I've recompiled 3.6.1 on a machine without PPA mentioned above, and channles with Twisted dependency was installed without issues.
