### ISSUE TITLE
About Channel("...").send("...") Method

### ISSUE THREAD

**Issue by lingliqianxun** [django/channels#565]
consumers.py

    def ws_receive(message):
        payload = json.loads(message['text'])
        payload['reply_channel'] = message.content['reply_channel']
        Channel("chat.receive").send(payload)

routing.py

    custom_routing = [ 
        route("chat.receive", chat_join, command="^join$"),
        route("chat.receive", chat_leave, command="^leave$"),
        route("chat.receive", chat_send, command="^send$"),
    ]

Find the core file:
channels.worker.py

    message = Message(
	    content=content,
	    channel_name=channel,
	    channel_layer=self.channel_layer,
    )

    match = self.channel_layer.router.match(message)
    if match is None:
	    logger.error("Could not find match for message on %s! Check your routing.", channel)
	    continue
    else:
	    consumer, kwargs = match

The problem:
if client send a message command not in ["join", "leave", "send"],
Channel("chat.receive").send(payload) will be log "ERROR - worker - Could not find match for message on user.receive! Check your routing.",
can you add a return result on Channel("chat.receive").send(payload) to determine whether the parameter exists?
I think this is a need to strengthen the function.
And I didn't find Channel("...").send("...") description use in the document, I only see in your channels-example multichat.

The following is Chinese:
问题：
如果客户端发送一个命令command不在["join", "leave", "send"],
Channel("chat.receive").send(payload)只会打印日志"ERROR - worker - Could not find match for message on user.receive! Check your routing.",
能否添加一个返回结果在Channel("chat.receive").send(payload)用于判断是否存在该参数？
我觉得这是一个需要加强的功能。
我没有找到Channel("...").send("...")方法说明在文档里，我只在你的channels-example multichat看到。

**Comment by andrewgodwin** [comment]
If you want to handle the default case where it does not match anything else, simply add a default route at the end like this:

```
custom_routing = [ 
    route("chat.receive", chat_join, command="^join$"),
    route("chat.receive", chat_leave, command="^leave$"),
    route("chat.receive", chat_send, command="^send$"),
    route("chat.receive", chat_error),
]
```

Then you can send back an error or do whatever you need to in this case.
