### ISSUE TITLE
 :doc:`concepts` broken in getting-started.rst

### ISSUE THREAD

**Issue by sebhaase** [django/channels#570]
I'm not sure if this is a bug to be reported here --
but I noticed that in 
https://github.com/django/channels/blob/master/docs/getting-started.rst
there are multiple links , - like e.g.  :doc:`concepts`  to something like 
https://github.com/django/channels/blob/master/docs/getting-started.rst#id9

and the `#id9` leads nowhere ...

**Comment by andrewgodwin** [comment]
That's because it's a Sphinx .rst template, not a plan .rst one, and that syntax does cross-document links. You can see it working properly at http://channels.readthedocs.io/en/latest/getting-started.html
