### ISSUE TITLE
HTTP/2 in development workflow.

### ISSUE THREAD

**Issue by funn** [django/channels#573]
Since daphne [supports](https://github.com/django/daphne/pull/61) HTTP/2 pretty much out of the box it would be great to be able to use it without much hassle in development workflow. I'd like to see a new option introduced to `manage.py runserver` command to specify SSL endpoint with custom certificates.

Let's discuss how this option could look like, also I'd like to implement it if needed.

**Comment by andrewgodwin** [comment]
I'd like to ask what exactly you'd want HTTP/2 in development _for_ right now. There's no additional features over HTTP/1, and the speedup gains are minimal as it's already a local connection.

Not to mention that autogenerated custom certs would mean either bypassing security warnings or installing a custom CA into someone's computer. I don't see a need for this to be in the main channels package right now; I'd rather let people run daphne with the right arguments if they need it locally. There's nothing to stop you implementing something and releasing it as a third-party package, though!
