### ISSUE TITLE
ng-django-channels

### ISSUE THREAD

**Issue by NadavK** [django/channels#576]
The new js-client is great!
Any chance of an Angular2 compatible package?

**Comment by andrewgodwin** [comment]
There won't be any framework-specific packages included in the official Channels project itself, but people are free to build them on top of the library we ship and I'll happily link to them in the docs.

**Comment by proofit404** [comment]
It will be definitely a third party package. And probably npm only package. Can you write a list of desired features? So if anyone decide to implement it, he will know what users already miss.
