### ISSUE TITLE
Unhandled exception in consumer breaks current socket connection

### ISSUE THREAD

**Issue by sachinrekhi** [django/channels#581]
One of the things I've noticed is that if I have a consumer handle a socket message and the consumer ultimately throws an unhandled exception, then subsequent socket messages from the client don't work and the client has to establish a new socket connection to continue having socket messages properly processed. This was not what I was expecting, as I assumed the subsequent requests would just work, despite this unhandled exception.

I'm still on channels 0.13.1 with asgi_redis back-end, so curious if this behavior is the same in the latest version of channels? If it is the same, is the best practice then that all consumers should at the highest level catch exceptions (or maybe via a decorator) to prevent it breaking the socket connection?

**Comment by andrewgodwin** [comment]
Do you have the `enforce_ordering` decorator turned on? If you do, then this behaviour will exist, if not, it should not.

**Comment by sachinrekhi** [comment]
Yes I do use enforce_ordering. OK, so that's expected behavior then in my case. Sounds like I should then always catch to ensure enforce_ordering can properly track and process the next message.

**Comment by andrewgodwin** [comment]
Yup. It's worth noting that if you're only enforcing ordering so connect happens first, then upgrading to 1.0 or above gives you that for free without the decorator.

**Comment by sachinrekhi** [comment]
Awesome, thanks Andrew! I do need full enforce ordering on all messages for my use-case (real-time editing scenario). But planning on upgrading to 1.0 soon anyway (since saw some critical fixes come in for things like avoiding dropping messages under high load).
