### ISSUE TITLE
Getting a TypeError while running TestCase

### ISSUE THREAD

**Issue by cjds** [django/channels#583]
I'm trying to run the basic Test Case, but I'm running into this error. 

Version: 1.1.1
OS: Ubuntu 14.04

```
class ROSChannelTestCase(ChannelTestCase):
    """
    ROS Channel Test Case
    Test if we can do things
    """

    def test_ros_channel(self):
        # List the available networks which should be an array
        print Channel("ROSChannelLayer").send({"foo": "bar"})
        result =  self.get_next_message("result", require=True)
```

> 
> Traceback (most recent call last):
>   File "/home/cjds/development/robot_configuration_interface/robot_configuration_interface/tests/unit/test_channels.py", line 23, in test_ros_channel
>     result =  self.get_next_message("result", require=True)
>   File "/usr/local/lib/python2.7/dist-packages/channels/test/base.py", line 67, in get_next_message
>     recv_channel, content = channel_layers[alias].receive_many([channel])
>   File "/usr/local/lib/python2.7/dist-packages/asgiref/base_layer.py", line 43, in receive_many
>     return self.receive(channels, block)
>   File "/usr/local/lib/python2.7/dist-packages/asgiref/inmemory.py", line 59, in receive
>     assert all(self.valid_channel_name(channel) for channel in channels), "One or more channel names invalid"
>   File "/usr/local/lib/python2.7/dist-packages/asgiref/inmemory.py", line 59, in <genexpr>
>     assert all(self.valid_channel_name(channel) for channel in channels), "One or more channel names invalid"
>   File "/usr/local/lib/python2.7/dist-packages/asgiref/base_layer.py", line 108, in valid_channel_name
>     raise TypeError("Channel name must be a valid unicode string containing only alphanumerics, hyphens, or periods.")
> TypeError: Channel name must be a valid unicode string containing only alphanumerics, hyphens, or periods.
>

**Comment by jeremytiki** [comment]
@cjds This error is due to Python 2.7 having strings as a 'str' (<type: 'str'>) instead of 'unicode' (<type: 'unicode'>) type which is tested against. The last line of your error says this explicitly:

> TypeError: Channel name must be a valid unicode string containing only alphanumerics, hyphens, or periods. 

Luckily there are multiple ways to fix this in the mean time:

`name = u'ROSChannelLayer'`
`name = unicode('ROSChannelLayer ')`

@andrewgodwin Should I change [asgiref.base_layer.BaseChannelLayer.match_type_and_length](https://github.com/django/asgiref/blob/master/asgiref/base_layer.py#L96) to try and convert 'str' types to unicode? Or do you have a better idea for how to solve this.

**Comment by andrewgodwin** [comment]
Nope, this is deliberately very strict. You can only pass in unicode. I recommend anyone writing in Python 2 does `from __future__ import unicode_literals`.

**Comment by cjds** [comment]
Thanks for that. My mistake. :-) But, it would be really useful if this was included in the testing Consumers docs. https://channels.readthedocs.io/en/stable/testing.html#channeltestcase
