### ISSUE TITLE
use of the CSRF cookie for authentification

### ISSUE THREAD

**Issue by SRPlatin** [django/channels#585]
Otherwise an user is already logged in, in all new connections even from other sites witch makes it attacking quiet easy.

**Comment by andrewgodwin** [comment]
The designed mechanism for WebSockets to check origins is the `Origin` header that's passed to you during the connection phase; in Channels that's something you can check in a `websocket.connect` handler and accept/deny based on origin there.

I'll leave this open as something to potentially implement in future though as it would probably be easier for those with dynamic domains or similar.

**Comment by SRLut3t1um** [comment]
Maybe it would help if channels checks by default if the origin is in the setting.allowHosts list. This would help to have better security by default or am I missing something?

**Comment by andrewgodwin** [comment]
That would probably be a sensible default behaviour, yes.
