### ISSUE TITLE
Base `Worker` class. 

### ISSUE THREAD

**Issue by SergeyKubrak** [django/channels#592]
Hey Andrew, we had discussing on django con, about channels and services. 
The topic of discussion was how to use django-channels as thing to communicate between services. Basically we can use any ASGI-compliant channel layer, as `asgi_redis`, but we need worker to do all the processing. 
So it would be great to have worker separately, out of django-channels, in this case you can run service communication even without installing django.

**Comment by andrewgodwin** [comment]
Hi Sergey - I actually made this yesterday after our discussion over at https://github.com/django/asgiref/issues/17 - sorry if I wasn't clear that I would do it! Thanks for remembering :)
