### ISSUE TITLE
Route with get parameters doesn't match

### ISSUE THREAD

**Issue by gyermolenko** [django/channels#602]
I try to match `route("websocket.connect", ws_connect, path=r'^/path/$')`
and it doesn't match urls like  '/path/?aaa=bbb'

For comparison, Django's URLconf 

> does not include GET or POST parameters, or the domain name

Aldo I couldn't find details about capturing get parameters in routing [documentation](http://channels.readthedocs.io/en/stable/routing.html) so I could have done something wrong.

Could anybody please explain it to me?

ps Don't know if it is relevant:
I found the issue while trying to test consumer, so path was provided like so
`client.send_and_consume('websocket.connect', {'value': 'my_value'}, path=url)`

**Comment by andrewgodwin** [comment]
This is just the side-effect of what you are getting in #601, not a bug in itself.
