### ISSUE TITLE
Document [in]compatibility between versions of channels, daphne, asgi backends, etc

### ISSUE THREAD

**Issue by dougkeen** [django/channels#605]
A (real world) scenario for context:
We run separate clusters of interface servers and workers. We recently pushed an update to the worker cluster upgrading asgi_redis from 1.0.0 -> 1.3.0, while the interface cluster was still running asgi_redis 1.0.0 (and daphne 1.0.3). Because of the new process-local response channel stuff in 1.3.0, we got into a situation where responses from the workers were ignored after the deployment.

You can replicate this by running daphne 1.1.0 with asgi_redis 1.1.0, then run a worker with asgi_redis 1.2.0. You'll find the site is unresponsive.

It would be nice if there was somewhere in the documentation to surface these kinds of incompatibilities between sub-components, or at least note

**Comment by proofit404** [comment]
Each channels related project have its own change log. New style process local channels were implemented at ASGI layer without changes to the channels package itself.

But I agree that this change logs are far from complete upgrade guide.

**Comment by dougkeen** [comment]
Does that imply that ASGI itself needs better versioning, with compatibility reported within each channels projects' docs?

**Comment by proofit404** [comment]
Of course it does. But it also requires way more effort from Andrew. Spec changes really infrequently relatively to `channels` package itself.

Also it's better not to run old Daphne version together with new channels. At least look at minimum required version from `setup.py`

**Comment by dougkeen** [comment]
For sure, that all makes sense. Maybe at a minimum a warning about mismatching interface and worker lib versions can be dropped in the "Deploying new versions of code" section of the channels docs? Perhaps somewhere in this bit:

> There’s no need to restart the WSGI or WebSocket interface servers unless you’ve upgraded the interface server itself or changed the CHANNEL_LAYER setting; none of your code is used by them, and all middleware and code that can customize requests is run on the consumers.

I think there's value even if it's a temporary warning until the ASGI spec gets fully shaken out. It's a little scary when a minor version upgrade can take down your site 😛

**Comment by proofit404** [comment]
Hopefully it can take down only your staging environment.

**Comment by dougkeen** [comment]
Haha... touché

**Comment by andrewgodwin** [comment]
The very newest version of the `channels` package actually introduces a version check for packages like this, but yes, that's not going to work across a cluster. I do note it down in the changelog when it happens, but that requires that you read the changelog, of course.

I need to get a better page up that covers channels as a project anyway, rather than just the Django interface package, and this would be something that fits well in there.

**Comment by dougkeen** [comment]
Right on. Let me know if there's anything I can do to help when that time comes.

**Comment by proofit404** [comment]
#591 is definitely a blocker for channels project page.

**Comment by andrewgodwin** [comment]
Now all the packages are tightly coupled into the same process, the Python dependency system solves this for us pretty much, and the incompatibilities that do exist (1 vs. 2) have whole doc pages on them.
