### ISSUE TITLE
consumer_finished.send(sender=None) in test case raise error

### ISSUE THREAD

**Issue by Akay7** [django/channels#607]
- OpenSUSE Leap 42.2
  python 3.4 
-   Django==1.11
    channels==1.1.3
    daphne==1.2.0
    Twisted==17.1.0

- I'm write Data Binding to Django models according to documentation http://channels.readthedocs.io/en/stable/binding.html. And then write unit test according http://channels.readthedocs.io/en/stable/testing.html#test-data-binding-with-httpclient. I'm call command `python manage.py test`

  - I'm expected all work well and UnitTest will finished correctly
  - I'm get error. Here is traceback 
    > Traceback (most recent call last):
  File "todo_item/tests.py", line 16, in test_creating_new_todo_items_send_notification
    consumer_finished.send(sender=None)
  File "site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "site-packages/channels/message.py", line 94, in send_and_flush
    delattr(self.threadlocal, "messages")
AttributeError: messages
- But if I delete line `consumer_finished.send(sender=None)` test finished correctly, why necessary that line? And if it is really necessary, why it raise error?

**Comment by Krukov** [comment]
You don't need to call `consumer_finished`. https://github.com/django/channels/pull/610
