### ISSUE TITLE
Trouble with sessions

### ISSUE THREAD

**Issue by adambyer** [django/channels#617]
Sessions do not seem to be working for me. I'm using the channel_session_user_from_http decorator on a function targeted by a websocket.connect route. In that function I set a session variable using message.channel_session, but on subsequent calls to the same route the session variable doesn't exist. I've also noticed that the message.reply_channel value changes on each call so I must be missing something.

Thanks.

- Adam

macOS 10.12.4
Chrome 57.0.2987.133
channels==1.1.3
daphne==1.2.0
Django==1.11
Twisted==17.1.0
redis==2.10.5
 
Running w/ runserver

**Comment by proofit404** [comment]
Can you provide source code for your consumers? What is the expected behavior? What you actually got?

**Comment by adambyer** [comment]
I've actually narrowed it down to simply this...

```
@channel_session_user_from_http
def tournament_view(message):

    print(message.reply_channel)

    if not message.channel_session.get('test'):
        print('*** test session var not set')

    message.channel_session['test'] = 'test'

    message.reply_channel.send({'accept': True})
```

That prints...

daphne.response.OlmrmAEuTl!DffJnOeeur
*** test session var not set

daphne.response.OlmrmAEuTl!nnqmyAAzPZ
*** test session var not set

So the session variable is not available on the 2nd call and the reply_channel is different.

Thanks.

**Comment by proofit404** [comment]
Can you provide routing and client code?

**Comment by adambyer** [comment]
routing.py

```
from channels.routing import route
from .consumers import tournament_list, tournament_join, tournament_view, tournament_message, tournament_disconnect


channel_routing = [
    route("websocket.connect", tournament_list, path=r'^/tournament/list/$'),
    route("websocket.connect", tournament_join, path=r'^/tournament/(?P<hsh>[a-zA-Z0-9]+)/join/$'),
    route("websocket.connect", tournament_view, path=r'^/tournament/(?P<hsh>[a-zA-Z0-9]+)/view/$'),
    route("websocket.disconnect", tournament_disconnect),
    route("websocket.receive", tournament_message),
]
```

javascript:

```function connect_to_tournament_view_socket(hash) {
    var socket = new WebSocket('ws://' + window.location.host + '/tournament/' + hash + '/view/');
    socket.onmessage = function (e) {
        console.log('tournament view socket onmessage');
    }
    socket.onopen = function () {
        console.log('tournament socket onopen');
    }
    socket.onclose = function () {
        console.log('tournament socket onclose');
    }
}
```

**Comment by proofit404** [comment]
So, everything is working as it should be. Let me explain what's going on:
- you set your consumer to be called on websocket connect
- this event can happens once for each connection
- reply channel correspond to concret client connection

Actually you need to create channel session in the tournament view and use it in the tournament message.

**Comment by adambyer** [comment]
Thanks for the quick responses, but I'm not quite understanding. Could you provide a sample?

**Comment by proofit404** [comment]
Try to check test session key in the `tournament_message` message. For this you should call send method on websocket object in your browser.

**Comment by adambyer** [comment]
I think I've tried that. Is this what you mean...

javascript:

```
var socket = new WebSocket('ws://' + window.location.host + '/tournament/' + hash + '/view/');
    socket.onmessage = function (e) {
        console.log('tournament view socket onmessage');
    }
    socket.onopen = function () {
        console.log('tournament socket onopen');
        socket.send('testing');
    }
    socket.onclose = function () {
        console.log('tournament socket onclose');
    }
```

routing
```
from channels.routing import route
from .consumers import tournament_list, tournament_join, tournament_view, tournament_message, tournament_disconnect


channel_routing = [
    route("websocket.receive", tournament_message, path=r'^/tournament/(?P<hsh>[a-zA-Z0-9]+)/view/$'),
    route("websocket.connect", tournament_list, path=r'^/tournament/list/$'),
    # route("websocket.connect", tournament_join, path=r'^/tournament/(?P<hsh>[a-zA-Z0-9]+)/join/$'),
    route("websocket.connect", tournament_view, path=r'^/tournament/(?P<hsh>[a-zA-Z0-9]+)/view/$'),
    # route("websocket.disconnect", tournament_disconnect),
]
```

consumers
```
@channel_session_user_from_http
def tournament_message(message, hsh):
    print(message.reply_channel)

    if not message.channel_session.get('test'):
        print('*** test session var not set')

    message.channel_session['test'] = 'test'
```

Still getting the same result, but not sure if that's what you suggested.

**Comment by proofit404** [comment]
Try to decorate `receive` consumer with `@channel_session` and `connect` consumer with `@channel_session_user_from_http`.

**Comment by adambyer** [comment]
Still getting the same result.

**Comment by adambyer** [comment]
The key was creating just one connection and using that for all related messages. Thanks for pointing that out.
