### ISSUE TITLE
Handshake fails with status 200

### ISSUE THREAD

**Issue by olegro** [django/channels#620]
Hi.
I'm trying to implement a simple chat example using channels following this guide: https://gearheart.io/blog/creating-a-chat-with-django-channels/

However, trying to test even a simple message passing by using Django shell:

>>> import websocket
>>> ws = websocket.WebSocket()
>>> ws.connect("ws://localhost:8000")

I'm getting:

>>> ws.connect("ws://localhost:8000")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/gilshu/Envs/multichat/lib/python3.6/site-packages/websocket/_core.py", line 214, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/Users/gilshu/Envs/multichat/lib/python3.6/site-packages/websocket/_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Users/gilshu/Envs/multichat/lib/python3.6/site-packages/websocket/_handshake.py", line 122, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 200
 

I saw that there might be an issue with the current channels version that prevens accepting the connection. How can I fix this?

Thanks in advance!

**Comment by andrewgodwin** [comment]
Getting a status 200 means you're not talking to a WebSocket capable server, you're talking to a normal HTTP server. Have you put channels into `INSTALLED_APPS`, and do you have any other installed apps that might override `runserver`?

**Comment by olegro** [comment]
Thanks for the quick response!
I updated the INSTALLED_APPS and now the error looks different:

>>> ws.connect("ws://localhost:8000")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/websocket/_core.py", line 214, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/websocket/_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/websocket/_handshake.py", line 120, in _get_resp_headers
    status, resp_headers = read_headers(sock)
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/websocket/_http.py", line 223, in read_headers
    line = recv_line(sock)
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/websocket/_socket.py", line 101, in recv_line
    c = recv(sock, 1)
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/websocket/_socket.py", line 80, in recv
    bytes_ = sock.recv(bufsize)
ConnectionResetError: [Errno 54] Connection reset by peer




My routing.py is like this:

from channels import route

# This function will display all messages received in the console
def message_handler(message):
    print(message['text'])


channel_routing = [
    route("websocket.receive", message_handler)  # we register our message handler
]

**Comment by andrewgodwin** [comment]
Hm, your websocket is apparently not handshaking fully - the traceback you posted looks like you're trying to connect from a Python client? Have you tried a browser to see if that works?

**Comment by olegro** [comment]
Yes, I'm trying it from the browser. Apparently a workaround from some other thread helped me to solves this by adding:

@channel_session_user_from_http
def ws_connect(message):
    **message.reply_channel.send({'accept': True})**
    # Initialise their session
    message.channel_session['rooms'] = []

Now, I have another (more advanced) issue when sending a message in JSON format. This is the exception that I get on the server side:

2017-04-26 21:41:51,411 - ERROR - worker - Error processing message with consumer chat.consumers.chat_join:
Traceback (most recent call last):
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/channels/worker.py", line 120, in run
    consumer(message, **kwargs)
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/channels/sessions.py", line 64, in inner
    return func(message, *args, **kwargs)
  File "/Users/olegro/Envs/multichat/lib/python3.5/site-packages/channels/auth.py", line 42, in inner
    return func(message, *args, **kwargs)
TypeError: inner() missing 1 required positional argument: 'args'

**And the client side JS that generates the message looks like this:**

console.log("Trying to join room (still in main JS)")
            // Join room
            $(this).addClass("joined");
            socket.send(JSON.stringify({
                "command": "join",
                "room": roomId
            }));


Any ideas?

Thanks in advance!

**Comment by andrewgodwin** [comment]
Oh, you didn't have a `ws_connect` function in your previous code so I didn't suggest that, but yes, if you override it you must accept the connection.

The error you have is not related to the javascript, it's probably that you haven't set up the consumer properly (maybe it's not been instantiated right). Could you paste your routing and the consumer code?

**Comment by olegro** [comment]
I'm trying to follow this guide: https://gearheart.io/blog/creating-a-chat-with-django-channels/ 
And apparently it didn't have ws_connect. Anyways, here are my routing and consumer:

Main routing.py:

`from channels import include


# The channel routing defines what channels get handled by what consumers,
# including optional matching on message attributes. In this example, we match
# on a path prefix, and then include routing from the chat module.
channel_routing = [
    # Include sub-routing from an app.
    include("chat.routing.websocket_routing", path=r"^/chat/stream"),

    # Custom handler for message sending (see Room.send_message).
    # Can't go in the include above as it's not got a 'path' attribute to match on.
    include("chat.routing.custom_routing"),

    # A default "http.request" route is always inserted by Django at the end of the routing list
    # that routes all unmatched HTTP requests to the Django view system. If you want lower-level
    # HTTP handling - e.g. long-polling - you can do it here and route by path, and let the rest
    # fall through to normal views.
]`

App routing.py:

`from channels import route
from .consumers import ws_connect, ws_receive, ws_disconnect, chat_join, chat_leave, chat_send


# There's no path matching on these routes; we just rely on the matching
# from the top-level routing. We could path match here if we wanted.
websocket_routing = [
    # Called when WebSockets connect
    route("websocket.connect", ws_connect),

    # Called when WebSockets get sent a data frame
    route("websocket.receive", ws_receive),

    # Called when WebSockets disconnect
    route("websocket.disconnect", ws_disconnect),
]

# You can have as many lists here as you like, and choose any name.
# Just refer to the individual names in the include() function.
custom_routing = [
    # Handling different chat commands (websocket.receive is decoded and put
    # onto this channel) - routed on the "command" attribute of the decoded
    # message.
    route("chat.receive", chat_join, command="^join$"),
    route("chat.receive", chat_leave, command="^leave$"),
    route("chat.receive", chat_send, command="^send$"),
]`

consumers.py

`import json
from channels import Channel
from channels.auth import channel_session_user_from_http, channel_session_user

from .settings import MSG_TYPE_LEAVE, MSG_TYPE_ENTER, NOTIFY_USERS_ON_ENTER_OR_LEAVE_ROOMS
from .models import Room
from .utils import get_room_or_error, catch_client_error
from .exceptions import ClientError


### WebSocket handling ###


# This decorator copies the user from the HTTP session (only available in
# websocket.connect or http.request messages) to the channel session (available
# in all consumers with the same reply_channel, so all three here)
@channel_session_user_from_http
def ws_connect(message):
    message.reply_channel.send({'accept': True})
    # Initialise their session
    message.channel_session['rooms'] = []


# Unpacks the JSON in the received WebSocket frame and puts it onto a channel
# of its own with a few attributes extra so we can route it
# This doesn't need @channel_session_user as the next consumer will have that,
# and we preserve message.reply_channel (which that's based on)
def ws_receive(message):
    # All WebSocket frames have either a text or binary payload; we decode the
    # text part here assuming it's JSON.
    # You could easily build up a basic framework that did this encoding/decoding
    # for you as well as handling common errors.
    payload = json.loads(message['text'])
    payload['reply_channel'] = message.content['reply_channel']
    Channel("chat.receive").send(payload)


@channel_session_user
def ws_disconnect(message):
    # Unsubscribe from any connected rooms
    for room_id in message.channel_session.get("rooms", set()):
        try:
            room = Room.objects.get(pk=room_id)
            # Removes us from the room's send group. If this doesn't get run,
            # we'll get removed once our first reply message expires.
            room.websocket_group.discard(message.reply_channel)
        except Room.DoesNotExist:
            pass


### Chat channel handling ###


# Channel_session_user loads the user out from the channel session and presents
# it as message.user. There's also a http_session_user if you want to do this on
# a low-level HTTP handler, or just channel_session if all you want is the
# message.channel_session object without the auth fetching overhead.
@channel_session_user
@catch_client_error
def chat_join(message):
    print("Inside consumers:chat_join ")
    print(message.content)
    # Find the room they requested (by ID) and add ourselves to the send group
    # Note that, because of channel_session_user, we have a message.user
    # object that works just like request.user would. Security!
    room = get_room_or_error(message["room"], message.user)

    # Send a "enter message" to the room if available
    if NOTIFY_USERS_ON_ENTER_OR_LEAVE_ROOMS:
        room.send_message(None, message.user, MSG_TYPE_ENTER)

    # OK, add them in. The websocket_group is what we'll send messages
    # to so that everyone in the chat room gets them.
    room.websocket_group.add(message.reply_channel)
    message.channel_session['rooms'] = list(set(message.channel_session['rooms']).union([room.id]))
    # Send a message back that will prompt them to open the room
    # Done server-side so that we could, for example, make people
    # join rooms automatically.
    message.reply_channel.send({
        "text": json.dumps({
            "join": str(room.id),
            "title": room.title,
        }),
    })


@channel_session_user
@catch_client_error
def chat_leave(message):
    # Reverse of join - remove them from everything.
    room = get_room_or_error(message["room"], message.user)

    # Send a "leave message" to the room if available
    if NOTIFY_USERS_ON_ENTER_OR_LEAVE_ROOMS:
        room.send_message(None, message.user, MSG_TYPE_LEAVE)

    room.websocket_group.discard(message.reply_channel)
    message.channel_session['rooms'] = list(set(message.channel_session['rooms']).difference([room.id]))
    # Send a message back that will prompt them to close the room
    message.reply_channel.send({
        "text": json.dumps({
            "leave": str(room.id),
        }),
    })


@channel_session_user
@catch_client_error
def chat_send(message):
    # Check that the user in the room
    if int(message['room']) not in message.channel_session['rooms']:
        raise ClientError("ROOM_ACCESS_DENIED")
    # Find the room they're sending to, check perms
    room = get_room_or_error(message["room"], message.user)
    # Send the message along
    room.send_message(message["message"], message.user)`

**Comment by olegro** [comment]
A quick update: I had some progress on this issue. Apparently, the line that was causing the problem was:

`@catch_client_error`

After commenting it out, the join_chat function started working as expected. Any idea why it's happening?

**Comment by Mikebarson** [comment]
Hi! @olegro I'm also following the gearheart article. I was able to resolve the HandShakeError 200 by adding the channels to installed apps. But I'm getting this error 

"Error 61 connecting to localhost:6379. Connection refused."

**Comment by olegro** [comment]
I think it might be related to redis configuration, but I'm not really sure
