### ISSUE TITLE
Test mail outbox does not work with ChannelLiveServerTestCase

### ISSUE THREAD

**Issue by jricardo27** [django/channels#621]
Hi,
Per Django documentation, the mail outbox is accessible in `django.core.mail.outbox` https://docs.djangoproject.com/en/1.11/topics/testing/tools/#email-services

The problem is that it is just a global list of emails and the problem is that `ChannelLiveServerTestCase` spawns multiprocesses making that global data inaccessible.

I tried to give it a try to `multiprocessing.manager` or similar approaches but I'm clueless where to plug it in.

I wrote a custom Email Backend that writes the list to a file and retrieves it when necessary. It's ugly but it shows that that is the problem.

Can you provide a better way to achieve it ?

My ugly code:
https://github.com/jricardo27/channels_example/pull/6/commits/637b689870c2f879286f30eeb0c3e1d65283d557

**Comment by andrewgodwin** [comment]
I'm afraid that given the way we need to run the live test case, there's no way around this. If you want to use the live test case, you won't be able to test emails - I'd suggest doing your email tests using the standard test client, if possible.

If you have a way around it, that's great, and I'd encourage you to publish it for others to use, but solving this is not something Channels can do right now given the limited resources we have. Sorry!

**Comment by johanneswilm** [comment]
This is a big problem. Running into this in 2024. It worked great when using tornado for websockets. I am starting to wonder whether it would be best to just stick with tornado instead of channels if this cannot be done. :(
