### ISSUE TITLE
request.META['QUERY_STRING'] returns utf-8 encoded bytes instead of string for non-ws connections

### ISSUE THREAD

**Issue by tykling** [django/channels#622]
Running under daphne with runworker request.META['QUERY_STRING'] is utf8 encoded bytes rather than a string like it usually is, but only for regular non-WS connections. 

django 1.10.5
channels 1.1.5

**Comment by tykling** [comment]
this appears to fix it for me: https://github.com/tykling/channels/commit/7a4e667b6eada7d0fafa3fb99c744cc43b11f5e5

**Comment by andrewgodwin** [comment]
Query string is specified to be a bytestring in the spec: http://channels.readthedocs.io/en/latest/asgi/www.html#request

The bug here is that WebSocket connections return unicode strings, which is probably related to #108.

**Comment by andrewgodwin** [comment]
Oh, wait, you're talking about `request.META`. My bad!

**Comment by andrewgodwin** [comment]
Can you open a pull request with your fix?

**Comment by tykling** [comment]
I would have, but I couldn't get the tox stuff running. Do you still want the pull request?

**Comment by andrewgodwin** [comment]
Yup, just open it and Travis will run the tests on the PR for you.

**Comment by tykling** [comment]
done :)
