### ISSUE TITLE
Django channels would not start redis server using CHANNEL_LAYERS

### ISSUE THREAD

**Issue by shulmag** [django/channels#624]
I am trying to replicate chat with Django channels posted here: [https://gearheart.io/blog/creating-a-chat-with-django-channels/](https://gearheart.io/blog/creating-a-chat-with-django-channels/)

and when I run the server: `$ python3 ./manage.py runserver` the redis server does not start. Here is the full message:

> Performing system checks...
> 
> System check identified no issues (0 silenced). April 27, 2017 - 20:59:01 Django version 1.10.3, using settings 'multichat.settings' Starting Channels development server at http://127.0.0.1:8000/ Channel layer default (asgi_redis.core.RedisChannelLayer) Quit the server with CONTROL-C. 2017-04-27 20:59:01,278 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive 2017-04-27 20:59:01,279 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive 2017-04-27 20:59:01,282 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive 2017-04-27 20:59:01,282 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive 2017-04-27 20:59:01,283 - INFO - server - HTTP/2 support not enabled (install the http2 and tls Twisted extras) 2017-04-27 20:59:01,283 - INFO - server - Using busy-loop synchronous mode on channel layer 2017-04-27 20:59:01,284 - INFO - server - Listening on endpoint tcp:port=8000:interface=127.0.0.1 2017-04-27 20:59:01,294 - ERROR - server - Error trying to receive messages: Error 61 connecting to localhost:6379. Connection refused. Exception in thread Thread-1: Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 439, in connect sock = self._connect() File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 494, in _connect raise err File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 482, in _connect sock.connect(socket_address) ConnectionRefusedError: [Errno 61] Connection refused

I can solve it by running redis server from a different terminal, however that is what Django Channels supposed to do in the settings:
```

redis_host = os.environ.get('REDIS_HOST', 'localhost')
# Channel layer definitions
# http://channels.readthedocs.org/en/latest/deploying.html#setting-up-
a-channel-backend
CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation asgi_redis
    "BACKEND": "asgi_redis.RedisChannelLayer",
    "CONFIG": {
        "hosts": [(redis_host, 6379)],
    },
   "ROUTING": "multichat.routing.channel_routing", # We will create it in a moment
    },
}
```
Appreciate any help and advice.

Many thanks!

**Comment by andrewgodwin** [comment]
This means that Redis is not running on the host and port you told Channels it was running on - you need to make sure it is running, and that it is accepting connections (for example, it might be on a VM and only accepting connections from localhost, which would fail).

We can't help with individual redis setups, unfortunately. You can test redis connection using the `redis-cli` command line client.

**Comment by rahul6612** [comment]
to start the Redis Server
1. install redis  from here https://github.com/rgl/redis/downloads
2. open task manager and go to services
3. in services find redis
4. right click on redis  and choose open services
5. a window will pop and you will see the Services(local) find there Redis Server
6. now click on start

**Comment by ratfink88** [comment]
rahul6612 is correct. many thanks

**Comment by NightHawk451** [comment]
I followed rahul6612 steps for starting the redis server and it works. The thing that confuses me is why the link takes you to Redis download that is 7 years old. There are newer versions of redis out there.

**Comment by ashok163** [comment]
I forgot to install redis server so followed steps from abhannan on mac and it works. Thanks.

**Comment by drivelous** [comment]
I started the Django Channels tutorial with my own custom docker-compose file with separate services. An issue I had was that I was trying to set `CHANNEL_LAYERS` hosts to `localhost` but I needed to set it as `redis`

```
# settings.py
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('redis', 6379)],
        },
    },
}
```

```
# docker-compose.yml
services:
  web:
    build: .
    command: python3.8 manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
  redis:
    image: redis:6.0-rc3-buster
    ports:
    - "6379:6379"
```

Further explanation from: https://stackoverflow.com/a/41303131/1746422

**Comment by drichardcarl** [comment]
> I started the Django Channels tutorial with my own custom docker-compose file with separate services. An issue I had was that I was trying to set `CHANNEL_LAYERS` hosts to `localhost` but I needed to set it as `redis`
> 
> ```
> # settings.py
> CHANNEL_LAYERS = {
>     'default': {
>         'BACKEND': 'channels_redis.core.RedisChannelLayer',
>         'CONFIG': {
>             "hosts": [('redis', 6379)],
>         },
>     },
> }
> ```
> 
> ```
> # docker-compose.yml
> services:
>   web:
>     build: .
>     command: python3.8 manage.py runserver 0.0.0.0:8000
>     depends_on:
>       - redis
>   redis:
>     image: redis:6.0-rc3-buster
>     ports:
>     - "6379:6379"
> ```
> 
> Further explanation from: https://stackoverflow.com/a/41303131/1746422

Thank you! This solved my problem :smile:

**Comment by omrastogi** [comment]
> 
> 
> to start the Redis Server
> 
>     1. install redis  from here https://github.com/rgl/redis/downloads
> 
>     2. open task manager and go to services
> 
>     3. in services find redis
> 
>     4. right click on redis  and choose open services
> 
>     5. a window will pop and you will see the Services(local) find there Redis Server
> 
>     6. now click on start

Thanks Rahul, it works

**Comment by tiwari1302** [comment]
> > to start the Redis Server
> > ```
> > 1. install redis  from here https://github.com/rgl/redis/downloads
> > 
> > 2. open task manager and go to services
> > 
> > 3. in services find redis
> > 
> > 4. right click on redis  and choose open services
> > 
> > 5. a window will pop and you will see the Services(local) find there Redis Server
> > 
> > 6. now click on start
> > ```
> 
> Thanks Rahul, it works

It is still not working  for me.. can you please help?
