### ISSUE TITLE
Group name must be 7-bit ASCII alphanumeric; misleading error message

### ISSUE THREAD

**Issue by rwillmer** [django/channels#626]
channels==1.0.3

I'm creating a group with a French alphabetic character "integrals".

It fails with this error "TypeError: Group name must be a valid unicode string containing only alphanumerics, hyphens, or periods."

I think that's misleading; this is a valid unicode string containing only alphanumerics, hyphens, or periods. It just happens to be a French alphanumeric.

Is it intended to constrain group names to US-ASCII? If so, we should change this message to say so.

Or is this a bug?

**Comment by andrewgodwin** [comment]
Yes, it is meant to constrain to US-ASCII by meaning "alphanumerics". I'll update the spec and error message to be clearer. To be precise, you're only allowed:

`a-z` `A-Z` `0-9` `-` `.`

**Comment by andrewgodwin** [comment]
Clarified in https://github.com/django/asgiref/commit/b741685af1e63f16b52040cd0b3fc790d44a1512
