### ISSUE TITLE
error handling on websocket connect

### ISSUE THREAD

**Issue by bastianh** [django/channels#63]
I'm currently a bit unhappy with the error handling in the messages.

The websocket connect message for example... any error or exception happening in there will keep the connection open and the client will be able to continue sending messages.

It should be possible to drop the connection attempt by raising permission denied for example or it should fail with a error 500 on other exceptions.

Bastian

**Comment by andrewgodwin** [comment]
Yes, that's a good point - a decorator would do the job, if you think that would work? Something like:

    @websocket.close_on_error
    def connect(message):
        raise ValueError()

I don't want to make the actual function itself special in any way. There's also the potential for something like a class-based-view approach.

**Comment by bastianh** [comment]
I guess that would be a solution that would not require any changes.

I would prefer a solution that would directly work in the request where the websocket ist created (to fail that with forbidden for example) but I guess thats not easy to do.

**Comment by andrewgodwin** [comment]
New ASGI stuff has fixed this, if the connect handler fails the websocket handshake is not even finished.
