### ISSUE TITLE
documentation improvement

### ISSUE THREAD

**Issue by sebhaase** [django/channels#631]
Please let me know if I'm missing something.
If I google "django channels group send" my best result seems to point to
http://channels.readthedocs.io/en/stable/reference.html
So I'm searching and finding  
http://channels.readthedocs.io/en/stable/reference.html#group 

However there is no clear separation after `They have the following attributes:`
where it immediately continues after `name` and `channnel_layer`  (the attributes) with `send`, `add` etc.  -  which are methods !!
Further `send(content)`  is not complete,   as would be expected from a page called "reference".
Looking at the source code I downloaded from git and doing a grep I finally find the `immediately` argument I was looking for:
```
def send(self, content, immediately=False):
        """
        Send a message to all channels in the group.

        Sends are delayed until consumer completion. To override this, you
        may pass immediately=True.
        """
```
Hope this helps to "inspire improvement I'm to lazy to provide myself" :-)

**Comment by andrewgodwin** [comment]
The `immediately` argument is deliberately not documented in the main docs right now as it's quite dangerous and you only need it in certain very complex situations (such as our own unit tests). If you are using `immediately` in a normal websocket handler, you likely have a long-running handler which is bad and will bring your system to deadlock if you deploy to production.
