### ISSUE TITLE
Send message to a client withoud receiving a client request

### ISSUE THREAD

**Issue by frankl1** [django/channels#632]
Hello,

The tutorial show how to manage websocket, that pretty good. But what I really want now is to send message to client without receiving any request when the websocket connection have been established.
Suppose I want to notify a specific user about an event, How can I achieve that ?

Thanks !

**Comment by jeremytiki** [comment]
@frankl1 The Channels Examples project provides a great example of how to do this: https://github.com/andrewgodwin/channels-examples/tree/master/liveblog 

Specifically for this example, a blog is created, and the [save method](https://github.com/andrewgodwin/channels-examples/blob/master/liveblog/posts/models.py#L94) is modified to add a [new call to the method send_notification](https://github.com/andrewgodwin/channels-examples/blob/master/liveblog/posts/models.py#L74) that sends out a channel or group reply.
Additionally you could also accomplish the same thing with [Django's signals framework](https://docs.djangoproject.com/en/1.11/topics/signals/)

**Comment by frankl1** [comment]
Thank's, clear and simple. 
It worked perfectly.
