### ISSUE TITLE
[FR] Bindings - Allow to limit the scope of receivers

### ISSUE THREAD

**Issue by ZuSe** [django/channels#634]
Hi folks,

as you know data bindings allows you to restrict execution unsafe methods on a model by implementing your custom code in the has_permission method.

I am seeking for a way to do it the other way round. I got view permissions on objects in my project that only allow specific users or groups to access object instances (using django guardian).
Unfortunately there seems to be no way to limit the scope of receivers in bindings by using a predefined or own Permission Class which makes all subscribers receive newly or updated created objects.

Is there any chance to get such a system working with bindings?

Best,
Patrick

**Comment by AlexejStukov** [comment]
My solution for a similar problem was using one group per user. The bindings `group_names` method then sends updates only users with the right permission. I also keep track of connected users via django's cache.

**Comment by andrewgodwin** [comment]
Yes, one group per user or permission level and then implementing `group_names` is the correct approach.
