### ISSUE TITLE
why does it disconnect ?

### ISSUE THREAD

**Issue by Ya2s** [django/channels#637]
Hello,

I dont't understand why websocket disconnect alone...
I run with : 

- daphne -e ssl:<port of ssl app>:privateKey=<path to .key>:certKey=<path to .cer> <my app>.asgi:channel_layer -p <port of websocket app> -b 0.0.0.0  

- python3.5 manage.py runworker

I have this : 
127.0.0.1:50398 - - [22/May/2017:11:30:01] "WSCONNECTING /" - -
127.0.0.1:50398 - - [22/May/2017:11:30:01] "WSCONNECT /" - -
127.0.0.1:50398 - - [22/May/2017:11:30:51] "WSDISCONNECT /" - 

It disconnect approximately 30 seconds after connection.
I want the connection persists.

Thank you

**Comment by andrewgodwin** [comment]
Please ask for help on the django-users mailing list.
