### ISSUE TITLE
How route Websocket Demultiplexer class?

### ISSUE THREAD

**Issue by dpineiden** [django/channels#638]
Hello.

I've read the documentation, i have some Consumer Class written and i put that on a Demultiplexer.  I can't find how to put the demux on the routing routes. So i beg for help about this. And if you can put on the doucmentation a little help

Thanks!

**Comment by andrewgodwin** [comment]
You can see an example here: https://github.com/andrewgodwin/channels-examples/blob/master/databinding/databinding/routing.py#L9

In future, the django-users mailing list is the best place to ask for help.
