### ISSUE TITLE
Worker cannot be stopped from WorkerGroup

### ISSUE THREAD

**Issue by AlexejStukov** [django/channels#640]
The worker class needs a stop method that works even if it is stuck listening for new messages. 
At the moment the worker will wait for new messages even when `termed` is `True` because `RedisChannelLayer.receive` is called and blocks forever.  

See https://github.com/django/asgi_redis/issues/44

**Comment by AlexejStukov** [comment]
This is needed when you call `runworker` with more than one thread. If there are no messages in the channels the workers are listening to, the process cannot be stopped via `crtl+c`.

**Comment by andrewgodwin** [comment]
Sending an empty message won't work if there's more than one process listening on those channels - you might disrupt the other channel instead. That's the wrong approach.

I'm curious why `sys.exit()` isn't making the receive call stop immediately - it's worth investigating what's stopping that working instead I think. I don't want to have to resort to `os._exit()`, but there is potential to inject all sorts of exceptions into the stack frame from the signal handler.

**Comment by AlexejStukov** [comment]
`sys.exit()` is not called in `WorkerGroup.sigterm_handler`. Raising an exception would be ideal, but it must be raised from the main thread to the child threads. There is [thread2](http://tomerfiliba.com/recipes/Thread2/) but that will only work, if the thread hangs in python bytecode, not something different.

**Comment by AlexejStukov** [comment]
Calling `sys.exit()` in `WorkerGroup.sigterm_handler` is not enough.

**Comment by andrewgodwin** [comment]
Ah, right, the threading complicates things. I suspect if you set `daemon` to `True` on the worker threads it will exit correctly.

**Comment by AlexejStukov** [comment]
Setting daemon=True helped. I removed the `join`s and other things, that are kind of pointless now.

**Comment by andrewgodwin** [comment]
Yup, I think the daemon threads were the issue all along. Thanks!

**Comment by AlexejStukov** [comment]
I've just noticed that I accidently removed `self.termed = True` from the sigterm_handler. It works without it, should I add it back in?

**Comment by andrewgodwin** [comment]
It's not needed for the code snippet you have as there's no graceful exit capability in that section (and it wouldn't have worked before); I'll open a separate ticket to fix that.

**Comment by AlexejStukov** [comment]
Ok, thanks!
