### ISSUE TITLE
Should I do something to enable HTTP2 support?

### ISSUE THREAD

**Issue by camilonova** [django/channels#645]
I just installed this package `twisted[http2]` to remove the warning at the logs, but I'm not sure if I need to do something else to enable HTTP2 compatibility.

**Comment by andrewgodwin** [comment]
The Daphne Read readme (https://github.com/django/daphne/blob/master/README.rst) says all the steps you need to do to get it working. It's not required to turn it on, though; it's not warning you it's off, it's just letting you know.
