### ISSUE TITLE
Autoreload in runworker

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#647]
This would allow use of advanced Daphne options (#646) while still maintaining the clean separation and implementation of `runserver`. We'd want to make sure it was opt-in, though, as such a feature would be detrimental in production.

**Comment by lwm** [comment]
Oh, this would be cool. I might take a stab at that. 

So, we'd add a `--autoreload` flag and borrow what we need from [autoreload.py](https://github.com/django/django/blob/master/django/utils/autoreload.py)?

Has any work been done on this yet?

**Comment by c0yote** [comment]
Fair warning, I played with it a bit in May.  I don't remember exactly what happened, but I think the issue was signals couldn't reach the autoreload functionality because the workers are run inside threads.  I know that's vague, but I only played with it for a few hours.

**Comment by proofit404** [comment]
Did you try to reload code only in workers?

**Comment by Alexx-G** [comment]
Are there some changes related to this issue?
I need this feature for my current project, I'm going to implement it anyway if there's no patch. So, I can help with PR/snippet for this.

**Comment by lwm** [comment]
Work away with it. Don't think anyone got motivated to get back on this.

**Comment by proofit404** [comment]
Actually, I am. But to do this properly we need to rework a lot of internals of Channels. And this feature will come at the end of this TODO list. I'm starting to work on this huge refactoring, but I can't commit to any date.

If you're really interested in this feature, you can implement it yourself. I'll review your PR quickly. Also, I promise that if you implement this feature, I'll keep it compatible with any changes we're about to introduce.

**Comment by Alexx-G** [comment]
I haven't really studied channels internals, so it's quite possible that I'm missing something.
From my point of view it should be as simple as django's runserver autoreload.
The point is that autoreload isn't really used in production, often in production controlled restart is required. 

Are there some not obvious problems?

**Comment by proofit404** [comment]
Reload code within worker should be easy with inotify library. The main concern here is to keep Twisted event loop unaffected with this reload.

**Comment by gabrielfgularte** [comment]
@proofit404 Are you still on this development? Do you have any thoughts of when it will be released? No pressure, just to know if worth to keep looking for a workaround or just wait for this functionality.

Thanks!

**Comment by proofit404** [comment]
Hi @gabrielfgularte 
I'm not involved into channels development right now. Please try a suggested workaround.

**Comment by andrewgodwin** [comment]
@gabrielfgularte I am also not working on this right now as the `runworker` command will be becoming much less important in Channels 2 (because you will only need the main server process for most sites - workers will be an optional extra for custom channels).

**Comment by gabrielfgularte** [comment]
@andrewgodwin Alright! So, I'll wait for Channels 2! :)

**Comment by andrewgodwin** [comment]
Closing as channels 2 is basically ready to ship and there is indeed no more `runworker`.

**Comment by erm** [comment]
Since `runworker` still exists, has anyone taken a look into this with Channels 2?

**Comment by andrewgodwin** [comment]
Sorry, my closing message was wrong - what I meant was "`runworker` is no longer a core part of Channels infrastructure at all and is likely to not be used by many projects". I should honestly have renamed the command in 2 as it does something entirely different.

Anyway, I don't think the return on investment is there for having it in 2 now unless loads of people start using runworker in a big way.
