### ISSUE TITLE
Implement graceful exit in WorkerGroup

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#650]
It needs the ability to read the `in_job` status of all subthreads and set the `termed` flag so they all end up terminated or outside of a job before they quit. Follows on from #640.

**Comment by sourabhtk37** [comment]
Anyone one working on this? @andrewgodwin 
Could you guide me? I'm new to the project.

**Comment by andrewgodwin** [comment]
Nobody is working on this as far as I know - the way of implementing it is in the description I wrote (if you read through the worker code you'll see those variables in there, but you'll need to read though and understand it before fixing).

I wish I had time to help mentor you on this, but I'm really busy right now :(

**Comment by andrewgodwin** [comment]
WorkerGroup is gone, and we did this anyway, so closing!
