### ISSUE TITLE
HTTP Documentation is confusing on format of 'headers' in request.

### ISSUE THREAD

**Issue by tomchristie** [django/channels#655]
In the [HTTP message spec](https://channels.readthedocs.io/en/latest/asgi/www.html) there's a confusion section about the format of 'headers' in request messages...

> "For this reason, we can safely make the request headers a dict, but the response headers must be sent as a list of tuples, which matches WSGI."

However the spec then declares...

> **Request** ... headers: A list of [name, value] lists.

I'd assume that the later is the definitive version, which the source of daphne appears to confirm.
I guess some rephrasing on the former paragraph is required, unless I've completely misunderstood the intended meaning?

**Comment by andrewgodwin** [comment]
Yup, I flip-flopped on header formats during development and forgot to erase my tracks, it seems. I'll fix!

**Comment by andrewgodwin** [comment]
Fixed in cd34f65
