### ISSUE TITLE
How to check the working status of worker and server

### ISSUE THREAD

**Issue by belongwqz** [django/channels#660]
Maybe wo should have a group of api or other method to support checking the status of the workers and servers, so people can make a app just like the flower for celery.

Possible list of features：
1) Message queue status
2) Task detail info
3) Worker/server blance load status
4) A task real-time monitoring(include succeeded/failed/queued task statistics etc.)

the flower I said here -> https://github.com/mher/flower

**Comment by andrewgodwin** [comment]
Worker remote control is something I wish to leave to orchestration tools design for it (Kubernetes/Docker Swarm/Nomad etc.). Status/length/latency of channels is already covered by the statistics extension on ASGI (and implemented for redis) - ingesting those into sources like Graphite is not something I think belongs in Channels core itself, but in third party packages, so I'm going to close this.

**Comment by belongwqz** [comment]
You are right, but now it seems that there is no good solution for the channels, can give some guidance.

**Comment by andrewgodwin** [comment]
I can't give guidance beyond "write something yourself" - there is no good integrated solution right now, I agree, but the answer is not "try to get us to write one"; the Channels project only has so many people and resources, and I just can't commit to doing this as well.
