### ISSUE TITLE
Persisting Data In Documentation

### ISSUE THREAD

**Issue by dsanders11** [django/channels#662]
In the ['Persisting Data' section](https://github.com/django/channels/blob/master/docs/getting-started.rst#persisting-data) of the documentation under 'Getting Started' the example is a bit confusing.

The first paragraph states:

> Let’s consider a basic chat site where a user requests a chat room upon initial connection, as part of the query string (e.g. wss://host/websocket?room=abc).

But then right before the example in that section, it switches to:

> Let’s use it now to build a chat server that expects you to pass a chatroom name in the path of your WebSocket request

I was expecting the example to parse the room name from the query string since that was mentioned earlier, and the example URL is in that format. I thought it was a mistake until I re-read that little sentence above the example.

Since the later ['Routing' section](https://channels.readthedocs.io/en/stable/getting-started.html#routing) shows how to pull the room name out of the path directly in the routing, I'd suggest the documentation reword that first paragraph under 'Persisting Data' to not mention the query string as it's confusing.

**Comment by andrewgodwin** [comment]
Yes, you're right, it's a symptom of how it was written. I can't get to fixing this for a bit because of travel, though.

**Comment by ftxrc** [comment]
I'll pick this up once I arrive home. :)

**Comment by ftxrc** [comment]
@dsanders11 I'm unsure if this is what you meant, but go ahead: #681 
Please evaluate this as thoroughly as possible; I think this is what you meant.

**Comment by andrewgodwin** [comment]
The inconsistency is fixed in https://github.com/django/channels/pull/681.

**Comment by ftxrc** [comment]
Taking @dsanders11's suggestions, I improved the example code in general to use sessions and the query string more appropriately.
#683
