### ISSUE TITLE
Custom channel layer not being added during a test

### ISSUE THREAD

**Issue by cjds** [django/channels#664]
I'm making a test for a consumer that uses a custom Channel layer, but the test is using a generic Channel layer instead.

- OS: Linux (Ubuntu 14.04) Python 2.7.3
- Channels 1.1.3, daphne (1.2.0), asgi-redis (1.3.0)asgiref (1.1.1)
- I expected to use the channel layer specified in settings.py (it uses it during runserver and daphne)
- How you're running Channels? python manage.py test
- This is a copy of the test itself

        client = HttpClient()
        client.send_and_consume(u'websocket.connect',{'order': 0}, path='/sock/')
        client.send_and_consume(u'websocket.receive',{'order': 1    }, path='/sock/', text={
                'stream': 'setting',
                'payload': {'action': CREATE, 'data': {'name': 'one', 'value': 1}}
        })
        self.assertEqual(client.receive(), {'key': 'value'})

**Comment by andrewgodwin** [comment]
Tests swap in an in-memory channel layer during tests so that they run quicker. If you wish to prevent this behaviour, set `test_channel_aliases = []` in the body of your TestCase subclass.
