### ISSUE TITLE
The Immediately parameter should bring to JsonWebsocketConsumer or other subclasses of BaseConsumer

### ISSUE THREAD

**Issue by belongwqz** [django/channels#665]
I need quickly send a lot of messages, in order to avoid ChannelFull errors, I write code like this(maybe a little ugly):
```
class MyConsumer(JsonWebsocketConsumer):
    def receive(self, content, **kwargs):
        send_info = {'stream': 'the key', 'payload': 'the stream'}
        msg_txt = {'text': self.encode_json(send_info)}
        self.message.reply_channel.send(msg_txt, immediately=True)
```
And maybe better like this:
```
class MyConsumer(JsonWebsocketConsumer):
    def receive(self, content, **kwargs):
        self.send({'stream': 'the key', 'payload': 'the stream'}, immediately=True)
```

**Comment by andrewgodwin** [comment]
Immediately is only for special-case handling where you are not sending to WebSockets (where instead you need to yield data in a non-atomic way), so I'm not going to add this.

**Comment by belongwqz** [comment]
Thank you, I'll try to take a closer look at the channels code for understanding.
