### ISSUE TITLE
The new release (1.1.4) is using an old version of daphne

### ISSUE THREAD

**Issue by ka7eh** [django/channels#671]
The `runserver` command in the latest release is passing `websocket_handshake_timeout` arg to daphne, which is a new argument and doesn't exist in the official release of daphne at this point, i.e. 1.2.0.

Users should either install the dev branch of daphne or there should be a new release compatible with the latest version of channels.

**Comment by andrewgodwin** [comment]
Yup, my bad. `1.1.5` is out now and fixes that.
