### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'ipv6'

### ISSUE THREAD

**Issue by SynAckPwn23** [django/channels#672]
After the installation process, when I start my appication I get:

**python manage.py runserver 0.0.0.0:8000**
Performing system checks...

System check identified no issues (0 silenced).
June 17, 2017 - 16:40:55
Django version 1.11.2, using settings 'SCTF.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0xb5c33a94>
Traceback (most recent call last):
  File "/root/Desktop/SCTF/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/root/Desktop/SCTF/venv/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 45, in inner_run
    return RunserverCommand.inner_run(self, *args, **options)
  File "/root/Desktop/SCTF/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 149, in inner_run
    ipv6=self.use_ipv6, threading=threading, server_cls=self.server_cls)
  File "/root/Desktop/SCTF/venv/lib/python3.5/site-packages/django/core/servers/basehttp.py", line 164, in run
    httpd = httpd_cls(server_address, WSGIRequestHandler, ipv6=ipv6)
TypeError: __init__() got an unexpected keyword argument 'ipv6'

**Comment by andrewgodwin** [comment]
Can you give versions of all the other related Channels packages please?

**Comment by skiv23** [comment]
It seems that the issue is django 1.11. I was able to run the app by downgrading to 1.10(.7).

**Comment by SynAckPwn23** [comment]
I confirm that It seems that the issue is django 1.11. I was able to run the app by downgrading to 1.10(.7).
Don't Works:
Package        Version
-------------- -------
asgiref        1.1.2  
attrs          17.2.0 
autobahn       17.6.1 
Automat        0.6.0  
channels       1.1.5  
constantly     15.1.0 
daphne         1.3.0  
**Django         1.11.2** 
hyperlink      17.2.0 
incremental    17.5.0 
pip            9.0.1  
pytz           2017.2 
setuptools     36.0.1 
six            1.10.0 
Twisted        17.5.0 
txaio          2.8.0  
zope.interface 4.4.2 

Works:
Package        Version
-------------- -------
asgiref        1.1.2  
attrs          17.2.0 
autobahn       17.6.1 
Automat        0.6.0  
channels       1.1.5  
constantly     15.1.0 
daphne         1.3.0  
**Django         1.10.3** 
hyperlink      17.1.1 
incremental    17.5.0 
pip            9.0.1  
pytz           2017.2 
setuptools     28.8.0 
six            1.10.0 
Twisted        17.5.0 
txaio          2.8.0  
zope.interface 4.4.2

**Comment by bopajdowski** [comment]
The same problem, I've tried 1.9.13, 1.10 and 1.11.2

**Comment by andrewgodwin** [comment]
I've fixed the issue, but it's only happening for you because you don't have `CHANNEL_LAYERS` set and so `runserver` is going back to normal Django mode. You should fix that, and then the next release will also fix the handoff back to Django that's causing this.

**Comment by askoretskiy** [comment]
Any chance to have 1.1.5 released soon with this fix?

**Comment by andrewgodwin** [comment]
I presume you mean 1.1.6, and I'll release it next week as I am not working this weekend.

**Comment by askoretskiy** [comment]
@andrewgodwin Thanks

**Comment by andrewgodwin** [comment]
OK, 1.1.6 released.
