### ISSUE TITLE
Regression on message sending from 1.1.3 to 1.1.5

### ISSUE THREAD

**Issue by ftxrc** [django/channels#673]
My application currently runs a cluster of Django-Q instances for a service, which sends a notification to a user if a specific condition is met. It uses a utility function I created, notify, to create it in the database and send a message to a group as well. It looks like this:

```
def notify(message, user, url=''):
    """ Sends a notification to a user. """
    notification = Notification(message=message, user=user, url=url)
    notification.save()
    return notification
```

Which triggers a signal which notifies the group. 

When updating to 1.1.5, running these notifications from the worker cluster in DjangoQ async does not work, and messages don't pass through. This worked just fine before. It works fine outside the Django-Q async task.

- OS: Ubuntu 16.04
- Runserver but also tested with redischannellayer
- No errors so far.

**Comment by ftxrc** [comment]
UPDATE: Tested again and it is working under RedisChannelLayer: however, it used to work just fine using InMemoryChannelLayer. I assume it's because IMCL can't cross-process communicate.

**Comment by andrewgodwin** [comment]
Yup, there's a big red warning in the documentation about InMemory not being able to talk across processes! If you want a non-Redis alternative, the IPC layer is still very fast and works cross-process on the same machine.

**Comment by ftxrc** [comment]
Sorry about that haha. I guess I didn't test it with IMCL and kept using Redis and didn't notice I was still using it, lol. Thanks for the quick response by the way.
