### ISSUE TITLE
Docs: "we’ll cover this later." ... where=

### ISSUE THREAD

**Issue by guettli** [django/channels#677]
On the page "Channel Concepts", chapter "How do we use channels?", you say _we’ll cover this later_

https://channels.readthedocs.io/en/stable/concepts.html#how-do-we-use-channels

For me this is actually the most important detail.

I am unsure which section you mean with "later".

It would be very nice if you could make this a link to the relevant section.

Thank you very much.

**Comment by ftxrc** [comment]
I'm sure it means Daphne. specifically this section: http://channels.readthedocs.io/en/stable/deploying.html?highlight=daphne#run-interface-servers
I'll try to commit an edit.
