### ISSUE TITLE
No module named 'channels' after install channels and have 'channels' in my INSTALLED_APPS

### ISSUE THREAD

**Issue by objectivemorality** [django/channels#682]
As the title says, I am getting the error "No module named channels" after installing and having channels in my INSTALLED_APPS, whenever I try to do any manage.py funcs. I am using Django 1.10 and python 2.7, Windows OS. What is wrong?

**Comment by andrewgodwin** [comment]
You haven't installed channels correctly - check your import paths and environment variables, I can't help you past that. You should be able to open a python interpreter and type `import channels` to see if it actually works.
