### ISSUE TITLE
The worker never comes up with runserver

### ISSUE THREAD

**Issue by lwm** [django/channels#684]
Over at [a project I'm working on](https://github.com/giving-a-fuck-about-climate-change/carbondoomsday), I'm trying to get `django-channels` set up. 

With the typical `asgiref.inmemory.ChanelLayer` (in my [settings here](https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/f9f2b8c03576c259f1c5a463063597da9ef973f1/carbondoomsday/settings.py#L174)), and running `runserver`, I see no logs from the worker and am unable to make a websocket connection (using `websocket-client` in the REPL) - I have no indication that the worker is up at all.  I only have some dummy code set up for the routing, but should that matter? I should at least see some confirmation that the worker is listening, right?

So, I started to think that channels must be borked with the versions of my dependencies.

I'm on `Django==1.11.2`, `channels==1.1.5`, `daphne==1.3.0`, and `Twisted==17.5.0`.

---

<details>
<summary>Here' my entire environment</summary>

```
$ pipenv run pip freeze
amqp==2.1.4
asgi-redis==1.4.2
asgiref==1.1.2
attrs==17.2.0
autobahn==17.6.2
Automat==0.6.0
billiard==3.5.0.2
cached-property==1.3.0
celery==4.0.2
certifi==2017.4.17
channels==1.1.5
chardet==3.0.4
click==6.7
colorama==0.3.9
constantly==15.1.0
coreapi==2.3.1
coreapi-cli==1.0.6
coreschema==0.0.4
coverage==4.4.1
daphne==1.3.0
decorator==4.0.11
dj-database-url==0.4.2
Django==1.11.2
django-celery-beat==1.0.1
django-configurations==2.0
django-cors-headers==2.1.0
django-extensions==1.7.9
django-filter==1.0.4
django-rest-swagger==2.1.2
django-webpack-loader==0.5.0
djangorestframework==3.6.3
djangorestframework-csv==2.0.0
djangorestframework-filters==0.10.1
docker==2.3.0
docker-compose==1.14.0
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
greenlet==0.4.12
httpie==0.9.9
hyperlink==17.2.1
idna==2.5
incremental==17.5.0
ipdb==0.10.3
ipython==6.1.0
ipython-genutils==0.2.0
isort==4.2.15
itypes==1.1.0
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter-core==4.3.0
kombu==4.0.2
MarkupSafe==1.0
mccabe==0.6.1
msgpack-python==0.4.8
nbformat==4.3.0
neovim==0.1.13
opbeat==3.5.2
openapi-codec==1.3.1
pexpect==4.2.1
pickleshare==0.7.4
plotly==2.0.11
prompt-toolkit==1.0.14
psycopg2==2.7.1
ptyprocess==0.5.2
py==1.4.34
pycodestyle==2.3.1
pydocstyle==2.0.0
pyflakes==1.5.0
Pygments==2.2.0
pylama==7.3.3
pytest==3.1.2
pytest-capturelog==0.7
pytest-cov==2.5.1
pytest-django==3.1.2
pytest-mock==1.6.0
python-dateutil==1.5
pytz==2017.2
PyYAML==3.12
redis==2.10.5
requests==2.18.1
simplegeneric==0.8.1
simplejson==3.11.1
six==1.10.0
snowballstemmer==1.2.1
texttable==0.8.8
traitlets==4.3.2
Twisted==17.5.0
txaio==2.8.0
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3==1.21.1
uWSGI==2.0.15
vine==1.1.3
wcwidth==0.1.7
websocket-client==0.42.1
Werkzeug==0.12.2
whitenoise==3.3.0
zope.interface==4.4.2
```
</details>

---

Thanks :+1:

**Comment by lwm** [comment]
It may be that the logging is related to https://github.com/django/channels/issues/612 or? Is there any other way to validate that the worker has come up?

**Comment by andrewgodwin** [comment]
Can you give me the entire console output of `runserver` when you run it?

**Comment by lwm** [comment]
Here's my output:

```
λ ~/hobby/carbondoomsday/ master python manage.py runserver -v 3
django-configurations version 2.0, using configuration 'Development'
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2017 - 15:49:11
Django version 1.11.2, using settings 'carbondoomsday.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

That's it.

**Comment by andrewgodwin** [comment]
That's not the channels `runserver` command. Did you add it to `INSTALLED_APPS`?

**Comment by lwm** [comment]
Ah, really!? Yes, [I have channels](https://github.com/giving-a-fuck-about-climate-change/carbondoomsday/blob/c6de1b534591db252e37f0d851d2836e7001f406/carbondoomsday/settings.py#L75) in `INSTALLED_APPS`. Perhaps another one of my apps is overriding it? I tried switching a few in and out.

**Comment by andrewgodwin** [comment]
Well, that's what it is; the channels runserver looks quite a bit different (on purpose). If you move `channels` to the end of the list of apps it should get highest precedence.

**Comment by lwm** [comment]
In fact, with all of them disabled, it still does not work. Even when disabling `django-configurations` with this diff:

``` diff
diff --git a/carbondoomsday/settings.py b/carbondoomsday/settings.py
index f786451..056ecd5 100644
--- a/carbondoomsday/settings.py
+++ b/carbondoomsday/settings.py
@@ -58,7 +58,6 @@ class Base(Configuration):
     MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")
 
     INSTALLED_APPS = (
-        "carbondoomsday.carbondioxide",
         "django.contrib.admin",
         "django.contrib.auth",
         "django.contrib.contenttypes",
@@ -66,14 +65,8 @@ class Base(Configuration):
         "django.contrib.sessions",
         "whitenoise.runserver_nostatic",
         "django.contrib.staticfiles",
-        "django_extensions",
-        "django_filters",
-        "rest_framework",
-        "rest_framework_swagger",
-        "opbeat.contrib.django",
-        "corsheaders",
+        "carbondoomsday.carbondioxide",
         "channels",
-        "webpack_loader",
     )
 
     MIDDLEWARE_CLASSES = (
diff --git a/manage.py b/manage.py
index ae076c2..ae893ac 100755
--- a/manage.py
+++ b/manage.py
@@ -3,5 +3,6 @@
 import sys
 
 if __name__ == "__main__":
-    from configurations.management import execute_from_command_line
+    # from configurations.management import execute_from_command_line
+    from django.core.management import execute_from_command_line
     execute_from_command_line(sys.argv)
```

I still see:

``` bash
λ ~/hobby/carbondoomsday/ master* python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2017 - 16:07:59
Django version 1.11.2, using settings 'carbondoomsday.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

**Comment by andrewgodwin** [comment]
You still have other stuff in there like `whitenoise.runserver_nostatic`; remove everything except `django.contrib` apps and see if it still gets overridden.

**Comment by lwm** [comment]
Alright, very good, that was it. It was actually just `whitenoise.runserver_nostatic`.

Thank you very much.

So, do you think this merits a note in the documentation some where? I'd be happy to submit a PR.

**Comment by andrewgodwin** [comment]
Sure - http://channels.readthedocs.io/en/latest/installation.html#installation is probably the best place to put a note.

**Comment by lawrence-gandhar** [comment]
I have installed channels, but on runserver I don't see any change. Its simply showing
`System check identified no issues (0 silenced).
September 26, 2018 - 21:30:38
Django version 2.0.4, using settings 'salescrm.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.`

Can anyone help.

**Comment by andrewgodwin** [comment]
@lawrence-gandhar If you want support please look at options in https://channels.readthedocs.io/en/latest/support.html, don't re-open old issues. Thanks.
