### ISSUE TITLE
Remove expired channels in Group

### ISSUE THREAD

**Issue by alan404** [django/channels#686]
I am not sure about if this is a feature request or a bug report.

Problem description:
There are too many invalid reply channels stored in a Group due to unusual disconnect. It will slow down the overall time to distribute a new message to all valid client in the Group. And those invalid channels always exist in the Group until I flush the redis db directly.

From the documentation this feature should have been included already:
"when the channel starts having messages expire on it due to non-consumption, we go in and remove it from all the groups it’s in as well."

However in practice it seems that no removal happens at all. There are logs "Cannot dispatch message on channel xxx" for the same channel until I flush the redis manually.

My temporary solution is to set a scehduled task to clean up by using zremrangebyscore.

Not sure if it is a bug or the feature is actually missing. Grateful if you can provide any hints or the revelant code for the auto removal so that I can debug by myself.

**Comment by ftxrc** [comment]
I believe this affects me too. Is this the error that makes the console display "invalid response channel" when sending to groups that have disconnected clients?

**Comment by andrewgodwin** [comment]
This is something you should file as an issue in `asgi_redis`, or just reduce `group_expiry` on the channel layer settings. It's not directly a Channels bug.

(I'm considering just removing groups entirely, they're too much of a support burden)

**Comment by alan404** [comment]
I understand group expiry is another mechanism to handle invalid clients, but it does not do the same job as the feature mentioned. For example, a short group expiry, say 10minute, is set and group_add is called whenever ws_received. Although it can avoid keeping client disconnected over 10 minutes, it brings issue:

1. it accidentally remove clients that have not sent any message for 10 minutes. To overcome this, all clients have to keeping sending a "ping" message to trigger group_add....

2. The group expiry is a global setting and a short expiry is not suitable for some groups. To overcome this, we have define a custom expiry time and set up our own scheduler to clear expired clients.

Therefore a much better solution is to remove a client when message cannot be delivered. And the reason why I post this issue here is that this feature is stated in the channels documentation:
http://channels.readthedocs.io/en/stable/concepts.html#groups

> Not only do groups have their own send() method (which backends can provide an efficient implementation of), they also automatically manage expiry of the group members - when the channel starts having messages expire on it due to non-consumption, we go in and remove it from all the groups it’s in as well.

I am thinking if I should implement a custom group and manage it in my code. Just want to make sure that I am not reinventing the wheel.

**Comment by ftxrc** [comment]
@andrewgodwin Removing groups entirely? A lot of code relies on this feature, including a large part of my  apps. It's the feature that makes Channels easy to use.

**Comment by proofit404** [comment]
> (I'm considering just removing groups entirely, they're too much of a support burden)

I remember how mush work it was to implement groups in asgi_rabbitmq. And reimplement it after it, because of protocol change. But I think this labor is worth it. Groups are widely used for things like broadcasting and my personal opinion they should stay.

I have few thoughts about channels internal design and communication with the layer. But I want to hear your thoughts first.

**Comment by proofit404** [comment]
@alan404 What exact **additional** or **changed** behavior you're planning to introduce into your custom `Group`?

**Comment by alan404** [comment]
@proofit404 I am referring to the bold part of the quoted text since I found that it is not working:

> Not only do groups have their own send() method (which backends can provide an efficient implementation of), they also automatically manage expiry of the group members - **when the channel starts having messages expire on it due to non-consumption, we go in and remove it from all the groups it’s in as well**.

**Comment by andrewgodwin** [comment]
Groups are an important part of the overall structure, I agree, but there is a question in my mind if membership-based groups is a better solution than something else (e.g. listen-to-named-channel-broadcast). I'm trying to work all this out in combination with some changes around how much async integration and sticky sessions are used, so I want to have time to present everything in one go and in context.

**Comment by ftxrc** [comment]
@andrewgodwin Subscriptions look like a good idea. Visualizing it, it would be a suitable replacement and would get rid of this issue.

**Comment by proofit404** [comment]
@alan404 I think you can try to fix this in general https://github.com/django/asgi_redis/blob/master/tests/test_core.py#L23

**Comment by alan404** [comment]
@proofit404 Got it. And I finally found that this feature is only implemented for the in-memory channel but missing in both redis and ipc. So from the remark this feature is not implemented due to perfomance consideration?

**Comment by proofit404** [comment]
This feature is implemented in the `asgi_rabbitmq` by the way.
