### ISSUE TITLE
Django Channels doesn't complete operation in devices with few memory

### ISSUE THREAD

**Issue by RibeiroFla** [django/channels#690]
I'm running a django app with channels in a raspberry pi, only my raspberry pi is very slow.

The channels connects ok, although it takes a time due to the few memory.

But when I press save in my admin page in oder to call the signal  to put data in the group and then get the changes in my template it just doesn't  happen.

My question is, Channels abort some task if it takes too long to process?

I'm using asgiref.inmemory.ChannelLayer.

**Comment by proofit404** [comment]
I guess this should be posted into Django users mailing list instead. By the way, can you provide us with complete code example to reproduce your behavior?

**Comment by andrewgodwin** [comment]
I don't see how this is a bug in Channels - please ask more general questions in django-users. Thanks.
