### ISSUE TITLE
runserver command has issues under 1.1.6

### ISSUE THREAD

**Issue by LegoStormtroopr** [django/channels#696]
Django channels 1.1.6 has issues running runserver using `django-admin runserver`:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fc76852ab70>
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/c9/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/.virtualenvs/c9/lib/python3.4/site-packages/channels/management/commands/runserver.py", line 45, in inner_run
    self.server_cls = RunserverCommand.server_cls
AttributeError: type object 'Command' has no attribute 'server_cls'
```

This is resolved by installing 1.1.5

- Detailed description of the overall behaviour
- Reasoning why it should be in Channels rather than a third-party app
- Examples of usage, if possible (it's easier to discuss concrete code examples)

If you're submitting a bug report, please include:

- Ubuntu, Python 3.4.3
- Channels 1.1.6, Daphne 1.3.0, Django 1.10.7
- Run server should run (What you expected to happen) vs. Run server *did not* run (what actually happened)
- How you're running Channels? - runserver
- Console logs and full tracebacks of any errors - See above

**Comment by andrewgodwin** [comment]
Yeah, there's a bug with Django below 1.11. Let me fix it.
