### ISSUE TITLE
add attributes to route_class not working

### ISSUE THREAD

**Issue by evyatar54** [django/channels#697]
I'm trying to add fields to my route_class on websocket connects.
for example: `self.key = value`
However, when I try to access the filed in `receive` function I get an error:
> AttributeError: '<route_class_name>' object has no attribue 'key'

I tried to move the above statement into `__init__` function and even into receive
but the attribute exsits only until the I return message. 
The next time I'll get a message (from the same websocket) the key will no longer exist.

Is there a way to fix it ?

**Comment by proofit404** [comment]
Hi, 

You definitely shouldn't try to store state inside consumer instances. There isn't any guarantee that messages will be processed by the same worker host.

So it is good practice to keep your consumers stateless. I can try to use session storage to share information between consumers run.

Regards, Artem.

**Comment by ftxrc** [comment]
@proofit404 I wholly agree with this - if you need to keep a small state between consumers across workers, use consumer sessions.

**Comment by evyatar54** [comment]
You're right, however, I was using this package to create a server side proxy for multiple steps authentication process. 
on new connection a selenium webdriver would be opened to enter username and password, if it succeeded, the client  would be prompted for the next credentials, which in turn will be given to the selenium webdriver and so on. 
The problem was that I couldn't access the webdriver in the next session and only one step of authentication would happen 
(sorry for bad english)

**Comment by proofit404** [comment]
I don't understand your exact use case. But it's definitely isn't a channels issue.

Channels session bound to the reply channel, not HTTP user. Channels have some helpers to handle both kinds of sessions. But the main point here, that you can use channels session to store shared data between consumer calls as long as they have same reply channel. In other words, as long as they triggered by same connection.
