### ISSUE TITLE
Android/iOS/Mobile Clients Best Practices Documentation

### ISSUE THREAD

**Issue by johnsonc** [django/channels#698]
I believe we would need something here? 

There seems to be almost nothing in the web about the connections ought to be best handled at the client side. 
It would be great if we have something from the channels team so that it could be counted as at least somewhat canonical.

Please submit **questions** about usage to django-users@googlegroups.com (https://groups.google.com/forum/#!forum/django-users) and about development to django-developers@googlegroups.com (https://groups.google.com/forum/#!forum/django-developers).

If you're submitting a feature request, please try to include:

- Detailed description of the overall behaviour
- Reasoning why it should be in Channels rather than a third-party app
- Examples of usage, if possible (it's easier to discuss concrete code examples)

If you're submitting a bug report, please include:

- Your OS and runtime environment, and browser if applicable
- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally)
- What you expected to happen vs. what actually happened
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
- Console logs and full tracebacks of any errors

**Comment by andrewgodwin** [comment]
Client side handling of websockets is such a broad topic you could write a book about it. Given the very small size of the team and the limited time we have, I'm afraid we can't provide anything more than basic JavaScript browser guidance for them.
