### ISSUE TITLE
json not imported[documentation][latest]

### ISSUE THREAD

**Issue by chintanjosh** [django/channels#700]
While going through the documentation from [here](http://channels.readthedocs.io/en/latest/getting-started.html#persisting-data) I found that `json.dumps` was used but json is not imported.

I don't know if this is the correct place to submit issues for documentation.

Let me know if otherwise.

**Comment by proofit404** [comment]
`import json` from standard library is such an obvious statement. It's implied. But feel free for improving doc with PR.

**Comment by chintanjosh** [comment]
I know its obvious, but users tend to copy and paste the code directly at first.
I am new to contributing to opensource and hence it might take some time to figure out some obvious things.
Sorry for inconvenience.

**Comment by andrewgodwin** [comment]
I added it in.

**Comment by chintanjosh** [comment]
@andrewgodwin Great. 
Thanks :+1:
