### ISSUE TITLE
Message not sent

### ISSUE THREAD

**Issue by hugoren** [django/channels#701]
django 1.10.5 
channels 1.1.6
python .3.5.2 

According to channels official configuration

Pycharm boot mode message sent normally

The issue is：
       Daphne start, socket normal connection, but the message did not send, no error

**Comment by proofit404** [comment]
Can you provide source code which doesn't work?

**Comment by hugoren** [comment]
Take care of your answer！
That's what I did.

@channel_session_user
def ws_connect(message):
    message.reply_channel.send({'accept': True})
    Group('socket').add(message.reply_channel)

Group('socket').send({'text': json.dumps({'text': refresh_object})}, immediately=True)

**Comment by proofit404** [comment]
Try to remove immediately flag.

**Comment by hugoren** [comment]
Immediately flag has been removed, or the same

**Comment by proofit404** [comment]
I don't think this is channel bug. Please submit your question to the Django users mailing list. We will continue this discussion there.

Also, provide your channel layer configuration, and try to send messages from the `./manage.py shell`
