### ISSUE TITLE
RFE: General heartbeat system

### ISSUE THREAD

**Issue by Herst** [django/channels#704]
Because of peculiar browser bugs such as http://crbug.com/706002 it might be hard to detect that the websocket connection is broken/lost/gone, i.e. the `error` event does not get triggered or only after a very very long time (minutes).

Now users could implement their own heartbeat systems (sending some no-operation message and waiting for some reply, if such does not arrive before a timeout the connection is considered closed) but seeing that channels is already providing a JS library for the the automatic reconnection handling (inside `websocketbridge.js`) I think it would make sense for it to also implement something for heartbeats as well.

The `ReconnectingWebsocket` is already providing an option for `connectionTimeout`, this option is ATM only referring to the maximal amount of time it can take a websocket connection to connect in the first place (reach the `open` state). I would propose to possibly reuse this option also for the maximal amount of time it can take a heartbeat reply to arrive because I can't think of any sensible use case where one would want to have differing timeout values for connecting and the connection itself.

**Comment by andrewgodwin** [comment]
The WebSocket protocol already has this - it's called `ping`, and Daphne implements it by default, as do browsers I believe. I'm going to close this ticket as I'm not sure there's much we can do here about a general heartbeat system; maybe it might be possible to override how browsers do ping and thus the reliability of the socket but I'm not sure.

**Comment by Herst** [comment]
The browser Google Chrome does not implemented it (see the bug tracker entry I linked to), that's why it needs to be implemented on application-level. For example [django-websocket-redis does it by offering an option for setting what messages are considered heartbeats which are to be mirrored and otherwise ignored.](http://django-websocket-redis.readthedocs.io/en/latest/heartbeats.html)

**Comment by andrewgodwin** [comment]
Well, if you just want to do it at the application level that's easily done as a websocket consumer - I'm not sure what part of this request needs to be done just at the framework level? Usually you would combine a heartbeat system like this with presence status on the server side, and I'd rather let people make their own one that suits their needs rather than trying to provide one that doesn't really work for anyone.

**Comment by proofit404** [comment]
I agree with @andrewgodwin 

I don't think that heartbeat emulation at the framework core is a good idea. Especially because this thing is really hard to change in future. But at least we can add a section at the channels faq.
