### ISSUE TITLE
Deprecation warnings raised from channels code

### ISSUE THREAD

**Issue by seocam** [django/channels#709]
```
$ python manage.py test -n notification
/usr/local/whatsgood/venv/lib/python3.4/site-packages/channels/test/http.py:5: DeprecationWarning: test.http.HttpClient is deprecated. Use test.websocket.WSClient
  DeprecationWarning,
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...../usr/local/whatsgood/venv/lib/python3.4/site-packages/asgiref/base_layer.py:42: DeprecationWarning: receive_many is deprecated; please use receive
  warnings.warn("receive_many is deprecated; please use receive", DeprecationWarning)
........................
----------------------------------------------------------------------
Ran 29 tests in 3.722s
```

When I look for the code using the deprecated methods nothing comes up:
```
$ grep receive_many -R .
$ grep HttpClient -R .
```

- Linux (Ubuntu 14.04)
- Python 3.4
- Django==1.11.3
- asgiref==1.1.2
- asgi-redis==1.4.2
- channels==1.1.6
- daphne==1.3.0
- twisted[http2,tls]==17.5.0

**Comment by proofit404** [comment]
Yes, Channels code base still use the old convention. I'm sure we will remove this warning in Channels 2.0

**Comment by andrewgodwin** [comment]
Yes, this is an internal thing that's already been fixed in the 2.0 branch.

**Comment by AlwxSin** [comment]
Is there a way to suppress such messages until Channels 2.0 released?
Too noisy.

**Comment by proofit404** [comment]
Hi @AlwxSin 

You can run Python with all deprecation warnings ignored 

    #!/usr/bin/env python -W ignore::DeprecationWarning

Add it to the `manage.py` shebang or run your project with `python -m`.

https://stackoverflow.com/questions/879173/how-to-ignore-deprecation-warnings-in-python/879208#879208

**Comment by AlwxSin** [comment]
Hi @proofit404 
Thanks, but your advice doesn't help. I keep receiving warnings.

Code like this in `manage.py`, doesn't help also.
```python
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
 ```

**Comment by proofit404** [comment]
Maybe it depends on Python version you use or compilation flags used when python was built.

**Comment by AlwxSin** [comment]
It's really strange.
5 different places (server with CentOS, MacOS, Windows and Ubuntu), python 3.6.1 and python 3.6.3
And we can't suppress deprecation warnings.
Can this be related to multithreading (if I understand correctly, each worker runs in separate thread)?

**Comment by proofit404** [comment]
Only if you run it with WorkerGroup, by default it is single threaded.
