### ISSUE TITLE
Reject WS connection if there's no matching consumer

### ISSUE THREAD

**Issue by Alexx-G** [django/channels#711]
I've noticed that I can open a connection via WebSockets and it will be accepted even there's no matching consumer (or no consumers at all).
Example of my config:
```python
# settings.py
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'ROUTING': 'config.routing.channel_routing',
        'CONFIG': {
            'hosts': [env('CHANNELS_REDIS_URL')],
        }
    },
}

# routing.py
channel_routing = [
    include('api.routing.channel_routing'),
]

# api.routing.py
channel_routing = [
    ClassBasedConsumer.as_route(path=r'^/ws/whatever/(?P<pk>\d+)/foobar/'),
]
```

Routing for valid path works as expected. However, if I try to connect to `/ws/` or `/ws/any-path`, my connection is accepted.
```
WebSocket HANDSHAKING /ws// [172.19.0.7:50651]
WebSocket CONNECT /ws// [172.19.0.7:50651]
```

In my opinion, those connections should be rejected since there's no matching consumer for them.
Am I missing something?

P.S. I'm using nginx to as reverse proxy, but I'm quite sure that it's not a problem since django-channels logs that handshake and connection are performed.

**Comment by andrewgodwin** [comment]
This is actually currently a deliberate design decision; prior versions of channels 1 did not have the accept/reject flow, and so implicit accept was part of the design. We'll be changing this in channels 2, but until then we can't for backwards compatability.

If you want default-deny, though, all you need to do is add a consumer on `websocket.connect` with no path match that always rejects as the very last item in your routing. Routing is evaluated in order and the first match taken, so this won't override anything above it.

**Comment by Alexx-G** [comment]
Thanks for reply. I see.
It's not intuitive, though. It would be nice to state this in the routing section.
It's quite simple to implement, however at the beginning I thought that there's something wrong with my routing/setup.
