### ISSUE TITLE
Named routes for URL / Route Tag

### ISSUE THREAD

**Issue by tomturner** [django/channels#712]
I want to name be able to name routes like you do with the urls. This is so you can use a template tag like {% url 'My named route' %}. or reserve method

```
channel_routing = [
    include("myapp.routing.custom_routing" namespace='myapp'),

]

custom_routing = [
    route_class(MyAppConsumer, path=r"/my-app/" name='consumer'),
]

```

In the HTML you could use

```
<script>
        $(function () {
            var ws_path =  "/my-app/";
            console.log("Connecting to " + ws_path);
            ...
```

instead of

```
<script>
        $(function () {
            var ws_path =  "{% route 'myapp:consumer' %}";
            console.log("Connecting to " + ws_path);
            ...
```

**Comment by proofit404** [comment]
Hi, 

That's an interesting feature request! I'm don't think template tag will be sophisticated implementation. Because this code will be used mostly for static assets like minified SPA application rather than from template html with script tag inside. Probably we can agree on some mechanism and implement additional JS client library for client side reverse function.

I don't think the route will be usefull only for websocket connect.

Did you try multiplexer wrapper?

Regards, Artem.

**Comment by andrewgodwin** [comment]
I'm actually not even a fan of this feature in Django (I maintain an alternative approach over at http://github.com/andrewgodwin/urlman) so I'm not too sure about adding it to Channels. Especially as the "routing" engine we have doesn't actually know anything about URLs particularly - it's a general attribute matching engine you happen to use to match on the `path` attribute.

I'll leave this open, but it's unlikely to happen before channels 2 occurs, if it happens at all.

**Comment by proofit404** [comment]
I apologise for unrelated discussion here.

Does urlman support any nesting mechanism? Something similar to `include`.

**Comment by andrewgodwin** [comment]
It supports shared components - you can refer to `self.foo` or other URL patterns - so that sort of fulfills the include() niche.

**Comment by Satyendra-IITR** [comment]
Hello People, I want to work on this enhancement. How should I start...?

**Comment by proofit404** [comment]
Hi, 

I think good starting point will be an explanation of use cases of this feature and possible usage API.

Regards, Artem.

**Comment by andrewgodwin** [comment]
I'm going to make an executive decision and close this as a WONTFIX, as the routing system in Channels 2 is generic enough that reversing through it, if it was even possible, would be a performance nightmare. Django's URL naming/reversing continues to work for views.
