### ISSUE TITLE
Sending responses in loop

### ISSUE THREAD

**Issue by alexvelickiy** [django/channels#713]
Hi,

I'm trying to find the way to do the following thing:

When I get websocket message from client, I want to send to this client the data every second. What is the best way to do this?
I think having consumer that will make send calls in loop is blocking approach.

Also I'd like to have the way to stop the loop with another client websocket call.

**Comment by proofit404** [comment]
Hi,

I shouldn't use the loop and sleep in the consumers for many reasons.

1. The number of connected clients is limited to the number of workers. It's a waste of resources.
2. Stop message will be processed by another worker. This makes loop shutdown process very tricky.

I suggest to use the following setup:

1. Run delay server.
2. The consumer which accepts initial message from the client will send the single message into delay channel with 1 second delay time.
3. After one second delay server will submit this message into channel layer.
4. You should setup routing so this intermediate message will be handled by special repeater consumer.
5. This consumer should do two things: send the message to the client, send the message to the delay channel.
6. When the second message arrives from a client you can remove delayed message from database and channel layer.

But if you describe the actual problem you're trying to solve I probably can suggest a solution without homemade ping :)

**Comment by alexvelickiy** [comment]
Did I understand to right that one worker means that maximum amount of connected clients is also one?

As I understand, delay channel will allow me to send only one delayed message? My task is the following, when client presses 'Monitor prices' and sends appropriate websocket message, I need to constantly send him prices every second. And stop this process when client disconnects or presses 'Stop monitor prices' button.

What is your suggested solution?

**Comment by andrewgodwin** [comment]
No, one worker can service many connections, but it can only handle one event at once. This is why you handle connection and incoming messages in separate function calls - this is how we let you service many connections from one synchronous worker.

If you want to constantly send prices, I suggest a group to send them to and an external process (management command?) that sends them into the group every second.

**Comment by alexvelickiy** [comment]
Thank you. So I managed to do it in following way:
(I use Redis and Daphne servers)
When client send specific websocket message, I add him to Group A
I created new .py file, connected to Redis server from there and call send_group method for group A in loop every second. When I run this py file everything seems to work as desired. 

BTW, is there a way to get list of all registered groups from asgi_redis.RedisChannelLayer?

**Comment by proofit404** [comment]
Yes, if you have control over observed process, it is better to trigger periodic notifications from the process itself. Django management command is the easiest one from many possible solutions.

**Comment by andrewgodwin** [comment]
In channels 1 or 2 you can send to a group from anywhere, including a model save method or signal handler. I'd go that route.

**Comment by rakeshR7** [comment]
What about data binding? that should work too right? but it's hard testing it since update statements from a script outside of django won't trigger the action. Is there a workaround for testing it?

**Comment by andrewgodwin** [comment]
Data binding just adds Django signal listeners, it's not doing anything particularly special. No solutions I know of will trigger on UPDATE statements coming from outside.

**Comment by rakeshR7** [comment]
so if i use post_save and try testing from django shell , will it work?

**Comment by Piyush12ahuja** [comment]
I am facing issue with sending multiple notification one by one to client. As of now all the notification which are sending in loop are received together on client side.
