### ISSUE TITLE
websocket connection disconnects just after handshake

### ISSUE THREAD

**Issue by Krittam** [django/channels#714]
Environment details:
Django==1.11.3
channels==1.1.6
asgi_redis==1.4.2

Firefox console error :
Firefox can’t establish a connection to the server at ws://localhost:8000/users/.
Terminal logs:
[2017/07/30 12:49:53] HTTP GET / 200 [0.03, 127.0.0.1:50286]
[2017/07/30 12:49:55] WebSocket HANDSHAKING /users/ [127.0.0.1:50294]
[2017/07/30 12:50:00] WebSocket DISCONNECT /users/ [127.0.0.1:50294]

I also tried to test it with python websocket-client. It gives this error
ConnectionResetError: [Errno 104] Connection reset by peer

Here are my connection functions :
def ws_connect(message):
    Group('users').add(message.reply_channel)
    return {"accept": True} 

def ws_disconnect(message):
    print('disconnect')
    Group('users').discard(message.reply_channel)

def ws_echo(message):
    message.reply_channel.send({
        'text': message.content['text'],
    })

This is my js code at frontend:
var socket = new WebSocket('ws://' + window.location.host + '/users/');

    socket.onopen = function open() {
      console.log('WebSockets connection created.');
    };

    if (socket.readyState == WebSocket.OPEN) {
      socket.onopen();     
      socket.send('test message');
    }

Please look in to this issue.

**Comment by proofit404** [comment]
Hi, 

You don't accept ws connection correctly. Use this consumer instead:

```python
def ws_connect(message):
    Group('users').add(message.reply_channel)
    message.reply_channel.send({"accept": True})
```
