### ISSUE TITLE
Extend WebsocketBindingWithMember to support Foreign Keys and m2m fields

### ISSUE THREAD

**Issue by ZuSe** [django/channels#716]
- Detailed description of the overall behaviour
When using bindings of models we would sometimes like to send out an updated message based on an updated foreign key value, m2m relation or computed property.
At the moment there is support for sending out custom model properties as long they are computed based on attributes of the same model but not if it depends on a related model e.g.
compute the number of unread chat messages in a chat room and return the count as property of the room
Therefore my idea would be to extend the existing send_members array of the WebsocketBindingWithMembers class to support at least m2m, foreign key so that an post_save hook that triggers the post_change method of the binding are automatically registered for the referenced classes.
e.g. action on chat-message triggers post_change on chat room

- Reasoning why it should be in Channels rather than a third-party app
I think this functionality would provide nicer code and avoids registering all post_save/delete hooks manually. Also I would think that it's not a very uncommon use case why it should be part of the base library.

**Comment by proofit404** [comment]
Hi, thanks for the feedback.

I think this approach would have some inconsistent behavior. For example, we have three models. The second and the third have the first one in its foreign keys. Also, this two models have bindings with this foreign key mentioned in the bindings field. So change in the first model will trigger two update events. This doesn't sound to me like a good design decission.

Why having separate bindings for each model is a problem? It has deterministic behavior.

Regards, Artem.

**Comment by ZuSe** [comment]
Hello Artem,
thanks for coming back to me. 
You are right, the first model would trigger the two others, but only if you add them to the list (so it's up to the developer if he wants that). Maybe let's discuss it on the example I came up with the issue.
Let's say I have 3 entities: 
Chat-Room and Chat-Message and Chat-Invitations
The ChatRoom has an attribute showing the count of all new unread messages.
I would like to update this count whenever someone creates a new message to all clients subscribed to my chat-rooms route, so basically send out a new message whenever a chat-message was created.
The clients are not subscribed to a specific chat-room at this point in time as joining them requires special permissions etc. so there is no chance to get informed about the new messages by subscribing to the chat-messages route/stream also I don't want it as it would simply kill my application when more than 1k chats are opened and everyone gets every message.

So the only way I see here is to allow some remote triggers for the bindings.
Maybe another way is to to extend the existing register functions by accepting more than just the own model specified in the binding.
Best
Patrick

**Comment by ZuSe** [comment]
@proofit404 
Artem, does it now make sense to you or do I oversee sth. ?

**Comment by andrewgodwin** [comment]
Binding has been removed in Channels 2 due to maintenance overhead so I'm going to close this.

**Comment by ZuSe** [comment]
Hey @andrewgodwin 

thanks for the information. So what does that mean to us? I there a new concept to replace it or would we need to implement everything by ourselfs?

Best
ZuSe

**Comment by andrewgodwin** [comment]
I will be shipping something like the previous implementation as a personal project (under my own name on GitHub) so it's not an official Django project, but you can also implement your own if you want (part of the reason I removed it was that it was a bit too generic and didn't really encourage anyone to do their own thing if it was in the main repo)
