### ISSUE TITLE
Routing Documentation improvment

### ISSUE THREAD

**Issue by jeremytiki** [django/channels#722]
On the [routing page of the documentation](https://channels.readthedocs.io/en/stable/routing.html) there is not mention or explanation of the additional filtering, just that the ability to filter is there. The [Getting Started](https://channels.readthedocs.io/en/stable/getting-started.html) doc's explain this much better: 

> The routing.py file acts very much like Django’s urls.py, including the ability to route things to different consumers **based on path, or any other message attribute that’s a string** (for example, http.request messages have a method key you could route based on).

I believe it would be beneficial to add the bold section of text to the routing docs as well to reduce the ambiguity of the examples.

**Comment by andrewgodwin** [comment]
I would agree with you in the past, but we're massively changing routing very soon so I'm going to close this issue as it will quickly become redundant. I'll try to make sure there are more examples of filtering in the future docs, though.
