### ISSUE TITLE
HTTPS support through Nginx

### ISSUE THREAD

**Issue by SynAckPwn23** [django/channels#723]
Channels works well with my local http installation.
On my production server (https) I running Channels through Nginx.

How can I manage this? http://imgur.com/IYFb9hp

If I try to modify the url with "wss" instead "ws" i get -> (index):450 WebSocket connection to 'wss://156.ip-151-80-57.eu/sctf_channels/' failed: Error during WebSocket handshake: Unexpected response code: 404

Daniele

**Comment by globophobe** [comment]
Did you notice the 404 error? It's not an SSL error.

**Comment by SynAckPwn23** [comment]
yes.. thats the point 

with:       socket = new WebSocket("ws://" + window.location.host + "/sctf_channels/"); no 404 but errors
with       socket = new WebSocket("wss://" + window.location.host + "/sctf_channels/"); I get 404

I miss something?
Thx

**Comment by andrewgodwin** [comment]
Probably means that whatever terminates your SSL is configured wrongly. This isn't a Channels problem, so I'm going to close this issue.

**Comment by SynAckPwn23** [comment]
Solved, I fighted with radis and daphne. Everithing it's ok.
Thx

2017-08-15 18:21 GMT+02:00 Andrew Godwin <notifications@github.com>:

**Comment by thuyahtut** [comment]
@SynAckPwn23 
Pls share us how did you solve?

**Comment by iamriel** [comment]
how did you solve the issue? I am experiencing the same thing. thanks

**Comment by whitehathackersree** [comment]
Yeah me too. Please share the solution.

**Comment by shtalinberg** [comment]
share how did you solve?

**Comment by elshaddae** [comment]
@SynAckPwn23, Next time please share

**Comment by SynAckPwn23** [comment]
Guys, please stop to comment “please share” my specific issue was not channels related it was a specific wrong configuration in my environement (nginx, radis, daphne).
