### ISSUE TITLE
Random timeouts connecting using websockets

### ISSUE THREAD

**Issue by xeor** [django/channels#725]
- Your OS and runtime environment, and browser if applicable
  - Alpine based setup running in docker

- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally)
  - channels==1.1.6
  - daphne==1.3.0
  - Django==1.11.4
  - Twisted==17.5.0
  - asgi-redis==1.4.2

- What you expected to happen vs. what actually happened
**Happens**
When connecting using websockets, I randomly get an error after 5 seconds. Example

```
import websocket
ws_client = websocket.create_connection('ws://localhost:5001/_/ws/')
...
/usr/lib/python2.7/site-packages/websocket/_socket.pyc in recv(sock, bufsize)
     78
     79     try:
---> 80         bytes_ = sock.recv(bufsize)
     81     except socket.timeout as e:
     82         message = extract_err_message(e)

error: [Errno 104] Connection reset by peer
```
It works about 70% of the time. When it connects, I am able to use `ws_client` to send data/receive data without hazzle.

**Expected**
The client would be able to connect everytime without errors as it does in my dev environment (only diff is the load).

- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
  - /data/src/manage.py runworker --only-channels=websocket.*
  - /usr/bin/daphne -p 5001 server_apps:websocket
  - Running test inside the same container as runworker and daphne to remove any interference from the nginx proxy in front.

- Additional info
There are no errors when I run daphne or runworker in "front".
I see a ton of LPOP messages in redis (around 1500/sec) like `│1503400278.093963 [2 lua] "LPOP" "asgi:websocket.send!FFcEzMZYxgpn"` this. I don't know if that is normal or have anything to do with this.

I am not seeing anything about `channel_full`, nor do I have a key in redis with `channel_full_count`.

**redis info**
```
~ # redis-cli info clients
# Clients
connected_clients:54
client_longest_output_list:263
client_biggest_input_buf:0
blocked_clients:2

~ # redis-cli --latency
min: 0, max: 2, avg: 0.08 (2073 samples)

~ # redis-cli --stat
------- data ------ --------------------- load -------------------- - child -
keys       mem      clients blocked requests            connections
11759      34.18M   54      2       351866741 (+0)      1235
11759      34.34M   54      2       351868366 (+1625)   1235
11759      34.30M   54      2       351870224 (+1858)   1235
11758      34.22M   54      2       351872025 (+1801)   1235
11758      34.18M   54      2       351873851 (+1826)   1235
```

- Console logs and full tracebacks of any errors

I don't know what to send, since it looks all normal (please suggest what I can send). Here is at least something from `redis monitor` output where I have cleaned up removing noise (at least most of it)..

**working connect**
```
1503398386.528606 [2 192.168.128.2:49776] "BLPOP" "asgi:websocket.disconnect" "asgi:websocket.receive" "asgi:websocket.connect" "5"
1503398388.430557 [2 192.168.128.3:39734] "BLPOP" "asgi:websocket.connect" "asgi:websocket.receive" "asgi:websocket.disconnect" "5"
1503398391.833996 [2 192.168.128.2:49776] "BLPOP" "asgi:websocket.disconnect" "asgi:websocket.connect" "asgi:websocket.receive" "5"
1503398393.308738 [2 lua] "llen" "asgi:websocket.connect"
1503398393.308848 [2 lua] "expire" "asgi:6e5ec6fbdab1445baf82c3018cd299f4" "60"
1503398393.308862 [2 lua] "rpush" "asgi:websocket.connect" "asgi:6e5ec6fbdab1445baf82c3018cd299f4"
1503398393.308886 [2 lua] "expire" "asgi:websocket.connect" "61"
1503398393.309306 [2 192.168.128.3:39734] "GET" "asgi:6e5ec6fbdab1445baf82c3018cd299f4"
1503398393.309381 [2 lua] "incr" "asgi-meta:websocket.connect:messages_count"
1503398393.309397 [2 lua] "expire" "asgi-meta:websocket.connect:messages_count" "3600"
1503398393.309412 [2 lua] "incr" "asgi-meta:#global#:messages_count"
1503398393.309423 [2 lua] "expire" "asgi-meta:#global#:messages_count" "86400"
1503398393.309715 [2 192.168.128.3:39734] "DEL" "asgi:6e5ec6fbdab1445baf82c3018cd299f4"
1503398393.329984 [2 lua] "expire" "asgi:3f934bbc3ad84755a8f8eab63f2ad4b8" "60"
1503398393.330490 [2 lua] "incr" "asgi-meta:#global#:messages_count"
1503398393.330504 [2 lua] "expire" "asgi-meta:#global#:messages_count" "86400"
1503398393.330779 [2 192.168.128.3:39734] "BLPOP" "asgi:websocket.disconnect" "asgi:websocket.connect" "asgi:websocket.receive" "5"
1503398393.361518 [2 192.168.128.3:39722] "GET" "asgi:3f934bbc3ad84755a8f8eab63f2ad4b8"
1503398393.361671 [2 192.168.128.3:39722] "DEL" "asgi:3f934bbc3ad84755a8f8eab63f2ad4b8"
1503398397.142851 [2 192.168.128.2:49776] "BLPOP" "asgi:websocket.receive" "asgi:websocket.connect" "asgi:websocket.disconnect" "5"
```

**hangs**
```
1503398560.886206 [2 192.168.128.2:49776] "BLPOP" "asgi:websocket.receive" "asgi:websocket.disconnect" "asgi:websocket.connect" "5"
1503398562.686080 [2 192.168.128.3:39734] "BLPOP" "asgi:websocket.connect" "asgi:websocket.disconnect" "asgi:websocket.receive" "5"
1503398563.914309 [2 lua] "llen" "asgi:websocket.connect"
1503398563.914406 [2 lua] "expire" "asgi:3adb294a26784801aa6816cebc55d53a" "60"
1503398563.914420 [2 lua] "rpush" "asgi:websocket.connect" "asgi:3adb294a26784801aa6816cebc55d53a"
1503398563.914443 [2 lua] "expire" "asgi:websocket.connect" "61"
1503398563.914828 [2 192.168.128.2:49776] "GET" "asgi:3adb294a26784801aa6816cebc55d53a"
1503398563.914887 [2 lua] "incr" "asgi-meta:websocket.connect:messages_count"
1503398563.914902 [2 lua] "expire" "asgi-meta:websocket.connect:messages_count" "3600"
1503398563.914916 [2 lua] "incr" "asgi-meta:#global#:messages_count"
1503398563.914928 [2 lua] "expire" "asgi-meta:#global#:messages_count" "86400"
1503398563.929196 [2 192.168.128.2:49776] "EXPIRE" "asgi::group:confluence.broadcast" "86400"
1503398563.933925 [2 lua] "set" "asgi:d783278ae4304b6ebb747614e674763e" "\x81\xc4\x06accept\xc3"
1503398563.933942 [2 lua] "expire" "asgi:d783278ae4304b6ebb747614e674763e" "60"
1503398563.934330 [2 lua] "incr" "asgi-meta:#global#:messages_count"
1503398563.934342 [2 lua] "expire" "asgi-meta:#global#:messages_count" "86400"
1503398563.935071 [2 192.168.128.2:49776] "BLPOP" "asgi:websocket.connect" "asgi:websocket.receive" "asgi:websocket.disconnect" "5"

# Hangs for 5 seconds

1503398567.991455 [2 192.168.128.3:39734] "BLPOP" "asgi:websocket.disconnect" "asgi:websocket.receive" "asgi:websocket.connect" "5"
1503398568.001258 [2 lua] "llen" "asgi:websocket.disconnect"
1503398568.001306 [2 lua] "expire" "asgi:578607f3f5b04c528f703d28c4011fcc" "60"
1503398568.001320 [2 lua] "rpush" "asgi:websocket.disconnect" "asgi:578607f3f5b04c528f703d28c4011fcc"
1503398568.001343 [2 lua] "expire" "asgi:websocket.disconnect" "61"
1503398568.001974 [2 192.168.128.2:49776] "GET" "asgi:578607f3f5b04c528f703d28c4011fcc"
1503398568.008009 [2 lua] "incr" "asgi-meta:websocket.disconnect:messages_count"
1503398568.008035 [2 lua] "expire" "asgi-meta:websocket.disconnect:messages_count" "3600"
1503398568.008051 [2 lua] "incr" "asgi-meta:#global#:messages_count"
1503398568.008064 [2 lua] "expire" "asgi-meta:#global#:messages_count" "86400"
1503398568.071138 [2 lua] "llen" "asgi:websocket.receive"
1503398568.071152 [2 lua] "set" "asgi:6014b0fdce2146cabc2e0c99c9351f5a" "\x84\xa4path\xb1/_/ws/\xa4text\xd9 {\"action\":\"heartbeat\",\"data\":{}}\xadreply_channel\xbbwebsocket.send!STxBhgZUkmTP\xa5order\x0e"
1503398568.071191 [2 lua] "expire" "asgi:6014b0fdce2146cabc2e0c99c9351f5a" "60"
1503398568.071205 [2 lua] "rpush" "asgi:websocket.receive" "asgi:6014b0fdce2146cabc2e0c99c9351f5a"
1503398568.071228 [2 lua] "expire" "asgi:websocket.receive" "61"
1503398568.071617 [2 192.168.128.3:39734] "GET" "asgi:6014b0fdce2146cabc2e0c99c9351f5a"
1503398568.071674 [2 lua] "incr" "asgi-meta:websocket.receive:messages_count"
1503398568.071691 [2 lua] "expire" "asgi-meta:websocket.receive:messages_count" "3600"
1503398568.071705 [2 lua] "incr" "asgi-meta:#global#:messages_count"
1503398568.071717 [2 lua] "expire" "asgi-meta:#global#:messages_count" "86400"
1503398568.072071 [2 192.168.128.3:39734] "DEL" "asgi:6014b0fdce2146cabc2e0c99c9351f5a"
1503398568.073776 [2 192.168.128.3:39734] "BLPOP" "asgi:websocket.receive" "asgi:websocket.connect" "asgi:websocket.disconnect" "5"
```

- Configuration

**settings.py**
```py
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'CONFIG': {
            'hosts': ['redis://redis:6379/2'],
            'capacity': 300
        },
        'ROUTING': 'routing.channel_routing',
    },
}
```

**part of consumer**
```py
class WebsocketConsumer(JsonWebsocketConsumer):
    http_user = True

    def connection_groups(self, **kwargs):
        return ['broadcast']

    def connect(self, message, **kwargs):
        self.message.channel_session['subscriptions'] = {}
        self.message.reply_channel.send({'accept': True})
```

**part of server_apps.py**
```py
from channels.asgi import get_channel_layer
websocket = get_channel_layer()
```

**Comment by andrewgodwin** [comment]
If you're getting `Connection reset by peer` it means that the piece of software between the browser and the WebSocket server is not correctly handling WebSockets - in particular, it might be too old to understand HTTP/1.1 and is just treating the connection like a HTTP connection then dropping it when nothing happens.

This is reinforced by the fact that the error does not happen when you connect to Daphne directly, so I'd say this is not a Channels issue but a problem with your stack.

**Comment by xeor** [comment]
The `Connection reset by peer` comes after 5 seconds, probably because the BLPOP (which times out after 5 seconds) fails to get something (at least thats the only 5 second timeout I could find)..

There is nothing between the "browser" (it is the `websocket` module from PyPI), and daphne. It connects directly to the port daphne is listening on. The error is happening when I connect directly.

I can dig deeper myself, and I will update this issue when I eventually find the solution.
I can see how it is difficult to give pointers in this case, but I hope you can answer the following:

* When I got `client_ws = websocket.create_connection('ws://localhost:5001/_/ws/')` working. Is it normal for it do stop working (gives me `Connection reset by peer`) if kept unused for around 30 seconds?

* Is it normal for redis to receive `LPOP` and `EVALSHA` commands ~20 times/second per connection? I suspect this is happening because something isn't working correctly, or is it normal?

* Have I overlooked some parameters I need to tweak for many connections. Like the `capacity` options for `asgi_redis`.

**Comment by proofit404** [comment]
* websocket python client doesn't send heartbeats, this is why your connection stop working.
* Which part of the system produce this redis calls? If it's Daphne, check you're using twisted backend reader.

**Comment by xeor** [comment]
If I run daphne with `/usr/bin/daphne -p 5001 -v 2 server_apps:websocket` it outputs this after the 5 secound timeout:

```
2017-08-23 10:25:21,000 WARNING  dropping connection to peer tcp4:127.0.0.1:56268 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)                                                                                                                          
```

**Comment by xeor** [comment]
@proofit404  thanks.. Number 1 make sense..
I am using from `channels.asgi.get_channel_layer.get_channel_layer()`, and it got the extensions `[u'groups', u'flush', u'twisted', u'statistics']`. force_sync is not enabled.

**Comment by proofit404** [comment]
I need so time to think about it. I'll come back to this at the weekend.

**Comment by xeor** [comment]
I upgraded all packages, and suddenly it started working without any issues.. :)
I tend to do that often, letting the tests fail a build instead of pinning versions, however this was eventually a cached layer in docker that was biting me and keeping old versions on new builds.

**Comment by proofit404** [comment]
Glad you solve it!

**Comment by xeor** [comment]
I did notice however that I'm down from `56` to `26` clients, end of day here, so thats probably why. However, I am not 100% sure the problem won't come back when people start connecting.. Time will show :)

**Comment by ReadMost** [comment]
> If I run daphne with `/usr/bin/daphne -p 5001 -v 2 server_apps:websocket` it outputs this after the 5 secound timeout:
> 
> ```
> 2017-08-23 10:25:21,000 WARNING  dropping connection to peer tcp4:127.0.0.1:56268 with abort=True: WebSocket opening handshake timeout (peer did not finish the opening handshake in time)                                                                                                                          
> ```

did you solve it? I have async consumer which send a lot of data for offline mode in my app, however other consumers for it does not work at that time by sending me similar issue as yours
