### ISSUE TITLE
Pytest plugin

### ISSUE THREAD

**Issue by dszmaj** [django/channels#726]
Hello,

is there any reason why this package doesn't include pytest support? Is this planned?

I would like to propose implementing pytest plugin featuring fixtures for WSClient etc. It would be just great to have more flexibility with choice of a test runner.

Regards,
Dominik

**Comment by proofit404** [comment]
Hi, 

We just don't think about it yet. It would be great if you can provide *all* usage examples. So we can start thinking about this possibility.

I'm still not sure if this will be included into channels itself or developed as third party library. Eather way I'm interested to see this implemented in some form.

Regards, Artem.

**Comment by andrewgodwin** [comment]
We maintain only standard unittest support because there's only a small maintenance team (and pytest is compatible with it) - I might accept a PR for pytest support, but only if it's very well documented, including maintenance docs.

**Comment by proofit404** [comment]
I'm familiar with pytest. And I want it to be well supported. People can use our UnitTest integration with pytest, but this is really inconvenient. Let's see what features we need and I'll work it out.

**Comment by dszmaj** [comment]
I'm creating a project with this, and will create some fixtures as well. In a couple of days I should have a picture of basic functionality, push some PR with things that worked for me and see what you have to say about this.

**Comment by andrewgodwin** [comment]
Going to close this as Channels 2's test helpers are much simpler than Channels 1 and I don't think there's much value in providing fixtures for the few basic things we have right now.
