### ISSUE TITLE
edit on github from readthedocs => 404

### ISSUE THREAD

**Issue by foxmask** [django/channels#733]
Hi,

The doc on readthedocs leads to a 404 when we click on "edit on github " here 

https://channels.readthedocs.io/en/stable/installation.html

We arrive here

https://github.com/django/channels/blob/origin/2.0/docs/installation.rst

And it the same behavior from any page from readthedocs 

It seems to be a config issue we URL provided to readthedoc

Regards

**Comment by andrewgodwin** [comment]
Looks like this is instead a bug in read the docs - I will go over and notify them.
