### ISSUE TITLE
Running scheduled jobs

### ISSUE THREAD

**Issue by erikash** [django/channels#74]
Hi, 
Kudos for the great job! 
This will be definitely take django to the next level! 

Are you planning to include support for scheduled jobs? Like celery beat? 

Any suggested workarounds? 

Best, 
Erik.

**Comment by andrewgodwin** [comment]
Yes, the intention is to have some sort of command that can push messages onto channels periodically. In the meantime, I suggest writing a custom management command that does this and calling it using `cron`.

**Comment by erikash** [comment]
Thanks, sounds great

**Comment by avayo** [comment]
Hello Andrew. Thank you for the great project!
Can you (or someone else) suggest the best way to send signals to channels via cron?

**Comment by andrewgodwin** [comment]
For now, I recommend writing a management command that sends the signals onto the channels, and calling that from cron.

**Comment by mrasband** [comment]
For anyone else coming here and not being sure where to start (like me), a quick example:

```python

# settings.py
CHANNEL_LAYERS = {
    # This is the channel layer id, you can have a bunch if you want
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.environ.get('REDIS_URL', 'redis://localhost:6379')],
        },
        # this defines the channels on the layer (in tutorials you probably see websocket.connect)
        'ROUTING': 'app.routing.channel_routing',  
    }
}

# app/routing.py
channel_routing = {
    # You can name your channel anything you want
    'your_channel_name': lambda x: print('Channel Triggered Event!'),
}

# ./manage.py shell
from channels import Channel, channel_layers

# default here matches your layer name (from settings.py) that can delegate to your_channel_name
c = Channel('your_channel_name', channel_layer=channel_layers['default'])
c.send({})
```

**Comment by andrewgodwin** [comment]
Yup, that's a great example - thanks @mrasband! I'll see if I can work stuff for calling from cron into the docs - it also looks like we're going to have some work start on a scheduled task interface server soon (similar to celerybeat), which might be better if you want things very frequently or can't set cron tasks.

**Comment by mrasband** [comment]
Thank you @andrewgodwin for the awesome work, this has helped swing me back to using Django more :)

**Comment by rajasimon** [comment]
@andrewgodwin you mention "scheduled task interface" server. Is developed fully...! Shall I try now?

**Comment by andrewgodwin** [comment]
I believe @jacobkm was looking into it, but I don't know what sort of progress he's made, or if he's found the time to start yet.

**Comment by rajasimon** [comment]
Please check <code>[beatserver](https://github.com/rajasimon/beatserver)</code> can do periodic tasks. Thanks @andrewgodwin for the ideas...

**Comment by ssteinerx** [comment]
You can do it in Twisted in two lines:
```python
looper = LoopingCall(send_some_message_function)
looper.start(1)
```

Where `send_some_message_function` sends your message.

**Comment by rajasimon** [comment]
@ssteinerx Yeah that can do! I did because it's easy to migrate from celerybeat ( same conf ). And this helps beginners more idea about scheduling. And one more thing what if you want to stop the notification and alter it ( restart the server not the best approach )

**Comment by ssteinerx** [comment]
`looper.stop()`

[docs](http://twistedmatrix.com/documents/13.2.0/core/howto/time.html)

**Comment by JohnDoee** [comment]
I went ahead and created a thin wrapper around [apscheduler](https://apscheduler.readthedocs.io/en/latest/) add_job command that'll send a message back on a specified channel when triggered [in my own asgi implementation](https://github.com/johndoee/txasgiresource#scheduler).

It would be simple to squeeze it into Daphne too and solves most, if not all, delayed-call / scheduling issues.

**Comment by andrewgodwin** [comment]
Closing this as there's delay for channels 1 and in channels 2 you can just use asyncio stuff.
