### ISSUE TITLE
Feature Request: Persistence of objects that can not be serialized and the ability to use the same instances of complex objects for a web socket's duration.

### ISSUE THREAD

**Issue by agronick** [django/channels#743]
I've found that Django Channel's lack of persistence limits it's usability. Every time a `receive()`, `connect()`, or `disconnect()` call comes into a class based consumer, the class based consumer is reinstantiated.  Anything that can't be serialized is unable to be persisted. In my opinion, this takes some of the limitations of HTTP and brings them to websockets, preventing a lot of use cases web sockets excel at.

How could I make a web based VNC client, or a web based command line client? Or anything where a user would manipulate a stream of data - one of the most common reasons for using web sockets. The command line client and VNC client are two of the use cases that are best served by websockets in the main application I write. Neither can easily be implemented by Channels. Both require an input and output stream to be persisted, and for them to be fed into the web socket. There is currently no clean way to keep these input and output streams from being lost.

I was able to get around it by instantiating a thread in the `connect()` method and using the low level Redis pub/sub API to pass messages to the thread from the `receive()`, and `disconnect()` methods. This seems sloppy. It seems like something that should be possible with Channels, and without resorting to low level backend specific APIs.

I would propose the ability to set a flag, or use a subclass on a class based consumer to keep it around for the duration of the web socket. That way a few use case specific endpoints can tie up an entire worker, without hogging workers where this functionality is not needed. 

Maybe state can be persisted without hogging a worker, by having a in memory cache tying connection IDs to Consumer instances. If this were possible, consumers would still only be tied to a worker while they are being used.

Even in a multi-process, multi-machine architecture, it seems like this should be doable since a web socket does not jump between machines. It might require changes to Daphne. I'm unfamiliar with the internals. 

In addition, this would be beneficial in other cases, where persistence isn't strictly needed. In use cases where a heavy initialization process happens. It would make more sense to run that expensive process once, rather than on every `receive()` call.

I know that the decision to instantiate Consumers on each request was probably a design decision, and one that probably makes sense in most cases. However, I think having the ability to keep complex classes around will be useful to many people. Forcing people to code around it, will only introduce anti-patterns to deal with the issues I've outlined, or cause people to move to other platforms and libraries more suited to object persistence.

**Comment by andrewgodwin** [comment]
This is already the design of Channels 2.0, where we have eliminated the network boundary between Daphne and Django and instead moved to consumers instantiated once per socket connection, so I'm going to close this.

You'll still have to write your code so it can run in a single-threaded asynchronous system, which means no long-running consumer stuff (unless potentially it's written as asyncio-compatible), but it's an improvement over now for the reasons you mention.

The reason it can't be done in Channels 1 is that there's a network boundary between Daphne and Channels/Django and so we can't guarantee the same socket will be serviced by the same machine, so shared memory is not an option. This is why we have to move it in-process to allow it.

**Comment by agronick** [comment]
When do you think Channels 2.0 will be production ready?

**Comment by andrewgodwin** [comment]
I can't give you any sort of timeline as nobody's paid to work on it so it's a spare time project. Somewhere between a few months and a few years?

**Comment by agronick** [comment]
Anything you need help on?
