### ISSUE TITLE
Feature request: Consumer able to know the actual WebSocket subprotocol being used

### ISSUE THREAD

**Issue by yongthecoder** [django/channels#744]
A consumer should be able to know the actual WebSocket subprotocol that is chosen by daphne when accepting a connection.

The "message" passed to WebSocketConsumer.connect includes the "Sec-WebSocket-Protocol" header, but it doesn't say which subprotocol is actually used.

If I haven't missed anything, it seems I can only mimic what Daphne does and find out the subprotocol that may be actually used every time when a consumer method is called. But this is a ugly approach.

Please consider to add this feature. Thanks.

**Comment by andrewgodwin** [comment]
Yes, this should be in there.

**Comment by yongthecoder** [comment]
Thanks. Also I would like to make a small correction: the consumer should be able to know it not only "when accepting a connection" but also when handling messages.

**Comment by andrewgodwin** [comment]
It'll only be in the connect message - if you need it later on it'll need to be persisted like all other headers.

**Comment by yli-cpr** [comment]
So I guess I will need to keep a reply_channel-to-subprotocol map. It should work

**Comment by andrewgodwin** [comment]
No need, in channels 1 you can just use the channel session and in channels 2 (where this will likely end up) you can just store on the `self` of a consumer.

**Comment by yli-cpr** [comment]
Thanks for the hint. I am seeing anything I store in a consumer gets lost. I am using the master branch actually. Will take a look at channel session.

**Comment by andrewgodwin** [comment]
Yes, in the current release consumers are volatile and just vanish, you have to use `channel_session`. It's taking some rearchitecting to fix this hence it not changing till the next major release.

**Comment by yli-cpr** [comment]
Thanks a lot!

**Comment by yongthecoder** [comment]
Another thing is about subprotocol selecting. The server specifies a list of subprotocols that it supports, and daphne chooses the first supported subprotocol in the client request header according to the code. This means the client decides which subprotocol is preferred. Is it possible to allow the server to decide which protocol is preferred?

**Comment by andrewgodwin** [comment]
Maybe, we can probably do this as part of the accept/deny connection phase now.

**Comment by andrewgodwin** [comment]
Channels 2 allows this! You get passed subprotocols in the `scope` and you can respond in the `accept` message with the one you want, so closing.
