### ISSUE TITLE
Updated py files are not refreshing

### ISSUE THREAD

**Issue by kyleabens** [django/channels#751]
Hello,

I apologize ahead of time for being a noob but I'm having issues reloading my updated py files on the server.  Everything has been working great so far but I just can't seem to find an answer for this one.  I had the same issue a while back with gunicorn and `kill -HUP <pid>` seemed to do the trick but I'm not having the same luck with daphne.  I know runserver takes care of this outside of production so I believe it's something simple that I might have to add to my systemd file.  Any help would be greatly appreciated!  Thanks!

My systemd file:
```
[Unit]
Description=Daphne service
Requires=worker_1.service
Requires=worker_2.service
Requires=worker_3.service
After=network.target

[Service]
User=####
Group=www-data
WorkingDirectory=/home/####/####
Environment="PATH=/home/####/####/env/bin"
ExecStart=/home/####/####/env/bin/daphne -b 0.0.0.0 -p 8001 myproject.asgi:channel_layer
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by andrewgodwin** [comment]
There's no autoreloading in Daphne - you have to completely kill and reload the server to reload the python code.
