### ISSUE TITLE
http session leak, which can be used to attack web server

### ISSUE THREAD

**Issue by anhzhi** [django/channels#754]
- OS: Ubuntu 14.04.5 LTS

-  Software versions:
django(1.10.4)
channels (1.1.6)
daphne (1.3.0)
Twisted (16.6.0)
asgi-redis (1.4.2)

- Bug Report：
the example project can be easyly derived from https://github.com/andrewgodwin/channels-examples.git
I choose  django.contrib.sessions.backends.file as the SESSION_ENGINE of this project.
```
SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_FILE_PATH = tempfile.gettempdir()
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

SESSION_COOKIE_NAME = 'liveblog_id'
SESSION_COOKIE_AGE = 60 * 60 * 24
SESSION_COOKIE_DOMAIN = ''  # 生产环境中修改
```
I added channel_and_http_session to the channel consumers. the code is like:
```
@channel_and_http_session
def connect_blog(message, slug):
    pass
```

When I open and close a new websocket from the browser, session file leaking occurs:
```
root@web-master:/tmp# ll liveblog* -lrt|wc -l   
9
```
```
ws=new WebSocket('ws://192.168.10.40:33333/liveblog/wodeliaotianshi/stream/')
ws.close()
```

```
root@web-master:/tmp# ll liveblog* -lrt|wc -l   
10
```

**Comment by anhzhi** [comment]
Unlike http session control in django:
```
auth.logout(request)
```
```
request.session.flush()         # the session file will be cleaned.
```

Even I manually call the session flush method  in an Explicit way:
```
# toDO: 清理session
def disconnect(self, message, **kwargs):
     message.channel_session.flush()
```
It won't help.

**Comment by proofit404** [comment]
You're cleaning reply channel session. It's different from HTTP session because it related to the WebSocket connection. You can try to flush HTTP session in the connect consumer. It is the only place where it's available.

**Comment by anhzhi** [comment]
@proofit404   
I already tried,  but failed

Even I manually call the session flush method  in an Explicit way:
```
# Consumer class

# toDO: 清理session
def disconnect(self, message, **kwargs):
     message.channel_session.flush()
```
It won't help.

**Comment by proofit404** [comment]
Try to use `message.http_session`.

**Comment by anhzhi** [comment]
@proofit404   failed again
My code is like as below: 
```
@channel_and_http_session_user_from_http
def connect_blog(message, slug):
    print message.user


@channel_and_http_session_user_from_http
def disconnect_blog(message, slug):
       # some code
      if message.http_session:
          message.http_session.flush()
      if message.channel_session:
          message.channel_session.flush()
```
The client test code like:
```
ws1=new WebSocket('ws://192.168.10.40:33333/liveblog/wodeliaotianshi/stream/')
ws2=new WebSocket('ws://192.168.10.40:33333/liveblog/wodeliaotianshi/stream/')
ws3=new WebSocket('ws://192.168.10.40:33333/liveblog/wodeliaotianshi/stream/')

ws1.close()
ws2.close()
ws3.close()
```
session file still leak

Besides, as a side effect,  removing the http session file will **force** those logged-in user offline.

**Comment by proofit404** [comment]
As I mention before http session is available only in the connect consumer during protocol negotiation.

**Comment by anhzhi** [comment]
So it is a bug?
I  added some logs,  and found that message.channel_session.flush do remove the session file, but another ssion file was created soon.

**Comment by proofit404** [comment]
Under which condition s this file is created "soon"?

**Comment by andrewgodwin** [comment]
It's not possible to flush channel sessions from inside a consumer - they will be removed by the session backends's cleanup mechanism once they're expired.
