### ISSUE TITLE
[Question] Is there a way to remove a message.reply_channel from all Groups?

### ISSUE THREAD

**Issue by japrogramer** [django/channels#758]
Hello Im trying to define what websocet.disconnect channel should do for a particular path,
and what I want to do is remove it from all Groups. But without adding a list of groups to the session I don't know how that would be done. And was wondering if there is already an implementation of this?

**Comment by andrewgodwin** [comment]
No, there is no way to know what groups a channel is in - it's your job to work out what and remove them (adding the ability to know what groups a channel is in would slow everything down). You can also just leave the channels subscribed to a group and they'll be cleaned up after 24 hours, but every channel you leave slows down group sends a little.
