### ISSUE TITLE
[Docs]: bug in tutorial code, the message sent to separate channels doesn't contain `path` key-value

### ISSUE THREAD

**Issue by explosic4** [django/channels#759]
According to issue #628, the message sent to customized/separate channels must have a `path` key-value.

However, the code example in the [docs](https://channels.readthedocs.io/en/latest/getting-started.html#models) is below and does not contain the `path` key.

```py
# Connected to websocket.receive
@channel_session
def ws_message(message):
    # Stick the message onto the processing queue
    Channel("chat-messages").send({
        "room": message.channel_session['room'],
        "message": message['text'],
    })
```

This leads to the error below:

```
ERROR - worker - Could not find match for message on chat-messages! Check your routing.
```

After adding the `path` key-value into the message content, the error is fixed.

```py
# Connected to websocket.receive
@channel_session
def ws_message(message):
    # Stick the message onto the processing queue
    Channel("chat-messages").send({
        "room": message.channel_session['room'],
        "message": message['text'],
        "path": message['path'],
    })
```

This needs to be fixed in the documents. And a brief explanation of how `path` key affects the message sending mechanism would be appreciated.

**Comment by andrewgodwin** [comment]
That issue says you need to include a `path` value if you're routing on it - you don't need it all the time. If you just route by channel name and not path (as the docs do) you don't need a path key.

**Comment by explosic4** [comment]
well, if I just copy the code example from the doc and run it, I will get the error message:
```
- ERROR - worker - Could not find match for message on chat-messages! Check your routing.
```
until I add the `path` to the message.

**Comment by explosic4** [comment]
It makes sense that you don't need a `path` value if you are not routing on it. I just wonder what's wrong with the code example, and why I'm getting the error.

**Comment by explosic4** [comment]
Sorry, I made the mistake. I include the `channel_routing` in the main routing, and I set a path for `channel_routing` there, that's the reason for the error.
