### ISSUE TITLE
 *106 recv() failed (104: Connection reset by peer) while proxying upgraded connection

### ISSUE THREAD

**Issue by jordan200k** [django/channels#761]
For my chat on django 1.11, I use django-channels, duphne, nginx and nginx to fill in the log with this error. Because of this I can not keep track of who has the socket open.

duphne start command: daphne -b 0.0.0.0 -p 8001 .asgi:channel_layer

help me to fix this please

`
server {
listen 80;
server_name <server_name>;

access_log /path/to/log/access-nginx.log;
error_log /path/to/log/error-nginx.log;
client_max_body_size 20M;

location / {
       proxy_pass http://0.0.0.0:8001;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_redirect     off;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;

}

location /static {
     root /static/path;
}

location /media {
     root /media/path;
}
}
`

**Comment by andrewgodwin** [comment]
I can't help with nginx configuration I'm afraid, or I'd have no time to work on the actual project - sorry! You should try looking around for nginx websocket help, there's lots of things to be careful about.
