### ISSUE TITLE
Does the npm package work serverside? I'm getting a window does not exist error.

### ISSUE THREAD

**Issue by palewire** [django/channels#762]
Following the instructions I drafted a very simple NodeJS client for my channels service. 

```
const channels = require("django-channels");
const webSocketBridge = new channels.WebSocketBridge();
const path = "wss://mydomain.com/stream/";
webSocketBridge.connect(path);
webSocketBridge.listen();
```

Running that with node on the terminal yielded this error.

```
$ nodejs test.js
/home/palewire/Code/orchestral-motion.github.io/node_modules/django-channels/lib/index.js:63
      var scheme = window.location.protocol === 'https:' ? 'wss' : 'ws';
                   ^

ReferenceError: window is not defined
    at WebSocketBridge.connect (/home/palewire/Code/orchestral-motion.github.io/node_modules/django-channels/lib/index.js:63:20)
    at Object.<anonymous> (/home/palewire/Code/orchestral-motion.github.io/test.js:25:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

The exact same JS code works perfectly when run in a browser. What's up? I don't understand.

**Comment by andrewgodwin** [comment]
That code is only for use in a browser, it doesn't run without a `window` object. You'll have to use a server-side client library for WebSockets instead.

**Comment by palewire** [comment]
Thanks for the tip. I don't know if it's worth including in your proper documentation, but I was able to ultimately achieve my goal by using the lower level ``ws`` node package instead.

The code I used that worked is available [here on Github](https://github.com/orchestral-motion/orchestral-motion.github.io/blob/master/test.js) for anyone who comes across this ticket in the future.

I'd also like to report that once I got my head screwed on, I was able to develop and deploy a working websockets server to Heroku using channels in less than day at the Los Angeles Philharmonic's hackathon. Using that ``ws`` trick we had a wearable device on a musician's wrist blasting data into the Django server which instantaneously passed it along to a web visualization on multiple devices.

You can watch a video of it in action [here](https://www.youtube.com/watch?v=fLHSwvhsp7M) and the entire working application with Heroku config is [here](https://github.com/orchestral-motion/django-orchestral-motion-db).

For anyone else setting out on a similar path, I'd recommend JKM's [excellent Heroku walkthrough](https://blog.heroku.com/in_deep_with_django_channels_the_future_of_real_time_apps_in_django).
