### ISSUE TITLE
Sending messages to channel

### ISSUE THREAD

**Issue by Necrobsd** [django/channels#766]
Hello! 
When server receives new connection in websocket.connect method it should run some python script and send messages from this script to established channel
Is it possible?

**Comment by andrewgodwin** [comment]
Just send messages to that channel from a consumer that runs against the connect channel - there's nothing special Channels would need to do for this.

**Comment by Necrobsd** [comment]
Hello Andrew!
I don't understand how.
Please give me a link to manual how send messages to channel while script
is running


2017-10-19 15:00 GMT+10:00 Andrew Godwin <notifications@github.com>:
