### ISSUE TITLE
[Question] When do channel_sessions expire?

### ISSUE THREAD

**Issue by AgCouper** [django/channels#768]
Hello,
I'm new to the Django/Channels development, so there is one thing for which I couldn't find the  answer in the source code: when a DB record for websocket's channel_session gets removed from the DB?
My expectations were that it gets removed after the corresponding websocket connection has been closed, but it doesn't seem to be the case. So, now I'm worried whether I should take additional measures to prevent session records from polluting the DB.

**Comment by andrewgodwin** [comment]
It follows the same rules as normal session backends, so whatever that is set to (and for non-auto-expiring backends like database, you need to run Django's session-cleaning command every so often, `clearsessions`).

**Comment by AgCouper** [comment]
I see... Thanks for the answer!
