### ISSUE TITLE
how to stop running script when costumer disconnected?

### ISSUE THREAD

**Issue by Necrobsd** [django/channels#770]
Hi,

I'm trying to find the way to do the following thing:

When I get websocket connects from client, I want to run the script that sends requests to some URL with client params and sends back to this client the recieved and processed data. 
And the most important: when websocket disconnects, I need to stop script if it is still in progress
What is the best way to do this?

**Comment by andrewgodwin** [comment]
With the current release of channels, you'd need to write a custom server process that did that sort of async fetch and which could be cancelled (in short, it's hard). The upcoming Channels 2 stuff would let you write the async part much easier, but it's not ready.
