### ISSUE TITLE
AWS and Django Channels

### ISSUE THREAD

**Issue by oularrea** [django/channels#773]
Does anyone know how I can publish an application with django-channel in Amazon Web Service on an EC2 instance, I have an EC2 instance where I have the redis server locally on the instance, when the forntend tries to connect to ws it returns me 404, can i solve this?

Thank you very much for the help you can give me

**Comment by EugeneBad** [comment]
Django-channels is platform agnostic; you just have to ensure that the
webserver your frontend is trying to connect to accepts websocket
connections. Nginx is a great choice for this and works seamlessly with
channels.

**Comment by andrewgodwin** [comment]
Yes, I'm afraid we can't do general deployment support here, or we'd spend forever helping everyone. I'd recommend looking up tutorials for deploying WebSockets on AWS in general - there can be some weird network interactions - or finding an experienced person to help.
