### ISSUE TITLE
Installing channels through pip delivers v0.7

### ISSUE THREAD

**Issue by pranjulps3** [django/channels#774]
On installing django-channels via `pip`, it gives version 0.7 instead of the latest stable one.
I checked for available versions but only 0.* ones are available to install. 
At first when I installed it I found that channels was unable to take control of `runserver` command and searched for the solutions for this. It took me a while to realize that the version I am using is 0.7 and so I had to install it from your git repository.
It is inconvenient and time consuming to find the issue.
Please look into this.

**Comment by andrewgodwin** [comment]
Please note that the `django-channels` package on PyPI is a different project - you want to install the `channels` package. My apologies for this, the other project was first and I didn't realise the clash until too late.
