### ISSUE TITLE
daphne not talking to workers if one blocks process

### ISSUE THREAD

**Issue by dszmaj** [django/channels#776]
> red hat, 
> oracle, 
> Django~=1.11.0, 
> channels>=1.1.3,<1.2, 
> asgi-redis>=1.4.0,<1.5, 
> twisted[http2,tls]>=17.5.0,<17.6

We have issue with very long db queries so we spawned like 20 workers to account for that a little at least for testing so when one process blocks worker, the other one could pick up and respond, but it seems like when one worker blocks for a long time the whole application just rejects websockets and not return anything. Could anyone at least point me where to look for a solution?

We run it with nginx as a reverse proxy to daphne handling all traffic except of static files. Daphne and workers are run by supervisor.

It's not giving any errors or tracebacks.

**Comment by andrewgodwin** [comment]
You can't block workers in Channels 1, each worker only has a single thread and you need them to be available. If you want to do long-running things you need to spin them off yourself.

**Comment by dszmaj** [comment]
What do you mean by spinning them off myself? I'm talking about long running db queries in consumers. If I encounter such scenario it blocks the worker until db query returns and worker can consume another message in the queue. What would you suggest in such scenario where for example 500 users hits the site in 1 hour. Right now we have 20 workers and it seems intuitive to raise the number to even 100 workers but that would mean that django-channels scale very badly as it would require lots of RAM for idle workers. Is this even possible to work around this without celery or smth? Could you suggest how to take on this problem or where to look for advice?

**Comment by andrewgodwin** [comment]
What I'm saying is that django-channels right now solves the problem of handling many idle sockets simultaneously; it does not solve Django's problem with long-running queries not being parallelisable, and so if you rely on long-running queries you need to do your own work to ensure that each query does not take up an entire thread/process.

Trying to scale the number of workers to fix that is just as pointless as trying to scale the number of WSGI server processes; neither is going to run your _database queries_ asynchronously. That's something I hope to have better support for in Channels 2 but even then it'll need a lot of manual work and direct use of asynchronous database APIs.
