### ISSUE TITLE
default routes should be configurable

### ISSUE THREAD

**Issue by makslevental** [django/channels#777]
haven't looked to closely but users should be able to choose not use the default routes and/or the default channels (i.e. workers shouldn't listen nor should routes exist)

https://github.com/django/channels/blob/98c1a844cf762d9f06332216d3118491fdda4b56/channels/routing.py#L46

use case: i'm using channels for background tasks right now (not websockets).

ideally i would be able to set this in config.py as opposed to as an arg to runserver (which is not how i run my django project).

**Comment by shulcsm** [comment]
Regarding same issue, could i get clarification regarding routes and correlation with runserver actually listening to something? Like what --only-channel exactly does? Worker class seems to be getting whole layer + filters?

**Comment by andrewgodwin** [comment]
If you want to override the default route just define your own catchall pattern as the last route, that will then override the defaults. As for `--only-channel`, it affects what channel names the worker will listen to.
