### ISSUE TITLE
Error "Message object has no attribute user" on JsonWebsocketConsumer get_handler

### ISSUE THREAD

**Issue by gabrielfgularte** [django/channels#778]
- Running on Docker and Firefox Develper Edition
- Channels 1.1.8, Daphne 1.3.0, Django 1.11.4, Twisted 17.9.0 and asgi_redis
- When decorating the `get_handler` method from the `JsonWebsocketConsumer` with the `login_required` (or any other custom method that requires for the `user` on `message` obj), it fires the error `'Message' object has no attribute 'user'`.
- Docker with Proxy Nginx and Daphne.
- Traceback:
```
2017-11-01 12:20:40,006 - ERROR - worker - Error processing message with consumer lobbies.consumers.LobbyRooms:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 119, in run
    consumer(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/generic/base.py", line 32, in __init__
    self.dispatch(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels/generic/base.py", line 70, in dispatch
    return self.get_handler(message, **kwargs)(message, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    if test_func(request.user):
AttributeError: 'Message' object has no attribute 'user'
```

**Comment by andrewgodwin** [comment]
You probably haven't set `user = True` on the class body.

**Comment by gabrielfgularte** [comment]
I've set `channel_session_user = True` and `http_user = True`.

**Comment by andrewgodwin** [comment]
Oh, you're trying to use login_required - Django decorators are not compatible with Channels views and messages, you'll have to do your own checking.

**Comment by gabrielfgularte** [comment]
@andrewgodwin Alright, so that's what I meant by "or any other custom method that requires for the user on message obj" on the issue description.

This part of the doc: https://channels.readthedocs.io/en/stable/generics.html#applying-decorators is not working either with a Django builtin decorator or a custom one.

**Comment by andrewgodwin** [comment]
Yes, the doc is somewhat deceiving in that it means custom-written decorators that act on `message`. `message.user` isn't added until you are inside the class.

This is all changing drastically pretty soon with Channels 2, so where I would normally promise that I'd update the docs and the code to make it clearer, in this case I will say that I'll try to make the brand new docs incorporate this when I write them.

**Comment by andrewgodwin** [comment]
Giving deadlines for volunteer projects is something I learned not to do, alas. It'll be ready... when it's ready.

**Comment by gabrielfgularte** [comment]
Wisely words...
