### ISSUE TITLE
Support sending immediately when multiplexing

### ISSUE THREAD

**Issue by richtier** [django/channels#779]
Multiplexer send does not support sending the message immediately.

To immediately send the message when not multiplexing:

```
self.reply_channel.send(content, immediately=True)
```

but [WebsocketMultiplexer.send](https://github.com/django/channels/blob/master/channels/generic/websockets.py#L200) does not expect `immediately` in the function signature.

Changing the signature to support the same arguments as [Channel.send](https://github.com/django/channels/blob/master/channels/channel.py#L32) would be a good feature addition.

If there are no reasons to not do this, I will create a Pull Request.

**Comment by andrewgodwin** [comment]
Multiplexers are currently being entirely reworked (and the no-send-immediately thing is being removed from channels as well), so this will be done as part of that work.

**Comment by richtier** [comment]
I will subclass `WebsocketMultiplexer` for now to allow `send` to receive `immediately`
