### ISSUE TITLE
Permanent login in websockets

### ISSUE THREAD

**Issue by SRLut3t1um** [django/channels#782]
It would be really helpful to be able to login a session with django's default auth system. This is important if I'm only having a websocket connection to django. It's a very basic feature so I think it sould be integrated in channels by default.

So a code example would be:

assume the message-text:

message.content['text'] = {"action": "login", "username":"foo", "password": "bar"}

In channels.py
```
def ws_message(message):
    if message.content['text']["action"] == "login":
        username = message.content['text']["username"]
        password = message.content['text']["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
```
Obv. The text would have bin made a dict earlier.

Best Regards. Tobias.

**Comment by andrewgodwin** [comment]
I'm afraid that without a regular request object Django's auth system is hard to integrate, and there's no plans to do this to this level in the near future - you can, if you want, use some of the lower-level code in Django and the `http_session` decorator to try to do something similar if you want.
