### ISSUE TITLE
Worker threads that die are not restarted

### ISSUE THREAD

**Issue by agronick** [django/channels#783]
Im running Channels 1.1.8 Django 1.11.7 Asgi Redis 1.4.3. I'm occasionally getting the following error.
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)

When the worker threads die, they never come back. Eventually the site grinds to a halt. This exception should be caught.

**Comment by agronick** [comment]
Still trying to figure out why the sockets are closing in the first place. I'm using a local socket. This will happen maybe twice an hour with 4 workers with 10 threads each.

**Comment by andrewgodwin** [comment]
Workers are now gone as of channels 2, so closing this ticket (and we added a nice connection pool to the redis stuff, which almost certainly fixed the underlying issue)
