### ISSUE TITLE
For the last couple of days I have been trying to re-start my Django (1.9) app (a blog) locally without much success. It had been working before and I was even able to push it onto Heroku. I am running Python 2.7 in the virtual environment. Now when I try to run python manage.py runserver below is what I get. I have tried Stackoverflow and every other support sites and forums for help without much success. Please Help !! 

### ISSUE THREAD

**Issue by Fulkay** [django/channels#785]
For the last couple of days I have been trying to re-start my Django (1.9) app (a blog) locally without much success. It had been working before and I was even able to push it onto Heroku. I am running Python 2.7 in the virtual environment. Now when I try to run python manage.py runserver below is what I get. I have tried Stackoverflow and every other support sites and forums for help without much success. Please Help !!  

Unhandled exception in thread started by <function wrapper at 0x00000000047110B8>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 472, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
posts.Post.image: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.python.org/pypi/Pillow or run command "pip install Pillow".

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.

System check identified 2 issues (0 silenced).

**Comment by andrewgodwin** [comment]
This is not a general Django support forum - just read the errors that you have been given and do what they say (install Pillow).

**Comment by Fulkay** [comment]
Thank you for the response. I did install Pillow and still keep getting the same error coming up. I am relatively new with Django and in the past I was able to get some help on Stackoverflow and other forums. This time however, I have tried several solutions suggested on some of the site to no avail. Any help would be appreciated
