### ISSUE TITLE
Django server doesn't start

### ISSUE THREAD

**Issue by fakabbir** [django/channels#789]
After creating the Django Project `python manage.py runserver` starts the server, but no output on command line appears (except GET commands). After creating an app and running the server it doesn't produces any output. Also, the server isn't started.

- OS : Windows 10
- Python : 2.7 and 3.6
- Django: 1.11.3

- Console Output: Performing system checks...
Wait time (around 30 minutes)
- Broswer Output: Firefox can’t establish a connection to the server at localhost:8000.

Expected Behavior: 
```
Performing system checks...

System check identified no issues (0 silenced).

You have unapplied migrations; your app may not work properly until they are applied.
Run 'python manage.py migrate' to apply them.

November 16, 2017 - 15:50:53
Django version 1.11, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
and **server starts working**

Current Behavior:
```
Performing system checks...
```
and **server doesn't starts.**

**Comment by emcniece** [comment]
@fakabbir did you ever find a fix?

**Comment by CoriAle** [comment]
How did you fixed it?

**Comment by lagartoJuan148** [comment]
any solution?

**Comment by tiago-peres** [comment]
One solution is to upgrade Django

    pip install django --upgrade

Oftentimes one will get other unrelated issues to solve that are linked with the upgrade but once all all fixed the server should run just fine.

**Comment by MalshaDeZ** [comment]
for me my project was using tensor flow. I was previously using a windows machine but had to run it on a mac M1 chip. After debugging for hours, I found that the problem was with tensor flow. Had to uninstall it to get the project running.
refer [this ](https://github.com/apple/tensorflow_macos).
