### ISSUE TITLE
[channels2] How to define application?

### ISSUE THREAD

**Issue by brianmay** [django/channels#794]
Everything is somewhat interlinked but will try to keep this issue specific to one specific point.

According to the [documentation](http://channels.readthedocs.io/en/2.0/deploying.html), we should define an `asgi.py` file that contains:

```
application = get_default_application()
```

Where `get_default_application()` is a function that looks up the value of ``ASGI_APPLICATION``.

However, the expected value of ``ASGI_APPLICATION`` is not defined. I initially assumed it should be ``app.asgi.application``. However, this means we end up with a loop and no actual definition of the application.

So instead I put the following in `asgi.py`:

```
application_mapping = {                                                         
    'websocket': Demultiplexer,                                                 
}                                                                               
application = ProtocolTypeRouter(application_mapping=application_mapping)
```

Which works (well apart from the fact Demultiplexer needs more work - something I have been working on). Just wondering what you had in mind, however.

**Comment by andrewgodwin** [comment]
The docs aren't finished, this will be in there when I move over to channels after Daphne is done this week. `ASGI_APPLICATION` should just be the top-level router object, so `project.routing.application`.

**Comment by brianmay** [comment]
Ok, that makes better sense than my solution. Thanks.
