### ISSUE TITLE
[channels2] Consumer receive function

### ISSUE THREAD

**Issue by brianmay** [django/channels#795]
In attempting to get multiplexed websockets working (I believe I have it "almost working" :-) ), I noticed the following problem:

```
  File "/Users/brianmay/tree/myro/channels/channels/generic/websockets.py", line 40, in websocket_receive
    self.receive(text=message['text'])
  receive() missing 1 required positional argument: 'content'
```

In `WebsocketConsumer` we define receive as:

```
    def receive(self, text=None, bytes=None):                                    
```

(the use of the name bytes is unfortunate :-( - we replace the built-in Python type)

The problem being when override `WebsocketConsumer` with `JsonWebsocketConsumer` we also change the parameters:

```
    def receive(self, content, **kwargs):
```

The function call doesn't provide the required content parameter.

As it is, I think we need two functions, one that takes text/bytes, and the other one takes the JSON content.

Maybe the ``raw_receive()`` function was somehow intended to fix this?

**Comment by andrewgodwin** [comment]
The idea of `raw_receive` was that you could override `receive` and not have to re-implement other stuff, but I think we could do with some reworking around this stuff. I might say call the second one `receive_json`, and probably now is the time to not call it `bytes` too.

**Comment by brianmay** [comment]
Any suggested alternatives to `bytes`? I am hopeless at naming things :-(

**Comment by andrewgodwin** [comment]
Well the underlying websocket concept is called a `binary frame`, but I didn't want to call it `binary` as that is perhaps even more misleading. Maybe `bytestring`? `byte_data` and `text_data`?

**Comment by brianmay** [comment]
`byte_data` and `text_data` seem fine to me.

**Comment by andrewgodwin** [comment]
Maybe even `bytes_data`. That seems to flow better somehow.

**Comment by brianmay** [comment]
Yes, agreed.
