### ISSUE TITLE
ping packets and heartbeat

### ISSUE THREAD

**Issue by Littlebus** [django/channels#800]
I'm building a websocket server using django&channels, and I am confused about something about heartbeat. 
I find that If the client stops responding to ping packets, the connection will be closed after several seconds when I turn off the wifi on websocket client device. 
I wonder if it's reliable that ping packets can handle all unexpected problems as heartbeat does?

And if there's an easy way implementing heartbeat?

**Comment by andrewgodwin** [comment]
Ping is a built-in part of the WebSocket protocol, most browsers, and Daphne, the Channels websocket server. It's enough for transport-level closure detection on both sides (you can adjust Daphne's ping frequency and timeouts for faster disconnects if you like), but not quite as full-featured as a heartbeat, which can detect things like your application code (javascript or python) going nonresponsive, for example.

The easiest way to implement heartbeat is having the client javascript send a message every X seconds and just reply to that from a consumer.

**Comment by Littlebus** [comment]
If I should set a timer to close the connection if a client doesn't send message for a long time? I can't find a way to set timer and stop it in time.

**Comment by andrewgodwin** [comment]
You can't "set timers" in Channels 1 like that as no code runs continuously, You could try using the `channels.delay` delay server, though it might be easier to use the `reply_channel` as a key into a database that tracks the last ping and then just check that every so often with a management command on a cron or similar.

Channels 2 will make this a lot easier as you'll be able to spin up a background loop with `while True: ... asyncio.sleep()` in it and do your own timers.

**Comment by Littlebus** [comment]
Thank you very much!
