### ISSUE TITLE
Group.send don't work in management command

### ISSUE THREAD

**Issue by GoshanFloyd** [django/channels#801]
Hello, i create custom management command "notify_tasks" and in there i try send message in my Group.
This is my code:

`    from django.core.management.base import BaseCommand, CommandError
    import datetime
    from tasks.models import Task
    import json
    from channels import Group, Channel

    class Command(BaseCommand):
    def add_arguments(self, parser):

        pass

    def handle(self, *args, **options):
        print ('Hello')

        Group("notify").send({
            "text": json.dumps({
                "type": 'task',
                "id": 'doer_id',
                "task_id": False,
                "content": False
            })
        },immediately=True)`

Command work, but i don't reseive data in my frontend code.
Would you help me?

**Comment by proofit404** [comment]
What channel layer do you use?

**Comment by GoshanFloyd** [comment]
I user standard settings from official site:
`CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "myproject.routing.channel_routing",
    },
}`

**Comment by proofit404** [comment]
In memory channel layer doesn't have any persistence mechanism. It works inside one process. Management command and runserver command can't communicate with it. I suggest you to switch to redis layer.
