### ISSUE TITLE
[channels2] [HttpResponseRedirect/HttpResponseNotFound] object has no attribute 'body'

### ISSUE THREAD

**Issue by osown** [django/channels#802]
Hi,
every page I try to load fails with $exception object has no attribute 'body'

My system:
OS: Linux vm 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Python 3; Firefox 57.0

Channels: (66bc298)
Daphne: (26fa870)
asgiref (3abaaed)
Django: (2.0)
Twisted: (17.9.0)

Started channels through runserver. Without channels the access to "/admin" works with channels enabled not.
https://pastebin.com/j2kU4C9P

When accessing just"/" there is also no page displayed. The browser is waiting for a reply. Normally there should be an error page.
https://pastebin.com/LuLtGxaq

**Comment by andrewgodwin** [comment]
Channels 2 is not even in a beta stage yet so this should be expected. I will be looking at it over the next couple of weeks and I can assure you that loading HTTP pages will be fixed before a beta phase.

**Comment by andrewgodwin** [comment]
(also, I just fixed this in 156b9f2 since it was an easy one)
