### ISSUE TITLE
Sending messages from async coroutine

### ISSUE THREAD

**Issue by emakarov** [django/channels#806]
Hello

I'm using channels as a tool to transmit messages from server which calculates some events in async style to the web interface.
Event generation is done in asyncio-based coroutine. And I send messages (`Group('channel_name').send`) with `immediately=True` inside `asyncio`'s `loop.run_in_executor`.

I'm using Redis as a backend

I'm experiencing following behaviour (in runserver mode)

1. Refreshing the browser, websocket is connected.
2. Starting the asyncio-based coroutine to generate events.
3. Browser is not receiving messages
4. Coroutine is continuing to generate events.
5. I'm refreshing the page (browser), and start receiving messages into browser

This looks strange to me and as a bug

Details: python3.6, (virtualenv) on Mac OS 10.13.1 (17B1003) High Sierra

Django==2.0, channels==1.1.8

**Comment by andrewgodwin** [comment]
I agree that's a bug, but without full steps to reproduce and code, or multiple reports, I won't have time to investigate it further at the moment I'm afraid.

**Comment by emakarov** [comment]
I will try to arrange a minimal configuration where this bug is reproduced

**Comment by emakarov** [comment]
closing issue. this wasn't channel's bug

but rather it was caused by redis's `flushall` command.
I didn't take into account that channels is keeping all references to subscribers in redis
