### ISSUE TITLE
Daphne command not found while channels is successfully installed

### ISSUE THREAD

**Issue by RealLau** [django/channels#811]
![image](https://user-images.githubusercontent.com/16678624/34287750-39046630-e724-11e7-99c7-69dfd905d914.png)
I have channles successfully installed, but, I can not run daphne command:
![image](https://user-images.githubusercontent.com/16678624/34287776-5464a0d4-e724-11e7-942f-35c2851ce33b.png)
can someone help me out?
I use python3.6 and Django2.0 on CentOS 7

**Comment by proofit404** [comment]
Please, ensure your `PATH` environment variable has a directory in it, where pip installs package entry points.

**Comment by RealLau** [comment]
My bad Thanks @proofit404

**Comment by tmazai** [comment]
How do I access the PATH directory?
