### ISSUE TITLE
question about consumer

### ISSUE THREAD

**Issue by AntiverX** [django/channels#812]
in my consumer , I write serveral reply_channel.send

![image](https://user-images.githubusercontent.com/22369960/34346891-ab0e1440-ea37-11e7-946c-0d862dfe72d3.png)

And I found that the comsumer did not send these three replies unitl the last message.reply_channel.send is executed.

What can I do to make it send reply immediately when each reply_channel.send is ececuted?

I did this because I have a program generating output at a random interval . If I use the code above , the webpage will wait unitl the full result arrives and it's quite unfriendlly for users.

Thanks!

**Comment by proofit404** [comment]
Hi 

You can pass immediate=True to the send argument.

**Comment by multimulti** [comment]
`immediate=True` is apparently no longer available in 2.0.2. Is there another solution?

**Comment by andrewgodwin** [comment]
All sends are immediate in Channels 2.

**Comment by multimulti** [comment]
Ah, that's good to know. By the way, thanks for all your work here!

**Comment by DajKatal-v2** [comment]
Nope, they are not immediate. Atleast for me.

They all get sent at the last second, not one at a time.
