### ISSUE TITLE
handle client reconnection

### ISSUE THREAD

**Issue by pgrandinetti** [django/channels#818]
Is it possible to handle the case when the client send a message through a channel, then disconnects while waiting for the reply, and then reconnects again hoping to find the message anyway? If possible at all, I am guessing some custom consumer is needed (maybe in the`websocket.disconnet` method), but I can't figure out how.
Use case: client asks for some operation that takes several seconds, meanwhile some network problem causes momentarily disconnection

**Comment by andrewgodwin** [comment]
I'm afraid not - nothing in Channels has a queuing system that would last over reconnect. You'll need to manage it yourself using a database table or similar persistent store.

**Comment by arnav13081994** [comment]
This may be a stupid question but can this be handled with Django-channels-presence library?
