### ISSUE TITLE
Remove an empty Group

### ISSUE THREAD

**Issue by olasfar** [django/channels#820]
Hey guys,

I just started using channels, and it looks great! You guys are doing a wonderful job :)
I do have some questions on how should I architecture my app using channels, any help answering them will be much appreciated.

* Could we have one user (or multiple users having the same username / id) per group? Do you see any inconvenience?
* What if the group is empty, will the code remove it automatically? Should I remove it manually?
* Is there a difference in terms of performance between sending 1 message to 1 group of N users and sending 1 message to N groups (1 user per group).
* Could we monitor the # of connected users / # of channels per group?

Please advice. Thx.

**Comment by andrewgodwin** [comment]
* Groups for each user is what I would recommend for sending to users, to be honest, as users might habe many tabs open.
* Empty groups are removed automatically.
* There is currently no performance difference, but sending one message to a group of N will be optimised in future to be much faster.
* In channels 1 you can get the number of connected users, but it's slow; in channels 2 you cannot get it at all and we will recommend you track online state elsewhere.
