### ISSUE TITLE
'AsgiRequest' object has no attribute 'session'

### ISSUE THREAD

**Issue by dragneel12** [django/channels#821]
![screenshot from 2018-01-11 13-02-31](https://user-images.githubusercontent.com/25398284/34813356-b1ccf40a-f6cf-11e7-8829-79954b806dea.png)
![screenshot from 2018-01-11 12-59-18](https://user-images.githubusercontent.com/25398284/34813328-91a04312-f6cf-11e7-8ca7-c31d15ebe300.png)

**Comment by andrewgodwin** [comment]
Looks like your `SessionMiddleware` isn't installed/working. I don't think this is a Channels bug; if you think it is, I need to see full steps to replicate on this.

**Comment by dragneel12** [comment]
@andrewgodwin you are right, not the channel bug.
changed MIDDLEWARE_CLASSES to MIDDLEWARE(introduced in django 1.10) in settings.py.No error now.Thanks.
