### ISSUE TITLE
Is it possible to use django-channels on a windows machine??

### ISSUE THREAD

**Issue by mizamae** [django/channels#822]
Hello,

Firstly I would like to thank the great work of the 'channels' people, it allows impressive web user experience.

I am using channels on a django project that runs on a raspberry. There, I have everything working fine, but for development and debug I use a Windows laptop with Eclipse. In this laptop, I have not been able to make it work so I have to comment out everything regarding channels which makes it very difficult to reproduce everything.

I wonder if there is a possibility to make it work on the windows machine... I couldn't find any guide nor procedure...

Kind regards and thanks!!

**Comment by andrewgodwin** [comment]
I develop Channels on Windows so I can guarantee you it does work; Python on Windows is just a bit harder to get running. I can't help you individually, but there's lots of guides out there on getting Python and Windows working that should apply to channels.
