### ISSUE TITLE
HTTP header not flushed until http.response.body sent

### ISSUE THREAD

**Issue by jkarneges** [django/channels#826]
Hi,

I noticed that sending `http.response.start` does not send anything to the client right away. Once the first `http.response.body` event is sent, then the earlier header will be sent to the client along with the body. It's sometimes nice to be able to send just the headers without content, as a way of telling the client that the stream opened successfully even if there isn't any content to send yet.

It's possible to work around this by sending `http.response.body` with an empty body in order to force a flush, but it feels weird to need to do that.

**Comment by andrewgodwin** [comment]
Hmm, this must be an artifact of the Twisted HTTP library, as the code sets the headers as soon as you send `response.start`. I suspect this is a side-effect of it being built to support WSGI, which explicitly specifies that you must not send headers until the first body chunk arrives.

Not sure how to solve this one really. I suspect the WSGI people had a good reason for doing this, so I might just line up the ASGI-WWW spec to match.

**Comment by andrewgodwin** [comment]
Added to the spec as desired behaviour in https://github.com/django/asgiref/commit/6cdeff123b55f80ba64e953d2de2028087563a27

**Comment by jkarneges** [comment]
It occurs to me that waiting for a body message allows the ASGI server to send more efficiently to the client, i.e. by writing the header and body in one shot.

As long as the Django app can flush the header by writing a zero-length first body chunk, then this seems fine to me.

**Comment by andrewgodwin** [comment]
Right. Reading through the WSGI spec again it also allows the server to send an error later on in the process if it never gets any body, which seems like another valid reason, so I see no point not to stick with the current standard on this one.
