### ISSUE TITLE
get valid reply_channel name from django channels

### ISSUE THREAD

**Issue by page1990** [django/channels#830]
I can get the reply_channel name by using `message.reply_channel`. And the using `Channel(reply_channel_name).send()` method. However, I found that the reply_channel name can be any of the text like 'a_very_casual_name'. The `Channel().send()` method won't raise any exception.
What I want is get all the valid reply_channel name in django channels. Is there any way?

**Comment by proofit404** [comment]
Hi,

If you send something to the nonexisting channel, it will be created.

You can refer to the ASGI spec to know more about valid channel names.
