### ISSUE TITLE
ChannelLiveServerTestCase: MySQL server has gone away

### ISSUE THREAD

**Issue by davidfstr** [django/channels#832]
It appears that in test cases inheriting from ChannelLiveServerTestCase, performing an HTTP request against the Django test server somehow invalidates the database connection such that subsequent model accesses raise a "MySQL server has gone away" error.

Here is a minimal repro, using Selenium to perform the HTTP request:

```
from channels.test import ChannelLiveServerTestCase
from django.contrib.auth.models import User
from selenium import webdriver

class ChannelSmokeTests(ChannelLiveServerTestCase):
    def test_can_access_database(self):
        # Create user
        User(username='channel_test').save()  # ok
        
        # Probe user
        User.objects.get(username='channel_test')  # ok
        
        # Perform HTTP request
        webdriver.Firefox().get(self.live_server_url)  # ok
        
        # Probe user
        # Fails with: django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
        User.objects.get(username='channel_test')  # ERROR
```

I ran the above test with:

```
python3 manage.py test myapp.tests.ChannelSmokeTests.test_can_access_database
```

My environment:

* Channels 1.1.6
* Django 1.8.17
* Python 3.4.4
* MySQL 5.6.34
* OS X 10.12.6 (Sierra)

Is this a known issue?

**Comment by andrewgodwin** [comment]
This is a standard Django error when you did not close a database connection properly or you waited too long between calls, unfortunately, I don't think it's something we can address specifically in the channels test case. How long is the gap between the query that works and the one that fails in seconds?

**Comment by davidfstr** [comment]
2.96 seconds +/- 0.2s

**Comment by proofit404** [comment]
Hi,

If you wrap your example into a repository which will reproduce this error easily, I'll look at it.

**Comment by davidfstr** [comment]
Hi @proofit404 , thanks for offering to take a look. I'll put a repository together with the repro on Wednesday or Thursday this week. A few other items have come up at work that I must attend to first.

**Comment by andrewgodwin** [comment]
Channels2 introduces a brand new structure of `ChannelsLiveServerTestCase` that should eliminate this problem as there's no longer separate processes, so I'm going to close this unless we can repro the problem on the new system (sorry about how aggressive that seems, but I only want open tickets we can actively work on)
