### ISSUE TITLE
Ajax long-poll example

### ISSUE THREAD

**Issue by xvdy** [django/channels#833]
I'm trying to implement HTTP long polling for a web request, but can't seem to find a suitable example in the Channels documentation, everything is about Web Sockets.

What I need to do when consuming the HTTP message is either:

wait for a message on a Group that will be sent when a certain model is saved (using signals probably)
wait for a timeout, if no message is received
and then return something to the client.

Right now I have the code that can be seen in the examples:

```
def http_consumer(message):
    # Make standard HTTP response - access ASGI path attribute directly
    response = HttpResponse("Hello world! You asked for %s" % message.content['path'])
    # Encode that response into message format (ASGI)
    for chunk in AsgiHandler.encode_response(response):
        message.reply_channel.send(chunk)
```

So I have to return something in this http_consumer that will indicate that I have nothing to send, for now, but I can't block here. Maybe I can just not return anything? And then I have to catch the new message on a specific Group, or reach the timeout, and send the response to the client.

**Comment by andrewgodwin** [comment]
It's pretty hard to block for long polling in Channels 1 - you need to raise `ResponseLater` and then have a separate task manually send things to the right `reply_channel` externally, which is a massive pain.

In Channels 2, you could just use an `AsyncConsumer` and `await`  instead, so it's probably easier to wait for that to be released or use it now in its beta state.
