### ISSUE TITLE
channels 2.0 (django 2.0) runserver does not serve static files

### ISSUE THREAD

**Issue by richardbann** [django/channels#834]
- Your OS and runtime environment, and browser if applicable:
ubuntu 16.04, inside alpine docker
- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (asgi_ipc or asgi_redis normally)
channels 2.0, django 2.0
- What you expected to happen vs. what actually happened
`runserver` should serve static files if `django.contrib.staticfiles` is in installed apps
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
runserver
- Console logs and full tracebacks of any errors

**Comment by richardbann** [comment]
I have tried putting `channels` below and above `django.contrib.staticfiles` in `INSTALLED APPS`.
I am happy to work on it, just point me to the right direction. The monkey patching does not seem to be the one...

**Comment by andrewgodwin** [comment]
Do you have any other packages installed that might override runserver? Do static files work if you run `manage.py runserver --noasgi`?

**Comment by larsrinn** [comment]
I'm experiencing the same issues here. Running
* Django 2.0.1
* Channels 2
* No further third-party applications installed

Running with the `--noasgi` option, static files are being served.

**Comment by andrewgodwin** [comment]
Oh, my bad, I missed the "channels 2" part and just read "django 2". Yes, the Channels 2 runserver doesn't have the staticfiles handler stuff turned on yet, so this is expected; it's one of the few things left to do before I can do a release (and stop trying to maintain two radically different versions!)

**Comment by andrewgodwin** [comment]
If you want to have them work in the meantime, installing `whitenoise` and its middleware will make everything work again - this is what I had in my dev project that was making everything work for a while.

**Comment by larsrinn** [comment]
Do you have a list of open to dos before you can release a first version apart from the issues here on github? This list here seems to contain mainly issues related to Channels 2 and it is quite confusing to see whether something has already been reported, is a known issue and where help would be needed.

Apparently `MIDDLEWARE` in my `settings.py` is ignored. In the docs I saw you need to use the `AuthMiddlewareStack` to setup the application. Is something similar required to use other middleware as well?

**Comment by andrewgodwin** [comment]
OK, nevermind, I stayed awake a bit longer and fixed this in e124f00972830b2a754b14f4b790f19878318abc.

As for the list of open todos, I need to sit down and work out what that is, which probably means just cleaning out a lot of the old issues and that's going to take a bit of time. I'm pretty sure there's nothing major left to do, so I might just release a 2.0, purge all the 1.x-specific issues, and have the issues actually represent the project again.
