### ISSUE TITLE
channels installation error on windows 

### ISSUE THREAD

**Issue by balaraju1278** [django/channels#835]
Hello,

I am trying to install channels on windows machine,I tried with normal cmd and administrator mode also but it fails 

I am getting this error

 running build_ext
 building 'twisted.test.raiser' extension
 error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual
 C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
 
 Command ""c:\program files (x86)\python36-32\python.exe" -u -c "import setuptool
s, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-build-auug5
rxt\\twisted\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read(
).replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install
 --record C:\Users\ADMINI~1\AppData\Local\Temp\pip-861usvpi-record\install-recor
d.txt --single-version-externally-managed --compile" failed with error code 1 in
 C:\Users\ADMINI~1\AppData\Local\Temp\pip-build-auug5rxt\twisted\

**Comment by proofit404** [comment]
Hi, thanks for giving channels project a try. 

Is there detailed error message instead of bare exit code?

**Comment by larsrinn** [comment]
So for me the installation worked fine on Windows 10 for Channels 1.1.8 as well as for 2.0.

Did you look at your exit code? It tells you **error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools** and even gives you a URL where to get it. Did you try that out?

**Comment by andrewgodwin** [comment]
Given the error message, I'm going to close this.

**Comment by stavlocker** [comment]
This happened to me too on Python 3.5 and @Nabelops is correct. After installing twisted in said way installing channels works fine. Here's a [stackexchange](https://superuser.com/questions/1179925/installing-twisted-on-python-3-5-and-virtualenv-using-pip) question with more details.
