### ISSUE TITLE
Release 1.1.8.1 on PyPi

### ISSUE THREAD

**Issue by Rayman** [django/channels#836]
Hey, can you release version 1.1.8.1 of django channels on PyPi? I think you also forgot to update the version [here](https://github.com/django/channels/blob/11903ad709ef3074f3203495dcf5675652a9d6fa/channels/__init__.py#L1).

**Comment by andrewgodwin** [comment]
There is no version 1.1.8.1 - looks like there was a rogue tag, I'll delete it.
