### ISSUE TITLE
Scale with WebSocket: can routing channel name contain path

### ISSUE THREAD

**Issue by yli-cpr** [django/channels#839]
In many cases, WebSocket is used to track live changes of a system. The module that monitors the internal system is usually done in a single process. In this case, using multiple worker processes doesn't help scaling. However, if routing channel names are like `websocket.<method name>.<path>`, I can run 2 worker processes with different channel name filters. Currently I see it is possible to designate different workers for different protocols: WebSocket, HTTP, etc. If channel name contains path in it, it will allow me to designate different workers to handle different WebSocket paths, and therefore help avoid one of them impacting another too much.

**Comment by yli-cpr** [comment]
An alternative solution I am thinking about is to run another set of daphne + worker.

**Comment by proofit404** [comment]
Hi,

Channel routing name cannot contain the path.

You have two options additionally to those described by you.

1. Run different Daphne instances connected to the different channel layers. For example, two different rabbitmq vhosts or redis databases.

2. Write your own channel layer wrapper to do the routing stuff. See rRedisLocalChannelLayer as example.

Hope this helps.

Regards, Artem.

**Comment by andrewgodwin** [comment]
Additionally, in Channels 2 you _can_ route on WebSocket paths, so this feature request will be satisfied when I release that soon.

**Comment by yli-cpr** [comment]
Thanks guys.
