### ISSUE TITLE
Add Group join/leave functionality to WebsocketConsumer

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#852]
Previously, the WebsocketConsumer classes had a feature where you could have a `group_names` attribute or property, and it would handle the joining and leaving of groups in connect/disconnect for you. This should come back!

**Comment by orn688** [comment]
Hi, I've been using channels quite a bit recently and would love to help out and take a stab at this. Were you thinking of using the same sort of API as in 1.x with a `connection_groups` method? What was the rationale behind using that on top of the `groups` attribute?

**Comment by stunaz** [comment]
Can this be closed as #901 is merged?

**Comment by andrewgodwin** [comment]
Yup!
