### ISSUE TITLE
Daphne server version in setup.py requirements

### ISSUE THREAD

**Issue by kregoslup** [django/channels#864]
Hi,

2 days ago new version of Daphne server came out, 2.0, which is backwards incompatible. 
https://github.com/django/channels/blob/1.1.3/setup.py#L17 Here in setup.py required version of Daphne server (>1.2.0) is incompatible with Channels because it installs version 2.0 which throws:
```
  File "/home/ubuntu/.virtualenvs/virtualenv1/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 5, in <module>
    from daphne.server import Server, build_endpoint_description_strings
ImportError: cannot import name 'build_endpoint_description_strings'
```
Steps to reproduce:
1. Install Channels version 1.1.3 with django on virtualenv, without previous installation of channels
2. Try to run any of the manage.py command

**Comment by andrewgodwin** [comment]
Later releases of Channels in the 1.x series fixed this requirement to a 1.x restriction: https://github.com/django/channels/blob/1.x/setup.py#L17 - so I recommend you upgrade to the latest Channels 1.x release (1.1.8)
