### ISSUE TITLE
I got an except  ChannelFull using Channels 2.0.0

### ISSUE THREAD

**Issue by amulett** [django/channels#866]
Exception Desc
```
    result = await self.awaitable(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/channels_redis/core.py", line 326, in group_send
    except self.ChannelFull:
  'RedisChannelLayer' object has no attribute 'ChannelFull'
```
Setting.py
  `CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}`
I found except just add 2 users means 2 messsage in one time.
and Channels 2.0.0 document is so little,please give me an entire demo or startup.

**Comment by andrewgodwin** [comment]
This was fixed in a new release of `channels_redis` - 2.0.2 - over the weekend.
