### ISSUE TITLE
Allow URLRouter to nest inside itself

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#870]
Right now, URLRouter does not work "as expected" if it's nested inside itself for people used to Django's URL routing and `include()` - it matches the whole URL every time, at every level.

Instead, it should only match on unmatched portions from previous URLRouters (if one is higher in the stack than it), and should combine captured positional/named groups. 

There's an xfailed test in place with desired behaviour: https://github.com/django/channels/blob/08047dddf65f44bf4312e639ad0009bd1ab6f837/tests/test_routing.py#L88

I'd recommend transporting the remaining path to be matched in the scope as a separate entry called `remaining_path`, having the router look for this before using `scope["path"]`, and then writing the rest of its URL out to that scope entry. Once that's done, unmark the test for xfail, add any extra tests that are needed, and update the routing docs to mention the behaviour.

**Comment by chuckoy** [comment]
Hi Andrew,

I've tried running the failing test locally and listing the routes but I can't seem to access the `outer_router` route from `inner_router`.

How should I go about making calls to parent routes on partial matches?

Am I correct in that it ought to try matching the path left to right, while taking away positional/named groups as matches are made?

**Comment by andrewgodwin** [comment]
You shouldn't need to access the outer router from the inner - the outer router should match as much as it can, and then put the remainder of the unmatched path into the `scope` for the inner router to look at. If you take a look at the URL code in Django itself you'll see it has a way of working out what part of the URL is left "unmatched" (as in, where the regular expression/path stops)

**Comment by hishnash** [comment]
Is it not possible to make the `URLRouter` just support nested url routes rather than nesting `URLRouter`s

**Comment by andrewgodwin** [comment]
Maybe, but people are going to nest `URLRouter` anyway because you can (and because it's a valid ASGI app) so I'd rather fix the core issue.

**Comment by hundredeir** [comment]
I dunno why didn't they return the new path.[link](https://github.com/django/django/blob/d4373b6da4b420fe9211438addeedb396a3821be/django/urls/resolvers.py#L342)

**Comment by andrewgodwin** [comment]
Right, that's probably one of the changes to make this work.

**Comment by matthiask** [comment]
I'm a bit surprised that the desired behaviour includes capturing both named and unnamed groups. The Django docs say:

> In either case, using only one style within a given regex is recommended. When both styles are mixed, any unnamed groups are ignored and only named groups are passed to the view function.

(From https://docs.djangoproject.com/en/2.0/topics/http/urls/#using-unnamed-regular-expression-groups)

I propose dropping this requirement. Here's a pull request implementing this change and adding support for nested `URLRouter` instances: https://github.com/django/channels/pull/946

**Comment by andrewgodwin** [comment]
Already fixed in #946
