### ISSUE TITLE
Websocket Disconnect consumer function close not called

### ISSUE THREAD

**Issue by svenauhagen** [django/channels#878]
Hi,

the function websocket_disconnect or close are not called when the webclient closes a websocket connection.
It seems the asyncio coroutine is killed before it can be executed.
Not sure how to fix this, I am happy to provide a patch if you give me a hint.

Can easily be reproduced with:

`
class TestConsumer(AsyncWebsocketConsumer):

  async def disconnect(self, code):
        """
        Called when a WebSocket connection is closed.
        """
        logger.debug('DISCONNECT')
`

it never executes.

**Comment by svenauhagen** [comment]
I pinned it down to daphne/ws_protocol.py

def onClose(...):
      self.server.discard_protocol(self)

cancels the processing of messages for the connection so the following line

    self.application_queue.put_nowait({
                "type": "websocket.disconnect",
                "code": code,
            })

is doing nothing.

**Comment by tsiaGeorge** [comment]
I mentioned this here #860.
As you said the actual issue is in the protocol server(Daphne) and it's still open.
django/daphne#152

**Comment by svenauhagen** [comment]
Thanks, sorry I did not see that ticket.

**Comment by andrewgodwin** [comment]
Yup, going to fix that as my first thing today!

**Comment by svenauhagen** [comment]
Thanks, let me know if you need someone to test it.
