### ISSUE TITLE
ChannelsLiveServerTestCase doesn't have staticfiles support

### ISSUE THREAD

**Issue by andrewgodwin** [django/channels#880]
It needs a class attribute that lets you turn it on, and sets the ASGI application to `StaticFilesWrapper(get_default_application())`

**Comment by dgilge** [comment]
I implemented that locally. I'm just not sure about the tests. As long as it's more or less copying from [Django](https://github.com/django/django/blob/master/tests/staticfiles_tests/test_liveserver.py) it's fine but if I have to make too many modifications I might need help.

**Comment by andrewgodwin** [comment]
I'm fine with there not being a test for this specific thing for now.

**Comment by dgilge** [comment]
What do you prefer? Having only one subclass and override `_create_server_thread` or having an additional subclass for static files?

1)
```python
class ChannelsLiveServerTestCase(LiveServerTestCase):

    server_thread_class = DaphneServerThread
    static_handler = StaticFilesWrapper
    serve_static = False

    @classmethod
    def _create_server_thread(cls, connections_override):
        if cls.serve_static:
            static_handler = cls.static_handler
        else:
            static_handler = None

        return cls.server_thread_class(
            cls.host,
            static_handler,
            connections_override=connections_override,
            port=cls.port,
    )
```

2)
```python
class ChannelsLiveServerTestCase(LiveServerTestCase):

    server_thread_class = DaphneServerThread
    static_handler = None


class ChannelsStaticLiveServerTestCase(ChannelsLiveServerTestCase):

    static_handler = StaticFilesWrapper

```

**Comment by andrewgodwin** [comment]
I'd rather 1 than two subclasses, but instead of changing the thread class to take a static handler, change it to take the whole application.
