### ISSUE TITLE
test_routing.py is failing

### ISSUE THREAD

**Issue by sfehlandt** [django/channels#881]
If you're submitting a bug report, please include:

- Your OS and runtime environment, and browser if applicable
- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (channels_redis normally)
- What you expected to happen vs. what actually happened
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
- Console logs and full tracebacks of any errors

Hi, I am trying to adapt my project from channels 1 to 2 and I have faced many challenges regarding testing. While doing this I cloned the repo in order to test something. I followed the instructions of the README and some tests failed:

- OS: Ubuntu 16.04, using virtualenv with python 3.6.3
- Running tests as: "pytest"
- Console log:
========================================== test session starts ==========================================
platform linux -- Python 3.6.3, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/sfehlandt/projects/channels, inifile: setup.cfg
plugins: asyncio-0.8.0, django-3.1.2
collected 24 items                                                                                      

tests/test_generic_websocket.py ....                                                              [ 16%]
tests/test_http.py .........                                                                      [ 54%]
tests/test_layers.py ...                                                                          [ 66%]
tests/test_routing.py ...x.                                                                       [ 87%]
tests/test_testing.py ..                                                                          [ 95%]
tests/security/test_websocket.py .                                                                [100%]

================================= 23 passed, 1 xfailed in 0.25 seconds ==================================

- Packages versions (pip feeze):
asgiref==2.1.3
async-timeout==2.0.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
-e git+git@github.com:django/channels.git@621e6a4fd47a328cb25877fb6d2bdbe69abf8f9a#egg=channels
constantly==15.1.0
coverage==4.5
daphne==2.0.2
Django==2.0.2
hyperlink==17.3.1
incremental==17.5.0
pkg-resources==0.0.0
pluggy==0.6.0
py==1.5.2
pytest==3.4.0
pytest-asyncio==0.8.0
pytest-django==3.1.2
pytz==2017.3
six==1.11.0
Twisted==17.9.0
txaio==2.8.2
zope.interface==4.4.3

**Comment by andrewgodwin** [comment]
This is an expected failure, which is normal test practice. The test is written for a bug that is not yet fixed (https://github.com/django/channels/issues/870).

**Comment by andrewgodwin** [comment]
(to clarify: the test suite has been told it should fail. If the test starts working, then it would actually complain and our CI server would go red)
