### ISSUE TITLE
Issues with InMemoryChannelLayer

### ISSUE THREAD

**Issue by jproffitt** [django/channels#882]
What is the recommended way to use channel layers for local development/testing?

Previously, in channels v1 I used asgi_redis for production environments, and asgiref.inmemory for local dev. I tried upgrading to channels v2 and noticed the in memory layer in asgiref was removed.

I somehow stubbled upon the `InMemoryChannelLayer` in channels itself, and figured that might be the replacement for the old asgiref one, so I tried using it, but ran into issues. 

I don't get any error messages, and I have a very basic consumer. (actually just one `JsonWebsocketConsumer`) The console says it is `HANDSHAKING`, but then nothing happens, and actually freezes the local server until I restart it. I know it's a problem with `InMemoryChannelLayer`, because if I set `CHANNEL_LAYERS` to `{}`, the consumer works just fine. (but of course then I can't use `self.channel_layer`)

Am I just using this the wrong way? I would like to not have to use redis for local development.

**Comment by andrewgodwin** [comment]
`InMemoryChannelLayer` is being worked on and improved here: https://github.com/django/channels/pull/863

However, the one that's shipped should still work if you're not trying to do group adds and are just sending stuff over it. What's your consumer code look like?

**Comment by jproffitt** [comment]
@andrewgodwin thanks for the quick reply. It does not work even with the most basic consumer I'm testing with:
```
class TestConsumer(JsonWebsocketConsumer):
    def connect(self):
        self.accept()
```
I kept thinking it might be due to my routing and consumer setup, (I was a little confused about the changes to channels 2) but everything works just fine with `CHANNEL_LAYERS = {}`, so I'm not sure what the issue is.

Again, I get no error message. It's just as soon as the client tries to connect over websockets, the local server just stalls. It won't respond to anything until I restart it again.

**Comment by andrewgodwin** [comment]
OK, I'll try and replicate this locally after I look at some other more critical issues.

**Comment by jproffitt** [comment]
@andrewgodwin FYI I just tried it with the fork from #863, and everything works great. So whatever was changed in that PR fixed whatever the problem was.

**Comment by andrewgodwin** [comment]
Ah, good to know! I'll close this when that lands then.

**Comment by andrewgodwin** [comment]
Landed that PR, so this is done.
