### ISSUE TITLE
Error: got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by Audace** [django/channels#891]
I'm trying to send a message using Channel Layer and the `group_send` method. I'm doing this from synchronous code, so have tried variants of `AsyncToSync` and `loop.run_until_complete` to no avail. My latest error is a RuntimeWarning:

`RuntimeError: Task <Task pending coro=<AsyncToSync.main_wrap() running at /Users/user/path/to/venv/lib/python3.6/site-packages/asgiref/sync.py:57> cb=[_run_until_complete_cb() at /Users/user/anaconda2/envs/py36/lib/python3.6/asyncio/base_events.py:176]> got Future <Future pending> attached to a different loop`. 

My current code is the following:
```
from asgiref.sync import AsyncToSync
from channels.layers import get_channel_layer
channel_layer = get_channel_layer()

AsyncToSync(channel_layer.group_send)(group_name, {'text': json.dumps(message),'type': 'receive_group_json'})
```

I'm interested in how I can call `group_send` from synchronous code. 

I tried the workaround referenced in issue #859 but received: `<string>:2: RuntimeWarning: coroutine 'RedisChannelLayer.group_send' was never awaited`

Context: `channels-redis==2.0.2`, `channels==2.0.2`, `asgiref==2.1.4`, `daphne==2.0.3`, `twisted==17.9.0`. Running using `runserver`.

**Comment by andrewgodwin** [comment]
Yes, this is all related to #859, the workaround there won't work in most cases. You just need to wait for that to be solved, sorry!
