### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by hishnash** [django/channels#893]
Python 3.5 supports [type hints](https://docs.python.org/3/library/typing.html). 

Adding these throughout the code base will improve autocomplete etc for many users IDEs

**Comment by andrewgodwin** [comment]
And those type hints should be compatible with `mypy`, ideally.

This is not something I'm going to work on as a priority, as it's very much a "nice to have", but I'll leave this open if someone wants to pick it up.

**Comment by hishnash** [comment]
I will try to have a basic coverage done this weekend for this.

**Comment by hundredeir** [comment]
Is anyone working on this?

**Comment by hishnash** [comment]
@hundredeirI was going to but felt that the multiplexing was more important (for my work) so feel free to give it a spin.

**Comment by hundredeir** [comment]
Since, django supports python 3.4,3.5. and type annotations for variables were first introduced in python 3.4.
There are two ways left to annotate variables in it. Either create stub file or use comments for annotating. 
Which way would be preferred ?

**Comment by carltongibson** [comment]
@hundredeir Channels is Python 3.5+. Unless I'm missing something, just using inline code annotations is totally fine.

**Comment by hundredeir** [comment]
Hi @carltongibson , it was a typo. 
I was talking [PEP526](https://www.python.org/dev/peps/pep-0526/) which was introduced in 3.6. Which allows type annotations for variables.

**Comment by carltongibson** [comment]
Type hinting is not all or nothing. Personally, I’d begin with the function annotations. We can worry about the rest later.

**Comment by skewty** [comment]
Watch out using typing in Python 3.5.  A few of the classes in there didn't exist in the earlier 3.5 releases (example: Queue). 

 Also note that binary (.exe) builds of newest python 3.5 versions are **not** available for Windows users.

**Comment by WisdomPill** [comment]
I'm available in working on a PR to start adding typing to channels, but I don't understand what's the difference in older versions of python. Channels 2 supports python 3.5 and up. Isn't typing available in 3.5? 
https://docs.python.org/3.5/library/typing.html

If anybody can tell me the difference between 3.5 and newer versions I can start working on that soon.

**Comment by brianmay** [comment]
Probably the biggest thing introduced in 3.6 is variable annotations.

https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html#variables

Python 3.7 introduces postponed evaluation, which I think is significant:

https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep563

Definitely not show stoppers, but, yes, things you do need to be aware of.

**Comment by skewty** [comment]
Keep in mind that some classes in typing came in later in the 3.5 series (like Queue for example).

So if 3.5.0 is supported you will have to avoid a few classes in typing that are only present in later versions.

**Comment by hishnash** [comment]
https://github.com/django/channels/issues/1282 looks like we should be moving to 3.6 soon?

**Comment by WisdomPill** [comment]
Thank you @brianmay I started working on it and I will post a pr draft shortly for other related questions. I used the mypy docs to see how to treat the awaitables and changed the order of a class declaration for the second point to keep it backward compatible.

**Comment by WisdomPill** [comment]
@skewty Yes, thank you, I don't think some of those classes are in use in channels directly, or at least I didn't come across them

**Comment by WisdomPill** [comment]
@hishnash I understand your point of view but please, don't drop other versions of python, it makes it hard for people to stay updated with important updates. As a matter of fact in my opinion too many changes has happened in version 3 that completely change the way of coding

**Comment by carltongibson** [comment]
Follow Gonna close this for now. Further discussion on https://github.com/django/channels/discussions/1819.

**Comment by collinanderson** [comment]
Update: there's some recent work on adding Django channels stubs to typeshed if anyone wants to help test and review: https://github.com/python/typeshed/pull/13939
