### ISSUE TITLE
Sending group messages from celery

### ISSUE THREAD

**Issue by ploggingdev** [django/channels#894]
I have a celery task that sends json data every 10 seconds to a group. In Channels 1 I used the following code :

```
Group(topic_name).send({
            'text': json.dumps({
                'type': 'presence',
                'payload': {
                    'channel_name': topic_name,
                    'members': list(topic_users[topic_name]),
                    'lurkers': topic_anon_count[topic_name],
                }
            })
        })
```

How do I achieve the same in Channels 2? I tried following the [docs](https://channels.readthedocs.io/en/latest/topics/channel_layers.html#using-outside-of-consumers), but I couldn't get it to work ("got Future <Future pending> attached to a different loop"). [Traceback](https://dpaste.de/92yh)

```
channel_layer = get_channel_layer()
async_to_sync(channel_layer.group_send)(
            topic_name,
            {
                "type": "presence.data",
                'payload': {
                    'channel_name': topic_name,
                    'members': list(topic_users[topic_name]),
                    'lurkers': topic_anon_count[topic_name],
                }
            },
        )
```

I have a `presence_data` [method](https://github.com/ploggingdev/hackerschat/blob/master/mainapp/consumers.py#L18) inside a `JsonWebsocketConsumer` that handles sending messages to the group.

Does the async by default nature of Channels 2 introduce complications when communicating across processes? Or am just incorrectly calling the `presence_data` method?

I don't expect you to debug my specific code base, I guess the question is more general : what's the proper way to send messages to a group from another process (eg-a celery task)? I set the `type` to the method name, but do I also need to prefix the name of the consumer since I'm calling it from another process?

**Comment by bastbnl** [comment]
I did this on a consumer inherting from `WebsocketConsumer`
```
async_to_sync(channel_layer.group_send)(a_channel_connection, {"type": "websocket.send", "text": dumps({'payload': {
                    'channel_name': topic_name,
                    'members': list(topic_users[topic_name]),
                    'lurkers': topic_anon_count[topic_name],
                }}
), })
```

You'll run into issue #859. At least I did

**Comment by ploggingdev** [comment]
I don't think you can send messages directly to all the clients connected to a certain group over the channel layer using `websocket.send`. Instead a handler method is required to be set in `type` which then handles sending messages to the clients. Or at least that's what I understood from https://github.com/django/channels/issues/858 .

**Comment by bastbnl** [comment]
Understood. I may be incorrect here, but it is working for the first message that I sent it to the group.

**Comment by andrewgodwin** [comment]
You're running into #859, unfortunately - as it says, the call works the first time, and then the caching internals of the redis layer fail and it doesn't work the second time.
