### ISSUE TITLE
workers global data

### ISSUE THREAD

**Issue by brianmay** [django/channels#898]
Hello,

Just trying to work out how to best store global data in a worker process that is shared by connections. In this case, I have a long poll task that should be shared.

Overriding the Worker class seemed to be the obvious place to do this, however, has two issues:

* Overriding the Worker class requires replacing the "runworker" command to use my class instead of the system class.
* There doesn't appear to be any trivial way of passing the data to the application instance.

I do have a solution for both these issues (I can supply on request), but it isn't very pretty, wondering if there is a better way...

Regards

**Comment by andrewgodwin** [comment]
Why do you want to have global data at all? This is something WSGI heavily discourages and I would sort of say the same here...

The Worker class is not used at all in Channels 2 for connection handlers, either, so you're not going to find much helpful there. The best you can probably do is use a class-level variable and have everything look at that, but be wary that every application runs in either a different coroutine (async) or thread (sync)

**Comment by brianmay** [comment]
The use case is we need to get real time data from a remote source using long polling but don't want a separate long poll connection for every websocket. The problem with a class level variable is that gets created when in other processes if that module is imported in other processes.

Actually, I can't remember why the main process now was importing this file, will look at that after I investigate the tests some more.

**Comment by andrewgodwin** [comment]
Well, I would suggest you run it in a separate process then and use the channel layer to communicate with the application instances - that's sort of the ideal architecture.

There's plenty of ways to make singletons in Python though - I don't think this needs any particular support from Channels even if I did like it :)

**Comment by brianmay** [comment]
This is what I was using a worker process. Are you saying that a worker process isn't the correct solution here?

**Comment by andrewgodwin** [comment]
I'm perhaps not quite clear on what's happening here. Are you using `runworker`? Connections are not handled inside of worker processes, they are only for listening on specific channels, as per http://channels.readthedocs.io/en/latest/topics/worker.html

If you are doing all that correctly, I don't see why you'd want to have a global process item that connections can handle, as connections are not in the same process as the worker (this is very different to channels 1, btw)

**Comment by brianmay** [comment]
The requirement is that we listen to "subscribe" events using websockets.

When a websocket subscribe request comes in, a single shared asyncio task, will:

1. abort any long poll operation in process.
2. send subscribe to server.
3. long poll the server for further information.
4. when long poll returns, send data back to websocket.

The worker model seemed idea, the websocket consumer will forward subscribe requests to the worker process. The asyncio consumer can contact the asyncio global long poll task - I believe they are all handled in the one asyncio loop. The asyncio global long poll task can send data back to the consumer, which can forward the data back to the websocket.

Presumably this model also means we can identify the particular worker consumer and send messages direct to it (e.g. unsubscribe) should we fix the code to support multiple worker processes.

However we get one application instance per scope. Which might actually be sufficient. More importantly however, the application instance is only created when we receive a message. We need the worker to start listening immediately as soon as it starts (as it needs to subscribe to some channels that aren't associated with websockets).

Does any of this make sense?

I hope I am making sense :-)

**Comment by andrewgodwin** [comment]
I'm not entirely clear what you want to do, but I ask this: are you just saying that the new worker model is fine, because you only get one application instance/scope per channel name? Or is there something else you would like to ask of Channels?

**Comment by brianmay** [comment]
I will try to simplify. The 1st problem only:

The Worker model is fine. But: There is no easy way to replace the worker class with my own because the worker class is hardcoded in ``channels/management/commands/runworker.py``. So I have to replace the entire ``runworker.py``` file.

Does this bit make sense?

**Comment by andrewgodwin** [comment]
Ah, yes, that makes sense, and I would hope something like https://github.com/django/channels/commit/afcb007c7c8b68bc4cace5ff6d634330f70603ec helps?

**Comment by brianmay** [comment]
That looks good, thanks. Will try it out ASAP.
