### ISSUE TITLE
Runserver / debug with get_channel_layer is None

### ISSUE THREAD

**Issue by robmoorman** [django/channels#913]
The method `get_channel_layer` returns `None` if no `default` channel layer in `settings.CHANNEL_LAYERS` is defined.

By removing the bindings in Channels 2.0 you should now write your own code to accomplish the same behaviour. According the docs this should be with `channel_layer = get_channel_layer()`.

I have e.g. the following code to notify clients with currency updates:
```python
@receiver(post_save, sender=Currency)
def notify_currency_ws_clients(sender, instance, created, **kwargs):
    channel_layer = get_channel_layer()
    channel_layer.send('currency', {
        'type': 'currency.update',
        'id': instance.id,
    })
```

While channel_layer being None with runserver (I assume we don't want Redis to be a hard dependency for development), this code can't be executed.

**Comment by dgilge** [comment]
You may set `CHANNEL_LAYERS` to this in dev:

```python
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
```

(You might need the newest version from GitHub master directly. I don't know if it's released already.)

**Comment by robmoorman** [comment]
Thanks @dgilge . Got some problems with handshaking now. Seems it's overriding the http listeners (`DEBUG=True`):

```python
application = ProtocolTypeRouter({
    'websocket': AllowedHostsOriginValidator(
        URLRouter([
            path('', CurrencyConsumer),
        ])
    ),
})
```

Connecting with ws://localhost:8000 (were channels 1 also served http over port 8000).

```javascript
bridge = new WebSocketBridge()
bridge.connect('ws://localhost:8000')
bridge.listen((payload, stream) => {
  console.log('[WebSocket] payload:', payload, 'stream:', stream)
})

bridge.demultiplex('currency', (payload, stream) => {
  console.log('[steam:currency] payload:', payload, 'stream:', stream)
})
```

**Comment by dgilge** [comment]
Maybe the empty path doesn't work here. Try instead:

```python
application = ProtocolTypeRouter({
    'websocket': AllowedHostsOriginValidator(
        URLRouter([
            path('^$', CurrencyConsumer),
        ])
    ),
})
```

**Comment by robmoorman** [comment]
Hi @dgilge seems it doesn't do the trick (tried some urls as well as paths).

Also multiple type of consumers (sync, async, etc.).
State keeps in HANDSHAKING mode.

```python
class CurrencyConsumer(WebsocketConsumer):
    groups = ['currency']

    def connect(self):
        self.accept()
```

Exact same settings with Redis backend (while having `DEBUG=True`) works.

**Comment by robmoorman** [comment]
Ok it works now! Seems I had an outdated master version installed.

**Comment by Naman-Monga** [comment]
> 
> 
> Ok it works now! Seems I had an outdated master version installed.

Can you please elaborate on this point, I am facing the same issue.
get_channels_layer() is returning a None type object.
