### ISSUE TITLE
Auth helper functions [Feature Request]

### ISSUE THREAD

**Issue by hishnash** [django/channels#917]
Detailed description of the overall behaviour
--------------------------------------------

A set of helper functions (like Django's `login(request, user)` `logout(request)` that use the `session` object that is injected into the `scope`

Reasoning why it should be in Channels rather than a third-party app
-----------

Channels does not expose the HttpRequest object to the consumers. It is thus not clear how one might log in a user, (short of creating a mocked HttpRequest object just for the login event). it does, however, include the `AuthMiddleware` that will attempt to expose the currently authenticated user but will not let you log in a user or logout a user.

Examples of usage, if possible (it's easier to discuss concrete code examples)
---------------

```python
class SimpleHttpApp(AsyncConsumer):

    async def http_request(self, event):
       user = # go find a user somewere ;)
 
       login(self.scope, user)

        await self.send({
            "type": "http.response.start",
            "status": 200,
            "headers": [],
        })
       # ...... do some stuff and send that good old body along !


class SimpleLogoutHttpApp(AsyncConsumer):

    async def http_request(self, event):
       logout(self.scope)

        await self.send({
            "type": "http.response.start",
            "status": 200,
            "headers": [],
        })
       # ...... do some stuff and send that good old body along !

```

**Comment by andrewgodwin** [comment]
This will only be possible on `http` connections, not `websocket` connections, and I don't regard it as high-priority as you can do this via views right now. If anyone wants to take it on they are welcome, though!

**Comment by hishnash** [comment]
would there be any way to have Daphne send a message upstream to the Websocket consumer (that listest to the `http.reequest` message) before it responds with the first HTTP response (that upgrades to a WebSocket connection)? for that stuff like auth/rate limiting, etc.

**Comment by andrewgodwin** [comment]
Nothing in the websocket flow goes near the `http` consumers or events, and you can't send things back to the browser as it's not expecting a HTTP connection. The _only_ way you can set cookies is on a genuine HTTP response from a non-websocket HTTP request.

**Comment by hishnash** [comment]
When the browser starts a websocket conneciton it sends at traditional HTTP request 
```http
GET / HTTP/1.1
Connection: Upgrade
Host: 172.20.10.2:8000
Origin: ws://172.20.10.2:8000
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits; server_max_window_bits=15
Sec-WebSocket-Key: ZmRkc25hZmpsb2tpYXh2bw==
```

then the server responds with with a plain old https response:

```http
HTTP/1.1 101 Web Socket Protocol Handshake
Sec-WebSocket-Accept: JU8AQVewgTrlQOi0OSkf+XfmViE=
Connection: Upgrade
Server: Kaazing Gateway
Date: Tue, 20 Feb 2018 07:28:21 GMT
Upgrade: websocket
```

only at this point does the connection then become a WebSocket stream.  This above response can have headers and if it does these can (and will) set cookies in all browsers I have tested.

I know it would require a change to Daphne to send a message upstream to the WebSocket consumer before responding with the `HTTP/1.1 101 Web Socket Protocol Handshake` but it would allow for more control.

what does the `websocket.accept` message do at the moment? does Daphne wait for this before responding with the above http response?

**Comment by andrewgodwin** [comment]
Oh, right, there's a reply handshake header set. We use a library called `autobahn` to handle the websocket negotiation so that would have to support it for us to. I believe the point where we pause Autobahn is before it sends the response headers for the handshake, though.

`websocket.connect` does contain the connection headers already, don't know why you are worried about that. It's just setting them on the response we don't do and I'm in no hurry to add it.

**Comment by hishnash** [comment]
> websocket.connect does contain the connection headers already

ok cool, that is the most important so that one can have auth tokens checked with custom middlewares and reject connections properly etc. 

> It's just setting them on the response we don't do and I'm in no hurry to add it.

yer its not massively important as you way for WebSocket connections the norm at the moment is that you will get some auth token/cookie from a plain old HTTP endpoint first before you connect to the WebSocket. (be that in the browser just loading the main domains HTTP/js files) or on a client app where you might have already completed some fancy OAuth dance.

**Comment by thaxy** [comment]
Hi, I would be interested in setting a cookie during a WebSocket connection.

> in general, exposing the headers in websocket.connect would be very important also for users who are using WebSockets not from the browser but from their native clients (iOS/Android) apps were the rest of the server might user auth signatures in the header.

https://github.com/django/daphne/blob/18f2d67f34e33a5f8c87a7bca093dfffea44d7a7/daphne/ws_protocol.py#L97

Without knowing the implications but if I don't return ``self.handshake_deferred`` but a tuple of ``(None, {'my_cookie': 'the_value'}`` I can make the HTTP response of the handshake return a custom cookie. Any thoughts on that or how this could be supported in the future through channels?
