### ISSUE TITLE
./manage.py runserver exception when inspecting headers for static files using curl -I

### ISSUE THREAD

**Issue by ploggingdev** [django/channels#920]
I was trying to inspect the headers for a channels application started using `python manage.py runserver` in my development environment using `curl -I "address"` and it raised an exception when the address was the location of a static file (js or css). No exception is raised when I inspect the headers for a html endpoint.

Here's the [traceback](https://dpaste.de/UJtU).

**Comment by proofit404** [comment]
Hi,

Looking at the traceback I'm thinking that the actual one is hiding inside 

    File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result

Is there any other error messages? Something like an exception in the Thread-1?

**Comment by ploggingdev** [comment]
No other error messages are displayed. The traceback contains the entire error message.

**Comment by andrewgodwin** [comment]
This is actually an issue in Daphne (https://github.com/django/daphne/issues/175) so I'm going to close this.
