### ISSUE TITLE
Implement Graceful Restarting

### ISSUE THREAD

**Issue by agronick** [django/channels#922]
I've scoured the codebase and I can't seem to find a way to restart without interrupting user's connections. There should be a signal handler that will allow previous connections to finish while not allowing new connections. 

This was present in the old version of Channels. The changelog says:

<pre>
0.9.4 (2016-03-08)
------------------

* Worker processes now exit gracefully (finish their current processing) when
sent SIGTERM or SIGINT.
</pre>
This is no longer the case.

**Comment by andrewgodwin** [comment]
This is no longer easy because the programs are run in-process rather than externally, so we lose the ability to restart without touching program code. I'll leave this open as a feature request.

**Comment by andrewgodwin** [comment]
Actually, thinking about it, this should be filed against Daphne, not channels. Can you open the issue there?

**Comment by agronick** [comment]
Sure thing. I realized that as well. I'm in the process of upgrading to Channels 2 and this is something I need to figure out before I can deploy.

**Comment by veeru-gedageri** [comment]
@agronick did you find out how to do graceful restarts?

**Comment by agronick** [comment]
I keep two sets of services and put Haproxy between them and Nginx. I but one set into drain mode and Haproxy stops sending traffic to them. Once the deployment is complete I shut one side down. The next deployment I do the opposite.
