### ISSUE TITLE
runserver CHANNELS_WS_PROTOCOLS is ignored

### ISSUE THREAD

**Issue by dvdmgl** [django/channels#928]
Running runserver setting CHANNELS_WS_PROTOCOLS is ignored

pip freeze
```
aioredis==1.0.0
asgiref==2.1.6
async-timeout==2.0.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
channels==2.0.2
channels-redis==2.1.0
constantly==15.1.0
daphne==2.0.4
Django==1.11.10
graphene==2.0.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
graphql-ws==0.2.0
hiredis==0.2.0
hyperlink==17.3.1
incremental==17.5.0
iso8601==0.1.12
msgpack==0.5.6
promise==2.1
pytz==2018.3
Rx==1.6.1
singledispatch==3.4.0.3
six==1.11.0
Twisted==17.9.0
txaio==2.8.2
typing==3.6.4
zope.interface==4.4.3
```

Expected `Sec-WebSocket-Protocol: graphql-ws` to be present on the response

request headers
```
Host: localhost:8000
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: pt,pt-PT;q=0.5
Accept-Encoding: gzip, deflate
Sec-WebSocket-Version: 13
Origin: http://localhost:8000
Sec-WebSocket-Protocol: graphql-ws
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: J7Gmi00eGxF8fdMLt4kU2Q==
Cookie: csrftoken=AFmSHfqmkCZ4W2M7IXYdjjg0ypovw3kwUQTsL27G50giZMtDmU8dOUNXsxMCg8Ra; sessionid=2jmemv2zxrmdrpsfm6eom271j766xr1a
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```
response headers
```
Server: Daphne
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: 9btJeSYRvPXKw6cEUzeJP70ZMm4=
```

**Comment by andrewgodwin** [comment]
`CHANNELS_WS_PROTOCOLS` is no longer a setting in Channels 2.0. You can instead control what protocols you wish to accept during the connecting phase of a socket. This is not in the generic consumers yet, but you can do it yourself by calling this rather than `await self.accept()`:

```
await self.send({"type": "websocket.accept", "subprotocol": "protocol-name"})
```

Spec is here: https://github.com/django/asgiref/blob/master/specs/www.rst

**Comment by andrewgodwin** [comment]
Oh, and the protocols the client asked for are in `scope["subprotocols"]`

**Comment by dvdmgl** [comment]
Tank you for the short reply.

I was using the code as a guide, and
https://github.com/django/channels/blob/d6643d96dd59e153cda13681a6d5a8963b9d577c/channels/management/commands/runserver.py#L89

**Comment by andrewgodwin** [comment]
Yup, that line is now gone as well - it was missed as I ported `runserver` from channels 1 to chanels 2.

**Comment by CodeVINCI** [comment]
@andrewgodwin i am trying to send some data along with the sec-websocket-protocol header. I am unable to accept any one of the protocols if i donot use self.connect, before, self.send({"type": "websocket.accept", "subprotocol": "protocol-name"})  then it gives me error cannot send before connect something. Can you tell me how i can accept one of the protocols and also receive the data.

**Comment by CodeVINCI** [comment]
failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received this is the error my browser gives.

**Comment by carltongibson** [comment]
Hi @CodeVINCI. I'm afraid we can't debug your issues on here. Please see https://channels.readthedocs.io/en/latest/support.html for support channels.

**Comment by cochiseruhulessin** [comment]
^ this is not a debugging issue; but an issue of bad documentation.

**Comment by cochiseruhulessin** [comment]
You can not invoke `self.send()` instead of `self.accept()`. This produces the following exception:

```
raise ValueError("Socket has not been accepted, so cannot send over it")
```

**Comment by CodeVINCI** [comment]
Maybe i resolved it long time ago and can't remember what issue this was.
