### ISSUE TITLE
Add a way to get a list of channels currently in a group

### ISSUE THREAD

**Issue by ugopozo** [django/channels#941]
# Detailed description of the overall behaviour

This is more of a protocol change (which would require other packages i.e. [`channels_redis`](https://github.com/django/channels_redis) to comply) than a code change. When using `InMemoryChannelLayer`, one can get the list of channels by doing `channel_layer.groups.keys()`, and when using `RedisChannelLayer` a `return` statement [here](https://github.com/django/channels_redis/blob/f1580fcc3d5b1e28be9ba03e8a38fc57c68bed8c/channels_redis/core.py#L323) would suffice, but it would be interesting to have an official API such as `channel_layer.group_channels(group)` to standardize this information.

It's useful, for instance, when you need to know whether the current channel is the first one added to the group (by doing `is_first_channel = len(channel_layer.group_channels(group)) == 0`) and perform group initialization tasks, or storing application-specific group metadata which relies on the channels currently on the channel, or even implementing an alternative `group_send` method in your application that won't depend on the channel layer storage method.

# Reasoning why it should be in Channels rather than a third-party app

This should be in Channels because implementations of `BaseChannelLayer` can choose to not implement a reusable way to access this information if it's not. For instance, the only way to get access the list of channels in a group in `channels_redis` is to completely reimplement the first half of the `groud_send` method, such as:

```python
from channels.layers import get_channel_layer

channel_layer = get_channel_layer()

class MyCustomClass:
    (...)
    
    async def _hacky_channels_in_group(self):
        key = channel_layer._group_key(self.group_id)
        index = channel_layer.consistent_hash(self.group_id)

        async with channel_layer.connection(index) as connection:
            await connection.zremrangebyscore(
                key,
                min=0,
                max=int(time.time()) - channel_layer.group_expiry
            )

            channels = {name.decode('utf8')
                        for name in await connection.zrange(key, 0, -1)}

        return channels
```

Which is kinda hacky and uses non-standard APIs that are subject to change between versions without prior warning.

# Examples of usage, if possible (it's easier to discuss concrete code examples)

For instance, I could implement a parallel `group_send` as such:

```python
import asyncio

class MyCustomClass:
    (...)
    async def my_group_send(self, message):
        channels = await channel_layer.group_channels(self.group_id)

        await asyncio.gather(*[channel_layer.send(channel, {
            "type": "message.send",
            "data": message,
        }) for channel in channels])
```

**Comment by andrewgodwin** [comment]
This is explicitly not going to be in the group abstraction in Channels, I'm afraid - it was there in Channels 1 and deliberately removed in Channels 2. If you want this functionality, I recommend you implement your own group layer.

The reason we're not implementing it is because it's not well-defined what people mean by "in" a group. The default implementations are free to cheat and not expire things until you try to send to them, which means that most operations people want to do with "list members of a group" have different definitions of how exactly they should work based on who you ask. Only send is consistent, so that's what is provided.
