### ISSUE TITLE
Getting 404 error on socket connection

### ISSUE THREAD

**Issue by DmitryNoven** [django/channels#942]
Getting 404 error on socket connection if i running project with gunicorn.
I'm using Django==1.10.8,  channels==1.1.6.
Everuthing works fine if run with runserver. But when i'm changing it to gunicorn it says:
`WebSocket connection to 'ws://localhost:8000/11' failed: Error during WebSocket handshake: Unexpected response code: 404.
`
Daphne runs with command `daphne -b 0.0.0.0 -p 8001 core.asgi:channel_layer`

here`s settings i used:
```
settings.py
CHANNEL_LAYERS = {
    "default": {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('redis', 6379)],
        },
        "ROUTING": "app.routing.channel_routing",
    },
}
```

```
routing.py
channel_routing = {
    'websocket.connect': 'app.consumers.ws_connect',
    'websocket.receive': 'app.consumers.ws_message',
    'websocket.disconnect': 'app.consumers.ws_disconnect',
}

```

```
consumers.py
import json
import redis

from channels.channel import Group
from channels.sessions import channel_session

redis_conn = redis.Redis("redis", 6379)


@channel_session
def ws_connect(message):
    room = message.content['path'].strip("/")
    message.channel_session['room'] = room
    redis_conn.sadd('readers', message.reply_channel.name)
    redis_conn.sadd('groups', room)
    message.reply_channel.send({'accept': True})
    Group(room).add(message.reply_channel)


def ws_message(message):
    Group('chat').send({'text': json.dumps(
        {'message': message.content['text'],
         'sender': message.reply_channel.name})
    })


def ws_disconnect(message):
    Group('chat').discard(message.reply_channel)

```

Am i missing sumething or using too old version and should update to newest? Will be appritiated for ANY help. ty

**Comment by andrewgodwin** [comment]
Gunicorn does not support WebSockets in a way that Channels can use them, so you cannot use it.

**Comment by Sispheor** [comment]
and so, how to use this lib in prod with Django?

**Comment by MrFus10n** [comment]
Use Daphne for example:
https://channels.readthedocs.io/en/latest/deploying.html

**Comment by Sispheor** [comment]
Thx for your answer @MrFus10n. The idea is to use both Gunicorn and Daphne to handle HTTP and Ws requests? Or just Daphne?

**Comment by MrFus10n** [comment]
You can handle both WS and HTTP requests by Daphne or use Gunicon for HTTP requests and Daphne for WS. See https://channels.readthedocs.io/en/latest/deploying.html#http-and-websocket

**Comment by ebsaral** [comment]
https://www.uvicorn.org/

**Comment by Codeburst09** [comment]
I am facing the same error in localhost can anyone help me?
