### ISSUE TITLE
Request: Middleware equivalent of is_secure()

### ISSUE THREAD

**Issue by ovekaaven** [django/channels#955]
Django's HttpRequest has the handy is_secure() function. It might be useful to add a middleware component to Channels that can give the same information for http/websocket connections. The main complication here that if we're behind a proxy, i.e. settings.SECURE_PROXY_SSL_HEADER is set to something, then it's necessary to check the http headers, instead of just scope['scheme'].

May not be that hard to do in my application, but it would be much cleaner (and possibly more efficient) if some middleware could do it. Perhaps this could even be part of the existing AuthMiddleware.

**Comment by andrewgodwin** [comment]
Middleware could definitely do it, but that middleware is free to overwrite `scope["scheme"]` as it needs to based on proxy headers, so I would suggest that as the canonical source used by apps.

Given that what proxy headers are used and the format of the header varies, I think this is something best solved by custom/third-party middleware, so I don't think this is something we can easily ship in Channels!

**Comment by ovekaaven** [comment]
I don't know. As far as I know, the overwhelming majority of Django installations run behind something which adds X-Forwarded-Proto. For anything else custom middleware might be needed, sure, but I'd think it would be nice to reduce the need for everyone to duplicate code for this common case, at least?

But if not, OK... I suppose I can live with some custom code for now.

**Comment by andrewgodwin** [comment]
I have to try and keep the surface area of things down, unfortunately! Django doesn't ship with direct support for this enabled (you have to set up `SECURE_PROXY_SSL_HEADER` yourself), and given that support for the IP/port headers is in Daphne, it might be better off there anyway.

I might be up for taking a pull request for this, but it's not something I'm going to have time to work on and support in the near future.

**Comment by Jonathan-Landeed** [comment]
Here's a rough draft if anyone is interested. I agree that it's probably better off in Daphne. With django, you want to upgrade http connections to https with a redirect instead of denying them outright. With websockets, it's unlikely that anyone will accidentally hit a ws endpoint, so upgrading ws to wss is unnecessary.

```
class WSSValidator:
    """
    Validates that the incoming connection is a secure websocket.
    Allows unsecured connections if SECURE_SSL_REDIRECT is False (for testing in local).
    todo: check SECURE_SSL_EXEMPT
    """

    def __init__(self, application):
        self.application = application

    async def __call__(self, scope, receive, send):
        # todo: make configurable (SECURE_PROXY_SSL_HEADER does not work because websockets don't
        # process x-header names like django does)
        # todo: calculate properly when there isn't a proxy
        x_forwarded_for = None
        for header_name, header_value in scope.get("headers", []):
            if header_name == b"x-forwarded-proto":
                try:
                    x_forwarded_for = header_value
                except UnicodeDecodeError:
                    pass

        if settings.SECURE_SSL_REDIRECT and x_forwarded_for != b"https":
            # Deny the connection
            denier = WebsocketDenier()
            return await denier(scope, receive, send)

        return await self.application(scope, receive, send)
```
