### ISSUE TITLE
BaseChannelLayer.valid_group_name non ASCII

### ISSUE THREAD

**Issue by dilyanpalauzov** [django/channels#958]
Hello,

what is the rationale to exclude non-ASCII characters from `Group` names?  To my knowledge this limitation does not come from redis, in which case the restriction could be lifted.

Regards
  Дилян

**Comment by andrewgodwin** [comment]
It is so we can support other backends where the restrictions are more direct - for example, RabbitMQ and filesystem-based backends. Each could in theory support full unicode if we tried hard enough, but there are enough edge cases with encodings and not knowing binary from unicode that I felt it best to stick to a very restricted character set.

Sorry that this affects non-English languages - maybe one day we can lift it, but I don't have enough time to research everything or the maintenance time to do that right now.
