### ISSUE TITLE
Include sync versions of channel_layer methods

### ISSUE THREAD

**Issue by ipartola** [django/channels#959]
It seems like the use case for synchronous WebSocket code and using groups is quite common. In 2.X we now have to write the code as follows:

    async_to_sync(self.channel_layer.group_add)(GROUP_NAME, self.channel_name)

This code is not very readable. It would be nice to just provide a sync version of `group_add()` and `group_discard()`, perhaps named `sync_group_add()` and `sync_group_discard()`. The documentation calls `async_to_sync()` "handy" but in reality it just gets cumbersome.

Alternatively, would it be possible to provide a sync version of `channel_layer` with all functions being sync when using the sync generic consumers? Or even something like `self.sync_channel` and `self.async_channel`?

**Comment by andrewgodwin** [comment]
I'm afraid the current design is very deliberate - I don't want to maintain two separate interfaces. If you find it cumbersome, you can write your own aliases onto your consumer classes, but that's about all I can offer.
