### ISSUE TITLE
In-memory database and live tests

### ISSUE THREAD

**Issue by dgilge** [django/channels#961]
What is the reason for not using in-momory databases with `ChannelsLiveServerTestcase`?

https://github.com/django/channels/blob/fd9f69c8fc276581efd0a6bc3dba7421e6dcb70b/channels/testing/live.py#L33

Is it because you shouldn't use SQLite?

If not it was nice to have a solution to use a SQLite database on filesystem. In this case I might have a look on how to accomplish that.

By the way, there is a *s* missing in that error message: Channel**s**LiveServerTestcase

**Comment by andrewgodwin** [comment]
It's because the live test case webserver runs in a separate process, and so can't use an in-memory database shared with the test-running process.
