### ISSUE TITLE
override_settings doesn't work for my async test cases

### ISSUE THREAD

**Issue by bruecksen** [django/channels#963]
I'm trying to test my websocket consumer and send and receive a group message. I thought I do it simmilar to the `test_generic_websocket.py` test case (https://github.com/django/channels/blob/master/tests/test_generic_websocket.py#L143) and use `override_settings` to set the channel layer backend to `InMemoryChannelLayer`. But even though the setting is overridden, the `get_channel_layer()` function still returns a `RedisChannelLayer`. Am I doing something wrong or is this a bug?

```
from django.test import override_settings
import pytest
from channels.layers import get_channel_layer

@pytest.mark.asyncio
async def test_ws():
    CHANNEL_LAYER_SETTINGS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
    with override_settings(CHANNEL_LAYERS=CHANNEL_LAYER_SETTINGS):
        channel_layer = get_channel_layer()
        raise Exception(type(channel_layer))
```

I'm using:
- Mac OS X
- channels@master, daphne==2.1.0, django==1.11

**Comment by dgilge** [comment]
Did you try the `settings` fixture?

https://pytest-django.readthedocs.io/en/latest/helpers.html#settings

**Comment by andrewgodwin** [comment]
Actually, there's caching inside `get_channel_layer` that will ignore any settings changes. We should fix this, but until then you can flush the cache with `channels.layers.channel_layers.backends = {}`

**Comment by bruecksen** [comment]
@andrewgodwin thanks, that helped!
