### ISSUE TITLE
Request: a way to know if group_send sent to anyone

### ISSUE THREAD

**Issue by ovekaaven** [django/channels#964]
While the documentation says that groups "do not allow you to enumerate or list the channels in a group", I wonder if you would still consider at least letting the program know when a group has no members at all, i.e., when group_send does nothing, so that the user can get an error message. It could be a return value from group_send() on whether it did anything, or it could be a function I could call to check if a group is currently empty. Is that something you would consider adding to the spec?

**Comment by ovekaaven** [comment]
Yeah, you're probably right. Shortly after I asked, I even realized that something like the PostgreSQL asynchronous notification feature wouldn't be able to do this. With the current API, it would be possible to write a channel layer for Postgres (and chances are I will), but this kind of feature would make such a layer impossible to write.

**Comment by andrewgodwin** [comment]
Right, that was one potential target among many. There's also variability in how you do sent notifications - do you over-count or under-count in case of error? It's things like this that means the design has the core sending component done and then wants you to add anything extra on top.
