### ISSUE TITLE
Printing inside async methods in example

### ISSUE THREAD

**Issue by chrisbarry** [django/channels#967]
Sorry if posting this here is the wrong place.

I'm trying to print inside these methods in from this example in django channels:

https://github.com/andrewgodwin/channels-examples/blob/master/multichat/chat/consumers.py

But nothing is coming through to the console.

I haven't worked with python Async before, so I'm not sure if I'm doing something really stupid? The examples in the python docs seem to show prints working no problem.

**Comment by andrewgodwin** [comment]
Printing should work fine from within async methods - I'd make sure you are flushing like this to see if that helps:

```
print("hello world", flush=True)
```

**Comment by chrisbarry** [comment]
Ah, that didn't do it, so I did a full upgrade of channels, something in this set of upgrades sorted it.

Installing collected packages: asgiref, autobahn, daphne, Django, setuptools
  Found existing installation: asgiref 2.1.6
    Uninstalling asgiref-2.1.6:
      Successfully uninstalled asgiref-2.1.6
  Found existing installation: autobahn 17.10.1
    Uninstalling autobahn-17.10.1:
      Successfully uninstalled autobahn-17.10.1
  Found existing installation: daphne 2.0.4
    Uninstalling daphne-2.0.4:
      Successfully uninstalled daphne-2.0.4
  Found existing installation: Django 2.0.2
    Uninstalling Django-2.0.2:
      Successfully uninstalled Django-2.0.2
  Found existing installation: setuptools 38.5.1
    Uninstalling setuptools-38.5.1:
      Successfully uninstalled setuptools-38.5.1
Successfully installed Django-2.0.3 asgiref-2.2.0 autobahn-18.3.1 daphne-2.1.0 setuptools-38.5.2
