### ISSUE TITLE
private message's  user A to user B only

### ISSUE THREAD

**Issue by rahul6612** [django/channels#976]
hii i want to create a app using django channels to send message from user A to user B so that only B will get the message (and B can reply my message). means to whom i want to send message only that person got my message not group of peoples (like facebook does) for this what i have to do please tell me in simple language bcoz i am not too expert in django. is django channel is good choice for that . and if  u know any tutorials on that please recommend me. thanks in advance.

**Comment by andrewgodwin** [comment]
I'm afraid I can't give individual coding help for problems like this, or I would be busy all day! I suggest you start out by building your app without channels and then add it in later with one group per target user.

**Comment by rahul6612** [comment]
i already created an app where peoples can post their messages(text/audio/videos)they can follow/unfollow  like/unlike posts etc. Now i want to add messaging feature (already ask about it) so please guide me..
1. what actually i have to do and  from where should i start it ?
2. if i read whole channel documentation will it be helpful to create this type of app

**Comment by matthiask** [comment]
The most important point is already there: Use a group per target user (don't be afraid of creating many many groups!)

First step: Work through the tutorial, and send feedback or better yet, documentation edits if you find anything: https://channels.readthedocs.io/en/latest/tutorial/index.html

And *of course* reading the documentation will be helpful.

**Comment by rahul6612** [comment]
thnaks  @matthiask
