### ISSUE TITLE
AttributeError: module 'posts.models' has no attribute 'image_upload_to'

### ISSUE THREAD

**Issue by rahul6612** [django/channels#979]
## i am getting this error
` ('images', models.FileField(blank=True, null=True, upload_to=posts.models.image_upload_to)),
AttributeError: module 'posts.models' has no attribute 'image_upload_to' `

## even i am not using image field in my models.py

> class Post(models.Model):
    parent      = models.ForeignKey("self", blank=True, null=True)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    content     = models.CharField(max_length=2000, validators=[validate_content])
    liked       = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='liked')
    reply       = models.BooleanField(verbose_name='Is a reply?', default=False)
    updatd      = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    objects = PostManager()

**Comment by andrewgodwin** [comment]
This is not a Channels issue, I'm afraid, so I have to close this. It looks like you might have a bad migration, but you should ask somewhere else (e.g. django-users mailing list)
