### ISSUE TITLE
Weird ConsumeLater Exception

### ISSUE THREAD

**Issue by felipe3dfx** [django/channels#982]
- Ubuntu 17.10
- Channels 1.8.8, Django 1.11.7 and asgi_redis 1.4.3

i have a weird ConsumerLater exception, i guess it happens when it is connecting the consumer but i am not certain, this is my configuration:

- `python3.6 manage.py runworker --only-channels=websocket.* --threads=2` and Nginx

```
# consumers.py

def send_payload(group, **kwargs):
    Group(group).send({'text': json.dumps(kwargs, cls=DjangoJSONEncoder)})


@channel_session_user_from_http
def ws_connect(message, slug):
    if not message.user.is_authenticated:
        return

    if slug == WS_USER_SLUG:
        Group(
            WS_USER_GROUP.format(user_id=message.user.id)
        ).add(message.reply_channel)

        from userprofile.utils import pending_notification_count
        office = cache.get(OFFICE_CACHE_KEY.format(user_id=message.user.id))
        send_payload(
            group=WS_USER_GROUP.format(user_id=message.user.id),
            notification_counter=pending_notification_count(message.user),
        )
```

Logs: https://s3.amazonaws.com/uploads.hipchat.com/50553/3393916/AtRX9vUDC4CtjGh/Screen%20Shot%202018-03-20%20at%203.42.08%20PM.png

any ideas?

**Comment by andrewgodwin** [comment]
No real idea, I'm afraid, and since it's a Channels 1 thing I'm not going to leave this bug open as it's no longer supported. ConsumeLater is an exception class so it's worth seeing what raises it and if you can stop that?
