### ISSUE TITLE
ImportError: cannot import name 'Group'

### ISSUE THREAD

**Issue by dawntcherian** [django/channels#989]
I am using channels==2.0.2 and getting the following error while trying to import Group.

File "/home/user/python_projects/django_channels/my_project/game/models.py", line 3, in 
from channels import Group
ImportError: cannot import name 'Group'

- OS: Ubuntu 14.04
- Channels: 2.0.2, 
- Daphne: 2.1.0, 
- Django: 2.0.3,
- Twisted: 17.9.0,

**Comment by matthiask** [comment]
Groups work differently with channels 2 than they did with channels 1. There is no `Group` class anymore.

The new groups API is documented here:
https://channels.readthedocs.io/en/latest/topics/channel_layers.html#groups
