### ISSUE TITLE
Genorators using database_sync_to_async are called on the main thread

### ISSUE THREAD

**Issue by agronick** [django/channels#991]
This is probably true for the other decorators as well. Same issue if you call the decorators directly.

`threading.get_ident()` is the same as the async code when the function uses yield. If you change it to return a list it has a different ID.

**Comment by andrewgodwin** [comment]
Can you give a full example? And what you expect to happen instead?

**Comment by agronick** [comment]
Yeah I can tomorrow. This happens because calling a generator does not run it. Only iterating through it does. The code that calls the iteration is outside the decorator. The decorators will probably need a change to detect if it is a generator and return a new generator where each iteration calls next () inside an executor on the original generator.

**Comment by agronick** [comment]
Heres the code

```

    @database_sync_to_async
    def function_foo(self):
        print(threading.get_ident(), 'function')
        return 4

    @database_sync_to_async
    def generator_foo(self):
        print(threading.get_ident(), 'generator')
        yield 4

    async def receive_json(self, content):
        print(threading.get_ident(), 'loop')
        print(await self.function_foo())
        for i in await self.generator_foo():
            print(i)
```

Heres the output
```
139945948370688 loop
139945849284352 function
4
139945948370688 generator
4
```

**Comment by andrewgodwin** [comment]
Ah, yes. Can you open this as a bug against `asgiref`, please, as it's an issue with that package's `sync_to_async` function?
