### ISSUE TITLE
An error while installing channels on pip : UnicodeDecodeError

### ISSUE THREAD

**Issue by sj602** [django/channels#993]
Please submit **questions** about usage to django-users@googlegroups.com (https://groups.google.com/forum/#!forum/django-users) and about development to django-developers@googlegroups.com (https://groups.google.com/forum/#!forum/django-developers).

If you're submitting a feature request, please try to include:

- Detailed description of the overall behaviour
- Reasoning why it should be in Channels rather than a third-party app
- Examples of usage, if possible (it's easier to discuss concrete code examples)

If you're submitting a bug report, please include:

- Your OS and runtime environment, and browser if applicable
OS: Windows 10 Pro

- The versions of Channels, Daphne, Django, Twisted, and your ASGI backend (channels_redis normally)
python: 3.6.4
asgi-redis==1.4.3
asgiref==2.2.0
async-timeout==2.0.1
attrs==17.4.0
autobahn==18.3.1
Automat==0.6.0
certifi==2018.1.18
channels==2.0.2
chardet==3.0.4
constantly==15.1.0
daphne==2.1.0
dj-database-url==0.5.0
Django==2.0.3
django-heroku==0.3.1
gunicorn==19.7.1
haikunator==2.1.0
hyperlink==18.0.0
idna==2.6
incremental==17.5.0
msgpack-python==0.5.6
oauthlib==2.0.7
pipenv==11.9.0
psycopg2==2.7.4
pypiwin32==223
pytz==2018.3
pywin32==223
redis==2.10.6
requests==2.18.4
requests-oauthlib==0.8.0
six==1.11.0
Twisted==17.9.0
txaio==2.9.0
urllib3==1.22
virtualenv==15.2.0
virtualenv-clone==0.3.0
websocket-client==0.47.0
whitenoise==3.3.1
zope.interface==4.4.3

- What you expected to happen vs. what actually happened
What I expected to happen: I run my app under channels through daphne.
I did 'daphne -b 0.0.0.0 -p 8001 chat.asgi:channel_layer' on the console
What actually happened : I got an error saying :

File ".\chat\asgi.py", line 2, in <module>
import channels.asgi
ImportError: No module named 'channels.asgi'

my asgi.py is ...

```
import os
import channels.asgi

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "snorkel.settings")
channel_layer = channels.asgi.get_channel_layer


```
- How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)
- Console logs and full tracebacks of any errors

**Comment by ovekaaven** [comment]
Maybe you're using an asgi.py that's meant for Channels 1.x. That won't work on Channels 2.x.

My own asgi.py looks like

```
import os
import django
from channels.routing import get_default_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "chatbox.settings")
django.setup()

application = get_default_application()
```

Make sure you check the docs for how things should look.

**Comment by andrewgodwin** [comment]
Yes, @ovekaaven  is correct. You can find the new asgi.py file contents in http://channels.readthedocs.io/en/latest/deploying.html
