### ISSUE TITLE
error runserver 

### ISSUE THREAD

**Issue by mahmood0** [django/channels#995]
what`s a problem with this i can`t understand 
![fgfdg](https://user-images.githubusercontent.com/24221644/38168616-b21abf6c-3551-11e8-8e3f-480e5ea9f553.png)

**Comment by matthiask** [comment]
This has nothing to do with channels; the Django version you're running requires an `on_delete` argument to `ForeignKey` (e.g. `team = models.ForeignKey(Team, on_delete=models.CASCADE)` to get the default behavior of earlier Django versions)

**Comment by mahmood0** [comment]
how can i get earlier Django versions @matthiask
