### ISSUE TITLE
socket Disconnected after 24 hours 

### ISSUE THREAD

**Issue by puregod27** [django/channels#999]
i use channels 1.1

Are there any settings related to 24 hours?

**Comment by matthiask** [comment]
Yes, `daphne --websocket-timeout` defaults to 86400 seconds.

**Comment by puregod27** [comment]
Why is it set to 86400 seconds?
Is it because of memory management?

**Comment by andrewgodwin** [comment]
It is to match the default group expiry time in the channel layers (the websocket timeout has to be shorter than the group expiry).
